### ISSUE TITLE
CP Code for new properties

### ISSUE THREAD

**Issue by partamonov** [akamai/terraform-provider-akamai#10]
CP Code is required in schema, even during create. But create function has logic to create CP Code

**Comment by partamonov** [comment]
And may be it will be better to move CP Code creation from property to separate resource and then just use it, will be much better if I want to create 2 properties with same CP Code.

**Comment by dcherniv** [comment]
@partamonov 
I was able to reuse an existing CP code (created through luna) with terraform.
But definitely +1 for akamai_cpcode resource.

**Comment by partamonov** [comment]
@dcherniv I mean, if I will try to create property, based on code I saw I can skip cpcode option, as create func has `create CP code` but in resource schema, cp_code is mandatory parameter.

We have two ways to my mind:
1. make cp_code optional and create it during property creation
2. keep cp_code mandatory, but move cp code creation functionality to resource `cp_code`

**Comment by dcherniv** [comment]
@partamonov Not sure i follow.
The behaviour that i observed was as follows:
```
resource "akamai_property" "property01" {
// [...]
  cp_code    = "669473"
//[...]
}
```
In my case cp_code 669473 already existed in luna. So terraform didn't create it.
If i specify lets say 669474, then terraform creates that cp_code and assigns it to the property. 
But something in the creation of cpcode is definitely buggy.
```
resource "akamai_property" "property01" {
// [...]
  cp_code    = "669474"
//[...]
}
```
The above does create a cp_code but it doesn't assign 669474 as cp_code number to it, instead 669474 becomes the name of cp_code and number is assigned randomly.


Valid cp_code:
![image](https://user-images.githubusercontent.com/19437418/36039685-3caefadc-0d91-11e8-9c34-e04bf9a3808e.png)

cp_code created by terraform:
![image](https://user-images.githubusercontent.com/19437418/36039712-51a5c484-0d91-11e8-88cc-78e75464736f.png)

Notice how name and number is swapped in the one created through terraform.
Another thing is that it takes ?120? minutes to create a cp_code so separate cp_code resource might not even be feasible through api/terraform.

I would like to see your second point implemented rather than making cp_code optional, which will likely mean that cp_code needs to be created automatically at resource creation, behind the scenes. Provided of course, we can terraform import existing cp_code resources.
Debug output:
Using an existing cp_code:
```
akamai_property.property01: Refreshing state... (ID: prp_439660)

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  ~ akamai_property.property01
      cp_code: "670473" => "669473"
      network: "production" => "staging"


Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

akamai_property.property01: Modifying... (ID: prp_439660)
  cp_code: "670473" => "669473"
  network: "production" => "staging"
akamai_property.property01: Still modifying... (ID: prp_439660, 10s elapsed)
akamai_property.property01: Still modifying... (ID: prp_439660, 20s elapsed)
akamai_property.property01: Still modifying... (ID: prp_439660, 30s elapsed)
akamai_property.property01: Still modifying... (ID: prp_439660, 40s elapsed)
akamai_property.property01: Still modifying... (ID: prp_439660, 50s elapsed)
akamai_property.property01: Still modifying... (ID: prp_439660, 1m0s elapsed)
akamai_property.property01: Still modifying... (ID: prp_439660, 1m10s elapsed)
akamai_property.property01: Still modifying... (ID: prp_439660, 1m20s elapsed)
akamai_property.property01: Still modifying... (ID: prp_439660, 1m30s elapsed)
akamai_property.property01: Still modifying... (ID: prp_439660, 1m40s elapsed)
akamai_property.property01: Still modifying... (ID: prp_439660, 1m50s elapsed)
akamai_property.property01: Still modifying... (ID: prp_439660, 2m0s elapsed)
akamai_property.property01: Still modifying... (ID: prp_439660, 2m10s elapsed)
akamai_property.property01: Still modifying... (ID: prp_439660, 2m20s elapsed)
akamai_property.property01: Modifications complete after 2m27s (ID: prp_439660)

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.
dcherniv@debbie:~/$ 
```
Creating new cp_code:
```
dcherniv@debbie:~/$ terraform apply
akamai_property.property01: Refreshing state... (ID: prp_439660)

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  ~ akamai_property.property01
      cp_code: "669474" => "670473"
      network: "production" => "staging"


Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

akamai_property.property01: Modifying... (ID: prp_439660)
  cp_code: "669474" => "670473"
  network: "production" => "staging"
akamai_property.property01: Still modifying... (ID: prp_439660, 10s elapsed)
akamai_property.property01: Still modifying... (ID: prp_439660, 20s elapsed)
akamai_property.property01: Still modifying... (ID: prp_439660, 30s elapsed)
akamai_property.property01: Still modifying... (ID: prp_439660, 40s elapsed)

Error: Error applying plan:

1 error(s) occurred:

* akamai_property.property01: 1 error(s) occurred:

* akamai_property.property01: Error - Invalid Property Rules
 Rule validation error: https://problems.luna.akamaiapis.net/papi/v0/validation/illegal_option_value_format  The 'Content Provider Code' option on the Content Provider Code behavior has an illegal value for its type.  
```

**Comment by partamonov** [comment]
I will check cp_code creation via API calls and we will see that it returns, but based on doc it returns location, from which ID can be extracted. Question if we will be able to create property with just created cp code. I will try that.

**Comment by dshafik** [comment]
This is correct behavior — if the opcode is numeric, or starts with `cpc_`, we assume it's a CPCode ID and look it up via that. If it's not an ID, or isn't found, we treat it as the name, and iterate over all the CPCodes the group/contract has access to.

If that is unsuccessful, a new CPCode with that _name_ is created, and automatically assigned to the property. Typically this would be for new properties, and therefore there is no service disruption as indicated in Luna.

**Comment by dshafik** [comment]
As this is working as expected, I'm going to close this and create a new ticket to discuss and decide on adding a new `akamai_cpcode` resource.

**Comment by dshafik** [comment]
@partamonov @dcherniv I've created #15 to discuss this
