### ISSUE TITLE
SiteShield behavior expects object instead of string

### ISSUE THREAD

**Issue by ghost** [akamai/terraform-provider-akamai#10]
Hi,

I'm trying to build an Akamai property with Terraform but the "terraform apply" fails on setting up the SiteShield behavior. Is this something the Akamai provider doesn't support yet?

### Versions:
Terraform version: v0.11.14
Provider version: provider.akamai v0.1.0

### Debug Output
Terraform outputs:
{  instance type (string) does not match any allowed primitive type (allowed: ["object"]) }

### Terraform Configuration Files
I'm using these lines of code in my Terraform file:

`behavior {
      name = "siteShield"
        option = {
          key = "ssmap"
          value = "mapname.akamai.net"
        }
    }
`

It looks like a mismatch with the PAPI API according to this page:
https://community.akamai.com/customers/s/question/0D50f00005Rtr6oCAB/siteshield-ssmap-data-type-changed?language=es_PR

Normally the API accepted:

`
 {
      "name" : "siteShield",
      "options" : {
        "ssmap" :  "$some_ssmap"
      }
 }
`

Now the API expects:

`
 {
      "name" : "siteShield",
      "options" : {
        "ssmap" :  {"value":"$some_ssmap"}
      }
 }
`

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Add resrouce "akamai_property_rules" to Terraform file
2. Add SiteShield behavior rule under the default rule in resource "akamai_property_rules"
3. Run terraform apply
4. Terraform apply will fail with the output mentioned above

**Comment by dshafik** [comment]
@wvdhengel: thanks for the heads up, a few behaviors have slightly different format to the majority (currently this one and CP Codes), I'll look into resolving this one also, shortly.

**Comment by dshafik** [comment]
@wvdhengel this has been fixed and will be included in the next release, thanks! :)
