### ISSUE TITLE
feature request - Activating property on product name

### ISSUE THREAD

**Issue by asonitis365** [akamai/terraform-provider-akamai#104]
Hi, 

With the current **akamai_property_activation** the prp_ ID needs to be specified which is created after the property is created. Currently you can reference the id from the **akamai_property** resource however you don't have the ability to activate the property version outside the "main.tf"

Creating a generic module to create a property that multiple products can use, minimizing duplicate config is difficult. 

A data source would be beneficial which allows someone to retrieve the prp_ id by the property name and therefore allowing you to have a separate module for activating the staging or production env.

### Terraform Version
Terraform version: 0.12.6

### Affected Resource(s)

- akamai_property_activation

### Terraform Configuration Files
**example**

provider "akamai" {}
data "akamai_property_activation" "example" {
    property = "${var.product_name}"
    
}
resource "akamai_property_activation" "example" {
        property = "${data.akamai_property_activation.example.id}"
        contact = ["example@terraform.example.com"]
        network = "STAGING"
        activate = true 
        version = "${data.akamai_property_activation.example.staging_version}"
}

### Debug Output
NA

### Panic Output
NA

### Expected Behavior
prp_ id is retrieved from property name

### Actual Behavior
activation needs to reference the property id within the main tf

### Steps to Reproduce
NA

### References
- https://github.com/terraform-providers/terraform-provider-akamai/pull/103

**Comment by IanCassTwo** [comment]
This looks like a documentation issue. The datasource you're looking for does exist.

https://github.com/akamai/terraform-provider-akamai/blob/master/pkg/providers/property/data_akamai_property.go

**Comment by lkowalsk-akamai-com** [comment]
Hi, this datasource has been added to the documentation:
https://registry.terraform.io/providers/akamai/akamai/latest/docs/data-sources/property
