### ISSUE TITLE
Doc update request: resource_edge_hostname import

### ISSUE THREAD

**Issue by joel-g** [akamai/terraform-provider-akamai#109]
This document needs instructions for importing edge hostname resources

https://www.terraform.io/docs/providers/akamai/r/edge_hostname.html

**Comment by sidph** [comment]
@joel-g when you say import, do you mean documenting how an existing edgehostname can be reused or more?

**Comment by zstlaw** [comment]
Thanks for reporting this issue. The documentation requested was added as part of the 1.0.0 release. https://registry.terraform.io/providers/akamai/akamai/latest/docs/resources/property_edge_hostname#import

We also recommend upgrading your Akamai Provider version to 1.0.0 as the provider has undergone design improvements. Please refer https://registry.terraform.io/providers/akamai/akamai/latest/docs/guides/1.0_migration for details on how to upgrade to this 1.0.0 version. 

Closing this issue.
