### ISSUE TITLE
Cannot create multiple types of records with the same name

### ISSUE THREAD

**Issue by benjamink** [akamai/terraform-provider-akamai#11]
### Terraform Version
0.11.14

### Affected Resource(s)
Please list the resources as a list, for example:
- akamai_dns_record

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
resource "akamai_dns_record" "f34mail_a_123_123_123_113" {
  zone       = "example.com"
  name       = "f34mail.example.com"
  target     = ["123.123.123.113"]
  recordtype = "A"
  ttl        = "3600"
  active     = true
}
resource "akamai_dns_record" "f34mail_mx_f34mail_example_com" {
  zone       = "example.com"
  name       = "f34mail.example.com"
  target     = ["f34mail.example.com"]
  recordtype = "MX"
  ttl        = "3600"
  active     = true
}
```

### Debug Output
```text
Error: Error applying plan:

1 error occurred:
        * akamai_dns_record.f34mail_mx_f34mail_example_com: 1 error occurred:
        * akamai_dns_record.f34mail_mx_f34mail_example_com: Zone "example.com" validation failed: [Duplicate rdata found for record with name f34mail.example.com and type MX]
```

### Expected Behavior
Ability to create an A record and an MX record with the same record name.

**Comment by dshafik** [comment]
@benjamink can you try with Terraform 0.12? 

What's happening here is not an issue with the A and MX having the same name, but rather that there is an existing identical MX. Do you know if that's possibly the case (existing data in the zone) so we can determine if the provider is doing something weird leading to that situation?

**Comment by bogdan-grozoiu** [comment]
I am using TF v0.12.5 and akamai provider v0.1.1. 

Here is my setup:

```
variable "mx_records" {
  default = [
      {
          priority = 0
          server = "justaserver.mail.protection.outlook.com"
      },
      {
            priority = 10
            server = "hereisanotherserver.domain.tld"
      },
      {
          priority = 20
          server = "thisisanotherserver.anotherdomain.tld"
      }
  ]
}

resource "akamai_dns_record" "mx_records" {
  count = 3
  zone       = var.zone
  name       = "acceptance.companydomain.tld"
  recordtype = "MX"
  ttl        = var.default_ttl
  active     = true

  target = [var.mx_records[count.index].server]
  priority = var.mx_records[count.index].priority

  depends_on = [akamai_dns_zone.acceptance_companydomain_tld]
} 

```

and here is the output of `terraform apply`

```
akamai_dns_record.mx_records[0]: Creating...
akamai_dns_record.mx_records[1]: Creating...
akamai_dns_record.mx_records[2]: Creating...

Error: Zone "acc.companydomain.tld" validation failed: [Duplicate record set found with name acc.companydomain.tld and type MX]

  on acc.companydomain.tld.tf line 110, in resource "akamai_dns_record" "mx_records":
 110: resource "akamai_dns_record" "mx_records" {



Error: Zone "acc.companydomain.tld" validation failed: [Duplicate record set found with name acc.companydomain.tld and type MX]

  on acc.companydomain.tld.tf line 110, in resource "akamai_dns_record" "mx_records":
 110: resource "akamai_dns_record" "mx_records" {



Error: Zone "acc.companydomain.tld" validation failed: [Duplicate rdata found for record with name acc.companydomain.tld and type MX]

  on acc.companydomain.tld.tf line 110, in resource "akamai_dns_record" "mx_records":
 110: resource "akamai_dns_record" "mx_records" {

```

Seen differently, when trying to create a payload with all 3 MX servers, such as:

```
 target = ["justaserver.mail.protection.outlook.com", "hereisanotherserver.domain.tld", "thisisanotherserver.anotherdomain.tld"]
```
restricts me from setting a priority on each.


_domain names purposely obfuscated and name servers purposely having different FQDNs and no rank-introducing numbers_

_route53 example that actually works:_
```
  records = [
    "0 justaserver.mail.protection.outlook.com,
    "10 hereisanotherserver.domain.tld",
    "20 thisisanotherserver.anotherdomain.tld",
  ]
```

**Comment by dshafik** [comment]
@grozoiu I agree this _should_ work. It seems that maybe priority is being ignored when it comes to determining if they are duplicates (or when creating them, causing it to be 0 for all of them?)

**Comment by bogdan-grozoiu** [comment]
> @grozoiu I agree this _should_ work. It seems that maybe priority is being ignored when it comes to determining if they are duplicates (or when creating them, causing it to be 0 for all of them?)

Could be. What I observed though, is that running `terraform apply` for 3 times in my case (the same number of times as the number of MX records), it crashes every time (see above), but the records are eventually saved correctly in Akamai... o.O

**Comment by martinstibbe** [comment]
I have a sorting enhancement in a PR for MX records
branch AT-25 has this for an upcoming release
