### ISSUE TITLE
Feature request - accountSwitchKey support

### ISSUE THREAD

**Issue by YaroslavJanrain** [akamai/terraform-provider-akamai#115]
Hello,

Please add accountSwitchKey support into provider (https://learn.akamai.com/en-us/learn_akamai/getting_started_with_akamai_developers/developer_tools/accountSwitch.html).
I've found few lines here https://github.com/terraform-providers/terraform-provider-akamai/blob/d63f6d806daf6554091d72b1940deb909ebd2451/akamai/resource_akamai_gtm_domain.go#L189 but they are commented.

Thanks!

**Comment by IanCassTwo** [comment]
It works today if you format your .edgerc like this:-

[section]
client_secret = XXXXXXXXXX/XXXXXXXXXXXXX/+XXXXXXXXXXX=
host = akab-XXXXXXXXXXX-XXXXXXXXXXX.luna.akamaiapis.net
access_token = akab-************-************
client_token = akab-************-************
account_key = 1-ABCFGH

You can simply create a .edgerc section for each account. Of course, this doesn't help if you don't use .edgerc though.

**Comment by Yuxael** [comment]
This does not work in version 0.10.0, please add this.
