### ISSUE TITLE
Can't remove a backup_cname from GTM property

### ISSUE THREAD

**Issue by IanCassTwo** [akamai/terraform-provider-akamai#124]
### Terraform Version
Terraform v0.12.20
+ provider.akamai v0.5.0

### Affected Resource(s)
akamai_gtm_property.

### Terraform Configuration Files
```hcl
resource "akamai_gtm_property" "test5" {
    domain = "iancass.co.uk.akadns.net"
    name = "test5"
    type =  "weighted-round-robin"
    score_aggregation_type = "median"
    handout_limit = 5
    handout_mode = "normal"
    traffic_target {
        datacenter_id = akamai_gtm_datacenter.Frankfurt.datacenter_id
        enabled = true
        handout_cname = "www.example.com"
        weight = 1
        name = null
        servers = ["www.example.com"]
    }

    traffic_target {
        datacenter_id = akamai_gtm_datacenter.Dublin.datacenter_id
        enabled = true
        handout_cname = "www.exampe.com"
        weight = 0
        name = null
        servers = ["www.exampe.com"]
    }
    backup_cname = "www.akamai.com"
}
```

### Debug Output
Plan shows that the backup_cname should be removed.
      - backup_cname                = "www.akamai.com" -> null

However, the json sent over the wire clearly shows that the backup cname is still there...

{
    "backupCName": "www.akamai.com",
    "balanceByDownloadScore": false,
    "dynamicTTL": 300,
    "ghostDemandReporting": false,
    "handoutLimit": 5,
    "handoutMode": "normal",
    "ipv6": false,
    "lastModified": "2020-03-25T12:18:54.000+00:00",
    "links": [
        {
            "href": "https://xxxxxxxxxxxxxx.luna.akamaiapis.net/config-gtm/v1/domains/iancass.co.uk.akadns.net/properties/test5",
            "rel": "self"
        }
    ],
    "name": "test5",
    "scoreAggregationType": "median",
    "trafficTargets": [
        {
            "datacenterId": 3133,
            "enabled": true,
            "handoutCName": "www.example.com",
            "servers": [
                "www.example.com"
            ],
            "weight": 1
        },
        {
            "datacenterId": 3134,
            "enabled": true,
            "handoutCName": "www.exampe.com",
            "servers": [
                "www.exampe.com"
            ]
        }
    ],
    "type": "weighted-round-robin",
    "useComputedTargets": false
}

### Expected Behavior
Backup cname should be removed

### Actual Behavior
Backup cname was not removed

### Steps to Reproduce
1. Create GTM property with a backup cname & apply
2. Verify in GUI that backup cname is present
3. Remove backup cname form .tf & apply
4. Verify in GUI that backup cname is not present (it IS present but should not be)

You can change the backup cname but you can't set it blank "". That does not result in a change. Results in same behaviour as above

**Comment by edglynes** [comment]
looking at it.
