### ISSUE TITLE
feature request - akamai_property_rules options fields allow object

### ISSUE THREAD

**Issue by hitsumabushi** [akamai/terraform-provider-akamai#128]
Hi,

I found some akamai property option's value has object type, for example [siteShield]( https://developer.akamai.com/api/core_features/property_manager/vlatest.html#siteshield), [origin](https://developer.akamai.com/api/core_features/property_manager/vlatest.html#origin) behavior.
How about add support new types at akamai property option's value.

### Terraform Version
Terraform v0.12.24

### Affected Resource(s)
akamai_property_rules

### Terraform Configuration Files
NA

### Debug Output
NA

### Panic Output
NA

### Expected Behavior
object can be set at option field value.

### Actual Behavior
string or set of string are only allowed at option fields value.

### Steps to Reproduce
NA

### Important Factoids
NA

### References
NA

**Comment by zstlaw** [comment]
Thanks for creating this feature request. 

In the 1.0.0 release, rule tree will be constructed from template files and the current data source “akamai_property_rules” will be used only to fetch rule tree from PAPI. The requested behavior will be achieved by utilizing the new “akamai_property_rules_template” json templating solution. 

Please refer https://registry.terraform.io/providers/akamai/akamai/latest/docs/guides/1.0_migration for details on how to upgrade to this 1.0.0 version
