### ISSUE TITLE
DXE-2449 TXT Record RData containing embedded quotes not handled correctly 

### ISSUE THREAD

**Issue by edglynes** [akamai/terraform-provider-akamai#137]
### Terraform Version
v0.12.20
Akamai provider

### Affected Resource(s)
akamai_dns_record

### Terraform Configuration Files
```hcl
resource "akamai_dns_record" "testprimary_com_text_testprimary_com_TXT" {
    zone = local.zone
    target = ["He\"ll\o"]
    name = "text.testprimary.com"
    recordtype = "TXT"
    ttl = 7200
}
```
### Expected Behavior
Correct RData value should be set in EdgeDNS thru API

### Actual Behavior
EdgeDNS mangles the value, inserting a space in the string, "\"He\" \"ll\"o"
Subsequest Read/Refresh will retrieve this mangled data.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by DonatasFe** [comment]
IN GTM issue still exists after import, it needs to be manually fixed. Working on docker 

Terraform v0.13.6
+ provider registry.terraform.io/akamai/akamai v1.6.1

After import
```
    static_rr_set {
        type = "TXT"
        ttl = 1800
        rdata = [""text_here""]
    }
```
the right way
```
    static_rr_set {
        type = "TXT"
        ttl = 1800
        rdata = ["\"text_here\""]
    }
```

**Comment by mgwoj** [comment]
Hello @DonatasFe ,

Is the problem that TF file exported using `akamai terraform create-domain` has `"` not properly escaped?

Thanks,
Michal

**Comment by lkowalsk-akamai-com** [comment]
This issue was addressed in recent release
