### ISSUE TITLE
documentation is wrong

### ISSUE THREAD

**Issue by ericrichtert** [akamai/terraform-provider-akamai#146]
On https://www.terraform.io/docs/providers/akamai/r/property_variables.html , is mentioned the arguments hidden and sensitive are optional, but the output of terraform apply shows:

Error: Missing required argument
   on main.tf line 13, in resource "akamai_property_variables" "useim":
   13:     variable {
 The argument "hidden" is required, but no definition was found.
 Error: Missing required argument
   on main.tf line 13, in resource "akamai_property_variables" "useim":
   13:     variable {
 The argument "sensitive" is required, but no definition was found.

**Comment by martinstibbe** [comment]
Merged to master

**Comment by ericrichtert** [comment]
is released
