### ISSUE TITLE
Newer provider versions give 404 on previously created properties

### ISSUE THREAD

**Issue by dstevensson** [akamai/terraform-provider-akamai#147]
### Terraform Version
Terraform v0.12.24
+ provider.akamai v0.5.0

### Affected Resource(s)
Please list the resources as a list, for example:
- akamai_property

### Expected Behavior
The property resource previously created by Terraform should continued to be recognized and found by the provider after updating provider version.

### Actual Behavior
The terraform provider gets a 404 API error when trying to locate the `akamai_property` resource.
```
module.app_cdn.akamai_property.app: Refreshing state... [id=prp_594335-be064acda67fd82da78d0433e9c8745253d8b346]
Error: API Error: 404 404 Not Found The system was unable to locate the requested resource. More Info https://problems.luna.akamaiapis.net/papi/v0/http/not-found
```
```
2020/05/05 11:02:54 [ERROR] module.app_cdn: eval: *terraform.EvalRefresh, err: API Error: 404 404 Not Found The system was unable to locate the requested resource. More Info https://problems.luna.akamaiapis.net/papi/v0/http/not-found
2020/05/05 11:02:54 [ERROR] module.app_cdn: eval: *terraform.EvalSequence, err: API Error: 404 404 Not Found The system was unable to locate the requested resource. More Info https://problems.luna.akamaiapis.net/papi/v0/http/not-found
```

### Steps to Reproduce
1. Create a property using provider version `0.1.5` or lower.
2. Upgrade provider version to `0.2.0` or higher.
3. Run `terraform plan`.

**Comment by martinstibbe** [comment]
If you open state file in an editor and remove sha value from ID it should correct this issue
prp_594335-be064acda67fd82da78d0433e9c8745253d8b346
becomes this ...
prp_594335

Save file and plan/apply should be ok

**Comment by dstevensson** [comment]
Yep, that fixed it!
I had to remove the hash from both the property and the property activation. Since I use AWS DynamoDB for locks I also had to modify the digest key to match the md5 of the modified state file.
Thank you for the assistance @martinstibbe
