### ISSUE TITLE
Environment variable resolution

### ISSUE THREAD

**Issue by wonboyn** [akamai/terraform-provider-akamai#161]
### Terraform Version
0.12.26

### Affected Resource(s)
- property
- edge host

### Terraform Configuration Files
```hcl
# Configure the Akamai Provider
provider "akamai" {
    property {
      host          = "var.akamai_host"
      access_token  = "var.access_token"
      client_token  = "var.client_token"
      client_secret = "var.client_secret"
    }
}

# Get contract id
data "akamai_contract" "contract" {
    group = "test1"
}

# Get group id
data "akamai_group" "group" {
    name = "test1"
}

# Create a CP code
resource "akamai_cp_code" "cpcode" {
    contract = "data.akamai_contract.contract.id"
    group    = "data.akamai_group.group.id"
    name     = "var.property_name"
    product  = "var.product_id"
}

# Create an edge host
resource "akamai_edge_hostname" "edgehost" {
    group         = "data.akamai_group.group.id"
    contract      = "data.akamai_contract.contract.id"
    product       = "prd_SPM"
    edge_hostname = "var.edge_hostname_akamai"
}

# Create a Property
resource "akamai_property" "property" {
  contract  = "data.akamai_contract.contract.id"
  group     = "data.akamai_group.group.id"
  name      = "var.property_name"
  contact   = ["someone@somewhere.com"]
  product   = "prd_SPM"
  hostnames = {
      "var.edge_hostname_origin" = "var.edge_hostname_akamai"
  }
}
```

### Debug Output
https://gist.github.com/wonboyn/5e60bc057f23e132ddddd26900e069a0

### Expected Behavior
Shell environment variables set as TF_VAR_akamai_host / TF_VAR_access_token etc get resolved and used by the provider rather than being treated as literals.

### Actual Behavior
The values provided in the provider block for host, access_token, client_token & client_secret were treated as literals, consequently when you run terraform plan it attempts to lookup the api host https://var.akamai_host/papi/v1/groups & fails

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:

1. Create main.tf as detailed above
2. Create environment variables TF_VAR_{variable name} for each variable specified in the provider configuration block
3. Run terraform plan

### References
None

**Comment by martinstibbe** [comment]
@wonboyn I will check out the TF_VAR_ variable approach to see what the issue is
If you want to use ENV vars to drive provider block another option is to use (see below)

According to documentation and code in provider.go line #39 as and example
Env var it is looking for is prefixed with AKAMAI_
if v := os.Getenv("AKAMAI_" + section + "_HOST");

**Comment by ericrichtert** [comment]
@wonboyn I think you have to remove the " chars. I have the same approach:

> provider "akamai" {
  version = "= 0.7.2"
  property {
    # The akamai vars are injected by gitlab as TF_VAR_ envvars
    host          = var.akamai_host
    access_token  = var.akamai_access_token
    client_token  = var.akamai_client_token
    client_secret = var.akamai_client_secret
  }
}

**Comment by martinstibbe** [comment]
@wonboyn @ericrichtert Thanks Eric in TF .12 it should work without quotes to expand the variable values

**Comment by wonboyn** [comment]
@ericrichtert - Thanks for the tip about the quotes. I must still be doing something slightly wrong as I am still getting the same error.

The provider configuration now looks like:
provider "akamai" {
    property {
      host          = var.akamai_host
      access_token  = var.akamai_access_token
      client_token  = var.akamai_client_token
      client_secret = var.akamai_client_secret
    }
}

I then exported the following variables:
- TF_VAR_akamai_host
- TF_VAR_akamai_access_token
- TF_VAR_akamai_client_token
- TF_VAR_akamai_client_secret

At this point if I run terraform validate it throws error saying the variables have not been declared. As an example:

Error: Reference to undeclared input variable

  on main.tf line 8, in provider "akamai":
   8:       client_secret = var.akamai_client_secret

An input variable with the name "akamai_client_secret" has not been declared.
This variable can be declared with a variable "akamai_client_secret" {} block.

Any suggestions on what I'm doing that's not right?

Thanks

**Comment by martinstibbe** [comment]
@wonboyn I added a vars file with blank placeholders and the Env vars worked to connect the provider

variable "akamai_host" {
}

variable "access_token" {
}

variable "client_token" {
}

variable "client_secret" {
}

**Comment by wonboyn** [comment]
Thanks @martinstibbe - that fixed the issue. 

One further related question. I'm using environment variables to pass in the origin & edge host names:

resource "akamai_property" "property" {
  contract  = "data.akamai_contract.contract.id"
  group     = "data.akamai_group.group.id"
  name      = var.property_name
  contact   = ["someone@somewhere.com"]
  product   = "prd_SPM"
  hostnames = {
      var.edge_hostname_origin = var.edge_hostname_akamai
  }
}

I have added these variable definitions (with blank placeholders) into a vars file. When I run terraform validate it errors with:

~/Desktop/Terraform/akamai1 % terraform validate

Error: Ambiguous attribute key

  on main.tf line 50, in resource "akamai_property" "property":
  50:       var.edge_hostname_origin = var.edge_hostname_akamai

If this expression is intended to be a reference, wrap it in parentheses. If
it's instead intended as a literal name containing periods, wrap it in quotes
to create a string literal.

Is there a way to handle this scenario?

Thanks again

**Comment by martinstibbe** [comment]
@wonboyn This parameter is a map not supported via env vars according to https://learn.hashicorp.com/terraform/getting-started/variables.html

Note: Environment variables can only populate string-type variables. List and map type variables must be populated via one of the other mechanisms.
Structure example

variable "hostnames" {
  type = "map"
  default = {
    "edge_hostname_origin" = "edgehostname"
    "edge_hostname_origin1" = "edgehostname2"
  }
}

**Comment by ericrichtert** [comment]
> resource "akamai_property" "property" {
> contract = "data.akamai_contract.contract.id"
> group = "data.akamai_group.group.id"
> name = var.property_name
> contact = ["[someone@somewhere.com](mailto:someone@somewhere.com)"]
> product = "prd_SPM"
> hostnames = {
> var.edge_hostname_origin = var.edge_hostname_akamai
> }
> }

You can do it like this:

resource "akamai_property" "property" {
contract = data.akamai_contract.contract.id  # ->> remove the "
group = data.akamai_group.group.id  # ->> remove the "
name = var.property_name
contact = ["someone@somewhere.com"]
product = "prd_SPM"
hostnames = {
"${var.edge_hostname_origin}" = var.edge_hostname_akamai
}
}

**Comment by wonboyn** [comment]
Thanks @ericrichtert 
That worked.
