### ISSUE TITLE
Cannot find group when there are groups with the same name under multiple contract.

### ISSUE THREAD

**Issue by tommywo** [akamai/terraform-provider-akamai#168]
### Terraform Version
Terraform v0.12.28

### Affected Resource(s)
Please list the resources as a list, for example:
- data_property_akamai_group

Fix in pull request #94 is waiting to be merged.

**Comment by martinstibbe** [comment]
@tommywo Merged to master

**Comment by martinstibbe** [comment]
@tommywo This should be in new release 0.8.0

**Comment by martinstibbe** [comment]
@tommywo This has introduced a bug in the use case where contract not specified using search by name

**Comment by martinstibbe** [comment]
@tommywo Added some additional default logic https://github.com/terraform-providers/terraform-provider-akamai/pull/170

**Comment by tommywo** [comment]
@martinstibbe I made an alternative pull request to fix this, but now I'm wondering if it wouldn't be better to just make contract a required field. What do you think?

**Comment by martinstibbe** [comment]
@tommywo This is in release 0.8.1 for your review published yesterday feel free to test close issue if solved thanks

**Comment by zstlaw** [comment]
Thanks for reporting this issue. Please try upgrading to 1.0.0 and if you still face issues, Please let us know. Please refer https://registry.terraform.io/providers/akamai/akamai/latest/docs/guides/1.0_migration for additional details.
