### ISSUE TITLE
Error: property is still active

### ISSUE THREAD

**Issue by roymartinezblanco** [akamai/terraform-provider-akamai#172]
Hi there,

I have an issue when applying my TF from what I've been able to test/replicate if a TF apply fails in the process of activating a config (for example missing the tag `normalize` using current `latest`) it keeps this state. If we update/fix whatever caused the error it keeps thinking its activating and gives the error:

```
Error: property is still active on STAGING and cannot be deleted
```

Clearing the TF State takes care of this and allows the process to complete once the error has been fixed but he application does not seem so safely fail and clear the `activating` state even if it never really started/completed.
### Terraform Version
Terraform v0.12.28
+ provider.akamai v0.7.2
+ provider.local v1.4.0
+ provider.template v2.1.2

### Affected Resource(s)

- akamai_property
- akamai_property_activation

### Debug Output
https://gist.github.com/roymartinezblanco/3ae25b880dfa82cc2c3385ba825aec93.js

### Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
Fail and clear state

### Actual Behavior
Fail stating its been activated when it's not

### Steps to Reproduce
Use existing configuration that does not use `normalize` and use `latest` for the format.

1. plan (will succeed)
2. apply (will fail)
3. update json rules with proper tags.
4. clear state
5. plan
6. apply

**Comment by martinstibbe** [comment]
@roymartinezblanco I will try to replicate this assuming general flow is trying to activate a ruleset that would fail so activation technically should not attempt to run to avoid this result in state file

**Comment by roymartinezblanco** [comment]
@martinstibbe , this also happens if I apply a plan with where nothing changes. I assume it tries to activate something and then thinks it's activating even if it didn't really activate a version

**Comment by martinstibbe** [comment]
@roymartinezblanco can you send me rules file you are using if I have errors it refuses to activate/save

**Comment by roymartinezblanco** [comment]
@martinstibbe, sure
[rules-copy.json.zip](https://github.com/terraform-providers/terraform-provider-akamai/files/5052112/rules-copy.json.zip)

**Comment by martinstibbe** [comment]
@roymartinezblanco I got a bit further thanks which product did you use for cp code I am using prd_SPM which is incompatible

**Comment by martinstibbe** [comment]
@roymartinezblanco Github location moved just looking for product id you used to test out the whole flow of this property

**Comment by zstlaw** [comment]
Thanks for reporting this issue. Provider has been revamped in the 1.0.0 release. Please try upgrading to 1.0.0 and re-run your scenario. Please refer https://registry.terraform.io/providers/akamai/akamai/latest/docs/guides/1.0_migration for additional details.If you encountered a failure with 1.0.0 retesting your scenario, please submit a new issue.
