### ISSUE TITLE
Error: rpc error: code = Unavailable desc = transport is closing

### ISSUE THREAD

**Issue by EmmanuelMaduwuba** [akamai/terraform-provider-akamai#173]
Hi there,
I have an issue when trying to create  a new GTM property in an existing domain.

### Terraform Version.
$ terraform --version
Terraform v0.12.29
+ provider.akamai v0.8.0

### Affected Resource(s)
Please list the resources as a list, for example:
- akamai_GTM_property

### Debug Output
https://gist.github.com/EmmanuelMaduwuba/1472532b7d76bf0a1a730b6634519a91

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
What should have happened?
```Terraform plan``` should work

### Actual Behavior
What actually happened?
```Terraform plan``` command forces it to crash 

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan`
2. `terraform apply`

**Comment by roymartinezblanco** [comment]
I see this too

**Comment by lkowalsk-akamai-com** [comment]
Hi Emmanuel, 

This is due to a bug introduced in provider.akamai 0.8.0. The error is showing because field 'contract' for data source 'akamai_group' has become kind of required. This will be fixed soon, but to have everything working right away, a work around is to add this field 'contract' (with appropriate value) to your terraform script.

Best regards,
Łukasz

**Comment by EmmanuelMaduwuba** [comment]
Hi Lukasz,

I applied the work-around and it worked for me, looking forward to more updates.

Thanks,
Emmanuel

**Comment by rezagh** [comment]
@EmmanuelMaduwuba which workaround?

**Comment by lkowalsk-akamai-com** [comment]
Hi, the workaround is about adding contractID to groups data source. There has been a bug introduced in 0.8.0 which makes this field required.

**Comment by doc82** [comment]
I'm getting this error with the above, using terraform v0.13.0:

`data "akamai_group" "default" {
  contract = data.akamai_contract.default.id
  name     = var.group_name
}`

module.dns_cdn_stack.module.cdn_akamai.data.akamai_group.default: Refreshing state...
Error: rpc error: code = Unavailable desc = transport is closing

**Comment by lkowalsk-akamai-com** [comment]
Hi @EmmanuelMaduwuba, can you please confirm that the issue is fixed with the latest version of Akamai Terraform Provider?

**Comment by EmmanuelMaduwuba** [comment]
Hi, I can confirm it works as expected now
