### ISSUE TITLE
Property changed without any actual changes (related to edge hostnames)

### ISSUE THREAD

**Issue by siwyd** [akamai/terraform-provider-akamai#174]
### Terraform Version
Terraform v0.12.28
Akamai v0.8.0

### Affected Resource(s)
- akamai_property

### Terraform Configuration Files
```hcl
resource "akamai_property" "dsa_foobar" {
  name        = "dsa_foobar_${var.env}"
  contract    = local.akamai_contract
  product     = "prd_Site_Accel"
  group       = data.akamai_group.lfvp.id
  rule_format = "v2020-03-04"
  contact     = local.akamai_contact

  rules = templatefile(
    "akamai-rules.json.tpl",
    {
      cp_code = replace(data.akamai_cp_code.lfvp.id, "cpc_", "")
      env     = var.env
    }
  )

  hostnames = merge(
    {
      "foobar.failover.invalid"          = "foobar.edgekey.net"
      "${var.env == "prod" ? "www" : var.env}.foofoo.be" = "foofoo.edgekey.net"
    },
    var.env == "prod" ? {} : { "${var.env}.barfoo.be" = "barfoo.edgekey.net" }
  )

  lifecycle {
    prevent_destroy = true
  }
}
```

### Expected Behavior
No changes should be made.

### Actual Behavior
Despite no rule or hostname changes, Terraform reports this 'change' in the property config:

`+ edge_hostnames     = (known after apply)`

It only wants to change the property (not the activation), and then creates a new version of the property. When looking at the diff in the Akamai console, there are no actual changes in the hostnames or rules of the new property, only these metadata changes:

```
  | Version 3 |   | Version 2
-- | -- | -- | --
  |  
<comment:note value="Property name: dsa_foobar_prod, version: 3"/> | <comment:note value="Property name: dsa_foobar_prod, version: 2"/>
  |  
<arl-version>3</arl-version> | <arl-version>2</arl-version>
  |  
<value>3</value> | <value>2</value>
  |  
```

Then during the next deploy using Terraform, it wants to change the property again in the same manner and then change the activation as well. This pattern then repeats itself over and over again.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
- The Akamai provider failed to provision the edge hostnames when first creating the property, it was complaining about Site Failover behavior needing to refer to a valid edge hostname... This seemed like a chicken-egg kind of bug with the edge hostnames, so I then proceeded to manually define the edge hostnames in the property. After that, the provider no longer complained about the Site Failover behavior and proceeded to deploy. But so the manual provisioning of edge hostnames might have something to do with it?
- This property exists in three environments: prod, acc and test. For some reason, I have this problem with prod and test, but not with acc. The acc property is perfectly idempotent. The properties are pretty much identical, except for other edge hostnames.

**Comment by siwyd** [comment]
The property that is idempotent has 'edge_hostnames' map in the TF state. I've checked the state for the non-idempotent properties and there the edge_hostnames map are effectively missing.

**Comment by siwyd** [comment]
So I managed to work around this problem for now by manually changing edge_hostnames in the TF state from 'null' to the same map in hostnames.

**Comment by zstlaw** [comment]
@siwyd Thank you for your diligent analysis.  We had noticed the problem and hoped to analyze and fix.  Your work here helped accelerate this process by giving us exactly the information we needed to reproduce the issue and test any fix.

**Comment by siwyd** [comment]
@zstlaw Thanks for the reply. With regards to my initial problem of creating a property with a Site Failover behavior, should I create a seperate issue for that?

**Comment by zstlaw** [comment]
Yes please.  Keeping issues separate helps others with the same issue find and identify workarounds as well as makes it easier to assign work to individual developers.

**Comment by martinstibbe** [comment]
@siwyd Would you have a sanitized akamai-rules.json.tpl available to replicate this issue ?

**Comment by siwyd** [comment]
@martinstibbe I'm on holidays now, so I can't get to that until a few weeks from now. I think for this issue though, the rules don't really matter all that much. I think the main problem was that the edge hostnames were added manually to the property and the provider doesn't add the edge hostnames to the state unless it creates or updates them.

**Comment by martinstibbe** [comment]
@siwyd Just checking in on this issue would like to get rules template as hostnames merge is working for my test case

**Comment by zstlaw** [comment]
Thanks for reporting this issue. Provider has been revamped in the 1.0.0 release. Please upgrade to 1.0.0 and retest your issue. Please refer https://registry.terraform.io/providers/akamai/akamai/latest/docs/guides/1.0_migration for additional details.

If you encounter an issue with release 1.0.0 retesting your scenario, please submit a new issue.

Closing this issue.

**Comment by siwyd** [comment]
@martinstibbe @zstlaw Cheers, completely lost track of this, sorry about that. If I encounter this isse again, I'll resubmit.
