### ISSUE TITLE
unable to create property because terraform says product isn't set

### ISSUE THREAD

**Issue by jellevanhees** [akamai/terraform-provider-akamai#178]
### Terraform Version
Terraform v0.12.24
+ provider.akamai v0.7.2
+ provider.akamai v0.8.1
+ provider.akamai v0.8.0

### Affected Resource(s)
akamai_property

when running apply on the following config terraform says it needs the product id while the product id is set explicitly and is optional according to the docs
### Terraform Configuration Files
```hcl
resource "akamai_property" "SOME-PROPERTY" {
  name    = "somename"
  contact = ["some@contact.com"]
  product = "prd_Site_Accel"
  cp_code = akamai_cp_code.CP-CODE.id
  hostnames = {
    "some.hostname.com" = akamai_edge_hostname.SOME-EDGEKEY.edge_hostname
  }

  rule_format = "v2018-02-27"
  rules       = data.akamai_property_rules.example.json
  origin {
    hostname = "dummy.example.com"
  }
}
```

### Panic Output

Error: product must be specified to create a new property

  on akamai/akamai-property.tf line 1, in resource "akamai_property" "SOME-PROPERTY":
   1: resource "akamai_property" "SOME-PROPERTY" {

### Expected Behavior
it should create the property with the correct product
### Actual Behavior
all other resources are created correctly 
error is thrown as shown above for property

### Steps to Reproduce
1. `terraform apply`

**Comment by martinstibbe** [comment]
@jellevanhees akamai In console GUI PAPI-Use-Prefixes property-manager set-prefixes <true/false> if you toggle this value it may help with this issue

**Comment by jellevanhees** [comment]
@martinstibbe I don know what you mean exactly but i have tried both with the prefix
product = "prd_Site_Accel"
and without the prefix
product = "Site_Accel"

**Comment by martinstibbe** [comment]
@jellevanhees Actually this setting is in Luna web portal I will try to locate documentation link that shows this setting

**Comment by javiergarza** [comment]
The product ID (productId) can be retrieve by running a couple of API calls like (I am using HTTPie):

1) List contracts:
http -A edgegrid -a devrel-admin: -b :/papi/v1/contracts           
```
{
    "accountId": "act_B-C-1FRYVMN",
    "contracts": {
        "items": [
            {
                "contractId": "ctr_C-1FRYVV3",
                "contractTypeName": "AKAMAI_INTERNAL"
            }
        ]
    }
}
```

2) List products on a given contract:
http -A edgegrid -a devrel-admin: -b ":/papi/v1/products?contractId=ctr_C-1FRYVV3"                                                                                
```
{
    "accountId": "act_B-C-1FRYVMN",
    "contractId": "ctr_C-1FRYVV3",
    "products": {
        "items": [
            {
                "productId": "prd_Download_Delivery",
                "productName": "Download_Delivery"
            },
            {
                "productId": "prd_SPM",
                "productName": "SPM"
            },
            {
                "productId": "prd_Adaptive_Media_Delivery",
                "productName": "Adaptive_Media_Delivery"
            },
            {
                "productId": "prd_EdgeConnect",
                "productName": "EdgeConnect"
            },
            {
                "productId": "prd_Dynamic_Site_Del",
                "productName": "Dynamic_Site_Del"
            },
            {
                "productId": "prd_Site_Defender",
                "productName": "Site_Defender"
            },
            {
                "productId": "prd_Security_Failover",
                "productName": "Security_Failover"
            }
        ]
    }
}

```

**Comment by jellevanhees** [comment]
I solved the issue. 

The product was indeed correct and it was set correctly.
after setting both the group and the contract it worked.
So the error indicated that the product was not set but setting the group and contract solved it.

thanks for all the feedback

**Comment by martinstibbe** [comment]
@jellevanhees Please feel free to close ticket if you find everything solved around this issue
Thanks
