### ISSUE TITLE
provider doesn't recognize papi_section argument

### ISSUE THREAD

**Issue by joel-g** [akamai/terraform-provider-akamai#183]
### Terraform Version
12.5

### Affected Resource(s)
Please list the resources as a list, for example:
- opc_instance
- opc_storage_volume

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
provider "akamai" {
  edgerc = "~/.edgerc"
  papi_section = "default"
}

resource "akamai_cp_code" "test" {
    
}
```

### Expected Behavior
Should complain that I have not filled out the cp_code required arguments yet

### Actual Behavior
Error: Unsupported argument

  on /Users/j0g02ab/Terraform/sandboxes/akamai-cp-code-test/main.tf line 3, in provider "akamai":
   3:   papi_section = "default"

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan`

### Important Factoids
Built the `terraform-provider-binary` from source freshly cloned from this repo. Did not let terraform download from registry.

**Comment by martinstibbe** [comment]
@joel-g https://github.com/akamai/terraform-provider-akamai/blob/master/CHANGELOG.md
Has some details on deprecated settings

**Comment by joel-g** [comment]
Deprecated settings? @martinstibbe I'm following the most current version of the docs: https://registry.terraform.io/providers/akamai/akamai/latest/docs

it does the same thing for `property_section`: 
![image](https://user-images.githubusercontent.com/26105158/94198988-fb0bd080-fe6c-11ea-804a-2c9903ca1584.png)

**Comment by martinstibbe** [comment]
@joel-g could you try something like this ...

provider "akamai" {
  edgerc = "~/.edgerc"
  alias = "papi"
}

**Comment by zstlaw** [comment]
Can you specify the version of Akamai provider you are using?  You can get that info by calling terraform init.  

Example :
```
# terraform init
2020/12/14 19:10:14 [WARN] Log levels other than TRACE are currently unreliable, and are supported only for backward compatibility.
  Use TF_LOG=TRACE to see Terraform's internal logs.
  ----

Initializing the backend...

Initializing provider plugins...
- Using previously-installed akamai/akamai v1.0.0

The following providers do not have any version constraints in configuration,
so the latest version was installed.

To prevent automatic upgrades to new major versions that may contain breaking
changes, we recommend adding version constraints in a required_providers block
in your configuration, with the constraint strings suggested below.

* akamai/akamai: version = "~> 1.0.0"
```

Also as others have noted `papi_section` has been deprecated in favor of the term `config_section`.  Both values should still work as of 1.0.0 but if you can give us more information on what version you are using we can help you better.

**Comment by lkowalsk-akamai-com** [comment]
Hi @joel-g, is there any additional help needed? If not, please close the issue.
