### ISSUE TITLE
Product: prd_SPM does not work

### ISSUE THREAD

**Issue by sagardeo2105** [akamai/terraform-provider-akamai#184]
Hi,
I am trying to create a property in akamai using terraform. 
It keeps failing with below error code:
**Error: Unable to find product: "prd_SPM"**

Based on the documentation, I believe this is the default value for Ion

### Affected Resource(s)
Akmai Property creation.

provider "akamai" {
  edgerc = "~/.edgerc"
}

resource "akamai_property" "test" {
  name = "akavadeveloper"

  contact = [""]

  product = "prd_SPM"
  cp_code = akamai_cp_code.cp_code.id
  contract = data.akamai_contract.contract.id
  group = data.akamai_group.group.id

  hostnames = {
	"terraform.example.org" = akamai_edge_hostname.edgeHostNameTest.edge_hostname
  }
  
  rule_format = "latest"
  
  rules = data.akamai_property_rules.rules.json
}

data "akamai_contract" "contract" {
}

data "akamai_group" "group" {
}

resource "akamai_cp_code" "cp_code" {
	name = "test"
	contract = data.akamai_contract.contract.id
	group = data.akamai_group.group.id
	product = "prd_SPM"
}

resource "akamai_edge_hostname" "edgeHostNameTest" {
	product = "prd_SPM"
	contract = data.akamai_contract.contract.id
	group = data.akamai_group.group.id
	edge_hostname =  "terraform.example.org.edgesuite.net"
	ipv4 = true
	ipv6 = false
}

data "akamai_property_rules" "rules" {
	rules {
		behavior {
			name = "origin"
			option {
				key ="cacheKeyHostname"
				value = "ORIGIN_HOSTNAME"
			}
			option {
				key ="compress"
				value = true
			}
			option {
				key ="enableTrueClientIp"
				value = false
			}
			option {
				key ="forwardHostHeader"
				value = "ORIGIN_HOSTNAME"
			}
			option {
				key ="hostname"
				value = "terraformexampleorg.z9.web.core.windows.net"
			}
			option {
				key ="httpPort"
				value = 80
			}
			option {
				key ="httpsPort"
				value = 443
			}
			option {
				key ="originSni"
				value = false
			}
			option {
				key ="originType"
				value = "YOUR_ORIGIN"
			}
			option {
				key ="verificationMode"
				value = "YOUR_OWN"
			}
			option {
				key ="originCertificate"
				value = ""
			}
			option {
				key ="ports"
				value = ""
			}
		}
		behavior {
			name ="cpCode"
			option {
				key ="id"
				value = akamai_cp_code.cp_code.id
			}
            option {
				key =  "name"
				value = akamai_cp_code.cp_code.name
			}
		}
		behavior {
			name ="caching"
			option {
				key ="behavior"
				value = "MAX_AGE"
			}
			option {
				key ="mustRevalidate"
				value = "false"
			}
			option {
				key ="ttl"
				value = "30m"
			}
		}
	}
}

### Expected Behavior
Create Property in Akamai controller

### Actual Behavior
Failed to Created Property: **Error: Unable to find product: "prd_SPM"**

### Steps to Reproduce
1. `terraform plan`
2. `terraform apply`

**Comment by zstlaw** [comment]
Thanks for reporting this issue. This is probably an issue with API client access control grants and not a provider issue. Please work with Akamai support to review your API client configuration.

**Comment by lkowalsk-akamai-com** [comment]
Hi @sagardeo2105, is there any additional help needed? If not, please close the issue.

**Comment by javiergarza** [comment]
@sagardeo2105 you can use the Property Manager CLI to print the list of products available for your contract to ensure you use the right product_id in the .tf file.

For example this is what I see on my account (you need to use the right contractID for your account):
akamai pm --format json list-products --contractId ctr_P-31YPZJ9
[
    {
        "productName": "Download_Delivery",
        "productId": "prd_Download_Delivery"
    },
    {
        "productName": "Security_Failover",
        "productId": "prd_Security_Failover"
    },
    {
        "productName": "Fresca",
        "productId": "prd_Fresca"
    }
]

An error response showing permission issues would mean your API credentials don't have access to the Property Manager API
