### ISSUE TITLE
Error: Invalid Operation: [SOA record set is required for zone xxxxx.com ] during Primary DNS Zone creation using Terraform Akamai Provider.

### ISSUE THREAD

**Issue by csahli** [akamai/terraform-provider-akamai#186]
Hi there,

I am not able to create an AKAMAI DNS Zone of type PRIMARY using the Terraform Akamai provider. I did a lot of different tests but I didn't succeed to have it working.
I am getting following error:

**Error: Invalid Operation: [SOA record set is required for zone xxxxx.com ] during Primary DNS Zone creation using Terraform Akamai Provider.**

### Terraform Version
Terraform v0.12.21
+ provider.akamai v0.8.2

### Affected Resource(s)
Please list the resources as a list, for example:
- akamai_dns_zone

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
data "akamai_authorities_set" "ns" {
  contract = var.akamai_contract
}

resource "akamai_dns_zone" "zone" {
  count               = var.create_akamai_dns_zone == true ? 1 : 0
  contract            = var.akamai_contract
  group                = var.akamai_group
  zone                  = var.zone
  type                   = "primary"
  #masters           = ["${join(",", data.akamai_authorities_set.ns.authorities)}"]
  comment           = local.comment
  sign_and_serve  = false
}

#resource "akamai_dns_record" "ns" {
#  zone           = var.zone
#  name          = var.zone
#  recordtype = "NS"
#  active          = true
#  ttl               = 86400
#  target         = ["a11-67.akam.net.,a14-64.akam.net.,a5-67.akam.net.,a20-65.akam.net.,a4-66.akam.net.,a1-254.akam.net."]
#  depends_on = [akamai_dns_zone.zone]
#}

resource "akamai_dns_record" "record" {
  for_each   = { for record in var.recordsets : join("/", [record.name, record.type]) => record }
  zone       = var.create_akamai_dns_zone == true ? akamai_dns_zone.zone.0.zone : var.zone
  name       = "${each.value.name}.${var.zone}"
  active     = true
  recordtype = each.value.type
  ttl        = each.value.ttl
  target     = each.value.records
  depends_on = [akamai_dns_zone.zone]
}

```

### Output
```
data.akamai_authorities_set.ns: Refreshing state...
akamai_dns_zone.zone[0]: Creating...
akamai_dns_zone.zone[0]: Creation complete after 0s [id=073aa11c-cf44-4296-ab7b-9c7676b957df#aaaabbbccd4.safenetid.com#aaaabbbccd4.safenetid.com]
akamai_dns_record.record["green/A"]: Creating...
akamai_dns_record.record["red/A"]: Creating...
akamai_dns_record.record["blue/A"]: Creating...

Error: Invalid Operation: [SOA record set is required for zone aaaabbbccd4.safenetid.com]

  on main.tf line 26, in resource "akamai_dns_record" "record":
  26: resource "akamai_dns_record" "record" {



Error: Invalid Operation: [SOA record set is required for zone aaaabbbccd4.safenetid.com]

  on main.tf line 26, in resource "akamai_dns_record" "record":
  26: resource "akamai_dns_record" "record" {



Error: Invalid Operation: [SOA record set is required for zone aaaabbbccd4.safenetid.com]

  on main.tf line 26, in resource "akamai_dns_record" "record":
  26: resource "akamai_dns_record" "record" {

```

### Debug Output
https://gist.github.com/csahli/fd1b3a1503259612ae36fb88bfbab98e 

### Panic Output
No Panic

### Expected Behavior
What should have happened?
An Active Primary DNS zone with SOA and NS records should have been created. And subsequent recordsets should have been created.
 
### Actual Behavior
What actually happened?
Got following errors:
`Error: Invalid Operation: [SOA record set is required for zone aaaabbbccd4.safenetid.com]`

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Set environment (credentials for provider)
2. Prepare terraform.tfvars file
```
zone       = "aaaabbbccd4.safenetid.com"
recordsets = [
  {
    name = "blue"
    type = "A"
    ttl  = 30
    records = [
      "10.10.10.10"
    ]
  },
  {
    name = "red"
    type = "A"
    ttl  = 30
    records = [
      "10.10.10.11"
    ]
  },
  {
    name = "green"
    type = "A"
    ttl  = 30
    records = [
      "10.10.10.12"
    ]
  }
]
``` 
3. `terraform init`
4. `terraform plan`
5. `terraform apply`

### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?
We tried to run this code from several places, gitlab kubernetes runner executor on different docker images, from gcp and from aws. We also tried to run it from different personal computers. 

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- https://github.com/akamai/terraform-provider-akamai/issues/9

**Comment by csahli** [comment]
I also faced the same issue reported here: https://github.com/akamai/terraform-provider-akamai/issues/163

**Comment by edglynes** [comment]
Creating and populating a primary zone from the Terraform client requires a specific sequence of steps be taken. SOA and NS records will be created automatically when a primary zone is created. Additionally, the zone must be in the configuration. if already exists, it should be imported. See https://registry.terraform.io/providers/akamai/akamai/latest/docs/guides/get_started_dns_zone

**Comment by lkowalsk-akamai-com** [comment]
Hi @csahli, please let us know if that resolves your issue. If yes, please close the ticket.
