### ISSUE TITLE
The Provided Etag is not the latest

### ISSUE THREAD

**Issue by amcfaddenQHR** [akamai/terraform-provider-akamai#188]
### Terraform Version
terraform v0.13.5

### Affected Resource(s)
Please list the resources as a list, for example:
- akamai_property

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```terraform {
  source = "git::git@github.com:/terraform-modules.git//deployments/service/frontend?ref=akamai_dns"
}

include {
  path = "${find_in_parent_folders()}"
}

inputs = {
  env_level       = "d"
  property_name  = "d5-host.com"
  frontend_hostnames = ["d5-service1.host.com","d5-service2.host.com","d5-service3.host.com","d5-service4.host.com"]
  activate_staging = true
  activate_production = true
}
```

### Debug Output
https://gist.github.com/amcfaddenQHR/70fca4dfef02e019ab47c562a6ec40a0

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
Expected behavior is to update or the Akamai property

### Actual Behavior
The Akamai property was created via the terraform script with no issues.  The property was then altered manually in the gui, creating new versions.  Then deploying an update via terraform the terraform fails due to "The provided Etag is not the latest"

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by ssrirama-aka** [comment]
@amcfaddenQHR What version of the Akamai provider are you using?

**Comment by amcfaddenQHR** [comment]
We are running Akamai Provider version 0.10.2

**Comment by ssrirama-aka** [comment]
@amcfaddenQHR We tested this with provider version 0.10.2. The steps we followed:

1. Terraform apply to create a property version
2. Edit and revise property directly in Akamai Control Center
3. Leave the Property Manager open in Akamai Control Center
4. Modify Terraform script and run Terraform apply

New version of property created, no errors encountered in Terraform.

Can you provide details of the sequence of steps you executed? Can you rerun your test, with logging turned on TF_LOG=DEBUG, and setting TF_LOG_PATH to a path and log file name? Having the log file will help.

**Comment by amcfaddenQHR** [comment]
Created via Terraform version 1 staging/prod migrated over 4 "Property Hostnames" from a different property as the property7 was set to activate
Created via akamai as we re activated the hostnames on the original properties forcing version 2 staging/prod inactive as the above 4 "Property Hostnames" were migrated back as the host migration was and unexpected result
Created via web GUI version 3/4/5 in an inactive state and we are no longer able to use terraform to update the properties
Created via web GUI version 6 created from version 5 and activated pulling the 4 "Property Hostnames" back in from the original property but we are still unable to use terraform.

Trace out put
2020/11/12 18:13:19 [INFO] Terraform version: 0.13.5
2020/11/12 18:13:19 [INFO] Go runtime version: go1.14.7
2020/11/12 18:13:19 [INFO] CLI args: []string{"/home/terraform/.tfenv/versions/0.13.5/terraform", "--version"}
2020/11/12 18:13:19 [DEBUG] Attempting to open CLI config file: /home/terraform/.terraformrc
2020/11/12 18:13:19 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2020/11/12 18:13:19 [DEBUG] ignoring non-existing provider search directory terraform.d/plugins
2020/11/12 18:13:19 [DEBUG] ignoring non-existing provider search directory /home/terraform/.terraform.d/plugins
2020/11/12 18:13:19 [DEBUG] ignoring non-existing provider search directory /home/terraform/.local/share/terraform/plugins
2020/11/12 18:13:19 [DEBUG] ignoring non-existing provider search directory /usr/local/share/terraform/plugins
2020/11/12 18:13:19 [DEBUG] ignoring non-existing provider search directory /usr/share/terraform/plugins
2020/11/12 18:13:19 [INFO] CLI command args: []string{"version", "--version"}

**Comment by amcfaddenQHR** [comment]
New debug  output
https://gist.github.com/amcfaddenQHR/c0bd94714e5e67eb6331a23fb205f568

**Comment by ssrirama-aka** [comment]
@amcfaddenQHR Thank you for the debug output. Our team was able to reproduce the 412 error executing these steps:

1. Create new property through terraform with a set of hostnames

2. Update the hostnames in Control Center UI and activate the version

3. Update the hostnames again through terraform this time and you will run into 412 error as the new version create will fail

We are working on fixing this issue.

**Comment by amcfaddenQHR** [comment]
Any idea on the turn around on this bug?  It is preventing us from moving forward on our own development.
Thanks

**Comment by 110hideki** [comment]
I had the same problem, and the workaround worked well. However, hope to fix the issue.

**Comment by amcfaddenQHR** [comment]
Appreciate the heads up, thanks!

**Comment by amcfaddenQHR** [comment]
New provider version has resolved the issue, thank you.
