### ISSUE TITLE
Inverted parameters when: recordtype = SRV

### ISSUE THREAD

**Issue by bogdan-grozoiu** [akamai/terraform-provider-akamai#19]
Hi there,

I've found an issue when creating records of type **SRV**

### Terraform Version
- Terraform v0.12.5
- provider.akamai v0.1.1

### Affected Resource(s)
- akamai_dns_record (**SRV** record type)

### Expected Behavior
When using `recordtype = "SRV"`, the values provided for the parameters `priority`, `port`, `weight` should create a record in the following format: `<priority> <weight> <port> <target>`

Example: `<priority> <weight> <port> <target>` --> `100 1 443 sipdir.online.lync.com.`

### Actual Behavior
When using `recordtype = "SRV"`, the values provided for the parameters `priority`, `port`, `weight` create a wrong DNS record, as following:  ` <weight> <port>  <priority> <target>`

Example: `< weight > < port > < priority > <target>` --> `1 443 100 sipdir.online.lync.com.`

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. HCL:
```HCL
resource "akamai_dns_record" "_sip__tls_acc_companydomain_com" {
  zone       = var.zone
  name       = "_sip._tls.acc.companydomain.com"
  recordtype = "SRV"
  ttl        = var.default_ttl
  active     = true
  target = [
    "sipdir.online.lync.com",
  ]
  priority = "443" #BUG This is actually: PORT
  weight   = "100" #BUG This is actually: PRIORITY
  port     = "1"   #BUG This is actually WEIGHT
}
```
2. `terraform apply`

### Workaround

Intentionally set the wrong values, as following
```
priority = <Value of PORT>
weight = <Value of PRIORITY>
port = <Value of WEIGHT>
```

### Important Factoids
- N/A

### References
 - N/A

**Comment by dshafik** [comment]
@grozoiu This has been fixed in #20, and will be included in the next release which I intent to make later this week.
