### ISSUE TITLE
 Unrelated property changes are shown without any actual changes 

### ISSUE THREAD

**Issue by julidekadam** [akamai/terraform-provider-akamai#192]
### Terraform Version

Terraform v0.13.5
+ provider registry.terraform.io/-/akamai v0.10.2
+ provider registry.terraform.io/akamai/akamai v0.10.2
+ provider registry.terraform.io/hashicorp/aws v3.15.0

### Affected Resource(s)
List the resources as a list, for example:
- akamai_gtm_property

### Terraform Configuration Files
```
resource "akamai_gtm_property" "xyz-3" {
  domain                 = "platform.akadns.net"
  name                   = "xyz-3"
  type                   = "weighted-round-robin"
  score_aggregation_type = "median"
  handout_limit          = 5
  static_ttl             = 300
  handout_mode           = "normal"


  traffic_target {
    datacenter_id = module.datacenters.xyz-3_id
    enabled       = false
    handout_cname = "public-gateway.xyz-3.platform.net"
    weight        = 0
    servers       = ["public-gateway.xyz-3.platform.net"]
  }

  liveness_test {
    name                        = "liveness test"
    test_interval             = 60
    test_object               = "healthz/ready"
    test_object_port       = 30024
    test_object_protocol = "HTTPS"
    test_timeout         = 25
    http_error3xx        = true
    http_error4xx        = true
    http_error5xx        = true
    disabled             = true
    http_header {
      name               = "Host"
      value              = "public-gateway.xyz-3.platform.net"
    }

  }

}
```

### Debug Output

https://gist.github.com/julidegulen/6ab0b7415dd3a777f3aa52aa439964c8

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.
No

### Expected Behavior

The diff should show only the relevant changes and apply all proposed changes.

### Actual Behavior

`terraform plan` shows unrelated changes i.e.`static_ttl`. Despite no rule or property changes, terraform shows some extra changes in the plan. If accept proposed changes and run `terraform apply` those changes are not applied and keeps showing. 
When looking at the Akamai console, there are no actual changes applied. 

### Steps to Reproduce

Please list the steps required to reproduce the issue, for example:
1. `terraform plan`

### Important Factoids

No

### References

No

**Comment by TristanBaoui** [comment]
static_ttl is returned 'null' for this type of properties, so no [default value](https://github.com/akamai/terraform-provider-akamai/blob/25c506db3dcd64b505483807228e974b3870b9ff/pkg/providers/gtm/resource_akamai_gtm_property.go#L80) should be set in code  in order not to launch an update at every apply action.

A workaround for the time being is to set static_ttl = 0 in the resource parameters.
The equivalent to DNS TTL parameter in UI is dynamic_ttl parameter in the provider.

**Comment by edglynes** [comment]
Issue reproduced.

**Comment by edglynes** [comment]
Property  Static TTL  deprecated  with the introduction of StaticRRSets. static_ttl should not be in the Terraform  zone configuration and will be ignored. A warning will be generated if present in the next provider update.

**Comment by lkowalsk-akamai-com** [comment]
Hi, with new release there is a proper warning added for this case. Please close this case if you do not need any further assistance.
