### ISSUE TITLE
Property with nested rules and empty behaviors are failing

### ISSUE THREAD

**Issue by TristanBaoui** [akamai/terraform-provider-akamai#194]
### Terraform Version
Terraform v0.13.5
+ provider registry.terraform.io/akamai/akamai v0.11.0
+ provider registry.terraform.io/hashicorp/local v2.0.0

### Affected Resource(s)
- resource "akamai_property"

### Terraform Configuration Files
```hcl
resource "akamai_property" "food" {
	name = "food.${var.domain}_pm"
	contact = [var.user_email]
	product = "prd_SPM"
	contract = data.akamai_contract.default.id
	group = data.akamai_group.default.id
	hostnames = {
		"food.${var.domain}" = akamai_edge_hostname.food.edge_hostname
	}
	rule_format = "v2020-03-04"
	rules = data.local_file.rules.content
	variables = akamai_property_variables.origin.json
}
```

### Debug Output
https://gist.github.com/TristanBaoui/4f985de02247e8bc1e6e14764fe2488e

### Expected Behavior
Rule tree to be updated

### Actual Behavior
Rule tree is not udpated

### Steps to Reproduce
1. Create a property with nested rules, some of them should have empty behaviors
1. `terraform apply`

### Important Factoids
Rules with empty behaviors are expected when nesting several rules
The same rules.json sent through the raw API call is working great

### References
https://github.com/akamai/AkamaiOPEN-edgegrid-golang/blob/v2/pkg/papi/rule.go#L176
The validation here seems to be causing the error, 'Behaviors' should not be Required

**Comment by ericrichtert** [comment]
Is this issue solved in the latest version?

**Comment by hitsumabushi** [comment]
In v1.2.0(current latest version), I got same error.

**Comment by lkowalsk-akamai-com** [comment]
This issue should be resolved in v1.2.1 release, which is available now.

**Comment by lkowalsk-akamai-com** [comment]
Hi @TristanBaoui , we believe that issue is fixed already. Please confirm and close the issue.

**Comment by TristanBaoui** [comment]
@lkowalsk-akamai-com Hi !
It's all good (tested in 1.4) thanks !
