### ISSUE TITLE
[v1.0.0] resource_akamai_cp_code "product_id" is not expected here

### ISSUE THREAD

**Issue by carnei-ro** [akamai/terraform-provider-akamai#196]
Following the pattern of other resources, I think `resource_akamai_cp_code` should also deprecate `product` and use `product_id`, but this is not the case. In version `v1.0.0` we have `contract_id`, `group_id` but no `product_id`, fall backing to "old" `product`.

**Comment by carnei-ro** [comment]
https://github.com/akamai/terraform-provider-akamai/pull/197

**Comment by lkowalsk-akamai-com** [comment]
This issue should be resolved in v1.2.1 release, which is available now.
