### ISSUE TITLE
rpc error : code = Unavailable desc = transport is closing

### ISSUE THREAD

**Issue by ojesvi** [akamai/terraform-provider-akamai#206]
Hello,
I am trying to run terraform apply and getting this error. 

Terraform version on image:
terraform --version
Terraform v0.14.2
+ provider registry.terraform.io/akamai/akamai v1.0.0
+ provider registry.terraform.io/alxrem/jsonnet v1.0.1
+ provider registry.terraform.io/hashicorp/local v2.0.0

debug output / crash log: https://gist.github.com/ojesvi/cb65d8a3f153ce0b9319a925e8232e2f

Steps to Reproduce
Please list the steps required to reproduce the issue, for example:

terraform plan
terraform apply

**Comment by ssrirama-aka** [comment]
@ojesvi Does your Terraform configuration use the akamai_property_rules_template data source available starting release 1.0.0?

**Comment by ojesvi** [comment]
@ssrirama-aka .No, I am using akamai_property_rules_template

**Comment by ssrirama-aka** [comment]
Please share your akamai_property_rules_template data source configuration. If there is any sensitive information, please mask / sanitize it before posting.

**Comment by ojesvi** [comment]
@ssrirama-aka  please check new files: https://gist.github.com/ojesvi/cb65d8a3f153ce0b9319a925e8232e2f

**Comment by ynohat** [comment]
@ssrirama-aka hi, I took it upon myself to share the actual rule tree generated by the template in @ojesvi's [gist](https://gist.github.com/ojesvi/cb65d8a3f153ce0b9319a925e8232e2f).
We successfully updated the configuration with this same rule tree using direct PAPI calls.

**Comment by andersquist** [comment]
Any updates on this issue? Having the same problem.

**Comment by lkowalsk-akamai-com** [comment]
Hi, @andersquist @ojesvi - could you please try again with latest version?
