### ISSUE TITLE
IAM (Sub)Provider

### ISSUE THREAD

**Issue by stack72** [akamai/terraform-provider-akamai#209]
Hi

Is there any reason why the new IAM sub provider isn't implemented like that of property or GTM? Basically, we use the go package to be able to scaffold the corresponding [Pulumi provider](https://github.com/pulumi/pulumi-akamai)

In the Pulumi code, we are able to get access to the providers using code similar to the following

```
providerFunc := akamai.Provider(
		gtmProvider.Subprovider(),
		appSecProvider.Subprovider(),
		dnsProvider.Subprovider(),
		propertyProvider.Subprovider(),
	)
```

But IAM doesn't follow a similar convention of using a Subprovider and instream does it's registration in an init() func - is this for a specific usecase?

Paul

**Comment by clstokes** [comment]
Hi Akamai team, this is blocking Pulumi from upgrading (https://github.com/pulumi/pulumi-akamai/issues/32) to better support some customers of yours. Can we get this addressed?

**Comment by lkowalsk-akamai-com** [comment]
Hi, we acknowledge this issue and we will plan to fixe it when we will be adding additional features for IAM subprovider. For now, there is not timeline I can share with you.

**Comment by stack72** [comment]
Thanks for the update here @lkowalsk-akamai-com 

would you be open to a pull request if I sent it? I am happy to do that if it would help get it updated faster

**Comment by lkowalsk-akamai-com** [comment]
@stack72 Thanks for wanting to contribute. We are open for a PR, but keep in mind that the change need to be in line with other Akamai subproviders design. We will review this PR in our cycle and let you know our feedback.

**Comment by lkowalsk-akamai-com** [comment]
Hi @stack72, therere was major refactoring done to the IAM subprovider that should resolve your issue. Please let us know if that is not the case. Closing the ticket, feel free to reopen in case of any follow ups.

**Comment by stack72** [comment]
@lkowalsk-akamai-com this is wonderful news :) I look forward to bringing this into the Pulumi provider
