### ISSUE TITLE
Property activation version incorrectly updated in state file when there are errors in the GetRuleTree response

### ISSUE THREAD

**Issue by henrytk** [akamai/terraform-provider-akamai#219]
When creating _and_ updating property activations there is a check of the rule tree. If this errors the state file does not get updated: https://github.com/akamai/terraform-provider-akamai/blob/release/v1.3.0/pkg/providers/property/resource_akamai_property_activation.go#L536-L537 - this is correct behaviour.

However, if the call to get the rule tree doesn't error, but the _response_ contains errors, the state file _does_ get updated. This is incorrect behaviour, because the property does not get activated when these errors are present.

### Terraform Version

0.12.9

### Affected Resource(s)

- akamai_property_activation

### Terraform Configuration Files

Any configuration of this resource will do, so long as you are trying to activate a property with rule tree errors

### Expected Behavior

State file should not be updated as there are errors with the rule tree and the property has not been activated.

### Actual Behavior

The property activation version is updated in the state file, despite not being activated due to rule tree errors.

**Comment by lkowalsk-akamai-com** [comment]
Hi, we believe this issue is fixed now. Please test and close the case.
