### ISSUE TITLE
Ability to Manage Users, Groups and Permissions

### ISSUE THREAD

**Issue by MarkDordoy** [akamai/terraform-provider-akamai#22]
Hello 

I would love to see the ability to manage Identity Management via terraform. My main purpose for this would be to provision / deprovision an account, add and remove an account to a group, create/delete a group. 

With this and SSO enabled it would allow me to automate my user provisioning. Its something cloudflare do and i'd love to see this provider to have feature parity

Thanks

**Comment by dekimsey** [comment]
Creating users would be nice, but more importantly (for us) it's creating API access tokens. Those are typically specific to where they are being used. I'd love to be able to generate them in terraform for easier management.

**Comment by lkowalsk-akamai-com** [comment]
Hi @MarkDordoy, this functionality is now available. Please close the ticket.
