### ISSUE TITLE
Error: rpc error: code = ResourceExhausted desc = grpc: received message larger than max (4861596 vs. 4194304)

### ISSUE THREAD

**Issue by ericrichtert** [akamai/terraform-provider-akamai#220]
After upgrading from version 0.9.1 to 1.4.0, we get this error:

Error: rpc error: code = ResourceExhausted desc = grpc: received message larger than max (4861596 vs. 4194304)

λ terraform version
Terraform v0.14.7
+ provider registry.terraform.io/akamai/akamai v1.4.0
+ provider registry.terraform.io/hashicorp/local v2.1.0

Issue is caused by a long list of warnings in the property.

Akamai issue:  F-CS-4963966

**Comment by lkowalsk-akamai-com** [comment]
Hi @ericrichtert , this looks like an error connected to Terraform limitation of the state file. There is currently similar case opened in Terraform queue - https://github.com/hashicorp/terraform-provider-local/issues/28 
Our advise is to limit the size of the terraform state file.

**Comment by ericrichtert** [comment]
@lkowalsk-akamai-com I can only reduce the size of the terraform state, if the akamai provider does not send 4MB of json data with warnings. These warnings are not in the terraform state with version 0.9.1, they are in version 1.4.0 and 1.5.0. You can find the details of the warnings in case F-CS-4963966.

**Comment by ericrichtert** [comment]
This issue is not solved with 1.51. I'll send the TRACE logs via F-CS-4963966

**Comment by robertolopezlopez** [comment]
Hi @ericrichtert ,

Thank you for reporting this - we have finally addressed it with [yesterday release](https://github.com/akamai/terraform-provider-akamai/releases/tag/v1.7.1). It should be fixed now, thus I will close the issue. If you continue experiencing this problem, please do not hesitate to reopen it.
