### ISSUE TITLE
Error when upgrading from 1.3.1 to 1.5.0: Error: missing expected [

### ISSUE THREAD

**Issue by siwyd** [akamai/terraform-provider-akamai#222]
I'm upgrading to 1.5.0, which means migrating to the new hostnames format. When doing so, I get errors unfortunately.

### Terraform Version
0.14.9

### Affected Resource(s)
akamai_property

### Expected Behavior
There should be no changes.

### Actual Behavior
Terraform errors:

```
Error: missing expected [



Error: missing expected [



Error: missing expected [



Error: missing expected [
```

This matches the fact that there are 4 properties in the state that I'm migrating. There are properties with a single hostname and properties with multiple hostnames.

**Comment by ericrichtert** [comment]
I can confirm this issue. Even the TF_LOG=TRACE doesn't show any issue.
λ terraform version
Terraform v0.14.7
+ provider registry.terraform.io/akamai/akamai v1.5.0
+ provider registry.terraform.io/hashicorp/local v2.1.0

**Comment by lkowalsk-akamai-com** [comment]
That is expected error from Terraform if the state becomes invalid due to breaking change in syntax. This is in documentation and changelog to fix the config and state after version upgrade. 
https://registry.terraform.io/providers/akamai/akamai/latest/docs/resources/property

Below are steps that could be used to fix this:
1.	Upgrade to latest(1.5.0) and update tf config with new block type syntax
2.	terraform state rm akamai_property.example. (Terraform also creates a state backup suffixed with timestamp)
3.	terraform import akamai_property. example prp_12345 (Refreshes the local state with new 1.5.0 syntax for hostnames). Resume normal operations

Sorry for any inconvenience caused by this change.

**Comment by ericrichtert** [comment]
I really don't understand why every new version of this provider has a new syntax or new issues. The latest stable is 0.9.1. As I'm waiting for a solution on #222, I can't continue with this one.

Changing the TF code every time and waiting for bugfixes really takes to mucht time.

**Comment by siwyd** [comment]
Aha, I did miss that because the info on the state was at the top of the akamai_property docs and not with the hostnames argument. I've made a small PR to perhaps improve on that a bit to avoid other people running into that: https://github.com/akamai/terraform-provider-akamai/pull/223.

I've reimported the props and the Terraform plan is working now, thanks for the help.

**Comment by ericrichtert** [comment]
So the correct migration is now:

1. Have a applied environment based on 1.4.0
2. Upgrade the akamai provider to 1.5.0
3. Change the hostnames TF code in your properties
4. Remove the properties from the terraform state
5. Import the properties in the terraform state
6. Pull the terraform state, add the correct value of product_id to the state file
7. Push the changed state file to your backend. In case you use AWS DynamoDB for locking, first remove the digest record from your DynamoDB table.
8. Run a terraform apply step

This is a lot work for an update of a terraform provider.

**Comment by carnei-ro** [comment]
The product_id not being populated on import is an old issue lol.
That’s why I created the script posted at #208 .
I think it is easier fix the hostnames at the state file.

**Comment by siwyd** [comment]
I managed to fix the error, but every time I do a plan, it wants to perform changes:

``` 
  # akamai_property.dd_lfvp_stv will be updated in-place
  ~ resource "akamai_property" "dd_lfvp_stv" {
        id                 = "prp_593090"
      ~ latest_version     = 22 -> (known after apply)
        name               = "dd_lfvp_stv"
      ~ production_version = 22 -> (known after apply)
      ~ staging_version    = 21 -> (known after apply)
        # (8 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }

  # akamai_property_activation.dd_lfvp_stv will be updated in-place
  ~ resource "akamai_property_activation" "dd_lfvp_stv" {
        id            = "prp_593090:PRODUCTION"
      ~ version       = 22 -> (known after apply)
        # (5 unchanged attributes hidden)
    }
```

When I do an apply, it 'changes' things, but nothing really happens. There is no activation or anything like that. How do I get idempotence again?

**Comment by lkowalsk-akamai-com** [comment]
Hi @siwyd, Is there anything more we can help under this issue? I believe you were able to overcome the breaking changes and this is working now and the issue about idempotency is traced separately. Can we close this issue?

**Comment by siwyd** [comment]
@lkowalsk-akamai-com Yes, for the other problem I've created another issue: https://github.com/akamai/terraform-provider-akamai/issues/226
