### ISSUE TITLE
Import of property does not set the product_id

### ISSUE THREAD

**Issue by ericrichtert** [akamai/terraform-provider-akamai#224]
For the migration to 1.5.0, I removed the property from state and did an import.

After the import, the state file has  _"product_id": null_ in the property.

The next terraform apply shows an error:
 Error: property attribute "product_id" cannot be changed after creation (immutable)

λ terraform version
Terraform v0.14.7
+ provider registry.terraform.io/akamai/akamai v1.5.0
+ provider registry.terraform.io/hashicorp/local v2.1.0

Snippet of the propery tf code:

> resource "akamai_property" "tf-property-xxxx" {
>   name        = "tf-property-${var.functionelehostnaam}"
>   product_id  = "prd_Site_Accel"

**Comment by anandg1984** [comment]
I get the same error after upgrading to 1.5.0, after removing the property from state and import.

Error: property attribute "product_id" cannot be changed after creation (immutable)

**Comment by carnei-ro** [comment]
I have this issue prior the provider 1.0.0. It is a really old bug.
I am doing `state pull`, editing the hostname part and the serial, then `state push`. At #208 I posted my really silly script that does the job.

**Comment by lkowalsk-akamai-com** [comment]
Hi, we believe this issue is fixed now. Please test and close the case.

**Comment by ericrichtert** [comment]
This is solved
