### ISSUE TITLE
[1.5.1] 'akamai_appsec_configuration' resource does not work as expected

### ISSUE THREAD

**Issue by elfinston** [akamai/terraform-provider-akamai#233]
Hi Team,

I faced an issue that could have not created a new security configuration using Terraform provider(v1.5.1) with 'akamai_appsec_configuration' resource. 

The error message is a little bit strange because it said "create KDD config from open(API?) is not allowed", not KSD. 
Also, the error code probably '403(FORBIDDEN)'.
I am not sure why 403 returned because I tried the test on an account that has entitlement AppSec Beta. 

The other resources of AppSec are worked well.

### Terraform Version
```
[elfin@localhost security-configuration-allnew]$ terraform -v
Terraform v0.15.1
on linux_amd64
+ provider registry.terraform.io/akamai/akamai v1.5.1
```

### Affected Resource(s)
- akamai_appsec_configuration

### Terraform Configuration Files
https://github.com/elfinston/private/blob/main/akamai.tf

### Actual Behavior
Returned error message below.
```
akamai_appsec_configuration.create_config: Creating...

Error: Title: This operation is invalid; Type: https://problems.luna.akamaiapis.net/appsec-configuration/error-types/FORBIDDEN-OPERATION; Detail: create KDD config from open is not allowed.

with akamai_appsec_configuration.create_config, on akamai.tf line 19, in resource "akamai_appsec_configuration" "create_config": 19: resource "akamai_appsec_configuration" "create_config" {
```

### Steps to Reproduce
1. `terraform apply`

**Comment by atuljain16** [comment]
Akamai Japan has KSD & KDD in one contract, this combination of products in a contract is not supported. Plz remove the KDD eng prod and try again.

**Comment by lkowalsk-akamai-com** [comment]
Hi @elfinston, if this issue is resolved, please close this ticket.

**Comment by alilakhani786** [comment]
Hi, I am facing the same issue. We had KDD, KSD and AAP in the contract. We requested to remove KDD and KSD after seeing this post. Now we have only AAP in the contract. However, I am still seeing this issue.

ACC Account: Akamai South East Asia SEA

Terraform will perform the following actions:

  # akamai_appsec_configuration.akamai_appsec will be created
  + resource "akamai_appsec_configuration" "akamai_appsec" {
      + config_id   = (known after apply)
      + contract_id = "V-434SAU2"
      + description = "Security configuration ew.lakhanis.net"
      + group_id    = 215287
      + host_names  = [
          + "ew.lakhanis.net",
        ]
      + id          = (known after apply)
      + name        = "ew.lakhanis.net"
    }

Plan: 1 to add, 0 to change, 0 to destroy.
akamai_appsec_configuration.akamai_appsec: Creating...
╷
│ Error: Title: This operation is invalid; Type: https://problems.luna.akamaiapis.net/appsec-configuration/error-types/FORBIDDEN-OPERATION; Detail: create KDD config from open is not allowed.
│ 
│   with akamai_appsec_configuration.akamai_appsec,
│   on main.tf line 8, in resource "akamai_appsec_configuration" "akamai_appsec":
│    8: resource "akamai_appsec_configuration" "akamai_appsec" {

**Comment by atuljain16** [comment]
@alilakhani786 Thanks for reaching out to us, It seems scopes are not refreshed on this account. I could still see the KDD entitlement coming back from our authorization service. We will request refresh of scopes and keep you posted.

**Comment by lkowalsk-akamai-com** [comment]
Hi @alilakhani786, is this issue still ocuring for you?
