### ISSUE TITLE
DataStream 2 support

### ISSUE THREAD

**Issue by siwyd** [akamai/terraform-provider-akamai#238]
As the title says :)

**Comment by lkowalsk-akamai-com** [comment]
Hi @siwyd
DataStream 2 is one of our immediate priorities. This support for it should be added in Q4 this year.

**Comment by lkowalsk-akamai-com** [comment]
Hi @siwyd 
we released today new version of Akamai Terraform Provider which includes support for DataStream (Version 2). More details can be found in the [Release notes v1.8.0](https://github.com/akamai/terraform-provider-akamai/releases/tag/v1.8.0)

**Comment by siwyd-garvis** [comment]
@lkowalsk-akamai-com I'm no longer working with Akamai I'm afraid, but I'll let ex-colleagues know, thanks for the heads-up!
