### ISSUE TITLE
Provisioning errors with datastream 2 behavior settings

### ISSUE THREAD

**Issue by siwyd** [akamai/terraform-provider-akamai#239]
When this kind of behavior is used in the rules, the activation fails.

```
            {
                "name": "datastream",
                "options": {
                    "logEnabled": true,
                    "logStreamName": ${ds2_id},
                    "samplingPercentage": 100,
                    "streamType": "BEACON_AND_LOG",
                    "enabled": true,
                    "datastreamIds": ""
                }
            }
```

Activation error:

```
│ Error: activation cannot continue due to rule errors: [
│     {
│         "behavior_name": "",
│         "detail": "[validation.generic_behavior_issue.invalid_data_stream_log_selected]",
│         "error_location": "#/rules/behaviors/20",
│         "instance": "",
│         "status_code": 0,
│         "title": "",
│         "type": "https://problems.luna.akamaiapis.net/papi/v0/validation/generic_behavior_issue.invalid_data_stream_log_selected"
│     }
│ ]
│
│   with akamai_property_activation.dsa_lfvp_api,
│   on akamai.tf line 58, in resource "akamai_property_activation" "dsa_lfvp_api":
│   58: resource "akamai_property_activation" "dsa_lfvp_api" {
```

Weirdly, I can activate the property version that was created by Terraform just fine in the GUI. There are no rule errors mentioned there whatsoever. The problem seems to be with the logStreamName option. If I don't use the Datastream 2 settings in the behavior, it works fine.

**Comment by mgwoj** [comment]
Dear @siwyd, 

Please verify if you still have this issue after changing `"logStreamName": ${ds2_id},` into ` "logStreamName": "${ds2_id}",`? What is the value of `ds2_id` property?
If problem persists, please provide a copy of your `*.tf` and `rules.json`. This should help us diagnose the problem.

Thanks,
Michal

**Comment by siwyd** [comment]
@mgwoj Sorry, I forgot to update this issue. I opened an Akamai support case where we were debugging this and all of a sudden this was not reproducible anymore as if the Akamai backend suddenly decided to accept the input. The case ID was F-CS-5118838 .
