### ISSUE TITLE
Invalid Resource Type: akamai_cps_enrollment

### ISSUE THREAD

**Issue by MarkDordoy** [akamai/terraform-provider-akamai#24]
### Terraform Version
```
Terraform v0.12.3
provider.akamai v0.1.2
```
### Affected Resource(s)
Please list the resources as a list, for example:
- akamai_cps_enrollment

### Expected Behavior
Terraform should pass validation

### Actual Behavior
The provider provider.akamai does not support resource type
"akamai_cps_enrollment".

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform init`
2. `terraform validate`

### Comments
Im trying to do terraform validate against a single resource of "akamai_cps_enrollment" but get the provider doesnt support the resource type. Same issue also occurs with version 0.1.1 of the provider

**Comment by MarkDordoy** [comment]
Copy of providers file 
```
terraform {
  required_version = "=0.12.3"
}

provider "akamai" {
    version = "=0.1.2"
    edgerc = "~/.edgerc"

}
```

main.tf with my data omitted 
```
resource "akamai_cps_enrollment" "my_cps_enrollment" {
    contract_id     = "******"
    admin_contact   = ["email@domain.com"]
    validation_type = "ov"
    techcontact     = ["email@domain.com"]
    ra              = "symantec"
    certificate_type = "wildcard"
    change_management = "false"
    csr {
        cn = "*.domain.live"
        c = "GB"
        l = "London"
        o = "O"
        ou = "OU"
        sans = ["domain.live","*.domain.live"] 
    }

    org {
        name = "******"
        addressLineOne = "****"
        addressLineTwo = "*****"
        city = "London"
        region = "London"
        postalCode = "******"
        country = "UK"
        phone = "*********"
    }
}
```

**Comment by dshafik** [comment]
@MarkDordoy for a number of reasons, we decided to hold back the release of certificate management (not least of which, the fact it would extend your `terraform apply` time by an unreasonable amount). We expect to re-add this later this year. 

Where did you see documentation for this?

**Comment by MarkDordoy** [comment]
@dshafik I see the documentation on the main terraform site: https://www.terraform.io/docs/providers/akamai/r/cps_enrollment.html

**Comment by dshafik** [comment]
@MarkDordoy that is a mistake, sorry about that! I'm in the process of updating all the documentation to ensure accuracy today, so that will go away shortly, along with numerous fixes.

**Comment by dshafik** [comment]
Closing this out as invalid for now
