### ISSUE TITLE
DNS Zone import always null value for contract and group

### ISSUE THREAD

**Issue by chipgata** [akamai/terraform-provider-akamai#242]
Hi there,

I have using akamai terraform with import function, but seen there have something wrong when import DNS Zone. Please help to check and give me some feedback if there have something need to fix and improve. Thanks team!

### Terraform Version
0.15.4

### Akmai provider Version
1.5.1

### Affected Resource(s)
- Import DNS Zone

### Terraform Configuration Files
```hcl
module "akamai_dns" {
  source = "../../modules/dns"

  akamai_contract = data.akamai_contract.current.id
  akamai_group = data.akamai_group.current.id
  akamai_zone_name = local.akamai_zone_name
  akamai_zone_type = "primary"
}

#### Module code modules/dns
resource "akamai_dns_zone" "this" {
    count = var.akamai_create_dns_zone ? 1 : 0

    contract = var.akamai_contract                # Contract ID variable
    group = var.akamai_group                      # Group ID variable
    zone = var.akamai_zone_name                   # Zone Name
    type = var.akamai_zone_type                   # Zone type
    masters = var.akamai_zone_masters             # Zone master(s)
    comment = var.akamai_zone_comment != "" ? var.akamai_zone_comment : ""
    sign_and_serve = var.akamai_zone_sign_and_serve ? true : false
    sign_and_serve_algorithm = var.akamai_zone_sign_and_serve && var.akamai_zone_sign_and_serve_algorithm != "" ? var.akamai_zone_sign_and_serve_algorithm : ""
    target = var.akamai_zone_target != "" ? var.akamai_zone_target : ""
    end_customer_id = var.akamai_zone_end_customer_id != "" ? var.akamai_zone_end_customer_id : ""
}

```

### Expected Behavior
Should have contract and group values on `terraform.tfstate` file

### Actual Behavior
Don't have contract and group values on `terraform.tfstate` file
```json
{
      "module": "module.akamai_dns",
      "mode": "managed",
      "type": "akamai_dns_zone",
      "name": "this",
      "provider": "provider[\"registry.terraform.io/akamai/akamai\"]",
      "instances": [
        {
          "index_key": 0,
          "schema_version": 0,
          "attributes": {
            "activation_state": "ACTIVE",
            "alias_count": 0,
            "comment": "test DNS zone",
            "contract": null,
            "end_customer_id": "",
            "group": null,
            "id": "xxxxxx",
            "masters": [],
            "sign_and_serve": false,
            "sign_and_serve_algorithm": "",
            "target": "",
            "tsig_key": [],
            "type": "PRIMARY",
            "version_id": "xxxxxx",
            "zone": "xxxxxx.com"
          },
          "sensitive_attributes": [],
          "private": "xxxxxx"
        }
      ]
    }
```

### Steps to Reproduce
`terraform import module.akamai_dns.akamai_dns_zone.this[0] xxxxxx.com`

**Comment by edglynes** [comment]
@chipgata pls provide the configurations for the data resources referenced and the associated tfstate sections. there should be depends_on references in the zone resource to the data resources as well. also, enable debug and provide the terraform log related to this case.

Is the state file snippet provided captured immediately after the import? If you do an apply right after the import does it show required updates to contract and group are needed?

**Comment by edglynes** [comment]
Final note. Contract and Group are not needed for resource operations after import. Only Contract is available for resource on import.  Changes: Made group optional. Populate contract on import. Always a recommended practice to run an apply following import.

**Comment by chipgata** [comment]
hi @edglynes thanks for your hard working, but it seen not consistence after import contract ID
```hcl
 ~ resource "akamai_dns_zone" "this" {
      ~ contract         = "3-xxxxxx" -> "ctr_3-xxxxxx"
```

Please help to recheck. Thanks

**Comment by edglynes** [comment]
hi @chipgata 
Pls clarify your use case:
1) are you using cli-terraform to generate the Terraform config.
2) are you seeing this change on a domain update?
3) do you have the contract defined as 'contract = "ctr_3-xxxxxx"' in your domain config?

thx.

**Comment by chipgata** [comment]
hi @edglynes I did not hard cord the Contract ID
My Contract ID got from this terraform code
```hcl
data "akamai_contract" "current" {
  group_name = local.akamai_group_name
}
```

And on your provider document, also mention this `id - The contract's unique ID, including the ctr_ prefix.`
https://registry.terraform.io/providers/akamai/akamai/latest/docs/data-sources/contract

**Comment by edglynes** [comment]
Thx. This will be a future Akamai Terraform Provider change.  I'll file an internal issue to track.

**Comment by lkowalsk-akamai-com** [comment]
Hi @chipgata
Additional code changes were introduced in v1.7.0 release to address this issue. Please check.

**Comment by chipgata** [comment]
confirmed, it fixed, thank team!
