### ISSUE TITLE
Network list does not support group identification

### ISSUE THREAD

**Issue by ericdebeij** [akamai/terraform-provider-akamai#243]
Resource "akamai_networklist_network_list" does not support Access Control Group.

This is a feature request to support group identification as this currently requires manual creation of the Network list via the UI and import it into tf.

Suggested syntax similar to DNS:
resource "akamai_networklist_network_list" "network_list" {
  name = "hdebeij"
  type = "IP"
  description = "Erics network list"
  **group = data.akamai_group.default.id**

Current output gives
│ Error: Unsupported argument
│ An argument named "group" is not expected here

**Comment by lkowalsk-akamai-com** [comment]
Hi @ericdebeij, we are currently working on this enhancement. I cannot share any exact dates, but it should be a part of one of next releases. I will update this ticket once released.

**Comment by lkowalsk-akamai-com** [comment]
Hi @ericdebeij,
This feature has been added with release v1.9.0 of Akamai Terraform Provider.
