### ISSUE TITLE
Failed to Install Provider - SHA256 checksum failed

### ISSUE THREAD

**Issue by davestreng-ally** [akamai/terraform-provider-akamai#252]
Unable to initialize Terraform due to a SHA256 checksum error.

### Terraform Version
Tested with Terraform v0.14.2 & v0.13.7

### Affected Resource(s)
Please list the resources as a list, for example:
- provider initialization (v1.7.0)

### Terraform Configuration Files
```hcl
terraform {
    required_version = ">=0.12"
  required_providers {
    akamai = {
      source  = "akamai/akamai"
    }
    aws = {
      source = "hashicorp/aws"
    }
  }
}

provider "aws" {
  region = var.region
}

provider "akamai" {}
```

### Expected Behavior
Terraform initialized the provider successfully 

### Actual Behavior
Terraform indicated the SHA256 checksum failed when installing the provider

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform init`

### Important Factoids
We are not yet running latest version of Terraform in our environment, however I backtracked a few provider releases (instead of trying to use latest at v1.7.0) and still got the same checksum errors regardless of what version of the provider or version of Terraform.

**Comment by lkowalsk-akamai-com** [comment]
Hi @davestreng-ally 
What platform/OS you are running this on? A lot of people are using one of the latests versions of our provider and we have never seen this error.

**Comment by davestreng-ally** [comment]
I'm on mac (10.15 - catalina) - we intend on using this in a CI/CD pipeline, so i can also test using a generic linux box, but we use macs for local development

**Comment by lkowalsk-akamai-com** [comment]
Can you please create fresh directory with just the terraform cofinguration file that you've sent, runn terraform init and paste here the whole console log output?

**Comment by davestreng-ally** [comment]
Done!
```
Initializing the backend...

Initializing provider plugins...
- Finding latest version of hashicorp/aws...
- Finding latest version of akamai/akamai...
- Installing hashicorp/aws v3.55.0...
- Installed hashicorp/aws v3.55.0 (signed by HashiCorp)
- Installing akamai/akamai v1.7.0...

Error: Failed to install provider

Error while installing akamai/akamai v1.7.0: archive has incorrect SHA-256
checksum 79e5f64169c67d5a56428020477b85b19ea3e8c82a7df7adf5a0ae0cbedcf982
(expected 3d45a2f2f9543a5c25c69def7f44e44d50140cd9cc23b5f0417f016c9f7cd9c5)
```

**Comment by davestreng-ally** [comment]
So I just checked on a separate machine and the provider is loading properly with the same config...

My work machine is running behind a proxy, so it must be blocking some part of the download - we do however use a variety of other partner providers in TF and have never seen this error?

Any suggestions on what I could start looking for? 

I know the checksums are verified after the binary is downloaded/installed but I'm not as familiar with the inner workings that TF executes to install/download it to know what to start looking for? I would assume it just downloads the binary or a zip and unzips it to the proper install directory?

**Comment by robertolopezlopez** [comment]
@davestreng-ally : that might be the case. SHA-256 hashes are correct, you can easily check by yourself downloading the desired zipped binaries + shasum file from our release page https://github.com/akamai/terraform-provider-akamai/releases/tag/v1.7.0
![image](https://user-images.githubusercontent.com/1519467/130650621-2f4a4e71-877f-4846-a8cb-3f75e6e94056.png)

If the above check is correct, I would try to run the provider directly from the .terraform/plugins/registry.terraform.io/akamai/x.x.x/darwin_amd64, as it might be a corrupted binary. Below a normal output:
![image](https://user-images.githubusercontent.com/1519467/130651967-513916c8-ecd5-43c8-81dc-38bc70dc0c19.png)

If it seems corrupted, it may well be due to your proxy. Any other ideas, @lkowalsk-akamai-com ?

**Comment by davestreng-ally** [comment]
Gotcha - yep our proxy is doing something screwy to our downloads from GH here...

I was able to take the same binary downloads off of our proxy and hoist them up into our own internal provider registry and once I got them up there, everything works just fine...

Appreciate the suggestions on the SHA hash checks - i'll keep them in mind if i run into this in the future!
