### ISSUE TITLE
cps_dv_enrollment dns_challenges should not be empty on initial apply

### ISSUE THREAD

**Issue by charims** [akamai/terraform-provider-akamai#253]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.
```

$ terraform -v
Terraform v1.0.6
on linux_amd64
+ provider registry.terraform.io/akamai/akamai v1.7.0
+ provider registry.terraform.io/hashicorp/google v3.82.0
```

### Affected Resource(s)
Please list the resources as a list, for example:
- akamai_cps_dv_enrollment

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
resource "akamai_cps_dv_enrollment" "enrollment" {
  contract_id                       = var.contract_id
  sans                              = var.cert_sans
  common_name                       = var.frontend_hostname
  secure_network                    = var.cert_secure_network
  sni_only                          = var.cert_sni_only
  signature_algorithm               = var.cert_signature_algorithm
  enable_multi_stacked_certificates = false
  certificate_chain_type            = "default"
  admin_contact {
    first_name       = var.admin_contact.first_name
    last_name        = var.admin_contact.last_name
    phone            = var.admin_contact.phone
    email            = var.admin_contact.email
    country_code     = var.admin_contact.country_code
    organization     = var.admin_contact.organization
    postal_code      = var.admin_contact.postal_code
    address_line_one = var.admin_contact.address_line_one
    city             = var.admin_contact.city
    region           = var.admin_contact.region
  }
  tech_contact {
    first_name       = var.tech_contact.first_name
    last_name        = var.tech_contact.last_name
    phone            = var.tech_contact.phone
    email            = var.tech_contact.email
    city             = var.tech_contact.city
    postal_code      = var.tech_contact.postal_code
    country_code     = var.tech_contact.country_code
    region           = var.tech_contact.region
    organization     = var.tech_contact.organization
    address_line_one = var.tech_contact.address_line_one
  }
  csr {
    country_code        = var.csr.country_code
    city                = var.csr.city
    organization        = var.csr.organization
    organizational_unit = var.csr.organizational_unit
    state               = var.csr.state
  }
  network_configuration {
    clone_dns_names         = var.network_configuration.clone_dns_names
    disallowed_tls_versions = var.network_configuration.disallowed_tls_versions
    geography               = var.network_configuration.geography
    ocsp_stapling           = var.network_configuration.ocsp_stapling
    preferred_ciphers       = var.network_configuration.preferred_ciphers
    must_have_ciphers       = var.network_configuration.must_have_ciphers
    quic_enabled            = var.network_configuration.quic_enabled
  }
  organization {
    name             = var.organization.name
    phone            = var.organization.phone
    address_line_one = var.organization.address_line_one
    city             = var.organization.city
    country_code     = var.organization.country_code
    postal_code      = var.organization.postal_code
    region           = var.organization.region
  }
}
```

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.
N/A
### Expected Behavior
The  akamai_cps_dv_enrollment resource should return the DNS challenge on initial apply so that we can satisfy it in the same run.

### Actual Behavior
The resource's dns_challenge is returned as an empty list, this means we cannot provision a new ceritficate in a single apply. Instead, we need to run "terraform apply" wait for a little bit, and then run "terraform apply" again. On state refresh, the dns_challenges list will be populated.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply` to create a new enrollment with a new domain
    akamai_cps_dv_enrollment.enrollment.dns_challenges is an empty list
     wait a little bit
2. `terraform apply`
    akamai_cps_dv_enrollment.enrollment.dns_challenges are not empty, and contain the challenges we need to complete the process.

### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?
N/A

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
N/A

**Comment by lkowalsk-akamai-com** [comment]
Hi @charims 
This issue is now fixed with relese v1.9.0 of Akamai Terraform Provider. I'm closing this issue now. Plesae feel free to reaopen the issue if you find it not fixed.
