### ISSUE TITLE
akamai_property_activation tries to update activation note on active version

### ISSUE THREAD

**Issue by partamonov** [akamai/terraform-provider-akamai#254]
Hi there,

### Terraform Version
```
terraform version
Terraform v1.0.6
on darwin_amd64
+ provider registry.terraform.io/akamai/akamai v1.7.0
```

### Affected Resource(s)
Please list the resources as a list, for example:
- akamai_property_activation

### Terraform Configuration Files
```hcl
resource "akamai_property_activation" "production" {
  property_id = "12345"
  network     = "PRODUCTION"
  contact     = var.contact
  version     = var.version
  note        = var.note
}
```

### Debug Output
```
│ Error: cannot update activation attribute note after creation
│ 
│   with akamai_property_activation.production,
│   on activations.tf line 1, in resource "akamai_property_activation" "production":
│    1: resource "akamai_property_activation" "production" {
│ 
```

### Expected Behavior
Note value should be not updated, if version is already activated, but due to some reason note value is changed

### Actual Behavior
It tries to change note for activated version and fails

**Comment by mcortinas** [comment]
Yesterday I received the same error message. Let me share in my case it was I'm not changing anything in the property activated and the activation resource try to change the comment of a property already activated.  My workaround it was I should add externally  the control to don't apply when the property don't change. I'm not sure if this is your exactly scenario. But it was usefull if the provider can manage my scenario.

**Comment by piotrpio** [comment]
Hello @partamonov, @mcortinas 
Thanks for submitting the issue. Can you please provide some more details on the scenario that you were following when you encountered this problem? In current version of the provider (since 1.7.0), the resource is meant to fail with an error on the update step if you attempt to update the note field (but only if the activation is already created for this version, as update can also create a new activation if the `version`field is updated). 

So if the scenario is as follows:
1. Create activation for version x
2. Update activation for version x with new value of `note`

Then the error message (`Error: cannot update activation attribute note after creation`) is correct.
Can you clarify which values in your config where changed between subsequent `terraform apply` executions that led to the problem?

**Comment by lkowalsk-akamai-com** [comment]
Closing this ticket as we cannot reproduce it and there has been no ansewer for 3 months. Please reopen/create new issue if problem persists.

**Comment by vegardengen** [comment]
I stumbled upon this issue after starting to parallellize deploy.

Previously, I wouldn't deploy anything unless there was actually a change, so this issue did not appear.

Scenario:

I have 5 properties that "belong" together per environment (environment = production, UAT-1, UAT-2, Performance test, Dev, Stage, etc...). A lot of the code will be shared, and should always be kept in sync, etc.

I run this in jenkins, and earlier, with manual trigger, if doing a change that should basically hit all environments, I'd have to trigger an awful amount of pipelines. After parallellizing, I always deploy  all properties in an environment.

So, the problem:

If I change something affecting only one property, and adding a note about what has changed, the remaining 4 properties will seem to be changed as seen by terraform, and it will happily try to deploy it, which will fail in akamai.

Still not sure what can be done, I am toying with checking outside akamai if there are changes. I do, however, have included jsons a couple of levels deep, which will only be stiched together once it hits terraform - upon which it deems there is a change in the "note" property.

**Comment by robertolopezlopez** [comment]
Hi,

Thank you for reopening this issue, @vegardengen. I am trying to understand + find a fix.

> I have 5 properties that "belong" together per environment (environment = production, UAT-1, UAT-2, Performance test, Dev, Stage, etc...). A lot of the code will be shared, and should always be kept in sync, etc.

What do you mean here? Have you created 5 different properties and activated each of them in a separate environment? Or one property + 5 activations on different environments?

> If I change something affecting only one property, and adding a note about what has changed, the remaining 4 properties will seem to be changed as seen by terraform, and it will happily try to deploy it, which will fail in akamai.

From this statement, I would say that you have 1 active property in different environments.

Could you please confirm + share your `.tf` script(s)? (as usual, please mask sensitive information)

Kind regards,

Roberto

**Comment by vegardengen** [comment]
> > I have 5 properties that "belong" together per environment (environment = production, UAT-1, UAT-2, Performance test, Dev, Stage, etc...). A lot of the code will be shared, and should always be kept in sync, etc.
> 
> What do you mean here? Have you created 5 different properties and activated each of them in a separate environment? Or one property + 5 activations on different environments?
> 

I will try to elaborate a bit.

When I am talking about environment, I am thinking in logical separation, i.e. in defining properties that belong together. For example, we have a www.xxx.yy and m.xxx.yy in production that belongs together and share some of the code. Whenever I deploy to production (as seen by business, nothing to do with akamai production/staging network) after changing something in the rule tree, I deploy both www.xxx.yy and m.xxx.yy - with separate activation, one per property.

We also have www-env1.xxx.yy and m-env1.xxx.yy that belongs together, and are deployed in the same job.

This used to work fine, if nothing has changed then no new version is created in Akamai and it just finishes with "no changes".

However, if I set an activation note to tell what I have changed, and the changes *only* affect www.xxx.yy and not m.xxx.yy, then deploying m.xxx.yy will fail with the error mentioned in the issue.


> From this statement, I would say that you have 1 active property in different environments.
> 
> Could you please confirm + share your `.tf` script(s)? (as usual, please mask sensitive information)
> 

Do you stil need my terraform scripts?

**Comment by robertolopezlopez** [comment]
> Do you stil need my terraform scripts?

Yes, that would ease my work much :-)

Thanks!
