### ISSUE TITLE
wrong example codes for 'contracts' and 'groups'

### ISSUE THREAD

**Issue by elfinston** [akamai/terraform-provider-akamai#255]
https://registry.terraform.io/providers/akamai/akamai/latest/docs/data-sources/contracts
https://registry.terraform.io/providers/akamai/akamai/latest/docs/data-sources/groups

two document URLs still show 'datasource' instead of 'data' invoking data sources.
I tried 'data' instead of 'datasource' in code, it worked propertly.

**Comment by robertolopezlopez** [comment]
Hi @elfinston ,

Thank you for pointing that out. We have addressed those two documentation defects in our internal repository and this change will be released soon.

Kind regards,

Roberto

**Comment by robertolopezlopez** [comment]
Hi @elfinston,

It turned out that "soon" meant today :-). The documents have been updated as suggested.

Regards,

Roberto
