### ISSUE TITLE
Changing CP Code name forces replacement

### ISSUE THREAD

**Issue by TBeijen** [akamai/terraform-provider-akamai#262]
### The problem

When changing the name of a CP Code, Terraform plans to replace the entire CP code.

Based on the cprg api, updating the name should be possible: https://techdocs.akamai.com/cp-codes/reference/cpcodescpcodeid#put-cpcode

### Terraform Version

Terraform: 0.13.7
Akamai provider: 1.8.0

### Affected Resource(s)
- akamai_cp_code

### Terraform Configuration Files
```hcl
resource "akamai_cp_code" "cp_codes" {
  count       = length(var.akamai_cp_codes)

  name       = lookup(var.akamai_cp_codes[count.index], "name", null)
  product_id = lookup(var.akamai_cp_codes[count.index], "product_id", var.akamai_product_id)

  contract_id = local.contract_id
  group_id    = data.akamai_group.group.id
}
```

### Debug Output

TF plan output (values anonymized):

```
  # module.akamai.akamai_cp_code.cp_codes[0] must be replaced
-/+ resource "akamai_cp_code" "cp_codes" {
      ~ contract    = "ctr_NNN" -> (known after apply)
        contract_id = "ctr_NNN"
      ~ group       = "grp_123456" -> (known after apply)
        group_id    = "grp_123456"
      ~ id          = "cpc_654321" -> (known after apply)
      ~ name        = "Old name" -> "New name" # forces replacement
      ~ product     = "prd_Site_Accel" -> (known after apply)
        product_id  = "prd_Site_Accel"
    }
```

### Expected Behavior
Update cp code in place by changing its name.

### Actual Behavior
Plan to destroy current CP code and create a new one

### Steps to Reproduce
Have a cp code managed by TF. Change its name and run tf plan.

**Comment by lkowalsk-akamai-com** [comment]
Hi @TBeijen,
This functionality has been added with current release. I'm closing the ticket. Feel free to open if you notice any issues.
