### ISSUE TITLE
Path to snippets when using akamai_property_rules_template is hard coded to "property-snippets"

### ISSUE THREAD

**Issue by jaescalo** [akamai/terraform-provider-akamai#265]
This is an enhancement request. Looking at the code I can see where the path is hard coded to "**property-snippets**". Can this actually honor the path specified under "**template_file**"? One use case is if the customer pulled the code with the Akamai pipeline CLI, which stores the snippets under a folder named "**templates**".

If this is not the case, then the first example [here](https://registry.terraform.io/providers/akamai/akamai/latest/docs/data-sources/property_rules_template) needs to be updated  and replace the "**/rules/**" path component to "**/property-snippets/**"

**Comment by Slonimskaia** [comment]
Hi @jaescalo

Path to snippets should stay as it is now and the template files should be locate under the "property-snippets" directory, when using akamai_property_rules_template.

We addressed documentation issue which you mentioned above about changing "/rules/" path component to "/property-snippets/" and it will be included in our upcoming release.

**Comment by jaescalo** [comment]
Thank you.
