### ISSUE TITLE
Question - Import existing Akamai properties into TF

### ISSUE THREAD

**Issue by rezagh** [akamai/terraform-provider-akamai#266]
I have had some luck with `terraform import`. It seems to have improved by unlike what was said in issue https://github.com/akamai/terraform-provider-akamai/issues/5 by @dshafik , when I export the rules using Akamai CLI and create a new TF property from scratch, it always complains with status code 400, name-in-use, `Property name already in use`.

Is this method supposed to work when a property exists in Akamai but not in the TF state file?

**Comment by lkowalsk-akamai-com** [comment]
Hi @rezagh2 
Sorry for delayed response. The issue you are reffering to (#5) is outdated. Starting from version 1.0.0 of Akamai Terraform Proivder, `terraform import` for Provisioning was upgraded. Please refer to current documentation: https://registry.terraform.io/providers/akamai/akamai/latest/docs/resources/property
Please let us know if you have any additional questions.
