### ISSUE TITLE
Instructions for building the provider no longer works

### ISSUE THREAD

**Issue by jeohist** [akamai/terraform-provider-akamai#27]
### Expected Behavior
Provider should build. 

### Actual Behavior
It doesn't.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
$ mkdir -p $GOPATH/src/github.com/terraform-providers; cd $GOPATH/src/github.com/terraform-providers
$ git clone git@github.com:terraform-providers/terraform-provider-akamai
Doesn't work as the repository no longer exists. So we try:
$ git clone git@github.com:akamai/terraform-provider-akamai
Which works.
$ cd $GOPATH/src/github.com/terraform-providers/terraform-provider-akamai
Obviously doesn't work. So:
$ cd $GOPATH/src/github.com/akamai/terraform-provider-akamai
$ make build
Doesn't work, so we update main.go to refer to akamai/terraform-provider-akamai as well...
$ make build
can't load package: import cycle not allowed
package github.com/terraform-providers/terraform-provider-akamai
        imports github.com/terraform-providers/terraform-provider-akamai
import cycle not allowed
package github.com/terraform-providers/terraform-provider-akamai
        imports github.com/terraform-providers/terraform-provider-akamai

**Comment by derekargueta** [comment]
@dshafik seems like this is fixed via PR #41 ?

**Comment by jeohist** [comment]
@derekargueta @dshafik Yep! Thanks!
