### ISSUE TITLE
Rollback To Previous Property Version - Does Not Activate

### ISSUE THREAD

**Issue by Darmajani** [akamai/terraform-provider-akamai#272]
I have version X of a property activated in staging and production, I create version Y, everything looks fine, so I activate it in staging and prod, everything good so far.
Then let's say I found an error on production, and I want to rollback to version X. I change the version number on the akamai_property_activation resource, run tf plan and tf apply, and the state gets updated with that version, but it doesn't trigger a new activation on Akamai.

Rollback plan:
Resource actions are indicated with the following symbols:
  ~ update in-place
Terraform will perform the following actions:
  # module.property_activation.akamai_property_activation.activation will be updated in-place
  ~ resource "akamai_property_activation" "activation" {
        id                             = "prp_762824:STAGING"
      ~ version                        = 2 -> 1
        # (7 unchanged attributes hidden)
    }

Rollback apply:
module.property_activation.akamai_property_activation.activation: Modifying... [id=prp_762824:STAGING]
module.property_activation.akamai_property_activation.activation: Modifications complete after 3s [id=prp_762824:STAGING]
Apply complete! Resources: 0 added, 1 changed, 0 destroyed.
Outputs:
activation_info = {
  "id" = "atv_10838123"
  "status" = "ACTIVE"
  "version" = 1
}

However - Version 1 does not get pushed out to Akamai.

**Comment by lkowalsk-akamai-com** [comment]
Hi @Darmajani 
We've identified this as a bug in the provider. We will work on fixing it and update the ticket once done.

**Comment by lkowalsk-akamai-com** [comment]
Hi @Darmajani 
We releasesd a patch (1.10.0) of the provider that should resolved this Issue. I'm closing the issue, if the problem persists, please comment and reopen.
