### ISSUE TITLE
datastream and property cycle error

### ISSUE THREAD

**Issue by Fuochi** [akamai/terraform-provider-akamai#273]
### Description
For new configurations only. If you need to create a property resource with a datastream behaviour, it will create a cycle error because the property ID is needed in the datastream configuration and the datastream ID in the property rule tree.

A possible solution could be to create a different resource to link property and datastream before the activation of the latest.
This way, Terraform would be able to create the akamai_datastream resource, leverage its ID in the akamai_property resource, and finally associate and activate the datastream.
Something like this:

```hcl
resource "akamai_property" "this" {
...
  rules = "something that contains akamai_datastream.this.id"
}

resource "akamai_datastream" "this" {
...
}

resource "akamai_datastream_association" "this" {
  datastream_id = akamai_datastream.this.id
  property_ids  = [akamai_property.this.id]
  active = true
}
```

### Terraform Version
Terraform v1.0.5

### Affected Resource(s)
Please list the resources as a list, for example:
- akamai_property
- akamai_datastream

**Comment by lkowalsk-akamai-com** [comment]
Hi @Fuochi 
Thank you for rising this issue. The workflow for adding datastream is described here:
https://registry.terraform.io/providers/akamai/akamai/latest/docs/guides/get_started_datastream
Solution proposed by you will not work due to the fact that datastream_id needs to be added to the property rule tree, not just a field in property resource.

**Comment by Fuochi** [comment]
Hi @lkowalsk-akamai-com 
Thank you for your answer. I understand now that the cycle dependency isn't only a limitation of terraform resources but it's part of the process as well.
I think then we can close the issue, since it can't be solved without changing the actual datastream creation behaviour.
