### ISSUE TITLE
[CPS provider feature request] Support for EV, OV, and third-party certificates?

### ISSUE THREAD

**Issue by siwinski** [akamai/terraform-provider-akamai#275]
I was checking out the [CPS Terraform provider](https://registry.terraform.io/providers/akamai/akamai/latest/docs/guides/get_started_cps) to get my certificate configurations into source control, but quickly noticed it only supports DV certificates.  Are there plans to add support for EV, OV, and third-party certificates?

### Terraform Version
N/A

### Affected Resource(s)
No "affected" resources

### Terraform Configuration Files
N/A

### Debug Output
N/A

### Panic Output
N/A

### Expected Behavior
Support EV, OV, and third-party certificate types

### Actual Behavior
Only DV certificate type (resource [`cps_dv_enrollment`](https://registry.terraform.io/providers/akamai/akamai/latest/docs/resources/cps_dv_enrollment)) is supported

### Steps to Reproduce
N/A

### Important Factoids
N/A

### References
https://registry.terraform.io/providers/akamai/akamai/latest/docs/guides/get_started_cps

**Comment by lkowalsk-akamai-com** [comment]
Hi @siwinski 
We are planning to extend CPS to support additional certificates. Types and dates are not commited yet. I will update this ticket once we have some more clarity on the scope and timelines.

**Comment by michfuer** [comment]
Hi @lkowalsk-akamai-com,

I was able to import an OV type certificate via `terraform import` and was wondering if maybe some other cert types are actually supported by Akamai and maybe just the documentation needs updating?

**Comment by lkowalsk-akamai-com** [comment]
Hi @michfuer 
The documentation is up todate and certificates types other then DV are not supported. The workflows in OV certs (and others) are different then the one for DV. You might be able to import other cert (we will fix that issue acutally), but proper management of other types of certificates is not possible currently. 

Once again, this is on our radar and we will extend this subprovider to handle other types of certs in the future.

**Comment by lkowalsk-akamai-com** [comment]
Hi, we are planning to extend CPS subprobider with 3rd party certificates. OV and EV certs will not be part of this work. The timelines are not finalized yet, but this extention should be available this year.

**Comment by Manikandanmuru** [comment]
Hi do we have any update regarding the cps OV enrollment? Is it still in the development phase?

**Comment by kaush-** [comment]
Hi @Manikandanmuru,

You are right, It is still in development phase. We will keep you posted once we have a timeline in place.

Regards,
Piyush

**Comment by lkowalsk-akamai-com** [comment]
@Manikandanmuru - the development is happening for the 3rd party and dual stack. OV and EV certs will not be part of this work. See my commet above.

**Comment by Manikandanmuru** [comment]
@lkowalsk-akamai-com thank you.  @kaush- So at this moment to automate the OV Certificate creation done through using Akamai CLI using yml or Json file? We don't have any terraform approach to achieve this am i correct ?

**Comment by lkowalsk-akamai-com** [comment]
OV Certificates support is not currenly supported in Akamai Terraform Provider and there are no plans to add it in the futre as of now.

**Comment by Manikandanmuru** [comment]
@lkowalsk-akamai-com thank you so do you have any best approach to automate the certificate creation. I am working through the akamai-CLI any best recommendation or other methods ?

**Comment by mgwoj** [comment]
Hello @Manikandanmuru ,

We are currently working on adding support for third-party certificates to both terraform and cli cps extension.

Thanks,
Michal

**Comment by kaush-** [comment]
Hi @Manikandanmuru,

Unfortunately at this moment we don't have any other approach towards OV certs. As you mentioned, you are already using akamai-cli which in turn installs https://github.com/akamai/cli-cps for CPS related work. A quick glance at the code gives the understanding that it should work with OV certs (though we are still waiting on confirmation of any issues from functional team).

Let me know if you have any other questions on this issue. I will update you in case I get any new information.

Regards,
Piyush

**Comment by lkowalsk-akamai-com** [comment]
Support in CPS subprovider for 3rd party and dual stack certificates was added in the recent release. I'm closing this ticket. Please raise any subsequent questions as new cases. Thank you.
