### ISSUE TITLE
DXE-3321 Support for shared cloudlets policies is missing

### ISSUE THREAD

**Issue by voroniys** [akamai/terraform-provider-akamai#276]
### Terraform Version
Terraform v1.1.2
+ provider registry.terraform.io/akamai/akamai v1.9.1

### Affected Resource(s)
- akamai_cloudlets_policy
- akamai_cloudlets_policy_activation
- 
### Expected Behavior
Resources should be able to create and activate shared policies

### Actual Behavior
ATM shared policies seems to be not supported at all by this provider

**Comment by lkowalsk-akamai-com** [comment]
Hi @voroniys,
Akamai Terraform Provider uses Cloudles API v2 to handle Cloudlets. Shared policies are only availalbe in Cloudlets API v3 which only supports Edge Redirector, Forward Rewrite and Audience Segmenation Cloudlets. Once the v3 support is extended to support more/all Cloudlests, Terraform Provider will be updated to use it and support of shared policies will be added.
Thank you for rising this issue.

**Comment by E-2** [comment]
Hi, is there a known ETA on when v3 is going to be extended?

**Comment by lkowalsk-akamai-com** [comment]
Hi @E-2  
The API v3 work should be handled this year, but no hard deadlines. Terraform work to handle this changes will need to be prioritized and plannaed as well. Cannot share any timelines at this moment.

**Comment by hypnotisttom** [comment]
Hi,

Is there any update on this?  I was about to submit a feature request myself, as Shared cloudlets are important for our delivery.

Thanks,

Tom

**Comment by lkowalsk-akamai-com** [comment]
Hi @hypnotisttom, unfortunatelly the work for shared policies in cloudles will not be held this year. Tentatively we are planning to investigate the possibilities (as V3 is not fully covering V2) in Q1 2023.

**Comment by hypnotisttom** [comment]
Okay, thanks for the update.  We will have to build our shared cloudlets manually for now and then import them into TF when the support for shared cloudlets is added.

**Comment by hypnotisttom** [comment]
Hi,

Just wanted to circle back as we are planning our pipeline.

We have some shared cloudlets that we will need to convert to non-shared and duplicate per property being shared if we don't have shared support.

I noticed that v2 API works only for unshared, and the v3 API works only for shared.  Trying the unsupported combinations result in a cloudlet-not-found message currently.

A couple questions:

1) Do we know for sure the engineering / API team is working on adding unshared support to the v3 API?  (As a pre-req for the Provider to support Shared)

2) Is there a possibility of doing something like "shared=true" in the resource config (which we probably need anyway) and then if true, use the v3 api in the provider?  Or maybe a separate akamai_cloudlets_policy_shared resource that uses the v3 api?

I realize creating unshared versions of the cloudlets is a workaround for us, while deciding which api version to use is a workaround for you, when both of us would prefer the v3 API to support both shared and unshared.  I'm just wanting to understand the likelihood of things so that I can plan accordingly.

Thanks,

Tom

**Comment by pavelpulec** [comment]
Hi,

we would welcome a lot the support for shared Cloudlets as well. That would help us to integrate our properties and improve the coverage of our properties by Terraform.

Is there any progress or any plans for this feature?

Kind regards,
Pavel

**Comment by lkowalsk-akamai-com** [comment]
Hi @pavelpulec, we are planning to add support for shared policies to the cloudlets subprovider. That requires using v3 version of API. Currently v3 does not support one of the Cloudlets (ALB to be exact). We are evaluating how to approach this transition. The work has not started yet, so I cannot share any timelines.

**Comment by pavelpulec** [comment]
> Hi @pavelpulec, we are planning to add support for shared policies to the cloudlets subprovider. That requires using v3 version of API. Currently v3 does not support one of the Cloudlets (ALB to be exact). We are evaluating how to approach this transition. The work has not started yet, so I cannot share any timelines.

That's great that there is a plan to work on that. If you are planning to release alpha/beta versions of provider we could try, let us know. We can help, provide feedback or contribute. :+1:

**Comment by hypnotisttom** [comment]
Hi @lkowalsk-akamai-com,

If there is an increase in interest for this capability, is there any possibility of doing my suggestion from my April 18 reply?

> 2. Is there a possibility of doing something like "shared=true" in the resource config (which we probably need anyway) and then if true, use the v3 api in the provider?  Or maybe a separate akamai_cloudlets_policy_shared resource that uses the v3 api?

I realize doing something like this might be throw-away once the cloudlet API team comes out with shared/unshared support in the same version of the API; however, in the interim this would give customers the ability to manage shared/unshared cloudlets by letting the provider decide which API to use depending on what type (shared/unshared) of cloudlet is being created.

In thinking about this further, a separate resource (or a shared=true argument) to manage shared cloudlets might not actually be throw-away come to think of it, as you still need a way to know if what is being built is shared or not, even if you are ultimately pointing to the v3 api in the future.

If the timeline lined up, it would make sense to wait for v3 to support everything.  It just doesn't appear that the cloudlet API team's timeline is lining up with customer desires to use this functionality with terraform.

I'm curious on your thoughts.

**Comment by lkowalsk-akamai-com** [comment]
@hypnotisttom thank you for your suggestion. We will evaluate how to best introduce v3 into the Terraform provider. Currently we are considering adding completely new set of resources/datasources along side current v2 ones. Or updating the current ones to use v3. We want to have generic approach for such changes. That being said, this is still far from development ready.

**Comment by lkowalsk-akamai-com** [comment]
Hi, support for shared cloudlets policies was added in 5.6.0 release yesterday.
