### ISSUE TITLE
Unable to create property with product_id - prd_Obj_Delivery

### ISSUE THREAD

**Issue by abystrov** [akamai/terraform-provider-akamai#277]
### Description

Good afternoon.

I'm unable to create property with product_id prd_Obj_Delivery due to read-only object - restrictObjectCaching.  
When I create a new property, I get this error every time, even though I don't change the object itself.  
I tried to delete this object from my rule tree, setting the same value, but every time the uuid field changes and I get the API response "Read-only behaviors have been added, removed, changed or moved". 
Also terraform tries to remove the property completely and create a new one every time (Plan: 1 to add, 0 to change, 1 to destroy.), so I can't even add uuid to my template because it changes every time.
```
module.akamai-property.akamai_property.default: Destroying... [id=<prp_id>]
module.akamai-property.akamai_property.default: Destruction complete after 3s
module.akamai-property.akamai_property.default: Creating...
module.akamai-property.akamai_property.default: Still creating... [10s elapsed]
```
The error itself:
```
│ Error: updating rule tree: API error:
│ {
│       "type": "https://problems.luna.akamaiapis.net/papi/v0/property-version/lock-error",
│       "title": "Unable to edit read-only element",
│       "detail": "Only Akamai representatives can change read-only behaviors, criteria and child rules.",
│       "instance": <instance_url>,
│       "statusCode": 403,
│       "errors": [
│               {
│                       "removed": [
│                               {
│                                       "behavior": {
│                                               "name": "restrictObjectCaching",
│                                               "options": {
│                                                       "maximumSize": "100MB"
│                                               },
│                                               "uuid": "e1d1111e-7047-42cd-979c-3d9b9bceb99a"
│                                       },
│                                       "location": "#/rules/behaviors/3"
│                               }
│                       ],
│                       "added": [
│                               {
│                                       "behavior": {
│                                               "name": "restrictObjectCaching",
│                                               "options": {
│                                                       "maximumSize": "100MB"
│                                               },
│                                               "uuid": "11a11111-8997-42f8-9b0d-51e42e859363"
│                                       },
│                                       "location": "#/rules/behaviors/3"
│                               }
│                       ],
│                       "type": "https://problems.luna.akamaiapis.net/papi/v0/property-version/lock-error/behaviors-changed",
│                       "title": "Read-only behaviors changed",
│                       "detail": "Read-only behaviors have been added, removed, changed or moved."
│               }
│       ]
│ }
```
Is there any chance to avoid modifying this object?

### Terraform Version
Terraform v1.1.4
on darwin_amd64
+ provider registry.terraform.io/akamai/akamai v1.9.1
+ provider registry.terraform.io/hashicorp/template v2.2.0

### Affected Resource(s)
Please list the resources as a list, for example:
- akamai_property

### Terraform Configuration Files
```hcl
resource "akamai_property" "default" {

  name       = var.property_name
  product_id = var.product_id

  group_id    = data.akamai_group.this.id
  contract_id = data.akamai_contract.this.id

  dynamic "hostnames" {
    for_each = var.property_hostnames

    content {
      cname_from             = hostnames.key
      cname_to               = "${hostnames.key}.edgekey.net"
      cert_provisioning_type = "CPS_MANAGED"
    }
  }

  rule_format = "latest"
  rules       = data.template_file.this.rendered
}
```

### Expected Behavior
The property should be created without any issues

### Actual Behavior
Terraform fails with API response "Read-only behaviors have been added, removed, changed or moved"

**Comment by lkowalsk-akamai-com** [comment]
Hi @abystrov 
We tried reproducing your problem, but for us it worked correctly. Only difference that might have been problematic, is the prouct_id itsefl - we used prd_Object_Delivery. Can you try with this id?

**Comment by Podginator** [comment]
I also have this issue. When using prd_object_delivery I get that there is no such product_id.

**Comment by Slonimskaia** [comment]
Hi @Podginator  could yo create an issue with some description? We will try to reproduce it from our side. This issue above was closed some time ago by creator

**Comment by GerardSoleCa** [comment]
Hi @Slonimskaia ,

I'm experiencing the same issue.

We are using prod_Obj_Delivery, when trying to use prod_Object_Delivery we get an error saying that we don't have that product.

And the property creation fails because the uuid changes and does not allow us to create the property.

How is the resolution process in akamai side going? Is anyone working in a solution that effectively allows people use terraform?

We are using the last version of the terraform provider (5.2.0)

Cheers,
