### ISSUE TITLE
terraform-provider-akamai_v1.10.0.exe plugin crashed

### ISSUE THREAD

**Issue by anandbhoopathyg** [akamai/terraform-provider-akamai#281]
Stack trace from the terraform-provider-akamai_v1.10.0.exe plugin:

panic: runtime error: invalid memory address or nil pointer dereference    
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x40211c]

goroutine 40 [running]:
runtime/internal/atomic.Xadd64(0x237bd5dc, 0x1, 0x0, 0xad5d310a, 0x16dbc80)
        runtime/internal/atomic/asm_386.s:105 +0xc
github.com/allegro/bigcache/v2.(*cacheShard).miss(...)
        github.com/allegro/bigcache/v2@v2.2.5/shard.go:398
github.com/allegro/bigcache/v2.(*cacheShard).getWrappedEntry(0x237bd550, 0x5390c798, 0xad5d310a, 0x40a767, 0x324668c8, 0x12289c40, 0x1fffdf, 0x0)
        github.com/allegro/bigcache/v2@v2.2.5/shard.go:88 +0x10a
github.com/allegro/bigcache/v2.(*cacheShard).get(0x237bd550, 0x12289c40, 0xf, 0x5390c798, 0xad5d310a, 0x12289c40, 0xf, 0xf, 0x12289c40, 0x12056000)
        github.com/allegro/bigcache/v2@v2.2.5/shard.go:64 +0x50
github.com/allegro/bigcache/v2.(*BigCache).Get(0x1218aa80, 0x12289c40, 0xf, 0x2, 0x2, 0x12289c40, 0xf, 0x32572100)
        github.com/allegro/bigcache/v2@v2.2.5/bigcache.go:117 +0x76
github.com/akamai/terraform-provider-akamai/v2/pkg/akamai.(*meta).CacheGet(0x273c5880, 0x1049d80, 0x123f05a0, 0x12289c40, 0xf, 0xd1ad20, 0x267839c0, 0x0, 0x0)
        github.com/akamai/terraform-provider-akamai/v2/pkg/akamai/meta.go:91 +0x16d
github.com/akamai/terraform-provider-akamai/v2/pkg/providers/property.getGroups(0x10442c0, 0x26783900, 0x32ab4160, 0x273c5880, 0xe9d3f2, 0xa, 0x12289bb0)
        github.com/akamai/terraform-provider-akamai/v2/pkg/providers/property/data_property_akamai_group.go:178 +0x73
github.com/akamai/terraform-provider-akamai/v2/pkg/providers/property.dataSourcePropertyContractRead(0x10442c0, 0x26783900, 0x120649b0, 0xe19180, 0x273c5880, 0x1227ee00, 0x12007890, 0x40adac)
        github.com/akamai/terraform-provider-akamai/v2/pkg/providers/property/data_property_akamai_contract.go:77 +0x1de
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0x1243e230, 0x1044260, 0x26783360, 0x120649b0, 0xe19180, 0x273c5880, 0x0, 0x0, 0x0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.0/helper/schema/resource.go:347 +0x11d
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).ReadDataApply(0x1243e230, 0x1044260, 0x26783360, 0x26783600, 0xe19180, 0x273c5880, 0x273c5880, 0x26783600, 0x0, 0x0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.0/helper/schema/resource.go:558 +0xc3
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadDataSource(0x266c9800, 0x1044260, 0x26783360, 0x26f8da20, 0x26783360, 0xe40d00, 0xe63f60)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.0/helper/schema/grpc_provider.go:1105 +0x3af
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ReadDataSource(0x26782920, 0x1044260, 0x26783360, 0x12053c80, 0x26782920, 0x26782701, 0x26783200)
        github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/server/server.go:247 +0xb4
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadDataSource_Handler(0xe63f60, 0x26782920, 0x10442c0, 0x26783200, 0x12053c50, 0x0, 0x10442c0, 0x26783200, 0x12020d70, 0x49)
        github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:416 +0x195
google.golang.org/grpc.(*Server).processUnaryRPC(0x12078360, 0x104dc00, 0x12189a00, 0x12442480, 0x26782980, 0x16bc0b8, 0x0, 0x0, 0x0)
        google.golang.org/grpc@v1.32.0/server.go:1194 +0x4df
google.golang.org/grpc.(*Server).handleStream(0x12078360, 0x104dc00, 0x12189a00, 0x12442480, 0x0)
        google.golang.org/grpc@v1.32.0/server.go:1517 +0xa7d
google.golang.org/grpc.(*Server).serveStreams.func1.2(0x12289ac0, 0x12078360, 0x104dc00, 0x12189a00, 0x12442480)
        google.golang.org/grpc@v1.32.0/server.go:859 +0x8a
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.32.0/server.go:857 +0x1b0

Error: The terraform-provider-akamai_v1.10.0.exe plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

**Comment by robertolopezlopez** [comment]
Hi @anandbhoopathyg ,

Thank you for creating this issue. Could you please attach more information, such as your .tf and other relevant data to try to reproduce it from our side? Thanks.

Regards,

Roberto

**Comment by robertolopezlopez** [comment]
Hi @anandbhoopathyg ,

As it's been 6 weeks already since its creation without any further feedback, we will assume that this is not an issue anymore. I will close the ticket now, please reopen if you have any further information to add.

Regards,

Roberto
