### ISSUE TITLE
DataStream cannot be created when using email_ids

### ISSUE THREAD

**Issue by holomekc** [akamai/terraform-provider-akamai#289]
### Terraform Version
1.0.11

### Affected Resource(s)
Please list the resources as a list, for example:
- resource akamai_datastream

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
email_ids     = ["test_email1@akamai.com","test_email2@akamai.com"]
```

### Debug Output
-

### Panic Output
-

### Expected Behavior
emails are used

### Actual Behavior
DataStream is not created because provider considers emails as invalid. Fails for both emails:

Error: must be a valid email address

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan`

### Important Factoids
-

### References
-

**Comment by mgwoj** [comment]
Hello @holomekc ,

What is your version of Akamai Terraform subprovider? Please provide output from `terraform version`
Please verify if you still have a problem with the latest version `1.11.0` which was released March 3rd.
If yes, please attach copy of your `tf` file.

Thanks,
Michal
