### ISSUE TITLE
Error when creating an ALB cloudlet policy

### ISSUE THREAD

**Issue by insynwyn** [akamai/terraform-provider-akamai#294]
Hi there,

### Terraform Version
Terraform v1.1.7
on windows_386

### Affected Resource(s)
Please list the resources as a list, for example:
- akamai_cloudlets_policy

### Terraform Configuration Files
terraform {
  required_providers {
    akamai = {
      source = "akamai/akamai"
      version = "1.11.0"
    }
  }
}

provider "akamai" {
}
resource "akamai_cloudlets_application_load_balancer" "apt_alb_ecom_prd" {
  origin_id      = "APT_ALB_ECOM_PRD"
  description    = "Multi-region Load Balancer"
  balancing_type = "WEIGHTED"
  data_centers {
    cloud_server_host_header_override = false
    cloud_service = true
    country  = "US"
    continent = "NA"
    latitude = 38.96019
    longitude = -77.3545
    percent = 100
    hostname= "xxx.us-east-1.elb.amazonaws.com"
    state_or_province = "VA"
    city = "Reston"
    origin_id = "ECOMPRDUSEAST1"
  }
}

data "akamai_cloudlets_application_load_balancer_match_rule" "alb_cloudlet_policy" {
    match_rules {
        name = "APT_ALB_ECOM_PRD"
        matches_always = "true"
        forward_settings {
            origin_id = "APT_ALB_ECOM_PRD"
        }
    }
}

resource "akamai_cloudlets_policy" "apt_alb_ecom_prd" {
  name          = "APT_ALB_ECOM_PRD"
  cloudlet_code = "ALB"
  description   = "multiregion alb cloudlet"
  group_id      = "grp_66337"
  match_rules   = data.akamai_cloudlets_application_load_balancer_match_rule.alb_cloudlet_policy.json
}

### Debug Output
Error: get policy versions: request failed: unmarshaling output: json: cannot unmarshal number 1647968152606 into Go struct field PolicyVersion.createDate of type int
│
│   with akamai_cloudlets_policy.apt_alb_ecom_prd,
│   on akamai.tf line 43, in resource "akamai_cloudlets_policy" "apt_alb_ecom_prd":
│   43: resource "akamai_cloudlets_policy" "apt_alb_ecom_prd" {

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
Success after terraform apply

### Actual Behavior
Error after apply

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by robertolopezlopez** [comment]
Hi @insynwyn ,

Does this happen on the creation stage? (After first `terraform apply`). Or rather on successive calls to `terraform apply`?

Regards,

Roberto

**Comment by insynwyn** [comment]
Creation stage.

**Comment by robertolopezlopez** [comment]
Hi @insynwyn ,

After shallow analysis we believe that this crash may be due that you are running this on a 32 bit machine. Internally, the creation date is transformed into an `int` value - which, in 32 bit systems, it is actually an `int32`. Thus the overflow.

We will address this problem internally and try to issue a fix for next release. In the meanwhile, could you please do the same test in a 64 bit system and let us know about the result? Thanks.

Kind regards,

Roberto

**Comment by insynwyn** [comment]
I am using 64-bit operating system, x64-based processor.
Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz   2.30 GHz
Edition Windows 10 Enterprise
Version 21H2
Installed on ‎4/‎27/‎2021
OS build 19044.1586
Experience Windows Feature Experience Pack 120.2212.4170.0

**Comment by robertolopezlopez** [comment]
Hi @insynwyn ,

Thank you for your answer. Good that you are using a 64 bit machine :-) Yet still, given the information from your first message, you are using a windows 32 bit binary:

> Terraform v1.1.7
> on windows_386

So, can you try with windows 64 bit akamai terraform provider binary? (I.e. https://github.com/akamai/terraform-provider-akamai/releases/download/v1.11.0/terraform-provider-akamai_1.11.0_windows_amd64.zip) Or maybe the 32 bit binary that you have is the terraform binary itself, not the provider - in any case, please verify.

Kind regards,

Roberto

**Comment by robertolopezlopez** [comment]
Hi @insynwyn ,

Thank you for sharing your `.tf` configuration. I have just managed to reproduce your problem locally, I will develop a fix which will be released as soon as possible.

Linux 32bit: there is an overflow because `PolicyVersion.createDate` is of type `int` (32 bit precission in 32bit architectures)
![image](https://user-images.githubusercontent.com/1519467/162424065-9c2c4bdb-8d17-4823-b016-40bacbc2d985.png)

Linux 64bit: no problem, because `int==int64` in 64bit architectures.
![image](https://user-images.githubusercontent.com/1519467/162424136-99c7b1d2-a455-4205-b978-f3edf3755319.png)

Regards,

Roberto

**Comment by robertolopezlopez** [comment]
In the meanwhile, as stated in my previous message, using the 64 bit binary should fix the problem for you (taking into account that you are using the 64bit windows version)

> Thank you for your answer. Good that you are using a 64 bit machine :-) Yet still, given the information from your first message, you are using a windows 32 bit binary:

**Comment by robertolopezlopez** [comment]
confirmed, the fix works for 32 bit architecture

![image](https://user-images.githubusercontent.com/1519467/162427061-093fc66d-fe4d-4880-b807-07528a515daa.png)

**Comment by lkowalsk-akamai-com** [comment]
This issue is fixed now, closing.
