### ISSUE TITLE
Resource request - Write an EdgeKV item

### ISSUE THREAD

**Issue by danieldbr** [akamai/terraform-provider-akamai#307]
Hi there,

This is a request to create a Terraform resource to perform the same action of this API endpoint: https://techdocs.akamai.com/edgekv/reference/put_item.

### Terraform Version
`1.1.9`

**Comment by robertolopezlopez** [comment]
Hi @danieldbr ,

As you can read in the [EdgeKV resource documentation](https://registry.terraform.io/providers/akamai/akamai/latest/docs/resources/edgekv), at this stage we just support inserting initial data. If the users need to update the edgekv namespace items, they must do it either from their EdgeWorker via API (the most common usage), or programmatically  through the [edgekv-golang](https://pkg.go.dev/github.com/akamai/AkamaiOPEN-edgegrid-golang/v2@v2.12.0/pkg/edgeworkers#EdgeKVItems.UpsertItem) library.

Thank you for your suggestion, we will take it into consideration (we already thought about that during the initial design phase for EdgeKV terraform support).

Regards,

Roberto

**Comment by lkowalsk-akamai-com** [comment]
Hi @danieldbr , just letting you know that we are currently working on adding this functionality. It should be available in coming months. Will update the ticket once I have more details

**Comment by lkowalsk-akamai-com** [comment]
Hi @danieldbr  - possibility to manage items within EdgeKV was introducent in recenent release.
