### ISSUE TITLE
edge hostname associated with property still exists after destroy

### ISSUE THREAD

**Issue by hasc** [akamai/terraform-provider-akamai#310]
Hi there,

when destroying an edge_hostname that is related to an activated property the edge_hostname is actually not deleted although Terraform terminates without any errors.

After destruction of the resources the edge hostname still exists.

### Provider Version
2.0.0

### Terraform Version
Terraform v1.1.9

### Affected Resource(s)
- akamai_edge_hostname

### Terraform Configuration Files
```hcl
resource "akamai_edge_hostname" "this" {
  product_id    = "..."
  contract_id   = "..."
  group_id      = "..."
  edge_hostname = "..."
  ip_behavior   = "IPV6_COMPLIANCE"
}

resource "akamai_property" "this" {
  name        = "..."
  product_id    = "..."
  contract_id   = "..."
  group_id      = "..."
  hostnames {
    cname_from             = var.hostname
    cname_to               = akamai_edge_hostname.this.edge_hostname
    cert_provisioning_type = "CPS_MANAGED"
  }
  ...
}
```

**Comment by robertolopezlopez** [comment]
Hi @hasc,

Thank you for creating this issue ticket. Quoting your terraform logs: `PAPI does not support edge hostname deletion - resource will only be removed from state` ([source](https://github.com/akamai/terraform-provider-akamai/blob/master/pkg/providers/property/resource_akamai_edge_hostname.go#L250))

Kind regards,

Roberto
