### ISSUE TITLE
DXE-1138 Rate limiting, when having many Datastream resources

### ISSUE THREAD

**Issue by Trojan295** [akamai/terraform-provider-akamai#311]
I want to manage Datastream using Terraform. We have a lot of groups and contracts, so finally there are around 80 Datastreams. When trying to apply the Terraform, I get:
```hcl
│ Error: fetching stream information: API error: 
│ {
│       "type": "",
│       "title": "Failed to unmarshal error body",
│       "detail": "invalid character 'Y' looking for beginning of value",
│       "instance": "",
│       "statusCode": 429,
│       "errors": null
│ }
│ 
│   with akamai_datastream.stream["grp_202690-ctr_W-28P9WG"],
│   on datastreams.tf line 22, in resource "akamai_datastream" "stream":
│   22: resource "akamai_datastream" "stream" {
```

I suspect I hit the rate limiting of the API: https://techdocs.akamai.com/datastream2/v2/reference/rate-limiting.
If I set `-parallelism=1`, then it works, but I think it's hacky, and it could happen, that even here we hit the rate limit.

I think it would be useful, if Terraform could retry these requests with some delay, if 429 are returned.

### Terraform Version
```
❯ terraform -v
Terraform v1.1.9
on linux_amd64
+ provider registry.terraform.io/akamai/akamai v2.0.0
+ provider registry.terraform.io/hashicorp/aws v4.14.0
+ provider registry.terraform.io/hashicorp/random v3.1.3
```

### Affected Resource(s)
- akamai_datastream

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files

I removed the resources, which IMO do not matter in this issue.

```hcl
terraform {
  backend "s3" {
    bucket         = "aws-krv-terraform-states"
    key            = "datastream2-export2aws"
    region         = "eu-central-1"
    dynamodb_table = "terraform-locks"
  }

  required_providers {
    akamai = {
      source  = "akamai/akamai"
      version = "~> 2.0"
    }
  }
}

provider "akamai" {
}

locals {
  all_contract_groups = merge(flatten([for group in data.akamai_groups.all.groups : [for contract in group.contract_ids :
    {
      "${group.group_id}-${contract}" = {
        "group_id"    = group.group_id,
        "group_name"  = group.group_name
        "contract_id" = contract
      }
    }
  ]])...)
}

data "akamai_groups" "all" {
}

data "akamai_properties" "all" {
  for_each    = local.all_contract_groups
  contract_id = each.value.contract_id
  group_id    = each.value.group_id
}

resource "akamai_datastream" "stream" {
  for_each = data.akamai_properties.all

  active = false
  config {
    format = "JSON"
    frequency {
      time_in_sec = 60
    }
  }

  group_id     = each.value.group_id
  contract_id  = each.value.contract_id
  property_ids = [for prop in each.value.properties : prop.property_id if prop.production_version > 0 && prop.staging_version > 0]

  dataset_fields_ids = var.datastream_dataset_field_ids

  email_ids = var.datastream_notification_emails

  stream_name   = "${local.all_contract_groups[each.key].group_name} - ${each.value.contract_id} Datastream"
  stream_type   = "RAW_LOGS"
  template_name = "EDGE_LOGS"

  s3_connector {
    access_key        = aws_iam_access_key.akamai_datastream.id
    bucket            = module.datastream_s3_bucket.s3_bucket_id
    connector_name    = "S3Destination"
    path              = "logs/${each.key}"
    region            = var.aws_region
    secret_access_key = aws_iam_access_key.akamai_datastream.secret
  }
}

```

### Debug Output
https://gist.github.com/Trojan295/74149170aabb8a5d7c8a263672732983

### Expected Behavior
Terraform should be able to manage the resources.

### Actual Behavior
Terraform errors, when refreshing the resources and trying to generate the plan.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Create a Terraform module, which creates 20+ Datastream resources
2. Apply the module

**Comment by Trojan295** [comment]
The workaround with `-parallelism=1` is also not really viable. I had to write a script, which lists and targets the Datastream resources is batches.

**Comment by dstopka** [comment]
Hi @Trojan295,

Thank you for reporting this issue to us. I'll try to reproduce it and get back to you with some more details, but it does seem to be related to rate limiting as you suggested.

Regards,
Darek

**Comment by lkowalsk-akamai-com** [comment]
Hi, please try using Rate limit on the Terraform Provider side to make it not hit the limit: https://techdocs.akamai.com/terraform/docs/request-limits-1
