### ISSUE TITLE
Feature Request: Data resource(s) for CPS enrollment(s)

### ISSUE THREAD

**Issue by hypnotisttom** [akamai/terraform-provider-akamai#319]
Hi,

As a feature request, could you kindly add a "data" resource for akamai_cps_dv_enrollment so that we can find existing enrollments?  Ideally, there could be 2 data resources: akamai_cps_dv_enrollments to list them all, and akamai_cps_dv_enrollment (singular) to take common_name and/or other parameters to return enrollment(s) that match.

This would be extremely helpful for several use cases.

Thanks,

Tom

**Comment by majakubiec** [comment]
Hi,

Thank you for your feedback.
We will consider your request and notify you of any updates.

Regards,
Mateusz

**Comment by lkowalsk-akamai-com** [comment]
Hi @hypnotisttom,
Can you share more details about expected data/fields you would like to see in those two datasources? As well with use case you want to resolve. We would then be able to define feasibility of creating such datasources.

**Comment by hypnotisttom** [comment]
Hi,

Thanks for your question.

One of the particular use cases that I'd like to use this resource for is to be able to get the enrollment ID so that I can automate the creation of the import string for some of the existing properties.

Basically, there's no way to get an enrollment after it is created, so if it's created outside of TF, I have to use the API manually to get the enrollment ID, whereas I could use one TF project to take the property hostname and output a local_file with the import strings for the property, the edge hostname, the certificate, and the cp_code.

Normally in TF, any resource that is created should have a corresponding data source that can retrieve it.

In this case, I have the property hostname, so I can use that with akamai_properties_search to get the property, I can then use akamai_property_hostnames to get the edge hostname ID, but there's no enrollment ID, even though other cert info is there.

In thinking through this some more, adding matching enrollment IDs into the hostnames section of akamai_property_hostnames where cert_provisioning_type == CPS_MANAGED, might just solve my use case.

In theory then we could take that ID with a CPS datasource to get more info, but that then comes back to your question on fields and such, which would probably be based on whatever the API GETer is returning when a particular enrollment ID is specified.

That might be the simplest solution.

Does that help?

Thanks,

Tom

**Comment by lkowalsk-akamai-com** [comment]
Hi @hypnotisttom, two data sources were added with 2.3.0 release - check out the CHANGELOG.

**Comment by hypnotisttom** [comment]
Hi,

Thanks.  Unfortunately, that's only one half of it.  The enrollment ID is missing from the akamai_property_hostnames datasource, so even if I use akamai_cps_enrollments, I have no way to know which enrollment belongs to the specific property hostname.  I could check for the hostname itself, iterating over the akamai_cps_enrollments; however, is that guaranteed to return 1 and only 1 CPS enrollment ID?

Thanks,

Tom

**Comment by wzagrajcz** [comment]
Hello @hypnotisttom,
That topic unfortunately is not so straightforward as currently there is no way to find out what certificates are associated with given hostname. The best what You can probably do is to match hostname by name with CN + sans (being careful here because some of them may have wildcards). But be aware because enrollments have option (allow_duplicate_common_name which is not returned from created datasource because we don't have such data) that allows to create an enrollment with some CN even tough there is already present enrollment with the same CN. So answering to Your original question: it is not guaranteed that 1 enrollment is associated with 1 hostname - it's possible to have 0 or even more then 1.

Regards,
Wojciech

**Comment by hypnotisttom** [comment]
Thanks for the info @wzagrajcz.  I did some digging with some help and found out that the edgehostname and CPS enrollments API both contain slot IDs, and if those slot IDs are the same, the cert is assigned to the EHN.  Only thing is I don't believe the slot values for both enrollments and EHNs are being returned by the provider.  Can you confirm if I'm missing something in this assessment, or if the values can be added to the provider, or if there's another limitation I'm unaware of?

Thanks,

Tom

**Comment by wzagrajcz** [comment]
Hello @hypnotisttom 
That is an interesting idea. There will one limitation (at least I am aware of one): based on edge hostnames documentation, the slot number will be returned only for securityType = "ENHANCED-TLS". I don't know also if it'll guarantee only one certificate found for given EHN.

Regarding the changes. For CPS side would it be sufficient for You to add slot number in akamai_cps_enrollments/akamai_cps_enrollment?
Regarding the EHN side it unfortunately won't be simple change and we need to discuss it within the team how to approach the topic. We will come back to You once we have some decisions.

Regards,
Wojciech

**Comment by hypnotisttom** [comment]
Thanks.  Enhanced TLS works for me.  Thanks for pointing that out, as it will be key if we change security type in the future.

I think we need the slot in both EHN and CPS data sources, otherwise we have no way to correlate them.  Yes, on the CPS side adding them into the akamai_cps_enrollments/akamai_cps_enrollment datasources should be fine.  Then we just need the EHN side.

If we can get it in the CPS data sources, while we await the EHN side, I can see if the workflow on our side would allow an nslookup of the EHN to determine the slot value in the CNAME chaining.  Due to security, nslookup may not be possible, but we can look into it.

Thanks for looking into this @wzagrajcz!
