### ISSUE TITLE
Resume existing property activation if in progress for the same version

### ISSUE THREAD

**Issue by dshafik** [akamai/terraform-provider-akamai#32]
If there is an activation pending/in progress for the same version when applying, we should "resume" the activation using it instead of failing or trying to create a new one.

This means the following works as expected:

1. `terraform apply` - creates new activation
2. Timeout occurs, currently leaving terraform in a broken state
3. `terraform apply` - resumes the activation transparently

**Comment by dshafik** [comment]
This should be resolved by #45, however this issue specifically isn't tested fully so I'm leaving it open.

**Comment by zstlaw** [comment]
Issue was resolved.
