### ISSUE TITLE
Feature Enhancement: Better EdgeWorker Hash Management for Drift Detection

### ISSUE THREAD

**Issue by hypnotisttom** [akamai/terraform-provider-akamai#321]
Hi,

For EdgeWorkers, I have a feature request because the gzip of the same source files is producing a different hash, even when using gzip's -n option.  In researching quite a bit, it looks as though hashing a resulting gzip file is not recommended, as the method used to create the compression can vary, and that gzip's RFC basically requires the uncompressed result to be the same, not the compressed one.  The recommendation from those who were discussing this online is to always use the hashes of the uncompressed files to detect drift.

There are two potential enhancements that I see:

1) Either store the hashes of the files in the bundle, rather than the hash of the bundle itself, OR
2) Create the bundle (with Go in the Provider code) such that the hashes remain the same no matter how many times the exact same source files are gzipped

I find that having the provider create the bundle is actually a nice feature enhancement in itself, as I don't have to rely on CI/CD pipelines to do it.  I don't want the user doing it either, as they should just check in their code, and then allow the CI/CD process to create the bundles.  Storing the bundle doesn't actually solve the problem because each CI build would still produce a new artifact.

If the source files didn't change, the provider should not detect a drift with the bundle.  GZIP does not guarantee the hash of the compressed file to be the same, only that the uncompressed files will be the same; therefore, I'm submitting this enhancement because if you still want to use the gzip compressed hash, there's option 2 where you can create the bundle such that it produces the same hash for us, and if you want us to continue to make the bundle, then there's option 1 where your storing of the source file hashes would allow us to make the bundle in the CI/CD process while still allowing drift detection only if the source files changed.

It should be noted that while I have seen methods for creating identical hashes of the compressed gzip file when created multiple times from the same source files, I have not tested them, so that is why my personal recommendation would be to go with option 1, essentially storing an object of hashes in the state file, where each source file in the bundle is hashed.  There would probably need to be a flag or other indicator in the EW resource to point to whether the path is a bundle itself or a path of source files, as this could still be done in a backwards-compatible way.  With using option 1, as an additional bonus or option in the resource, the provider could still make the gzip bundle, even if the hashes of the compressed file are different, as that hash would no longer be needed, and it would make the CI/CD user experience a bit better.

Thanks for allowing me to submit this.

**Comment by robertolopezlopez** [comment]
Hi @hypnotisttom ,

Thank you very much for reporting this. Do you mean that each time we gz-ip the same files may result into a .gz with different hash? We didn't know about this issue, to be honest. This shouldn't have a big impact (apart from creating a new EdgeWorker version each time we apply the update), but in any case we will take care of it and provide a fix as soon as we can.

Kind regards,

Roberto

**Comment by hypnotisttom** [comment]
Thank you very much.  That is exactly right about the behavior.

For me, the impact is also because the repository in the CI/CD pipeline is related to the property, which includes the rule tree json, and whatever the property needs, such as the EW code, cloudlets, etc., so we would have to increase the EW version for every single commit, even if we aren't changing the EW code, which could cause problems given branching, etc.

Thank for classifying it as a bug and agreeing to provide a fix.

Tom

**Comment by robertolopezlopez** [comment]
What I still don't get completely is why are you gzipping the bundle every time you run your pipeline (even if the bundle has not changed). I wonder if you can find a temporary workaround that way.

But well, that's actually not our business :-D so we will just focus on providing a solution from the provider side.

**Comment by lkowalsk-akamai-com** [comment]
Hi @hypnotisttom, this issue was now fixed. Please reopen if it still occurs.
