### ISSUE TITLE
Attempt to change cp_code group_id results in problematic state file

### ISSUE THREAD

**Issue by hypnotisttom** [akamai/terraform-provider-akamai#322]
Using Provider version 2.1.1, in testing what the release notes meant by "Added support for update akamai_cp_code resource" in the version 1.12.0 release notes in terms of what field support was added, I discovered a potential bug with the state:

### Affected Resource(s)
- akamai_cp_code

### Expected Behavior
The state should not have been altered if the group ID change is not permitted.  The expectation would be that simply getting the error message about the immutability then changing the group ID back to the previous group ID (the one the CP Code was created with) should work **without** the need to do state rm and import.

### Actual Behavior
After the apply fails, the user cannot just revert the tf back to the group the CP Code was created with, without performing state management functions first.

### Steps to Reproduce
1. Create the tf for a new cp_code with an existing group ID
2. Perform the terraform apply for this new cp code to create the CP Code
3. Perform another terraform apply to show that everything works after creation prior to the next step
4. Change the group ID on the CP Code in the tf to another existing group ID in the account
5. Perform the terraform apply (Result Expected: cannot change the group ID)
6. Change the group ID back in the TF on the cp_code to the group ID you created the cp_code with in step 1
7. Perform the terraform apply (Result Unexpected: error indicates cp code is not found, even though it exists in the account)
8. Perform state rm on the cp code
9. Perform import of the cp code
10. Re-run the apply (Result: it works again)

**Comment by robertolopezlopez** [comment]
Hi @hypnotisttom ,

Thank you for this new report. We will evaluate the possible defect and release a fix as soon as we can.

Regards,

Roberto

**Comment by lkowalsk-akamai-com** [comment]
Hi @hypnotisttom this issue was fixed, plesae reopen if it still occurs.
