### ISSUE TITLE
Missing some Cloudlets from documents

### ISSUE THREAD

**Issue by hokamoto** [akamai/terraform-provider-akamai#323]
User's Guide of Akamai Terraform Provider for Cloudlets did not list all available cloudlet_code. It mentioned only ER and ALB.
https://registry.terraform.io/providers/akamai/akamai/latest/docs/resources/cloudlets_policy

In another doc, some Cloudlets are still missing (ex. Request Control)
https://registry.terraform.io/providers/akamai/akamai/latest/docs/data-sources/cloudlets_policy

**Comment by dstopka** [comment]
Hi @hokamoto,
Thank you for bringing this to our attention. We'll take a look at it and update the cloudlets documentation.

BR,
Darek

**Comment by lkowalsk-akamai-com** [comment]
Hi @hokamoto, the documentation was udated, closing.
