### ISSUE TITLE
DXE-1344 Missing Pipeline CLI includes functionality in TF templating

### ISSUE THREAD

**Issue by jaescalo** [akamai/terraform-provider-akamai#324]
In the Akamai Pipeline CLI we can add include statements with variables in them, for example:
`"#include:${env.environment}/Offload.json"`

However, the TF templating engine does not appear to support this (even though the pipeline structure is referenced in the provider's documentation). Having this functionality in TF would allow for more flexibility our of the box when there are rules differences between different properties.

**Comment by wzagrajcz** [comment]
Hello @jaescalo 
Thank You for reporting this. Unfortunately the terraform does not provide such mechanism natively. If You provide for which resources/data sources You see it would be useful to have such feature, we will study implementing the mechanism there.

Thanks and best regards,
Wojciech

**Comment by jaescalo** [comment]
Thanks for your reply @wzagrajcz. The data source in question is akamai_property_rules_template (https://registry.terraform.io/providers/akamai/akamai/latest/docs/data-sources/property_rules_template).

**Comment by mgwoj** [comment]
It is related to https://github.com/akamai/terraform-provider-akamai/issues/325

**Comment by lkowalsk-akamai-com** [comment]
@jaescalo this issue was addressed in recent release.
