### ISSUE TITLE
Reusing rules across multiple properties

### ISSUE THREAD

**Issue by macalac** [akamai/terraform-provider-akamai#325]
Hi there,

I have 20+ properties on akamai and would be interested in reusing some of my rules across multiple properties.

Is this possible with this file structure? If not, do you have any pointers on rules reuse, maybe best practices?
```
.
├── preprod
│   └── properties
│       ├── property-a
│       │   └── main.json
│       └── property-b
│           └── main.json
├── prod
│   └── properties
│       ├── property-a
│       │   └── main.json
│       └── property-b
│           └── main.json
└── shared
    └── rules.json
```
I attempted to get the file from the shared dir in `main.json`:
```hcl
{
  "rules": {
    "name": "test",
    "children": [
      "#include:../../../shared/rules.json"
    ]
  }
}

```
But getting file not found error.
```
Error: template: main:33:18: executing "main" at <{{template "../rules.json" .}}>: template "../../../shared/rules.json" not defined
```

### Terraform Version
```
Terraform v1.2.4
on darwin_arm64
```

### Affected Resource(s)
- akamai_property_rules_template

### Expected Behavior
I want to be able to include files from other directories

### Actual Behavior
I am getting file not defined error

**Comment by wzagrajcz** [comment]
Hello @macalac 
Thank you for bringing this to our attention. Can You please provide Your .tf files and rules so we can reproduce that problem and do analysis.

Thanks and best regards,
Wojciech

**Comment by macalac** [comment]
Hey @wzagrajcz 

Thank you for a quick response.

I hope [this](https://github.com/macalac/provider-akamai-325) is a good example? I have included steps to reproduce the problem and the actual error in the main README.

**Comment by mgwoj** [comment]
Hello @macalac 

We are currently checking your issue. We will return to you once we collect more information.

Thanks,
Michal

**Comment by vegardengen** [comment]
Includes are absolute from the point of property-snippets. I'd use "#include shared/rules.json" here.

I have also seen that newer versions, 2.3.0, will skip and give "does not exist" for included files that doesn't validate in itself, so:

```
"children": [
   "#include shared/rules.json"
]
```
 where rules.json includes several arraymelements, does not work, but:

 `"children": "#include shared/rules.json"`
   
   where rules.json includes the elements and the enclosing [] will work.

For me, in the **rules**, I can live with this, but it breaks down when I include some shared variables with several variables in one included file, because **variables** is always a single array and it doesn't support nesting the same way as **rules** does. This bug is related to #353 which admittedly has a misleading title as I reported it before I had done a better investigation.

**Comment by lkowalsk-akamai-com** [comment]
Hi @macalac  @vegardengen 
we recently added new functionality called Includes (not to be confused with the includes handled by Terraform). You can check out the documentation here: https://registry.terraform.io/providers/akamai/akamai/latest/docs/guides/includes
Do let me know if that a viable solution for you.

**Comment by vegardengen** [comment]
On Thu, Feb 09, 2023 at 01:21:05AM -0800, Lukasz Kowalski wrote:
> Hi @macalac  @vegardengen 
> we recently added new functionality called Includes (not to be confused with the includes handled by Terraform). You can check out the documentation here: https://registry.terraform.io/providers/akamai/akamai/latest/docs/guides/includes
> Do let me know if that a viable solution for you.
> 
> 
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/akamai/terraform-provider-akamai/issues/325#issuecomment-1423873159
> You are receiving this because you were mentioned.
> 
> Message ID: ***@***.***>


I have seen it. Long term, that solution is tempting, but it will take a while.


-- 
- Vegard Engen, member of the first RFC1149 implementation team.

**Comment by vegardengen** [comment]
@macalac see my solution in #353 .

**Comment by macalac** [comment]
Hi @vegardengen thanks for this - I think I will try the new approach currently in beta where rules got split into TF resources.

My solution to this was to Jsonnet templates where I could import to my heart's content.
