### ISSUE TITLE
Data Sources for Datastream Getters

### ISSUE THREAD

**Issue by hypnotisttom** [akamai/terraform-provider-akamai#327]
Enhancement for two new data sources:

akamai_datastream
akamai_datastreams

Our streams are being created in one TF project, and then we want to query for a particular stream to apply to a property based on the property information.

akamai_datastreams could return all streams that we could iterate over.

akamai_datastream could be a query based on a combination of contract, group, and stream name, depending on what's provided.  Most likely we will be using the stream name.

Thanks!

**Comment by mgwoj** [comment]
Hi @hypnotisttom ,

Thank you for this suggestion, we are going to evaluate it early next week.

Thanks,
Michal

**Comment by lkowalsk-akamai-com** [comment]
Hi @hypnotisttom 
This seems like a valid request. We will try to add this datasources to the Akamai Terraform Provider. Cannot share any timelines yet. Will update the ticket once I will have some more details.

**Comment by lkowalsk-akamai-com** [comment]
Hi @hypnotisttom new datasources for Datastream were added in relese v3.0.0 of Akamai Terraform Provider.
