### ISSUE TITLE
Add terraform (*.tf) checks to build pipeline

### ISSUE THREAD

**Issue by atward** [akamai/terraform-provider-akamai#33]
The build pipeline should ensure terraform examples are syntactically valid & consistent with community style. 

Current master shows one syntactically invalid config (and all others requiring formatting):

```
$ terraform fmt
examples/akamai_cp_code/cp-code-example.tf
examples/akamai_cps/enrollment-example.tf
examples/akamai_dns_zone/add-records/dnsv2.tf
examples/akamai_dns_zone/add-zone/dnsv2.tf
examples/akamai_dns_zone/add-zone-records/dnsv2.tf
examples/akamai_property/activate-property/activate-property.tf
examples/akamai_property/create-property/create-property.tf
examples/akamai_property/existing-property/existing-property.tf
Error running fmt: In examples/akamai_property/property-json/property.tf: At 2:10: Unknown token: 2:10 IDENT string
$ git show-ref HEAD
f7321b7dae9eea272050fd86992f8bad97ed3b29 refs/remotes/origin/HEAD
```

This can be done with `terraform fmt -check` in an appropriate stage in the Makefile but will require that a terraform binary be available.

[Here](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/8260f1095e587713963b22a55fc829432dbadc8f/.travis.yml#L25-L44) is a travis example of a more complete set of tests which also performs a validate. This would pick up errors of the form:

```
$ cd examples/akamai_cps/; terraform validate

Error: akamai_cps_enrollment.enrollmenttwo: Provider doesn't support resource: akamai_cps_enrollment

Error: provider.akamai: : invalid or unknown key: cps_section
```

I feel this would be an implementable goal which will help to achieve #12

**Comment by dshafik** [comment]
@atward great suggestion, we're still working out our strategy for examples that are maintainable and discoverable. As we roll that out we'll keep this in mind!

**Comment by lkowalsk-akamai-com** [comment]
This has been addresed in the mean time. Closing the issue.
