### ISSUE TITLE
Import existing Akamai DNS/ZONE into TF

### ISSUE THREAD

**Issue by BAu0002** [akamai/terraform-provider-akamai#334]
Is there plan to have the ability to Import existing Akamai DNS/ZONE into TF?

**Comment by majakubiec** [comment]
Hi, thank you for your question.

It is possible to import dns zone.
Once you know what `<zone>` you want to import, create a akamai_dns_zone resource block in your terraform configuration and run the following command:
```sh
$ terraform import akamai_dns_zone.resource_name <zone>
```

BR,
Mateusz

**Comment by BAu0002** [comment]
That's great, I'll give it a go.  What about DNS records?

**Comment by majakubiec** [comment]
To import DNS record, create a akamai_dns_record resource block in your terraform configuration and run the following command:
```
$ terraform import akamai_dns_record.resource_name <zone>#<recordName>#<recordType>
```
Notice the ID consists of 3 values separated with `#` symbol. Here is an example:
```
$ terraform import akamai_dns_record.resource_name example.com#www.example.com#A
```
---
Alternatively you may want to use [akamai cli](https://github.com/akamai/cli) with [cli-terraform plugin](https://github.com/akamai/cli-terraform) to automatically generate tf configuration (zone + records) for you.
Here is an example how to use it:
```
$ akamai terraform export-zone  --importscript --resources  --createconfig <zone>
$ bash example_com_resource_import.script
```

**Comment by BAu0002** [comment]
Thanks.  the zone work. I've not tried the dns but that will be the next thing I'll do

**Comment by BAu0002** [comment]
Another question.  Is there a terraform Data source I can use to get all DNS records for a Zone?

**Comment by majakubiec** [comment]
No, there is no such Data source at the moment, but we will consider adding one in future.
