### ISSUE TITLE
Interger instance in rules not allow reference to variables

### ISSUE THREAD

**Issue by BAu0002** [akamai/terraform-provider-akamai#336]
Hi,
I have similar/same issue to https://github.com/akamai/terraform-provider-akamai/issues/159.
The main.json file have this snip of code:
```
 {
    "name": "cpCode",
    "options": {
        "value": {
            "cpCodeLimits": {
                "currentCapacity": 77,
                "limit": 100,
                "limitType": "global"
            },
            "id": "${env.cpCodeId}",
            "name": "fake",
            "products": [
                "Fresca"
            ]
        }
    }
}
```
I'm getting the following message 
```
"errors": [
│               {
│                       "location": "/rules/behaviors/1/options/value/id",
│                       "schemaLocation": "/definitions/catalog/option_types/cpcode/properties/id",
│                       "detail": "instance type (string) does not match any allowed primitive type (allowed: [\"integer\",\"number\"])",
│                       "foundType": "string",
│                       "allowedTypes": [
│                               "integer",
│                               "number"
│                       ]
│               }
│       ],
```

If I remove the double quote around ${env.cpCodeId} in the json file, I get an error saying 
`invalid JSON result: invalid character '$' looking for beginning of value`

**Comment by majakubiec** [comment]
Hi,
The error looks like api error caused by incorrect `id` type (it expects integer but received a string).

My best guess is that you have defined incorrect type for cpCodeId variable.

Please refer to [property_rules_template docs](https://registry.terraform.io/providers/akamai/akamai/latest/docs/data-sources/property_rules_template#example-usage-variables) for examples how to properly define variables and its types.

If you have problem figuring it out, please provide more information: preferably minimal reproducible example, but your variableDefinitions and variables file should be enough for me to replicate this issue, and we'll try to help you 😄

**Comment by BAu0002** [comment]
I think I'm not understanding of what "/definitions/catalog/option_types/cpcode/properties/id" should hold.
I thought it takes the cp id from the following resource:
```
resource "akamai_cp_code" "cp_code" {
  name        = var.PROPERTY_NAME
  contract_id = data.akamai_contract.contract.id
  group_id    = data.akamai_group.group.id
  product_id  = "prd_Fresca"
}
```
This is not right as akamai_cp_code.cp_code.id return "The ID of the CP code, including the cpc_ prefix".  Is "/definitions/catalog/option_types/cpcode/properties/id the number portion of akamai_cp_code.cp_code.id?

**Comment by majakubiec** [comment]
>  Is "/definitions/catalog/option_types/cpcode/properties/id the number portion of akamai_cp_code.cp_code.id?

yes, it expect integer. [See here](https://techdocs.akamai.com/property-mgr/reference/latest-cp-code)

You need to trim `cpc_` prefix with [trimprefix](https://www.terraform.io/language/functions/trimprefix) before using this value in template.

```
data "akamai_property_rules_template" "akarules" {
  template_file = abspath("${path.root}/property-snippets/main.json")
  variables {
    name  = "cpCodeId"
    value = trimprefix(akamai_cp_code.cp_code.id , "cpc_")
    type  = "number"
  }
}
```

**Comment by BAu0002** [comment]
Yep that seem the case.  For other people refernce, I added this code to get the correct id:
variables {
      name  = "cpCodeId"
      value = replace(akamai_cp_code.cp_code.id,"cpc_","")
      type  = "number"
  }
