### ISSUE TITLE
Is there resource to manage siteShield

### ISSUE THREAD

**Issue by BAu0002** [akamai/terraform-provider-akamai#340]
I want to manage the hostname that is attached to siteShield.
Is there a terraform resource that allow us to do this ?

**Comment by mgwoj** [comment]
Hello @BAu0002 ,

At this moment there is no such resource, but we will consider adding one in future.

**Comment by BAu0002** [comment]
Do you know of any other code method we can do this?

**Comment by Slonimskaia** [comment]
Hello @BAu0002,

Currently, there is no any other way to do that

**Comment by lkowalsk-akamai-com** [comment]
In order to keep things clean, I'm closing this ticket as a duplicate of this one: https://github.com/akamai/terraform-provider-akamai/issues/227. All status updates will be done in the mentioned ticket.
