### ISSUE TITLE
 akamai_cps_dv_enrollments error message

### ISSUE THREAD

**Issue by BAu0002** [akamai/terraform-provider-akamai#341]
akamai_cps_dv_enrollments is returning the below error

```
 {
      "type": "",
     "title": "ApiError(type=Forbidden, title=Invalid Contract, detail=The current contract does not belong to ACG list., source=Contract ID: <myContractID>)",
      "detail": "",
      "statusCode": 400
}
```
 
What does ACG list mean?

**Comment by mgwoj** [comment]
Hello @BAu0002,

`ACG` means "Access Control Group"

The contract does not belong to the user who is making the request. In this case, it looks like the contract ID is simply missing. The contract in question is the one with which the enrollment that is being updated is associated (or where the enrollment is being created).

**Comment by BAu0002** [comment]
sorry, I mask the contract id and it did not show in the previous comment.  I've updated the previous comment.
the contractId is there. When we create cert it is assign to that contractid.

**Comment by mgwoj** [comment]
Just in general, by far the most likely scenario under which you'd have this error is when the credentials are provisioned for one contract, but the changes are being made to an enrollment that lives on a different contract.
If this is not resolving the problem, then we need to see your configuration and TF file to check the details.

**Comment by BAu0002** [comment]
found the solution.
The Contract id must not contain "ctr_" prefix.
