### ISSUE TITLE
How to find sample akamai_appsec_attack_group condition_exception json

### ISSUE THREAD

**Issue by BAu0002** [akamai/terraform-provider-akamai#343]
Hi,

I see that you can set  akamai_appsec_attack_group condition_exception with a json file.
Do you have information on what the json file look like

**Comment by temibayo** [comment]
Hello @BAu0002, 

Please see documentation for an example of json that can be used for condition_exception - https://techdocs.akamai.com/application-security/reference/put-attack-group-condition-exception-1

**Comment by lkowalsk-akamai-com** [comment]
@BAu0002  - does that answer your question?

**Comment by BAu0002** [comment]
yes.  Thank you
