### ISSUE TITLE
DXE-1781 Edge-Hostname failed to create with 3rd party wildcard certificate

### ISSUE THREAD

**Issue by nguyendk270996** [akamai/terraform-provider-akamai#346]
Hi there,

I encounterd API error while trying to create an edge hostname using 3rd party wildcard certificate.

The cert is active and I can create edge hostname using that cert normally on web UI.

### Terraform Version
Terraform v1.1.7

### Terraform Configuration Files
```hcl
resource "akamai_edge_hostname" "this" {
  product_id    = var.edge_product_id
  contract_id   = data.akamai_contract.this.id
  group_id      = data.akamai_group.this.id
  edge_hostname = "${var.domain_name}.${var.domain_suffix}"
  certificate   = var.cps_enrollment_id
  ip_behavior   = var.ip_behavior
}
```

### Expected Behavior
Edge Host name successfully created 

### Actual Behavior

<img width="847" alt="image" src="https://user-images.githubusercontent.com/89342352/195532397-a934f701-3307-4686-9d9c-a07d760b45a9.png">

**Comment by wzagrajcz** [comment]
Hello @nguyendk270996 
Thank You for reporting this issue. Regarding the certificate You mentioned. Can you please confirm two values in the certificate: both `certificateType` and `validationType` are third-party (not e.g. ov or wildcard-san)? And the wildcard occurs in common name or in one of the sans?

Thanks and best regards,
Wojciech

**Comment by nguyendk270996** [comment]
Hi Wojciech,

The certificate type and validation type are 3rd party and wildcard is in CN not SAN

Thanks,

Nguyen

**Comment by Slonimskaia** [comment]
Hi @nguyendk270996,

Thank you for additional information. We will try to reproduce it from our side.

Best regards,
Tatiana

**Comment by wzagrajcz** [comment]
Hello @nguyendk270996 
We have some difficulties in recreating this issue - our tests successfully creates edge hostname based on provided information. 
Can You please provide some more details? Anything that You feel comfortable sharing would be beneficial for both edgehostname (e.g. product_id, ip_behaviour) and enrollment (e.g. usage of dual stack, change management, thirdParty.excludeSans, maxAllowedWildcardSanNames, networkConfiguration).
Was creation of hostname from UI and attempt from terraform made using the same credentials?

Thanks and best regards,
Wojciech
