### ISSUE TITLE
SECKSD-17106 akamai_appsec_activations return timeout error

### ISSUE THREAD

**Issue by BAu0002** [akamai/terraform-provider-akamai#348]
Hi,

akamai_appsec_activations return error "activation context terminated: context deadline exceeded"
is there a way to extend the wait time?

**Comment by JPLodineAK** [comment]
This resource does not currently support setting the context timeout to a value other than the default (20 minutes).

**Comment by BAu0002** [comment]
Can this feature be introduced as activation can take a while and it's a pain for it to break the deployment pipeline.

**Comment by BAu0002** [comment]
also, I get the issue where the statefile become tainted which result in rerun destroying the activation

**Comment by BAu0002** [comment]
Production activation takes more than 20min to activate, which means we cannot use terraform to manage the activation.  This a Major blocker to developing a full CD pipeline.

**Comment by JPLodineAK** [comment]
The akamai_appsec_activations resource will be updated in the next release (late October 2022) to increase the timeout for security configuration activations to 90 minutes. [SECKSD-17106]

**Comment by lkowalsk-akamai-com** [comment]
Hi @BAu0002, this issue has been addressed with v3.0.0 release.
