### ISSUE TITLE
SECKSD-17112 how to get security policy name

### ISSUE THREAD

**Issue by BAu0002** [akamai/terraform-provider-akamai#349]
akamai_appsec_security_policy return a set of policy id and no json.
is there an easy way to get policy name based on pollicy id?

**Comment by JPLodineAK** [comment]
The akamai_appsec_security_policy data source does not currently return policy names as part of its security_policy_id_list attribute. As a workaround, you can parse the output_text attribute, which will contain a few header rows followed by a sequence of ID, NAME columns.

**Comment by BAu0002** [comment]
in coding that's a pain to code.  as an improvement, can we have it return a json output.

**Comment by JPLodineAK** [comment]
We will add a "json" computed output to this resource in the next release, to include the ID & name information in JSON form. [SECKSD-17112]

**Comment by lkowalsk-akamai-com** [comment]
This issue should be now addressed with most recent release. Closing the ticket.
