### ISSUE TITLE
DXE-1789 Reading a nested akamai_property_rules_template fails if the parent file isn't in itself valid JSON.

### ISSUE THREAD

**Issue by vegardengen** [akamai/terraform-provider-akamai#353]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Terraform v1.1.6
on darwin_amd64

### Affected Resource(s)
Please list the resources as a list, for example:
- akamai_property_rules_template

### Expected Behavior
Validation should happen over the complete result, after includes

### Actual Behavior
The top-level rules.json was found invalid and terraform plan fails with:

Error: snippets file should be under 'property-snippets' folder with .json extension and valid json data. Invalid file: ./property-snippets/rules.json 

The fix for issue 332 seems to be what broke it. I have tested with 2.2.0, which succeeds.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform init` with akamai version 2.3.0 or higher.
2. `terraform plan`

### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?

### References
https://github.com/akamai/terraform-provider-akamai/issues/332

**Comment by kaush-** [comment]
Hi @vegardengen,

Thank you for reaching out to us. It might be an issue introduced in the bug fix as you mentioned. For the sake of better understanding can you please give us the `rules.tf` with any sensitive information redacted.

It will help us investigate the issue better.

Regards,
Piyush

**Comment by vegardengen** [comment]
Sorry for the long wait.

First, here is a run with 2.2.0 and 2.3.0:

`ab59987@Vegards-MacBook-Jobb www.dnbtech.no % terraform init -upgrade

Initializing the backend...

Initializing provider plugins...
- Finding latest version of hashicorp/aws...
- Finding akamai/akamai versions matching "2.2.0"...
- Installing akamai/akamai v2.2.0...
- Installed akamai/akamai v2.2.0 (signed by a HashiCorp partner, key ID A26ECDD8F0BCBA73)
- Using previously-installed hashicorp/aws v4.48.0

Partner and community providers are signed by their developers.
If you'd like to know more about provider signing, you can read about it here:
https://www.terraform.io/docs/cli/plugins/signing.html

Terraform has made some changes to the provider dependency selections recorded
in the .terraform.lock.hcl file. Review those changes and commit them to your
version control system if they represent changes you intended to make.

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
ab59987@Vegards-MacBook-Jobb www.dnbtech.no % terraform plan
akamai_edge_hostname.www-dnbtech-no: Refreshing state... [id=ehn_5233292]
akamai_cp_code.dnbbeta-prod-dce-tech-03-net: Refreshing state... [id=cpc_1409456]
akamai_property.www-dnbtech-no: Refreshing state... [id=prp_856982]
akamai_property_activation.www-dnbtech-no: Refreshing state... [id=prp_856982:STAGING]

Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the last "terraform apply":

  # akamai_property_activation.www-dnbtech-no has changed
  ~ resource "akamai_property_activation" "www-dnbtech-no" {
      ~ activation_id                  = "atv_12272850" -> "atv_12273196"
      ~ id                             = "prp_856982:STAGING" -> "prp_856982:PRODUCTION"
        # (7 unchanged attributes hidden)
    }


Unless you have made equivalent changes to your configuration, or ignored the relevant attributes using ignore_changes, the following plan may include actions to undo
or respond to these changes.

────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # akamai_property_activation.www-dnbtech-no will be updated in-place
  ~ resource "akamai_property_activation" "www-dnbtech-no" {
        id                             = "prp_856982:PRODUCTION"
      ~ network                        = "PRODUCTION" -> "STAGING"
      - note                           = "DCE-9138 make dnbtech.no without www work in akamai" -> null
        # (6 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

Note: You didn't use the -out option to save this plan, so Terraform can't guarantee to take exactly these actions if you run "terraform apply" now.
ab59987@Vegards-MacBook-Jobb www.dnbtech.no % vi _config.tf 
ab59987@Vegards-MacBook-Jobb www.dnbtech.no % terraform init -upgrade

Initializing the backend...

Initializing provider plugins...
- Finding akamai/akamai versions matching "2.3.0"...
- Finding latest version of hashicorp/aws...
- Installing akamai/akamai v2.3.0...
- Installed akamai/akamai v2.3.0 (signed by a HashiCorp partner, key ID A26ECDD8F0BCBA73)
- Using previously-installed hashicorp/aws v4.48.0

Partner and community providers are signed by their developers.
If you'd like to know more about provider signing, you can read about it here:
https://www.terraform.io/docs/cli/plugins/signing.html

Terraform has made some changes to the provider dependency selections recorded
in the .terraform.lock.hcl file. Review those changes and commit them to your
version control system if they represent changes you intended to make.

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
ab59987@Vegards-MacBook-Jobb www.dnbtech.no % terraform plan         
akamai_cp_code.dnbbeta-prod-dce-tech-03-net: Refreshing state... [id=cpc_1409456]
akamai_edge_hostname.www-dnbtech-no: Refreshing state... [id=ehn_5233292]
╷
│ Error: snippets file should be under 'property-snippets' folder with .json extension and valid json data. Invalid file: ./property-snippets/rules.json 
│ 
│   with data.akamai_property_rules_template.rules,
│   on data.tf line 1, in data "akamai_property_rules_template" "rules":
│    1: data "akamai_property_rules_template" "rules" {
│ 
╵
ab59987@Vegards-MacBook-Jobb www.dnbtech.no % 
`

**Comment by vegardengen** [comment]
rules.json:

`{END)
  "rules": {
    "name": "default",
    "behaviors": [
      {
        "name": "origin",
        "options": {
          "cacheKeyHostname": "ORIGIN_HOSTNAME",
          "compress": true,
          "#include:team/eplatform/dnb_ca.json",
          "customValidCnValues": [
            "{{Origin Hostname}}",
            "{{Forward Host Header}}"
          ],
          "enableTrueClientIp": true,
          "forwardHostHeader": "ORIGIN_HOSTNAME",
          "hostname": "{{user.PMUSER_TECHBLOG_ORIGIN}}",
          "httpPort": 80,
          "httpsPort": 443,
          "originCertificate": "",
          "originCertsToHonor": "COMBO",
          "originSni": true,
          "originType": "CUSTOMER",
          "ports": "",
          "standardCertificateAuthorities": [
            "akamai-permissive"
          ],
          "trueClientIpClientSetting": false,
          "trueClientIpHeader": "True-Client-IP",
          "verificationMode": "CUSTOM"
        }
      },
      {
        "name": "cpCode",
        "options": {
          "value": {
            "cpCodeLimits": null,
            "id": "${env.techblog_cpcode}",
            "products": [
                  "Site_Defender"
            ]
          }
        }
      },
      {
        "name": "caching",
        "options": {
          "behavior": "NO_STORE"
        }
      },
      {
        "name": "allowPost",
        "options": {
          "allowWithoutContentLength": false,
          "enabled": true
        }
      },
      {
        "name": "allowPut",
        "options": {
          "enabled": true
        }
      },
      {
        "name": "allowDelete",
        "options": {
          "allowBody": false,
          "enabled": true
        }
      },
      {
        "name": "allHttpInCacheHierarchy",
        "options": {
          "enabled": true
        }
      },
      {
        "name": "report",
        "options": {
          "logAcceptLanguage": false,
          "logCookies": "OFF",
          "logCustomLogField": false,
          "logHost": false,
          "logReferer": false,
          "logUserAgent": true,
          "logEdgeIP": false,
          "logXForwardedFor": false
        }
      },
      "#include:team/security/waf_eplatform.json",
      {
        "name": "denyAccess",
        "options": {
          "enabled": "${env.default_deny}",
          "reason": "default-deny-reason"
        }
      },
      "#include:team/security/siteshield.json",
      "#include:team/eplatform/custom_behavior_dnsprefetch.json",
      {
        "name": "dnsAsyncRefresh",
        "options": {
          "enabled": true,
          "timeout": "2h"
        }
      },
      {
        "name": "sureRoute",
        "options": {
          "enabled": false,
          "srDownloadLinkTitle": ""
        }
      }
    ],
    "children": [
      "#include:team/dce/prod/redirect_zone_apex_dnbtech.no.json",
      "#include:team/eplatform/redirect_to_https.json",
      "#include:team/dce/prod/hsts_www.dnbtech.no.json",
      "#include:team/dce/prod/dce_rules_techblog.json"
    ],
    "variables": "#include:variables.json",
    "options": {
      "is_secure": true
    }
  }
}`

**Comment by vegardengen** [comment]
rules.json:

[rules.txt](https://github.com/akamai/terraform-provider-akamai/files/10336039/rules.txt)

**Comment by vegardengen** [comment]
I have now created a full but more limited example than when I ran into it, that demonstrates the issue clearly:

rules.json
[rules.txt](https://github.com/akamai/terraform-provider-akamai/files/10336211/rules.txt)
dnb_ca.json as referenced:
[dnb_ca.txt](https://github.com/akamai/terraform-provider-akamai/files/10336213/dnb_ca.txt)
variables.json:
[variables.txt](https://github.com/akamai/terraform-provider-akamai/files/10336217/variables.txt)
dce_variables_techblog.json:
[dce_variables_techblog.txt](https://github.com/akamai/terraform-provider-akamai/files/10336223/dce_variables_techblog.txt)


rules.json will not valiadate in itself with akamai terraform provider 2.3.0 - but does with 2.2.0. However, if I remove the line including dnb_ca.json it also validates in 2.3.0 and terraform plan works.

So I believe something is validating more strictly.

**Comment by vegardengen** [comment]
I managed to solve a lot of it by changing the structure a bit, ensuring included snippets for rules are always valid json. I think that restriction might not be too bad in itself, even though it might cause some more empty parent rules to get enclosing **children** around some non-validating snippets here and there.

However, the one place I am not able to solve it when variables.json includes several snippets, each containing more than one variable - as the **variables** statement is only one array of elements and can't be nested in the same way as rules.

The actual change that caused this to break, I guess, is this éxcerpt from 2.3.0 in commit defb5edbfb2fb084782dec63e868d4c95e027532:

```
if filepath.Base(dir) != "property-snippets" || filepath.Ext(file) != ".json" || !json.Valid(fileData) {
			logger.Errorf("snippets file should be under 'property-snippets' folder with .json extension: %s", file)				logger.Errorf("snippets file should be under 'property-snippets' folder with .json extension and valid json data: %s", file)

```
!json.Valid(fileData) was added in this commit.

**Comment by kaush-** [comment]
Hi @vegardengen,

Thank you for providing the detailed analysis and files. I will go through them today and try to recreate it and get back to you as soon as possible.

Regards,
Piyush

**Comment by vegardengen** [comment]
I have found a workaround, at least.

Step 1: In data.tf, pull in variables.json:
```
data "akamai_property_rules_template" "variables" {
  template_file = "./property-snippets/variables.json"
}
```

Step 2: Create a variable for it in data.tf, using terraform functions to create a structure out of it, flatten it, then recreate json from it:

```
variables {
   name = "akamai_variables"
   value= jsonencode(flatten(jsondecode(data.akamai_property_rules_template.variables.json)))
   type = "jsonBlock"
}
```

Step 3: In property-snippets/rules.json, I replace:

`"variables": "#include:variables.json"`

with

`"variables": "${env.akamai_variables}"
`

I can now enclose all variables in included JSONs in variables.json with [], which will make the files validate nicely.


Rest of the work was to restructure the JSONs so that they were all valid. All in all, I now believe this was a good cleanup,
and I was now able to upgrade to newest akamai terraform provider

**Comment by Slonimskaia** [comment]
Hi @vegardengen,

Please close this issue if it is not valid anymore.

Best regards,
Tatiana Slonimskaia

**Comment by vegardengen** [comment]
I believe it's sort of valid, as in: Should be documented somewhere.

But I'll close it.
