### ISSUE TITLE
DXE-1790 Documentation for edge hostnames is wrong.

### ISSUE THREAD

**Issue by vegardengen** [akamai/terraform-provider-akamai#354]
When trying to update from IPV4 to IPV4+IPV6, documentation at [](https://registry.terraform.io/providers/akamai/akamai/latest/docs/resources/edge_hostname) states that IPV6_COMPLIANCE is IPV4+IPV6. This failed to update and left the error message that correct value is IPV6_IPV4_DUALSTACK.

When trying with this value, the change succeeds.

This is with akamai terraform provider 2.2.0.

**Comment by kaush-** [comment]
Hi @vegardengen,

I believe you are talking about the documentation [here](https://registry.terraform.io/providers/akamai/akamai/latest/docs/resources/edge_hostname#argument-reference) as,

> [ip_behavior](https://registry.terraform.io/providers/akamai/akamai/latest/docs/resources/edge_hostname#ip_behavior) - (Required) Which version of the IP protocol to use: IPV4 for version 4 only, IPV6_PERFORMANCE for version 6 only, or IPV6_COMPLIANCE for both 4 and 6.

I will check with our functional team and get it fixed.

Regards,
Piyush

**Comment by kaush-** [comment]
Hi @vegardengen,

After further investigation we found out that the issue is not with Docs but it's a bug as our code uses HAPI API to update the IP_BEHAVIOUR. We need to create a mapping between the two types mentioned above in TF code.

We will keep you posted on further updates on this bug.

Regards,
Piyush

**Comment by vegardengen** [comment]
I actually found it more logical that the value is IPV6_IPV4_DUALSTACK than IPV6_COMPLIANCE. And it worked with IPV6_IPV4_DUALSTACK.

**Comment by lkowalsk-akamai-com** [comment]
@vegardengen the issue should be resolved now with the recent (v3.1.0) release.
