### ISSUE TITLE
PAPI Rules Template jsonBlock support for null/empty blocks to allow dynamic rule tree configuration

### ISSUE THREAD

**Issue by hypnotisttom** [akamai/terraform-provider-akamai#355]
This is a potential feature enhancement.

### Affected Resource(s)
akamai_property_rules_template

### Expected Behavior
I'm trying to use the template to create rules/behaviors based on other settings.

The type=jsonBlock is validating the JSON of the block, which while may not be valid JSON, it is valid when incorporated into the rule tree.  I'd like the option to say that null values or empty strings are allowed for specific jsonBlock template variables, this way when the variable is "written out" in the template we can skip over writing that behavior/rule by the nature of the variable being empty.  Maybe a nullable=true parameter?

I don't think it makes sense to permit null/empty for every jsonBlock, as the validation of the json is a nice bonus; I think in cases where we know the variable is okay to being null/empty, that we should be able to say such in the configuration.

If I'm misunderstanding anything, please let me know.

### Actual Behavior
For type=jsonBlock, if the JSON from the variable is an empty string or null, the provider errors out.

If empty string, we get:

```
│Error: Missing required argument
│
│  with data.akamai_property_rules_template.akarules,
│  on rule_template_variables.tf line 1, in data "akamai_property_rules_template" "akarules":
│   1: data "akamai_property_rules_template" "akarules" {
│
│The argument "variables.11.value" is required, but no definition was found.
```

If null, we get:

```
Error: -01T20:54:39.250Z [ERROR] vertex "data.akamai_property_rules_template.akarules" error: unmarshaling value: 'jsonBlock` argument is not a valid json object: papi_post_options:
Error: -01T20:54:39.250Z [ERROR] vertex "data.akamai_property_rules_template.akarules (expand)" error: unmarshaling value: 'jsonBlock` argument is not a valid json object: papi_post_options:

╷
│Error: unmarshaling value: 'jsonBlock` argument is not a valid json object: papi_post_options: 
│
│  with data.akamai_property_rules_template.akarules,
│  on rule_template_variables.tf line 1, in data "akamai_property_rules_template" "akarules":
│   1: data "akamai_property_rules_template" "akarules" {
│
╵
```

### Steps to Reproduce

Create a jsonBlock template variable, setting its value to a null or empty string.  We did this referencing a local variable that had a condition in it, which resulted in either a behavior definition or an empty string.  We tested the same with null.

**Comment by kaush-** [comment]
Hi @hypnotisttom,

Thank you for reaching out to us. At this moment we are already evaluating a more declarative approach for rules and are quite aware of the limitations posed by json design.

The design is still in early phase to share any timeline but be assure that it's being considered. I will be closing this issue for now but feel free to reopen or raise another issue with us in case of any further doubts.

Regards,
Piyush
