### ISSUE TITLE
akamai_property_rules creation without json file ??

### ISSUE THREAD

**Issue by Manikandanmuru** [akamai/terraform-provider-akamai#356]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Terraform v1.3.4 on linux_amd64

### Affected Resource(s)
Please list the resources as a list, for example:
akamai_property_rules

### Expected Behavior
Can we create the akamai_property_rules without using the json file ??? Is that possible to declare the rules into terraform code ?

**Comment by kaush-** [comment]
Hi @Manikandanmuru,

Thank you for reaching out to us. At this moment we are already evaluating a more declarative approach for rules and are quite aware of the limitations posed by json design.

The design is still in early phase to share any timeline but be assure that it's being considered. I will be closing this issue for now but feel free to reopen or raise another issue with us in case of any further doubts.

Regards,
Piyush
