### ISSUE TITLE
DXE-1864 exception_ip_network_lists not working in v3.0.0

### ISSUE THREAD

**Issue by benbrd** [akamai/terraform-provider-akamai#357]
exception_ip_network_lists is not working in v3.0.0, but working fine under v2.4.2

### Terraform Version
`Akadev [/workdir/ip_geo_ipblocklist] >> terraform -v
Terraform v1.3.4
on linux_amd64` 

### Affected Resource(s)
akamai_appsec_ip_geo.ip_geo_block

### Terraform Configuration Files
```hcl
Akadev [/workdir/ip_geo_ipblocklist] >> cat main.tf 
terraform {
  required_providers {
    akamai = {
      source = "akamai/akamai"
//      version = "2.4.2"
    }
  }
}

provider "akamai" {
  edgerc = "~/.edgerc"
}

data "akamai_appsec_configuration" "configuration" {
  name = "Documentation"
}

resource "akamai_appsec_ip_geo" "ip_geo_block" {
  config_id                  = "87577"
  security_policy_id         = "BB55_191257"
  mode                       = "block"
  geo_network_lists          = ["138325_BBROUARDWAFGEOBLOCKLIST"]
  ip_network_lists           = ["138326_BBROUARDWAFIPBLOCKLIST"]
  exception_ip_network_lists = ["138323_BBROUARDWAFIPBLOCKLIST"]
}
```

### Expected Behavior
Block Exceptions under IP/Geo Firewall security controls should be populated with the NL specified.

### Actual Behavior
Block Exceptions under IP/Geo Firewall security controls is empty

### Steps to Reproduce
`terraform apply`

### Important Factoids
This is working fine on v2.4.2

**Comment by lkowalsk-akamai-com** [comment]
Hi @brrbrr , thanks for rising this issue. We were able to reporduce it and will be fixing in.

**Comment by lkowalsk-akamai-com** [comment]
This issue should be fixed in the recent release. I'm closing the ticket.
