### ISSUE TITLE
Unable to create Shared Certificate Hostname

### ISSUE THREAD

**Issue by isss802** [akamai/terraform-provider-akamai#358]
Hi there,

### Terraform Version
```
terraform -v
Terraform v1.3.4
on darwin_amd64
+ provider registry.terraform.io/akamai/akamai v3.0.0
```

### Affected Resource(s)
Please list the resources as a list, for example:
- akamai_property

### Terraform Configuration Files
```hcl
resource "akamai_property" "amd" {
  name        = var.cname_from
  contract_id = data.akamai_contract.contract.id
  group_id    = data.akamai_group.group.id
  product_id  = "prd_Adaptive_Media_Delivery"
  rule_format = "latest"
  hostnames {
    cname_from             = "example.akamaized.net"
    cname_to               = "example.akamaized.net"
    cert_provisioning_type = "CPS_MANAGED"
    cname_type = "SHARED_CERT"
  }
  rules = data.akamai_property_rules_template.rules.json
}
```

### Debug Output

terraform apply can be performed, but Shared Certificate Hostname cannot be created.
The content of tfstate is also set to cname_type = "EDGE_HOSTNAME".
It cannot be created even if it is set to SHARED_CERT.

```
terraform state show akamai_property.amd

 hostnames {
        cert_provisioning_type = "DEFAULT"
        cname_from             = "example.akamaized.net"
        cname_to               = "example.akamaized.net"
        cname_type             = "EDGE_HOSTNAME"
        edge_hostname_id       = "ehn_xxxxxxxx"
```

### Important Factoids
I need a solution to the problem of not being able to create a Shared Certificate Hostname using Terraform.

**Comment by majakubiec** [comment]
Hi, thank you for raising the issue.

`cname_type` will always be set to EDGE_HOSTNAME. It's optional field, but I don't see a single place in code where `cname_type` value is being read. It looks to me that cname_type should be fixed to `computed`(readonly) field only.

I think that using `*.akamaized.net` domain should be enough to enforce SHARED_CERT and it's implicit.
I will verify this and I will get back to you.

Regards,
Mateusz

**Comment by isss802** [comment]
Thanks for checking.

In the case of EDGE_HOSTNAME, the specified Hostname can be created but not a Shared Certificate.

It will be a configuration where you have to provide your own certificate.

Certificate is not 「TLS Enabled Manage in CPS 」, but 「Shared」 is correct.

<img width="1730" alt="image" src="https://user-images.githubusercontent.com/4577575/200714847-930fb9ae-5e8c-4f04-a9f6-3d845aad45c7.png">

Here are the settings to expect.(Created from ACC.)

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/4577575/200716275-af8dc979-7fc9-4d06-91d2-6b92a9e0cadc.png">

**Comment by majakubiec** [comment]
I have spend some time investigating this today. There seems to be some pubic api limitation that doesn't allow for adding shared cert hostnames to property. Unfortunately there is no known workaround for it that I know of. I will try to get more information about this and I will keep you posted.

**Comment by isss802** [comment]
It is critical that akamaized.net in SHARED_CERT cannot be managed by Terraform.
We would like to have this addressed as an API modification request.

**Comment by lkowalsk-akamai-com** [comment]
This change requires underling API to extend their scope. The request to do such thing was done. We cannot share any timelines as of now. We will close this ticekt for now and reopen when this capability is added to the API.

**Comment by jonasdkhansen** [comment]
@lkowalsk-akamai-com Hi, i'm also running in to this issue, with the missing shared certificate functionality. Do you know if there is there any updates on this ?
