### ISSUE TITLE
Terraform fails to create akamai_botman_custom_bot_category resource even with fully-permissioned API clients/service accounts

### ISSUE THREAD

**Issue by theron-idme** [akamai/terraform-provider-akamai#359]
### Terraform Version
1.2.9

### Affected Resource(s)
Please list the resources as a list, for example:
- akamai_botman_custom_bot_category

### Terraform Configuration Files
```hcl
resource "akamai_botman_custom_bot_category" "blocked_bot_category" {
  config_id           = akamai_appsec_configuration.bot_block_config.config_id
  custom_bot_category = jsonencode({
    categoryName = "blocked_bots"
    description  = "Requests from bots in this category will be blocked/sent to tarpit"
    notes        = "Created through Terraform"
  })
}
```

### Debug Output
I can't post the entire output, but the error is
```
akamai_botman_custom_bot_category.blocked_bot_category: Creating...
╷
│ Error: Title: Unauthorized Access/Action; Type: https://problems.luna.akamaiapis.net/appsec/error-types/UNAUTHORIZED; Detail: You do not have the necessary access to perform this operation.
│ 
│   with akamai_botman_custom_bot_category.blocked_bot_category,
│   on bot_management.tf line 20, in resource "akamai_botman_custom_bot_category" "blocked_bot_category":
│   20: resource "akamai_botman_custom_bot_category" "blocked_bot_category" {
```

### Expected Behavior
I've tried an API client with full permissions for all Akamai APIs, and a service account with full permissions for all Akamai APIs. Either should be able to create a `akamai_botman_custom_bot_category` resource. Other resources such as `akamai_appsec_security_policy` and `akamai_appsec_configuration` are created without issue. I also tried to create a custom bot category through the console, which worked, but then I tried to `terraform import` it and it failed with the same `Unauthorized Access` error.

### Actual Behavior
I received this error: `Error: Title: Unauthorized Access/Action; Type: https://problems.luna.akamaiapis.net/appsec/error-types/UNAUTHORIZED; Detail: You do not have the necessary access to perform this operation.`

### Steps to Reproduce
1. `terraform apply`

**Comment by theron-idme** [comment]
I also tried to use the `data "akamai_botman_custom_bot_category" "blocked_bot_category"` data source to refer to the category I created in the console and still get the same error.

**Comment by lkowalsk-akamai-com** [comment]
Hi @theron-idme thanks for trying to use Botman Terraform subprovider. 
We checked and your Akamai account ismissing BOTMAN_AKAMAI_API_TP scope due to which the you are not able to perform any botman open api operations.
Botman is currently in BETA. Please reach out to your Akamai Account Manager to have this setup for you.

Is there anything else we can help? If not, I think this case can be closed.

**Comment by theron-idme** [comment]
Thanks, will contact our account manager shortly.
