### ISSUE TITLE
akamai_edge_hostname - How to add mulitple hostnames

### ISSUE THREAD

**Issue by MarkDordoy** [akamai/terraform-provider-akamai#36]
Hello

What is the format required to add more than one edge hostname to a hostname resource. 

Eg 
```
resource "akamai_edge_hostname" "trade_edge_hostname" {
    product  = var.product
    contract = data.akamai_contract.clarksons_contract.id
    group    = data.akamai_group.clarksons_group.id
    edge_hostname = ["${staging_edge_hostname_prefix}.edgekey.net", "${production_edge_hostname_prefix}.edgekey.net"]
    ipv4 = true
    ipv6 = true
}
```
### Terraform Version
0.12.3

### Affected Resource(s)
Please list the resources as a list, for example:
- akamai_edge_hostname

### Expected Behavior
Create an edge hostname with mulitple hosts

### Actual Behavior
A reference to a resource type must be followed by at least one attribute
access, specifying the resource name.

### Steps to Reproduce
terrafom apply

### References
Documentation here implies you can add multiple edge hostnames but it doesnt say the format required

**Comment by dshafik** [comment]
@MarkDordoy you should either use a loop (count = 2) with a map containing each hostname, or have multiple `akamai_edge_hostname` blocks.

Something like this:

```hcl
variable "edge_hostnames" {
  default = [
      {
          hostname = "${staging_edge_hostname_prefix}.edgekey.net"
      },
      {
            hostname = "${produciton_edge_hostname_prefix}.edgekey.net"
      }
  ]
}

resource "akamai_edge_hostname" "trade_edge_hostname" {
    count = 2
    product  = var.product
    contract = data.akamai_contract.clarksons_contract.id
    group    = data.akamai_group.clarksons_group.id
    edge_hostname = var.edge_hostnames[count.index].hostname
    ipv4 = true
    ipv6 = true
}
```

**Comment by dshafik** [comment]
@MarkDordoy can you confirm that this solved your issue? Thanks!

**Comment by MarkDordoy** [comment]
@dshafik yes your proposal does work. However in my opinion that just creating two akamai_edge_hostname resources does the same job (albeit with more config). The documentation wording leads me to think it supports an array of values for the argument `edge_hostname`. 

I will close this ticket but i do think it might be worth updating the documentation as it is a bit misleading
