### ISSUE TITLE
multiple include JSON in akamai_property_rules_template not working in v3.0.0

### ISSUE THREAD

**Issue by chrisminton** [akamai/terraform-provider-akamai#361]
### Terraform Version
```
Terraform v1.3.5
on darwin_amd64
+ provider registry.terraform.io/akamai/akamai v3.0.0
```

also tested on 
```
+ provider registry.terraform.io/akamai/akamai v2.4.1
```

### Affected Resource(s)

`akamai_property_rules_template`

### Terraform Configuration Files
```hcl
data "akamai_property_rules_template" "this" {
  template {
    template_data = jsonencode({
      "rules" : {
        "name" : "default",
        "children" : [],
        "behaviors" : "#include:behaviors.json",
        "comments" : "The Default Rule template contains all the necessary and recommended behaviors.",
        "options" : {
          "is_secure" : var.secure
        }
      }
    })
    template_dir = abspath("${path.root}/property-snippets/")
  }
```

behaviors.json:
```
[
  {
    "name": "origin",
    "options": {
      "cacheKeyHostname": "ORIGIN_HOSTNAME",
      "compress": true,
      "enableTrueClientIp": true,
      "forwardHostHeader": "ORIGIN_HOSTNAME",
      "hostname": "some-hostname",
      "httpPort": 80,
      "httpsPort": 443,
      "originCertificate": "",
      "originCertsToHonor": "STANDARD_CERTIFICATE_AUTHORITIES",
      "originSni": true,
      "originType": "CUSTOMER",
      "ports": "",
      "standardCertificateAuthorities": [
        "akamai-permissive"
      ],
      "trueClientIpClientSetting": false,
      "trueClientIpHeader": "True-Client-IP",
      "verificationMode": "CUSTOM"
    }
  }
]
```
### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Expected Behavior
The akamai_property_rules_template is created with the expected includes.

### Actual Behavior
```
│ Error: template: main:1: unexpected "," in template clause
│ 
│   with data.akamai_property_rules_template.this,
│   on main.tf line 1, in data "akamai_property_rules_template" "this":
│    1: data "akamai_property_rules_template" "this" {
```

If the behaviors.json is put in place of the `"#include:behaviors.json"` it successfully generates.

JSON is valid. The problem appears to be with any `#include` blocks - if any other lines are added to the `template_data` JSON it does not parse correctly, e.g. the following will plan correctly:

```hcl
    template_data = jsonencode({
      "rules" : {
        "children" : [
          "#include:deny_access_header.json",
        ]
      }
    })
    template_dir = abspath("${path.root}/property-snippets/")
```

but this will not:

```hcl
    template_data = jsonencode({
      "rules" : {
        "children" : [
          "#include:deny_access_header.json",
          "#include:prefetch.json",
        ]
      }
    })
    template_dir = abspath("${path.root}/property-snippets/")
```

similarly this will:

```hcl
    template_data = jsonencode({
      "rules": {
        "behaviors": "#include:behaviors.json"
      }
    })
    template_dir = abspath("${path.root}/property-snippets/")
```

and this will not:

```hcl
    template_data = jsonencode({
      "rules" : {
        "name": "default",
        "behaviors": "#include:behaviors.json"
      }
    })
```

### Steps to Reproduce

1. `terraform plan`

### Important Factoids
This is running with Terragrunt `0.40.2` as a wrapper around Terraform.

**Comment by chrisminton** [comment]
The `jsonencode()` block is the issue, whereas heredocs work fine.

```hcl
data "akamai_property_rules_template" "this" {
  template {
    template_data = <<-EOT
    {
      "rules" : {
        "name" : "default",
        "children" : [
          "#include:template1.json",
          "#include:template2.json",
          "#include:template3.json"
        ]
        "behaviors" : "#include:behaviors.json",
        "comments" : "The Default Rule template contains all the necessary and recommended behaviors. Rules are evaluated from top to bottom and the last matching rule wins.",
        "options" : {
          "is_secure" : true
        }
      }
    }
    EOT
    template_dir  = abspath("${path.root}/property-snippets/")
  }
}
```

This could be clarified in the documentation, as it was not obvious to me!

**Comment by kaush-** [comment]
Hi @chrisminton,

Thank you for bringing this to our notice. I agree that the docs could be more clarified as in the description of `template_data`, we do say that "Content of the template as string". But there could be more emphasis on it being in string format and not using jsonencode, As we parse the string to JSON internally in data source code.

That being said, I would like to inform you that currently we are in process of redesigning rules in more declarative state. As it is still in early design phase I can't put a time line around it. But it will definitely give us the opportunity to provide a better experience when dealing with PAPI rules.

I will be closing this issue for now, but feel free to re-open in case you have any further questions related to this topic.

Regards,
Piyush
