### ISSUE TITLE
DXE-1909 can't activate  property  with akamai_property_activation

### ISSUE THREAD

**Issue by sissi48** [akamai/terraform-provider-akamai#363]
Hello,
I can't activate a property with the module akamai_property_activation, because in the behavior I add a site shield map of type **enhanced TLS:**
{
    "name": "siteShield",
    "options": {
        "ssmap": {
            "name": "test",
            "value": "test.**akamaiedge.net**",
            "srmap": "test.akamai.com",
            "hasMixedHosts": false,
            "src": "PREVIOUS_MAP"
        }
    }
}

**ERROR**
Error: activation cannot continue due to rule errors: [
│       {
│               "behavior_name": "",
│               "detail": "When `SiteShield` is used with the HTTP Only/Standard TLS security option the domain name of the `SiteShield` map must end with .akamai.net",
│               "error_location": "#/rules/behaviors/1",
│               "instance": "",
│               "status_code": 0,
│               "title": "",
│               "type": [https://problems.luna.akamaiapis.net/papi/v0/validation/validation_message.regex_validation_notsecure]

I think there is a regex in the module that checks that the name of the shield map ends in akamai.net but when the shield map is of type enhanced it ends in akamaiegde.net

**when I try to activate with a call api it works**

**Comment by kaush-** [comment]
Hi @sissi48,

Thank you for reaching out to us, It seems to me like a valid issue. We are currently in re-designing rules in more declarative approach.

I will check and confirm if this issue will be resolved as part of that feature or if there is a separate investigation needed. We will keep you posted.

Regards,
Piyush

**Comment by sissi48** [comment]
Thanks for your feedback.
can tell us if you were able to progress on the bug ?

Regards,

**Comment by kaush-** [comment]
Hi @sissi48,

We need some help from you in further investigating this issue, usually the workflow which is implemented in TF is as:

- When you run GetPropertyRuleTree you get the rules and errors if the rules have them.
- Before we do the call to Activate we check for those errors and if they are present we do an early return with an error.
- What is weird is as you said it passes through the API, from our experience activation call should fail if there are any errors, but maybe it is some specific configuration.

Can you provide me with the following:
- TF config file
- What GetIncludeRuleTree with validate=true returns
- After calling the Activate what does GetActivation return as well

Looking forward to hearing from you.

Regards,
Piyush

**Comment by sissi48** [comment]
Hello,
The bug has been fixed.
Had to set the is_secure variable to true in the JSON file generated by Terraform, as we are in Enhanced TLS.

Regards,

**Comment by wzagrajcz** [comment]
Hello @sissi48 
Thank You for update. In such case I will close this issue. In case of problems please create a new one (or reopen that). 

Thanks and best regards,
Wojciech
