### ISSUE TITLE
Match Targets and Security Policy Order

### ISSUE THREAD

**Issue by BAu0002** [akamai/terraform-provider-akamai#366]
I understand you can change the Secuirty policy Order in the akamai UI.
How does Secuirty policy Order get defined in terraform ?

**Comment by JPLodineAK** [comment]
Order does not apply to security policies. For match targets, you can change the order using the akamai_appsec_match_target_sequence resource, described [here](https://registry.terraform.io/providers/akamai/akamai/latest/docs/resources/appsec_match_target_sequence)
