### ISSUE TITLE
DXE-1928 when using akamai_cps_dv_enrollment to create DV san certs, it can't handle German language

### ISSUE THREAD

**Issue by janezhen08** [akamai/terraform-provider-akamai#368]
Hi there,

We are using terraform akamai provider to create DV san certs, for the csr part,

  csr {
    country_code        = var.csr_country_code
    city                = var.csr_city
    organization        = var.csr_organization
    organizational_unit = ""
    state               = var.csr_state
  }

we are using this value:

variable "csr_state" {
  type  = string
  #default  = "Baden-W\u00fcrttemberg"
  default = "Baden-Württemberg"
}

During the first time, we run terraform apply, it shows it will apply below value, which is correct.

<img width="513" alt="image" src="https://user-images.githubusercontent.com/47620416/205852762-fe1e8d5b-7e3d-44ca-bf48-64f268ccd43a.png">

After the cert is created, and in the terraform.tfstate file, it also shows correctly as below:

<img width="473" alt="image" src="https://user-images.githubusercontent.com/47620416/205853034-d3a69d45-826d-4ca1-a892-016068010fd7.png">

But when we rerun the terraform apply, it will made change as below, we did not change anything in the terraform code.

<img width="705" alt="image" src="https://user-images.githubusercontent.com/47620416/205853615-bda3770b-e5af-45cf-a291-c32570675a1d.png">

Could you take a look and resolve?

thanks

Jane

**Comment by janezhen08** [comment]
we checked in Akamai control center UI, and found the certificate is created with below state name:

Baden-WÃ¼rttemberg

<img width="620" alt="image" src="https://user-images.githubusercontent.com/47620416/205874467-1f7ff3d8-aab9-4280-afa7-7bf8639601f7.png">

**Comment by wzagrajcz** [comment]
Hello @janezhen08 
Thank You for opening that issue. We were able to recreate it and will work on a fix.

Thanks and best regards,
Wojciech

**Comment by janezhen08** [comment]
hello team,

Any update for this bug? it blocks our application onboarding.

thanks

Jane

**Comment by lkowalsk-akamai-com** [comment]
Hi @janezhen08, this issue should be fixed in next release. Most probalby at the end of the January.

**Comment by janezhen08** [comment]
Hi there,

Is this bug fixed yet?

thanks

Jane

**Comment by lkowalsk-akamai-com** [comment]
Hi @janezhen08 , next relesae of Terraform Provider is scheduled for 2nd of February (comming Thursday). Thank you for your patience with this one.

**Comment by lkowalsk-akamai-com** [comment]
Hi @janezhen08 , new version of Terraform Provider was just relesed. The issue should be fixed now.
