### ISSUE TITLE
akamai edge hostname not being deleted part of terraform destroy

### ISSUE THREAD

**Issue by BAu0002** [akamai/terraform-provider-akamai#369]
I noticed that terraform destroy of akamai_edge_hostname does not remove edge hostname.
Is this by design?

**Comment by wzagrajcz** [comment]
Hello @BAu0002 
Yes, it is by design - there is no endpoint to delete edge hostname neither from PAPI nor HAPI side. We log such information into terraform log.

Thanks and best regards,
Wojciech

**Comment by dvorakd** [comment]
Would this endpoint be appropriate? https://techdocs.akamai.com/edge-hostnames/reference/delete-edgehostname

**Comment by RemcoAA** [comment]
It looks like now there is a HAPI endpoint available for deleting an edge hostname. Are there plans  to integrate this in the Terraform module?

**Comment by identw** [comment]
@RemcoAA @dvorakd @BAu0002 
I added PR with implemented destroy method for edge hostname https://github.com/akamai/terraform-provider-akamai/pull/490. I hope PR will be merged

**Comment by arvidsnet** [comment]
can we reopen this issue?

**Comment by lkowalsk-akamai-com** [comment]
Hi @arvidsnet - we have another ticket we are tracking this request under -> https://github.com/akamai/terraform-provider-akamai/issues/504
