### ISSUE TITLE
Documentation discrepancy : property_activation.html.markdown

### ISSUE THREAD

**Issue by MarkDordoy** [akamai/terraform-provider-akamai#37]
Hello 

The documentation for `akamai_property_activation` example and argument reference are not the same. 

https://www.terraform.io/docs/providers/akamai/r/property_activation.html

**Comment by dshafik** [comment]
This should be resolved when the docs next rebuild, thanks 👍

**Comment by dshafik** [comment]
This has now deployed, so I'm going to close this issue. Let us know if there are any further issues!
