### ISSUE TITLE
DXE-1937 Impossible to use distinct values for priority, weight and port for SRV records with multiple targets

### ISSUE THREAD

**Issue by hightoxicity** [akamai/terraform-provider-akamai#370]
Hi there,

I am importing into terraform dns records already living in edgedns but I have a question regarding SRV records...

Looking at https://github.com/akamai/terraform-provider-akamai/blob/d3c9f2f27fc4058c91f50bf2fc832eabccc0f199/pkg/providers/dns/resource_akamai_dns_record.go#L1854

It means that only one value for respectively priority, weight and port can be provided for all specified targets of a SRV record.
But AFAIK and looking at example you provide in akamai GUI, we can have a record value like this for SRV:

```
10 60 5060 big.example.com
10 40 5060 small.example.com
20 10 5060 tiny.example.com
```

For each entry we can have distinct priority, weight, port...

You already manage the fact user can set priority directly in target for MX record type, so why do you not allow to do the same for SRV?

Thanks for your help

**Comment by majakubiec** [comment]
Thanks for creating this issue! We appreciate you bringing this to our attention.
> why do you not allow to do the same for SRV?

We will take a look at it, determine if it is feasible, and get back to you as soon as possible.

**Comment by hightoxicity** [comment]
Hi I am also hiting a weird behavior with a SRV record, looking at its associated sha1sum computed by the provider and inserted into the state file, I was trying to forge some json state for bulk state feeding and found this:

2023-01-27T15:12:10.032+0100 [DEBUG] provider.terraform-provider-akamai_v3.2.1: 2023/01/27 03:12:10 [DEBUG] READ SHA sum for Existing SHA test 10 80 5060 big.example.com. 10 80 5060 small.example.com. 10 80 5060 tiny.example.com. 75b7831d91ca1edc5d2c05d886d8291eb7357f83: AkamaiDNS=resourceDNSRecordRead OperationID=2efdc4f0-bef1-4ff5-8e48-f2a634e258f2

When the record is described as following:

![image](https://user-images.githubusercontent.com/11333624/215112707-44c6147a-823b-48a6-9318-a1f24b4b429a.png)

It is quite linked to my above comment but it may be qualified as an issue IMO since sha1sum does not represent what is living truly in edgedns.

Thx

**Comment by mgwoj** [comment]
Hello @hightoxicity,

I have analyzed this issue and here is my recommendation on how it should work. I see two modes: 
1. one when you provide values for fields `priority`, `weight` and `port`, you can omit them for **all** targets and provide only the canonical hostname. This will guarantee backward compatibility.
2. second is when you want to assign those values independently to **every** target, then fields `priority`, `weight` and `port` should not be populated.
With this approach we should not mix targets with and without priority, weight and port.

Here is example for mode 1
```hcl
resource "akamai_dns_record" "srv_record" {
  zone       = "origin.org"
  name       = "origin.example.org"
  recordtype = "SRV"
  active     = true
  ttl        = 300
  priority   = 10
  weight     = 60
  port       = 5060
  target     = [
    "big.example.com",
    "small.example.com",
    "tiny.example.com"
  ]
}
```

Here is example for mode 2:
```hcl
resource "akamai_dns_record" "srv_record" {
  zone       = "origin.org"
  name       = "origin.example.org"
  recordtype = "SRV"
  active     = true
  ttl        = 300
  target     = [
    "10 60 5060 big.example.com",
    "10 40 5060 small.example.com",
    "20 100 5060 tiny.example.com"
  ]
}
```

And here is an example of the combination which will not be supported:
```hcl
resource "akamai_dns_record" "srv_record" {
  zone       = "origin.org"
  name       = "origin.example.org"
  recordtype = "SRV"
  active     = true
  ttl        = 300
  priority   = 10
  weight     = 60
  port       = 5060
  target     = [
    "big.example.com",
    "small.example.com",
    "20 50 5060 tiny.example.com"
  ]
}
```

**Comment by lkowalsk-akamai-com** [comment]
This feature is now available in Akamai Terraform Provider
