### ISSUE TITLE
DXE-2039 akamai_property_include latest_version not being latest version

### ISSUE THREAD

**Issue by jjgrinwis** [akamai/terraform-provider-akamai#376]
### Terraform Version
$ terraform -v      
Terraform v1.3.6
on darwin_amd64
+ provider registry.terraform.io/akamai/akamai v3.2.1

### Affected Resource(s)
akamai_property_include

### Terraform Configuration Files
```hcl
resource "akamai_property_include" "my_example" {
  contract_id = data.akamai_contract.contract.id
  group_id    = data.akamai_contract.contract.group_id
  product_id  = lookup(var.aka_products, lower(var.product_name))
  name        = var.include_name
  rule_format = var.rule_format
  rules       = file("papi-rules/rules.json")
  type        = "COMMON_SETTINGS"
}

resource "akamai_property_include_activation" "activate_include" {
  include_id  = resource.akamai_property_include.my_example.id
  contract_id = data.akamai_contract.contract.id
  group_id    = data.akamai_contract.contract.group_id
  version = resource.akamai_property_include.my_example.latest_version
  network = "STAGING"
  notify_emails = [
    var.email
  ]
  note = "Activated via TF"
}
```

### Debug Output

After updating an existing include property, still version 1:
---
akamai_property_include.my_example: Modifying... [id=inc_872320]
akamai_property_include.my_example: Modifications complete after 7s [id=inc_872320]

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.

Outputs:

latest_version = 1
---

Running terraform apply again without any changes:
akamai_property_include_activation.activate_include: Modifying... [id=ctr_3-16TWBVX:grp_48668:inc_872320:STAGING]
akamai_property_include_activation.activate_include: Still modifying... [id=ctr_3-16TWBVX:grp_48668:inc_872320:STAGING, 10s elapsed]
akamai_property_include_activation.activate_include: Modifications complete after 2m16s [id=ctr_3-16TWBVX:grp_48668:inc_872320:STAGING]

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.

Outputs:

latest_version = 2

### Expected Behavior
the .latest_version should be the just-created version, not the previous version. Just like when updating a regular property when the .latest_version is the updated version so we can update and activate the latest version in one go.

### Actual Behavior
latest_version is still number 1, should be 2 after making a change.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. terraform apply
2. update rules
3. terraform apply
4. terraform apply

**Comment by kaush-** [comment]
Hi @jjgrinwis,

Thank you for raising this issue with us, we are already tracking this internally and is being worked upon in current sprint. We do have it scheduled for the next release unless something changes.

In case you have any other questions, feel free to ask.

Regards,
Piyush
