### ISSUE TITLE
DXE-2099 Missing data sources

### ISSUE THREAD

**Issue by hypnotisttom** [akamai/terraform-provider-akamai#377]
Hi,

In a previous issue, I had briefly mentioned some resources are missing data sources to look them up, and Akamai was able to create the specific data sources I needed at the time, which I am very thankful for.  I'm opening this issue so that we can track data sources for the remaining resources.

For example, we are currently implementing GTM.  There is no akamai_gtm_datacenter datasource to lookup DCs. 

Our creation of the properties is to be automated and as a result is asynchronous from the creation of the DCs.  This requires us to use the DC IDs instead of looking them up by name, which actually limits our templating capabilities.

I'm hoping Akamai can create the data sources that are missing in the Provider overall (and for what it's worth, any missing import capabilities as well).

Thanks,

Tom

**Comment by srumberger** [comment]
Hi,

To piggyback off of Tom, one of the biggest issues we are facing with hardcoding our Datacenter IDs is that if the datacenter were to be destroyed and readded with the same params the datacenter id will change. This will cause all of our GTM properties using that datacenter to fail on terraform deploys. 

In an ideal scenario would use a data source to tie the Property Traffic Targets to their datacenters using the nickname of the datacenter so if something were to happen and a datacenter was destroyed and then recreated, we would not need to edit the datacenter IDs of each property's traffic targets

Thanks,
Sam

**Comment by kaush-** [comment]
Hi @hypnotisttom and @srumberger,

Thanks for bringing this to our notice, we we have already tagged this request. This is an ongoing process where all our new resources are coming with their respective sub providers. At the same time we are trying to prioritize existing debt as well in between our sprints.

We will be tracking internally to create the missing data sources for GTM sub provider. In case of any other questions please do let us know.

Regards,
Piyush

**Comment by hypnotisttom** [comment]
Thanks @kaush- for your response.  I'm glad the team is chipping away at the tech debt and that we can surface the items we are running into to help with prioritization.  I really appreciate it!

Thanks,

Tom

**Comment by lkowalsk-akamai-com** [comment]
Two data sources for datacenters were added in 4.1 release.
