### ISSUE TITLE
DXE-2158 remove enforce property-snippets dir check

### ISSUE THREAD

**Issue by mza08** [akamai/terraform-provider-akamai#378]
@vnarra777

Could you explain to me what's the logic behind enforced base foldername?

https://github.com/akamai/terraform-provider-akamai/blame/2413125991ed67524edc7a1889e8f5eb0d128909/pkg/providers/property/data_akamai_property_rules_template.go#L136

I could place my snippets/templates in nested folders and it would work as long as the parent folder for json file (default rule) is called property-snippets. Example:

`blah/blah1/blah2/blah3/property-snippets/default.json`.

Can we drop that policy? In my opinion there's no common sense.

**Comment by kaush-** [comment]
Hi @mza08,

@vnarra777 is no longer directly involved with this project. Thank you for raising this issue with us, so far it has been more of a functional need and also the folder name helps as a point to start looking for rules json. Another simplification it provides us is with the removal of a new variable name to handle when communicating between multiple apps/TF instances eg: CLI-Terraform etc.

I can bring this to the notice of the PAPI team if they are okay with dropping this check, then we can further consider this. Let me know if you have any other questions.

Regards
Piyush

**Comment by mtz29** [comment]
Hi @kaush- 

Regarding the statement `also the folder name helps as a point to start looking for rules json`. Let's make it clear - it does not look for rules (json) in parent folder (starting point) but any path matching the pattern (hardcoded the lowest level folder name). So let's either make it consistent to start searching in specific parent folder or remove that useless constraint.

Thank you.

// forgot to login to my other account

**Comment by lkowalsk-akamai-com** [comment]
Hi @mtz29 , enforcemenet of the folder name was removed with recent release.
