### ISSUE TITLE
Unsupported Media Type property rule tree update with rule_Format v2022-10-28

### ISSUE THREAD

**Issue by gordonkramer** [akamai/terraform-provider-akamai#379]
Hi there,

### Terraform Version
Terraform v1.3.6
on linux_arm64
+ provider registry.terraform.io/akamai/akamai v3.2.1

### Affected Resource(s)
Please list the resources as a list, for example:
- akamai_property

all akamai_property resources affected

### Terraform Configuration Files
```hcl
resource "akamai_edge_hostname" "main" {
  product_id    = "prd_${var.product}"
  contract_id   = "ctr_${var.contract}"
  group_id      = "grp_${var.group}"
  edge_hostname = "${var.hostname}.${var.edge_hostname_domain_suffix}"
  ip_behavior   = "IPV6_COMPLIANCE"
  use_cases     = var.edge_hostname_use_cases_json
}

resource "akamai_property" "main" {
  name        = "test"
  product_id  = "prd_${var.product}"
  contract_id = "ctr_${var.contract}"
  group_id    = "grp_${var.group}"
  hostnames {
    cname_from             = var.hostname
    cname_to               = akamai_edge_hostname.main.edge_hostname
    cert_provisioning_type = "CPS_MANAGED"
  }
  rule_format = var.rule_format
  rules       = local.rules
}
```

changing rule_format from v2022-06-28 to v2022-10-28 fails 

rule tree update works with v2022-06-28)

### Expected Behavior
rule tree updated

### Actual Behavior
```
Error: updating rule tree: API error: 
│ {
│       "type": "https://problems.luna.akamaiapis.net/papi/v0/http/unsupported-media-type",
│       "title": "Unsupported Media Type",
│       "detail": "The system does not understand the media type from your `Accept`, `Content-Type`, or `Accept-Language` header.",
│       "instance": "https://akab*****.luna.akamaiapis.net/papi/v1/properties/prp_***/versions/7/rules?contractId=ctr_***\u0026groupId=grp_***",
│       "statusCode": 415
│ }
│ 
│   with module.stream-staging.module.akamai.akamai_property.main,
│   on ../terraform-akamai-cdn/main.tf line 43, in resource "akamai_property" "main":
│   43: resource "akamai_property" "main" {
│ 
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
- uses custom_overrides

### References
maybe related: https://github.com/akamai/terraform-provider-akamai/issues/376

**Comment by dstopka** [comment]
Hello @gordonkramer!
Thank you for reporting this issue. I see that you mention rule format `v2022-10-28`, which in fact does not exist. I suppose this is the reason for such error. Can I ask you to check if the same occurs with `v2022-10-18`? 

Regards,
Darek

**Comment by gordonkramer** [comment]
> Can I ask you to check if the same occurs with v2022-10-18?

tested with v2022-10-18 and succeeds. In that case only the error message is misleading that is reported by the API.

Thanks @dstopka
