### ISSUE TITLE
can't use SBD certificates with edgekey.net (ESSL) network

### ISSUE THREAD

**Issue by jjgrinwis** [akamai/terraform-provider-akamai#388]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
terraform -v   
Terraform v1.3.7
on darwin_arm64
+ provider registry.terraform.io/akamai/akamai v3.3.0
+ provider registry.terraform.io/hashicorp/local v2.3.0
+ provider registry.terraform.io/hashicorp/time v0.9.1

### Affected Resource(s)
akamai_edge_hostname

### Debug Output

Error: a certificate enrollment ID is required for Enhanced TLS edge hostnames with 'edgekey.net' suffix

### Expected Behavior
We should be able to also use SBD's on the enhanced TLS network (edgekey.net).

### Actual Behavior
apply will fail as we don't have any certificate enrollment-id. 

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. terraform apply

module.property.akamai_edge_hostname.aka_edge: Creating...

│ Error: a certificate enrollment ID is required for Enhanced TLS edge hostnames with 'edgekey.net' suffix
│ 
│   with module.property.akamai_edge_hostname.aka_edge,
│   on ../../modules/property/main.tf line 77, in resource "akamai_edge_hostname" "aka_edge":
│   77: resource "akamai_edge_hostname" "aka_edge" {
│

**Comment by jjgrinwis** [comment]
It looks like we don't need an EdgeHostname resource for an SBD certificate, so we just skipped creating an akamai_edge_hostname resource using a count: 
```
count = var.cert_provisioning_type == "DEFAULT" ? 0 : 1
```

**Comment by wzagrajcz** [comment]
Hello @jjgrinwis 
Thank You for opening the issue.
As the [documentation](https://registry.terraform.io/providers/akamai/akamai/latest/docs/resources/edge_hostname) states, the `Enhanced TLS edge` hostname requires by design to provide an enrollment ID to work correctly. So current behaviour is correct.

Based on Your second comment, can I assume that the issue is no longer valid and can be closed?

Best regards,
Wojciech

**Comment by jjgrinwis** [comment]
Indeed, ticket can be closed. Maybe update documentation that for SDB no EdgeHostname resource is required as Delivery resource will create it automatically.

Thanks
John

------- Original Message -------
