### ISSUE TITLE
Enhancement: Fast Purge API Support

### ISSUE THREAD

**Issue by hypnotisttom** [akamai/terraform-provider-akamai#390]
Enhancement Request: Could we add the Fast Purge API into the Provider? https://techdocs.akamai.com/purge-cache/reference/api

**Comment by lkowalsk-akamai-com** [comment]
Hi @hypnotisttom , can you please share your thougs on how this would work? Fast Purge does not follow usual declarative manner of Terraform. It is more like an action rather then object which state you could preserve. I'm interested to hear from you on the use cases and workflows envisioned.

**Comment by hypnotisttom** [comment]
Hi @lkowalsk-akamai-com,

Yeah, you are right.  The requirement came up for us to give clients the ability to purge cache, and the way it's typically done is with the GUI.

In thinking through it some more, it may make better sense for us to create a custom github action to perform the call to the fast purge API under a different workflow from the terraform.

What are your thoughts on that approach?

Thanks,

Tom

**Comment by lkowalsk-akamai-com** [comment]
@hypnotisttom , yes, I think separate, connected (triggered after/before depending on use case) workflow would make more sense. That would be our suggestion on how to join the two together.

**Comment by hypnotisttom** [comment]
In light of that, I'll close this out.  Thanks!
