### ISSUE TITLE
DXE-2402 MX Record Priority Mismatch. Target order must align with EdgeDNS Error

### ISSUE THREAD

**Issue by BAu0002** [akamai/terraform-provider-akamai#395]
We are trying to amend an existing mx record.
We are using akamai provider version 2.4.1

The terraform plan is showing 
```
target     = [ 
          - "0 stub.com", 
          + "5 stub2.com", 
          + "5 stub3.com", 
          + "10 stub.com", 
        ] 
```

And it is returning the following error message when running terraform apply:
   MX Record Priority Mismatch. Target order must align with EdgeDNS 

Any advice why this happening?

**Comment by kaush-** [comment]
Hi @BAu0002,

Thank you for reaching out to us. We will come back with you after investigating from functional side why this error is being hit here.

In the meantime, can you please share more info (tf config file and logs) that can help us get more clarity?

Regards,
Piyush

**Comment by kaush-** [comment]
Hi @BAu0002,

I spoke with the functional team and below is the excerpt from them:

> The documentation for the provider indicates that the MX record definitions can be specified in three forms. The provider attempts to reconcile the record definition in EdgeDNS (on backend) with the definition in the Terraform config. The error message is telling you that they don't reconcile. You will need to manually inspect both record definitions to do the reconciliation. Your can also do a clean import (in a temp area) from EdgeDNS and use that EXACT record definition in TF or update the EdgeDNS Record definition thru another means, e.g. Control Center.
> 
> Unfortunately, once the two sides get out of sync with MX records specifically, manual intervention is required to reconcile.

Let me know if you have any other issues, for now I will be closing this issue but feel free to reopen it or raise another one with us.

Regards,
Piyush

**Comment by tmccombs** [comment]
I'm running into this error. However, I don't know what is causing it, because AFAICT, my configuration is identical to what is in akamai, and I don't know what is meant by "manual intervention". What steps do I actually take to resolve this?

It would be really helpful if the error message could at least be more helpful and point to documentation on how to deal with this. A google search for the error message doesn't even reveal anything useful.

**Comment by tmccombs** [comment]
Actually, the error I get is a little different (and less helpful):

> Error: Recordset [gh-mail.lucidchart.com. MX]: Remote has diverged from TF Config. Manual intervention required.
