### ISSUE TITLE
DXE-2421 Docs - data.akamai_property.property

### ISSUE THREAD

**Issue by ajoslin103** [akamai/terraform-provider-akamai#398]
Please update the docs at https://registry.terraform.io/providers/akamai/akamai/latest/docs/data-sources/property

The claim that the output includes 2 values

Usage shows 4 outputs, property_ID is not included

**Comment by kaush-** [comment]
Hi @ajoslin103,

Thank you for reaching out to us. Can you please give me an example of what outputs you are receiving? This Data source seems up-to date with the documentation to me.
`name` and `version` are arguments (required and optional respectively) and `rules` is a computed attribute. Moreover you can access `property_id` as it's set as resource id in state.

Regards,
Piyush

**Comment by ajoslin103** [comment]
Thanks for answering! Being fairly new to TF I am not sure how to know what outputs are available from a data source beyond the docs (I couldn't figure it out from the source) by hacking away at it I found .id (as opposed to the documented property_ID) 

So attempting to use the documented `.property_ID` did not work, nor did `.property_id` - while `.id` did 

Also, the error message spoke about there being 4 outputs from that data source, and I don't know how to find out what they are

**Comment by Slonimskaia** [comment]
Hi @ajoslin103,

Could you provide example of your terraform configuration and output error which you are facing using `.id` for output? With the example, we will try to reproduce it from our side and will try our best in helping you to solve this issue.

Best regards,
Tatiana

**Comment by ajoslin103** [comment]
I do apologize for my poor explaining

I found, without the documentation’s help, .id which works just fine and I have not gone back to that code since.

The documentation states that the resource has two outputs, when in fact it has four

.id - which works for me - is not listed in the documentation

I thought I was pointing out a chance for you to improve your documentation

You may close this issue

Thank yo ufor your time and attention
Al;

**Comment by Slonimskaia** [comment]
@ajoslin103 thank you for pointing this out. We are going to improve documentation and it is going to be available in the upcoming release. I am closing this issue, please feel free to reopen it if needed
