### ISSUE TITLE
DXE-2444 CSR data source does not always return expected attributes

### ISSUE THREAD

**Issue by landrew57** [akamai/terraform-provider-akamai#402]
### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

```
Terraform v1.3.5
on darwin_arm64
+ provider registry.terraform.io/akamai/akamai v3.4.0
+ provider registry.terraform.io/hashicorp/local v2.3.0
```

### Affected Resource(s)
Please list the resources as a list, for example:
- data.akamai_cps_csr.csr

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
data "akamai_cps_csr" "this" {
  enrollment_id = <enrollment id with no pending changes and where most recent change in history did not generate a csr>
}

resource "local_file" "csr_rsa" {
  content  = data.akamai_cps_csr.this.csr_rsa
  filename = "./csr.pem"
}

terraform {
  required_providers {
    akamai = {
      source = "akamai/akamai"
      version = "3.4.0"
    }
  }
}

provider "akamai" {
  # Configuration options
}
```

### Debug Output

[Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.](https://gist.github.com/landrew57/b7f867708748650cbe08ff897e464595)

### Expected Behavior

It should be possible to make changes to an enrollment that do not generate a CSR without breaking future runs of terraform.  For example: changing the network configuration does generate a change to the enrollment and the certificate history of the most recent change will have no values for `multiStackedCertificates` or `primaryCertificates`

The enrollment that has surfaced this issue has the following response body from a call to `:/cps/v2/enrollments/<enrollment_id>/history/changes 'accept:application/vnd.akamai.cps.change-history.v5+json'`

```
{
    "changes": [
        {
            "action": "update-network-configuration",
            "actionDescription": "Update Network Configuration",
            "businessCaseId": null,
            "createdBy": "",
            "createdOn": "2022-11-28T09:55:29Z",
            "lastUpdated": "2022-11-28T10:02:12Z",
            "multiStackedCertificates": [],
            "primaryCertificate": null,
            "primaryCertificateOrderDetails": null,
            "ra": "third-party",
            "status": "completed"
        },
        {
            "action": "renew",
            "actionDescription": "Renew Certificate",
            "businessCaseId": null,
            "createdBy": "<auto-renewal>",
            "createdOn": "2022-11-17T15:31:38Z",
            "lastUpdated": null,
            "multiStackedCertificates": [],
            "primaryCertificate": null,
            "primaryCertificateOrderDetails": null,
            "ra": "third-party",
            "status": "cancelled"
        },
        {
            "action": "new-certificate",
            "actionDescription": "Create New Certificate",
            "businessCaseId": "",
            "createdBy": "",
            "createdOn": "2022-11-17T15:02:02Z",
            "lastUpdated": "2022-11-17T15:31:39Z",
            "multiStackedCertificates": [],
            "primaryCertificate": {
                "certificate": "-----BEGIN CERTIFICATE-----...\n-----END CERTIFICATE-----",
                "csr": "-----BEGIN CERTIFICATE REQUEST-----\...\n-----END CERTIFICATE REQUEST-----\n",
                "keyAlgorithm": "RSA",
                "trustChain": "-----BEGIN CERTIFICATE-----\n...\n-----END CERTIFICATE-----"
            },
            "primaryCertificateOrderDetails": null,
            "ra": "third-party",
            "status": "completed"
        }
    ]
}
``` 

https://github.com/akamai/terraform-provider-akamai/blob/7eb7f834037094f3809a526480287ec7ab6d3e01/pkg/providers/cps/data_akamai_cps_csr.go#L138-L146 

looks in the first item in the history response, and in this case no csr is found.

### Actual Behavior

If an enrollment does not have a pending change with a csr, and does not have a csr in the most recent change in history a `plan` will fail with 

```
╷
│ Error: Invalid Attribute Combination
│
│   with local_file.csr_rsa,
│   on csr.tf line 5, in resource "local_file" "csr_rsa":
│    5: resource "local_file" "csr_rsa" {
│
│ No attribute specified when one (and only one) of [content,sensitive_content,source] is required
╵
╷
│ Error: Invalid Attribute Combination
│
│   with local_file.csr_rsa,
│   on csr.tf line 5, in resource "local_file" "csr_rsa":
│    5: resource "local_file" "csr_rsa" {
│
│ No attribute specified when one (and only one) of [content,content_base64,source] is required
╵
╷
│ Error: Invalid Attribute Combination
│
│   with local_file.csr_rsa,
│   on csr.tf line 5, in resource "local_file" "csr_rsa":
│    5: resource "local_file" "csr_rsa" {
│
│ No attribute specified when one (and only one) of [content,sensitive_content,content_base64] is required
╵
╷
│ Error: Invalid Attribute Combination
│
│   with local_file.csr_rsa,
│   on csr.tf line 6, in resource "local_file" "csr_rsa":
│    6:   content  = data.akamai_cps_csr.this.csr_rsa
│
│ No attribute specified when one (and only one) of [sensitive_content,content_base64,source] is required
╵
```

### Steps to Reproduce
Given an enrollment in the state described above:l:
1. `terraform init`
2. `terraform plan`

### Important Factoids

I'm happy to share the enrollment id with whoever from Akamai investigates this issue if required.

**Comment by Slonimskaia** [comment]
Hi @landrew57,

Thank for bringing this issue to our attention. We will try reproducing it from our side and will come back to you soon.

Best regards,
Tatiana Slonimskaia

**Comment by mimazaka** [comment]
Hello @landrew57,

I have been investigating this issue for long time, but unfortunately I did not managed to reproduce it. Let me describe steps which I followed during this proces:

1. Creation of third party enrollment with usage of  `resource.akamai_cps_third_party_enrollment `
2. Generated enrollment id has been used to retrieve certificate with usage of `data.akamai_cps_csr`
3. Certificate has been signed using mkcert tool
4. Signed certificate was uploaded using `resource.akamai_cps_upload_certificate`
5. Second use of `resource.akamai_cps_third_party_enrollment` with updated network configuration ( change of `disallowed_tls_versions`)

Please not that for all actions terraform has been used ( except using of mkcert tool). I have received following changes history for API call which you have used, after performing all above steps:
```
"changes": [
        {
            "action": "renew",
            "actionDescription": "Renew Certificate",
            "status": "incomplete",
            "lastUpdated": "2023-03-16T08:14:35Z",
            "createdBy": "dummyUser",
            "createdOn": "2023-03-16T08:14:31Z",
            "ra": "third-party",
            "primaryCertificate": null,
            "multiStackedCertificates": [],
            "primaryCertificateOrderDetails": null,
            "businessCaseId": null
        },
        {
            "action": "renew",
            "actionDescription": "Renew Certificate",
            "status": "cancelled",
            "lastUpdated": null,
            "createdBy": "<auto-renewal>",
            "createdOn": "2023-03-15T17:20:15Z",
            "ra": "third-party",
            "primaryCertificate": null,
            "multiStackedCertificates": [],
            "primaryCertificateOrderDetails": null,
            "businessCaseId": null
        },
        {
            "action": "new-certificate",
            "actionDescription": "Create New Certificate",
            "status": "completed",
            "lastUpdated": "2023-03-15T17:20:15Z",
            "createdBy": "dummyUser",
            "createdOn": "2023-03-15T13:42:31Z",
            "ra": "third-party",
            "primaryCertificate": {
                "certificate": "-----BEGIN CERTIFICATE-----<dummy>-----END CERTIFICATE-----",
                "trustChain": null,
                "csr": "-----BEGIN CERTIFICATE REQUEST-----<dummy>-----END CERTIFICATE REQUEST-----\n",
                "keyAlgorithm": "RSA"
            },
            "multiStackedCertificates": [],
            "primaryCertificateOrderDetails": null,
            "businessCaseId": null
        }
    ]
}
```
Please note that at this stage first item is incomplete renewal. When we check status of this change with `/cps/v2/enrollments/:enrollmentId/changes/:changeid 'accept:application/vnd.akamai.cps.change.v2+json'` endpoint we receive:
```
{
    "statusInfo": {
        "status": "wait-upload-third-party",
        "state": "awaiting-input",
        "description": "Waiting for you to upload and submit your third party certificate and trust chain.",
        "deploymentSchedule": {
            "notBefore": null,
            "notAfter": null
        },
        "error": null
    },
    "allowedInput": [
        {
            "type": "third-party-certificate",
            "requiredToProceed": true,
            "info": "/cps/v2/enrollments/<enrollmentid>/changes/<changeid>/input/info/third-party-csr",
            "update": "/cps/v2/enrollments/<enrollmentid>/changes/<changeid>/input/update/third-party-cert-and-trust-chain"
        }
    ]
}
```
This change require to upload certificate again, what will lead new certificate change on first item with signed certificate. That not allow to reproduce issue you have reported.

**Please take a look on steps which I have described and advise if you see any difference?
Have you perform update of network configuration using Terraform or this data has been updated in some UI? 
Which fields have you updated in network configuration?** 

I have seen [pull request #403](https://github.com/akamai/terraform-provider-akamai/pull/403) and your solution also looks ok for me, but as @wzagrajcz mentioned there, firstly we have to reproduce issue.

Best regards,
Michał

**Comment by landrew57** [comment]
Hey @mimazaka thanks for looking into this!

To confirm, do you try to do anything with the `data.akamai_cps_csr.this.csr_rsa` or  `data.akamai_cps_csr.this.csr_ecdsa` the second time?  

In my experience the issue is that the CSR attributes are not set, which breaks any dependent resources.  The Akamai resources return without issue, but the returned attributes of the `data.akamai_cps_csr` resource will change depending on whether the pending change or most recent change contains a CSR. 

 In our configuration we access that attribute in the `local_file` resource:

```
resource "local_file" "csr_rsa" {
  content  = data.akamai_cps_csr.this.csr_rsa
  filename = "./csr.pem"
}
```

We could implement some logic to not always try to receive that information, but I don't think that should be required.  My expectation would be that you can always access that attribute and it will contain the most recent CSR.

**Comment by mimazaka** [comment]
Hi @landrew57 

I haven't perform any changes to `data.akamai_cps_csr.this.csr_rsa`.

Can you highlight differences i our steps to recreate issue? Have you updated network configuration using Terraform?

Can you also specify what do you exactly mean by "The Akamai resources return without issue,..." ? As far as I remember, Terraform cps resources does not return csr, but just used it as attribute to perform specific action. Still format of them differ from this used in discussed datasource. 

Regards,
Michał

**Comment by landrew57** [comment]
> I haven't perform any changes to data.akamai_cps_csr.this.csr_rsa.

I was not asking about changes to that attribute, let me try to clarify.

Do you do anything with information returned by the `data` resource?  The `data` resource itself does not see any issues regardless of change history.  `terraform` will execute fine.   The issue is if we try to use the output from that `data` resource in another resource.  Does the configuration you are testing with contain this block:

```HCL
resource "local_file" "csr_rsa" {
  content  = data.akamai_cps_csr.this.csr_rsa
  filename = "./csr.pem"
}
```

as that is the bit that is failing for us.

The problem is that there are inconsistent attributes set.  The `csr_rsa` attribute (or `csr_ecdsa`) is not set if the most recent change in the history does not contain one.  It makes it difficult to manage enrollments if that attribute is set sometimes and not others.  

> Have you updated network configuration using Terraform?

It wasn't done using Terraform.  I could easily be wrong, but I don't think that is related

**Comment by landrew57** [comment]
Hi 👋 @mimazaka do you need any more information from me?  Or would like me to investigate something else on my side.

As an extra piece of information, we did try to get round the inconsistent attributes by using a `try` block eg.

```
resource "local_file" "csr_rsa" {
  content  = try(data.akamai_cps_csr.this.csr_rsa, "")
  filename = "./csr.pem"
}
```

but the validation implemented in the `local_file` resource doesn't seem to handle that `try` as expected.  We got errors like

>"content": one of `content_base64,sensitive_content,source` must be specified

It seems like the validation happens before the `try` has been evaluated.  That is a different issue that we may investigate separately, but means the most clear way to mitigate this issue isn't an option for us at the moment.

**Comment by landrew57** [comment]
We have found a solution that prevents the errors for now, using the `one` function - [docs](https://developer.hashicorp.com/terraform/language/functions/one) to evaluate if that attribute is returned.

```
 resource "local_file" "csr_rsa" {
   content  = one([data.akamai_cps_csr.this.csr_rsa]) != null ? data.akamai_cps_csr.this.csr_rsa : "Placeholder for content if csr is not returned"
   filename = "./csr.pem"
 }
```

**Comment by mimazaka** [comment]
Hello @landrew57,

Sorry for such late response.

It's good to hear that You were able to omit the issue.  We have seen your pr [#403](https://github.com/akamai/terraform-provider-akamai/pull/403) which fix problem with `csr_rsa / csr_ecdsa ` not set if the most recent change in the history. In order to fix the issue (probably by merging Your PR) we first need to reproduce the issue on our side. 

You created enrollment, get the certificate, uploaded the certificate and it was activated. Based on Your response from original post there was some action related to:

```
{
    "action": "update-network-configuration",
    "actionDescription": "Update Network Configuration",
    "businessCaseId": null,
    "createdBy": "",
    "createdOn": "2022-11-28T09:55:29Z",
    "lastUpdated": "2022-11-28T10:02:12Z",
    "multiStackedCertificates": [],
    "primaryCertificate": null,
    "primaryCertificateOrderDetails": null,
    "ra": "third-party",
    "status": "completed"
}
```


> Have you updated network configuration using Terraform?
> 
> It wasn't done using Terraform. I could easily be wrong, but I don't think that is related
> 

This part is important for us. **Can You tell us (as precisely as You remember and can share) what field was changed, where, from which value to which.**

As we will be able to reproduce last action from changes history, and reproduce issue. We can move forward with pr in #403 

Regards,
Michal

**Comment by landrew57** [comment]
Hi @mimazaka my turn for a slow response, apologies!

I'm afraid that network change was done by a member of Akamai professional support and I can't see exactly what changed.  I will reach out to them to see if they can remember.

I have tested the process you described here

> - Creation of third party enrollment with usage of resource.akamai_cps_third_party_enrollment 
> -  Generated enrollment id has been used to retrieve certificate with usage of data.akamai_cps_csr
> -  Certificate has been signed using mkcert tool
> -  Signed certificate was uploaded using resource.akamai_cps_upload_certificate
> -  Second use of resource.akamai_cps_third_party_enrollment with updated network configuration ( change of disallowed_tls_versions)

and that does reproduce the issue for me.  The `data.akamai_cps_csr.this` does not contain any `csr` attributes:

```
terraform state show data.akamai_cps_csr.this
# data.akamai_cps_csr.this:
data "akamai_cps_csr" "this" {
    enrollment_id = 123456
    id            = "123456:0"
}
```

In your testing is that the state of the csr data source?  Or does yours contain a `csr`?  If yours contains a `csr` I think it must be to do with there being a pending change in your history.  The history for the certificate that I have created to test with can be retrieved from `:/cps/v2/enrollments/175565/history/changes accept:application/vnd.akamai.cps.change-history.v5+json`.  Can you try with that enrollment id?

```
"changes": [
        {
            "action": "update-network-configuration",
            "actionDescription": "Update Network Configuration",
            "businessCaseId": null,
            "createdBy": "z5p7wm5komdemghb",
            "createdOn": "2023-03-29T11:06:54Z",
            "lastUpdated": "2023-03-29T11:14:03Z",
            "multiStackedCertificates": [],
            "primaryCertificate": null,
            "primaryCertificateOrderDetails": null,
            "ra": "third-party",
            "status": "completed"
        },
        {
            "action": "renew",
            "actionDescription": "Renew Certificate",
            "businessCaseId": null,
            "createdBy": "<auto-renewal>",
            "createdOn": "2023-03-29T09:29:53Z",
            "lastUpdated": null,
            "multiStackedCertificates": [],
            "primaryCertificate": null,
            "primaryCertificateOrderDetails": null,
            "ra": "third-party",
            "status": "cancelled"
        },
        {
            "action": "new-certificate",
            "actionDescription": "Create New Certificate",
            "businessCaseId": null,
            "createdBy": "z5p7wm5komdemghb",
            "createdOn": "2023-03-29T09:19:33Z",
            "lastUpdated": "2023-03-29T09:29:53Z",
            "multiStackedCertificates": [],
            "primaryCertificate": {
                "certificate": "-----BEGIN CERTIFICATE-----dummy-----END CERTIFICATE-----",
                "csr": "-----BEGIN CERTIFICATE REQUEST-----dummy-----END CERTIFICATE REQUEST-----\n",
                "keyAlgorithm": "RSA",
                "trustChain": null
            },
            "primaryCertificateOrderDetails": null,
            "ra": "third-party",
            "status": "completed"
        },
        {
            "action": "new-certificate",
            "actionDescription": "Create New Certificate",
            "businessCaseId": "5004R00001yLqbIQAS",
            "createdBy": "z5p7wm5komdemghb",
            "createdOn": "2023-03-29T09:10:41Z",
            "lastUpdated": "2023-03-29T09:19:31Z",
            "multiStackedCertificates": [],
            "primaryCertificate": null,
            "primaryCertificateOrderDetails": null,
            "ra": "third-party",
            "status": "cancelled"
        }
    ]
```

I cannot see if you have confirmed or not in the thread whether you have tried to reproduce the issue with the `local_file` resource.  The error output comes from the validation of the `local_file` resource arguments.  That error message is not directly related to the Akamai terraform provider, but is caused by the unpredictable behaviour of the `cps_csr` data source.  If you are not trying to access the fields of that data source, you will not see any issues.  In my opinion, if the data source fails to find any `csr` it should fail, rather than returning `tostring(null)`.

**Comment by dawiddzhafarov** [comment]
Hello @landrew57!

I have managed to reproduce the issue You're experiencing and I can confirm that is it a valid one. The pull request You have opened seems to fix the issue - we will review it and if everything works as expected - merge it. Feel free to reach out if You have any further questions.

With regards,
Dawid

**Comment by dawiddzhafarov** [comment]
Hi @landrew57,

We have merged the PR with Your changes and closed this issue. Do not hesitate to open a new one if needed. Thank You for your contribution.

With regards,
Dawid

**Comment by landrew57** [comment]
Thanks @dawiddzhafarov!
