### ISSUE TITLE
DXE-2518 GTM liveness_test test_object is required even when the test_object_protocol doesn't require one

### ISSUE THREAD

**Issue by hypnotisttom** [akamai/terraform-provider-akamai#408]
### Affected Resource(s)
- akamai_gtm_property

### Expected Behavior
The liveness test's test object should only be required on the protocols that require it and should be optional for the protocols that don't require it. 

### Actual Behavior
The liveness test's test object is always being a required argument even for several test object protocols that don't need a test object. 

We can work around this issue by passing an empty string for the test object, although in theory that shouldn’t be needed for what is in practice an optional field.

**Comment by dawiddzhafarov** [comment]
Hi @hypnotisttom,

Thank You for opening the issue. We will investigate it and come back with with an answer.

With regards,
Dawid

**Comment by lkowalsk-akamai-com** [comment]
This issue was fixed in 5.0 release
