### ISSUE TITLE
akamai_property_activation: Documentation for version property invalid 

### ISSUE THREAD

**Issue by MarkDordoy** [akamai/terraform-provider-akamai#41]
Hi 

The docs here https://www.terraform.io/docs/providers/akamai/r/property_activation.html state i can set version to "latest", however the code says it only supports an int. How do i make sure it always uses latest.  I was using `akamai_property.example.version` which seems to work, but i did something get issues if there was any unpublished versions created in the portal. 

### Terraform Version
terraform v0.12.3
akamai 0.1.2

### Affected Resource(s)
Please list the resources as a list, for example:
- akamai_property_activation

**Comment by dshafik** [comment]
This has been fixed, the new documentation will build shortly. In short: to activate `latest` do not specify a version at all.

Thanks for reporting this!
