### ISSUE TITLE
DXE-2629 Akamai EdgeGrid configuration was not specified

### ISSUE THREAD

**Issue by rolmo** [akamai/terraform-provider-akamai#411]
### Terraform Version

Terraform v1.4.6
Akamai-Provider-Version: 3.6.0

### Affected Resource(s)

provider "akamai" (".edgerc")

### Terraform Configuration Files
```hcl
provider "akamai" {
  edgerc         = "~/.edgerc"
  config_section = "default"
}
```

### Output

```
Error: Akamai EdgeGrid configuration was not specified. Specify the configuration using system environment variables or the location and file name containing the edgerc configuration. Default location the provider checks for is the current user’s home directory. Default configuration file name the provider checks for is .edgerc.
```

### Expected Behavior

More specific error message:
* Is the file ~/.edgerc missing"?
* Is the section "default" not found?
* Is a attribute of this section wrong?
* ...

### Actual Behavior

Regardless of the problem (missing "~/.edgerc", missing section, ...) I get the same error message every time. This makes it difficult to see what you are failing at.

In my case I create the ".edgerc" via environment variables on a github action runner and I get stuck because everything looks correct but Terraform always gives the above error message.

### Steps to Reproduce

Remove the ".edgerc", remove the section, ... you get each time the same error message

**Comment by majakubiec** [comment]
Hi @rolmo,
Thanks for raising this issue.
It looks like a valid request that we should take care of fixing.

**Comment by lkowalsk-akamai-com** [comment]
Hi @rolmo, error messages were updated with recent release.
