### ISSUE TITLE
DXE-2695 Request for data source for generating an Akamai Authorization header

### ISSUE THREAD

**Issue by hypnotisttom** [akamai/terraform-provider-akamai#417]
In the event of missing data sources for Akamai resources, it would be nice if we could have a data source in the Provider for generating the Authorization header so that we could use that in https://registry.terraform.io/providers/hashicorp/http/latest/docs/data-sources/http to make a GET request to the APIs for where datasources are missing.

This would allow us to still have the automation be dynamic and be relatively streamlined, rather than crafting intricate workarounds for missing datasources.

If you are aware of a way to generate the Akamai Authorization header in Terraform today, please let me know.

**Comment by wzagrajcz** [comment]
Hello @hypnotisttom 
Thanks for opening the feature request. That is very interesting idea. As per now, there is no way to get `Authorization` phrase directly on Terraform level. We will give the concept a try and go back to You.

Best regards,
Wojciech

**Comment by lkowalsk-akamai-com** [comment]
Hi, we are not planning to add such generic solution. We are actively working on Akamai Terraform Provider and adding new features monthly. If you have any specific request for a product/funtionality that you would like to see added, please create new issue with proper description. Thank you.

**Comment by hypnotisttom** [comment]
Hi @lkowalsk-akamai-com 

This was requested coming from discussions with Akamai.

While I realize you are making progress on covering the catalog, currently, not every resource has a datasource, and not every dependent resource has one.

The current need for this ask is for NetStorage ( https://github.com/akamai/terraform-provider-akamai/issues/416 ).  Right now we are having to run the API GETer manually, copy the JSON output, update a file that is then read by the TF config.  Akamai wasn't going to add NetStorage support to the provider in the near future because of the move to Object Storage; however, this doesn't remove our need for existing properties that are relying on NetStorage.

So, we attempted to call the NetStorage API directly via the http provider; however, we have no way to auth it from within Terraform without some clunky rather unsupported external calls midflight.

Hence, the auth header was proposed.

The ability to generate an EdgeGrid auth header exists in CLI, various languages, and even via a native integration in Postman.

Yet, there is no way to generate the header from within Terraform, even though the provider generates one for its own use.

Having the ability to generate the header natively in Terraform would allow us to call the Akamai API via the http provider for cases that the provider does not support or will not support.  This solution allows us to not be impeded by the provider roadmap.

I hope this background is helpful, and I hope this will be reconsidered.

Please let me know if you need any additional information.

Thanks,

Tom
