### ISSUE TITLE
DXE-2716 Provider cannot read contract or group data sources and crashes on Windows.

### ISSUE THREAD

**Issue by bdonnie** [akamai/terraform-provider-akamai#418]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
1.4.6

### Affected Resource(s)

group and contract data sources

### Terraform Configuration Files
```hcl
any group or contract data source. All give the same error and crash the provider.
```
Please reference support case AKAM-CASE #F-CS-7146473

### Debug Output

Attached to support case

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
Read the data source 

### Actual Behavior
Provider crashes

### Steps to Reproduce
1. Create tf file with contract or group data source.
2. terraform init
3. terraform plan

### Important Factoids
Only happening on Windows. Have tried on multiple provider versions. If possible, please respond to email on support case. 

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- GH-1234

**Comment by mgwoj** [comment]
Akamai support resolved this issue in May.
