### ISSUE TITLE
DXE-2718 Issue with cname_from validation introduced in version 4.0.0

### ISSUE THREAD

**Issue by nedko-nedkov** [akamai/terraform-provider-akamai#422]
### Affected Resource(s)
Please list the resources as a list, for example:
- akamai_property

### Debug Output
"do not exist under this account, you need to remove or replace invalid hostnames entries in your configuration to proceed with property version update"

https://github.com/akamai/terraform-provider-akamai/blob/921339f4836c8b9fe0f939ca77686dfdc28427f5/pkg/providers/property/resource_akamai_property.go#L1349

### Expected Behavior
Any hostname supported by Akamai should be fine to be created.

### Actual Behavior
The terraform apply fails with the message above. Says that the hostnames do not pass the validation, which seems to be to match the list of edge hostnames.

### Steps to Reproduce
Try to create a hostname with cname_from value which does not contain any edge hostname in the account.

### Our case:
I guess there is a good reason to implement this check, but we cannot use the new version of the provider anymore, because of this validation. We have infrastructure in Akamai and use terraform to manage it. In our case we have hundreds of hostnames which are served by the same edge location (like site1.example1.com, site2.example2.com, something.com pointing to the same edge named like.. somename.edgekey.net). This is supported by Akamai and is fine to be like this. Also if you want to add hostname to the property/edge, you can do it in the web console. After implementing this validation in version 4.0.0 for this provider we are unable to manage those hostnames with terraform. Don't know what is the case, but if Akamai supports it, should there be an external validation/limit for the names? Also - every cname_from is different and we have hundreds , but all of them have the same cname_to value, which is the edge hostname. Are you sure you don't want to validate the cname_to parameter?

**Comment by Slonimskaia** [comment]
Hi @nedko-nedkov,

Thank you for reporting this issue. We need some time for investigations and will come back to you soon. For now, please use previously released Akamai terraform plugin versions. The previous released version is 3.6.0.

Best regards,
Tatiana Slonimskaia

**Comment by ericrichtert** [comment]
We have something similar: We removed some domains from the DNS. After removing the DNS zones, we found some reference in the cname_from values. We removed them from the code, but we were unable to apply. After removing the entries in the WebUI, we could run the apply with success.

**Comment by lkowalsk-akamai-com** [comment]
This issue was fixed in 5.0 release
