### ISSUE TITLE
DXE-2807 Document provider option request_limit

### ISSUE THREAD

**Issue by stigok** [akamai/terraform-provider-akamai#423]
We got some information about a provider flag for controlling rate limits towards the Akamai API's through our dedicated Akamai support team. I feel that this option should be documented in the provider documentation. I am unable to find any other references to this option apart from in the provider code itself.

The option was introduced in https://github.com/akamai/terraform-provider-akamai/commit/25090abc85d97d8aba60b5b9660b2d0d229929ad

The option can be toggled by setting the provider option `request_limit`, or by setting the environment variable `AKAMAI_REQUEST_LIMIT`, to a number higher than 0.

**Comment by lkowalsk-akamai-com** [comment]
Hi @stigok we will add this in comming weeks to the official Akamai Terraform Documentation on Techdocs.

**Comment by lkowalsk-akamai-com** [comment]
Details of this capability ar now available here: https://techdocs.akamai.com/terraform/docs/request-limits
