### ISSUE TITLE
Is there a plan to add Client List 

### ISSUE THREAD

**Issue by BAu0002** [akamai/terraform-provider-akamai#424]
Any information on when/if new "Client List" terraform resource be available?

**Comment by lkowalsk-akamai-com** [comment]
Hi @BAu0002 , sorry for late reply. Yes, the Client List suprovider is currently under development. I cannot share any specific date yet.

**Comment by lkowalsk-akamai-com** [comment]
Hi @BAu0002 , this functionality was included in the our recent release. Please check it out :)
