### ISSUE TITLE
DXE-2727 Changes to required elements in cache id for graphql does not result in any planned changes

### ISSUE THREAD

**Issue by Pelto** [akamai/terraform-provider-akamai#425]
### Affected Resource(s)
- `akamai_property`

### What
We have an Akamai property where we have enabled Graphql caching. When we updated our terraform files with a new rule the plan did not yield any changes. 

We did a change in the `GraphQL Caching` by adding a new header in the `cacheId` behavior. 

We generate the following rule in our terraform template through our cdktf project:

```json
{
  "name": "GraphQL Caching",
  "children": [],
  "behaviors": [
    {
      "name": "graphqlCaching",
      "options": {
        "advanced": "",
        "cacheResponsesWithErrors": false,
        "enabled": true,
        "operationsJsonBodyParameterName": "query",
        "operationsUrlQueryParameterName": "query",
        "postRequestProcessingErrorHandling": "NO_STORE"
      }
    },
    {
      "name": "cacheId",
      "options": {
        "elements": [
          "client-name",
          "client-version",
          "platform",
          "Platform",
          "origin"
        ],
        "includeValue": true,
        "optional": true,
        "rule": "INCLUDE_HEADERS"
      }
    },
    {
      "name": "cacheId",
      "options": {
        "rule": "INCLUDE_ALL_QUERY_PARAMS"
      }
    },
    {
      "name": "caching",
      "options": {
        "behavior": "CACHE_CONTROL_AND_EXPIRES",
        "cacheControlDirectives": "",
        "defaultTtl": "0s",
        "enhancedRfcSupport": false,
        "honorMustRevalidate": true,
        "honorPrivate": true,
        "mustRevalidate": true
      }
    },
    {
      "name": "allowPost",
      "options": {
        "allowWithoutContentLength": false,
        "enabled": true
      }
    }
  ],
  "criteria": [
    {
      "name": "path",
      "options": {
        "matchCaseSensitive": false,
        "matchOperator": "MATCHES_ONE_OF",
        "normalize": false,
        "values": [
          "/graphql",
          "/"
        ]
      }
    }
  ],
  "criteriaMustSatisfy": "all",
  "comments": ""
}
```

However once created any updates to the cache headers (`behaviors[1].options.elements`) will not result in an update while running `terraform plan`.

**Comment by dawiddzhafarov** [comment]
Hi @Pelto,

Thank You for opening the issue. We will investigate it and come back when we know more about it.

With regards,
Dawid

**Comment by dstopka** [comment]
Hi @Pelto,

I'm investigating the issue you described. May I ask you if the problem still occurs and if it does to provide more details? It'd be great to know terraform version, terraform-provider-akamai version as well as how are you handling the rules - do you use them directly in `akamai_property` resource or are you using any of the helper resources like `akamai_property_rules_template` or `akamai_property_rules_builder`.

Thanks,
Darek

**Comment by lkowalsk-akamai-com** [comment]
Closing due to lack of response and no possibility to reproduce the issue.
