### ISSUE TITLE
PRTLDEVOPS-60248 Property activation fails intermittently

### ISSUE THREAD

**Issue by navjotkaur10** [akamai/terraform-provider-akamai#427]
Hi there,

### Terraform Version
```
terraform -v
Terraform v1.2.9
on linux_amd64
+ provider registry.terraform.io/akamai/akamai v4.1.0
```
### Affected Resource(s)
Please list the resources as a list, for example:
- akamai_property_activation

When activating properties, we are encountering following error intermittently. Has this been seen before? 

```
│ Error: create activation failed: creating activation: API error: 
│ {
│ 	"type": "https://problems.luna.akamaiapis.net/-/resource-impl/forward-origin-error",
│ 	"title": "Server Error",
│ 	"detail": "",
│ 	"instance": "https://***/papi/v1/properties/prp_878352/activations",
│ 	"statusCode": 500
│ }
```

**Comment by mgwoj** [comment]
It looks it was temporary issue. Please retry the activation and let us know if the problem is resolved.

**Comment by navjotkaur10** [comment]
@mgwoj Retry usually activates successfully. However, we see this error couple of times a week and this causes us further issues when activation fails for a production property.

**Comment by mgwoj** [comment]
I've reported this issue to the Property API team

**Comment by lkowalsk-akamai-com** [comment]
ha @navjotkaur10   Is this issue still occuring to you?

**Comment by navjotkaur10** [comment]
Hi @lkowalsk-akamai-com yeah, we are still seeing this issue

**Comment by jgdev522** [comment]
I also run into the same 500 error multiple times a week. If you re run the deployment it is fine, however it breaks the deployment cycle causing delays. I have also noticed that most of my properties are activating. Today I noticed that 2 of my properties started deploying after most of the other ones were almost complete. Is there a limit to simultaneous activation's?

**Comment by jgdev522** [comment]
This still continues to happen, any update/progress on this?

Failed with exit code: 1
Error
Error: create activation failed: creating activation: API error: 
Error
{
Error
	"type": "[https://problems.luna.akamaiapis.net/-/resource-impl/forward-origin-error"](https://problems.luna.akamaiapis.net/-/resource-impl/forward-origin-error%22),
Error
	"title": "Server Error",
Error
	"detail": "",
Error
	"instance": "[https://akab-pbvn2wl22bp4evqs-ln5inpx2i6bv6dpq.luna.akamaiapis.net/papi/v1/properties/prp_978818/activations"](https://akab-pbvn2wl22bp4evqs-ln5inpx2i6bv6dpq.luna.akamaiapis.net/papi/v1/properties/prp_978818/activations%22),
Error
	"statusCode": 500
Error
}
Error
  with module.property_activation["mobile-sign"].akamai_property_activation.this,
Error
  on modules/property-activation/activate.tf line 1, in resource "akamai_property_activation" "this":
Error
   1: resource "akamai_property_activation" "this" {

**Comment by lkowalsk-akamai-com** [comment]
Thank you for letting us know. The problem lies in the underlying API and the investigation for how to fix it is ongoing. Unfortunately, this is a complex issue that is not easily resolvable. I cannot provide any ETU at this point.

**Comment by lkowalsk-akamai-com** [comment]
In 5.5.0 release we've improved error handling and added retries in akamai_property_activation resource. This should prevent intermittent API errors from failing the workflow.
