### ISSUE TITLE
How to import multiple `akamai_edge_hostname` using terraform import command-line.

### ISSUE THREAD

**Issue by mjx20045912** [akamai/terraform-provider-akamai#431]
Hi there,

How can we import multiple `akamai_edge_hostname` using terraform import command like following: 

$ terraform import akamai_edge_hostname.example ehn_123,ctr_1-AB123,grp_123

I have 3 akamai_edge_hostname like ehn_123, ehn_124, ehn_125.  

### Terraform Version
Terraform v1.5.0
on darwin_amd64.

**Comment by Slonimskaia** [comment]
Hi @mjx20045912,

`terraform import` is a building block to import only a single resource instance at a time. You can create some script to automate import for multiple resources. Something similar as:

import.sh
```
terraform init
terraform import akamai_edge_hostname.ehn_123 ehn_123,ctr_1-AB123,grp_123
terraform import akamai_edge_hostname.ehn_124 ehn_124,ctr_1-AB123,grp_123
terraform import akamai_edge_hostname.ehn_125 ehn_125,ctr_1-AB123,grp_123
```

Best regards,
Tatiana
