### ISSUE TITLE
Author is set to 'rubbish' when applying via terraform 

### ISSUE THREAD

**Issue by sebagomez** [akamai/terraform-provider-akamai#433]
### Terraform Version
1.4.6

### Affected Resource(s)
akamai_property_activation

### Terraform Configuration Files
```hcl
resource "akamai_property_activation" "my_property_activation" {
  property_id = akamai_property.my_property.id
  contact     = var.activation_contacts
  version     = akamai_property.my_property.latest_version
  network     = upper(var.akamai_environment)
  note        = var.activation_message
}
```

### Expected Behavior
I would like to have the author as part of the activation, or, at least having something like "via Terraform" instead of those characters.

### Actual Behavior
![image](https://github.com/akamai/terraform-provider-akamai/assets/1637983/3999a23b-63a8-4e04-9f90-79baf3e305ab)

### Steps to Reproduce
Just create a property activation and `terraform apply` it

**Comment by Slonimskaia** [comment]
Hi @sebagomez,

This is an open API credential ID and any API call would show you the ID. It shows username only on operations made from the UI, as you are logged user. If you go to the users list and filter by this ID, it will find the correct data.

Best regards,
Tatiana Slonimskaia

**Comment by sebagomez** [comment]
Hello, thanks for getting back to me. I can see now that it's not rubish, but I don't think it should be the right content. 
It would be better to see the name of the credentials instead of the ID, so in that case I can name the credentials something meaningful.
