### ISSUE TITLE
DXE-2812 akamai_cloudlets_application_load_balancer does not create new version if latest version is only active on staging or has been deactivated

### ISSUE THREAD

**Issue by aci-payon-ops** [akamai/terraform-provider-akamai#434]
Hi!

I found a problem where the akamai_cloudlets_application_load_balancer resource attempts to update an immutable version.
This happens when the latest version of the balancer is only active on staging or has been deactivated on production or  staging.

### Terraform Version
```
Terraform v1.5.1
on linux_amd64
+ provider registry.terraform.io/akamai/akamai v4.1.0
```
### Affected Resource(s)
Please list the resources as a list, for example:
- `akamai_cloudlets_application_load_balancer`

### Terraform Configuration Files

I can't provide my configuration here, but it can be reproduced with any sample load balancer configuration.
The one you use in tests will suffice!

### Expected Behavior
As the version is immutable (is active on staging / has been active on production or staging at some point), the provider should create a new version with the updated configuration.

### Actual Behavior
The provider attempts to modify an immutable load balancer configuration.

Example error:
```
│ Error: update origin version: API error: 
│ {
│       "type": "/cloudlets/error-types/illegal-argument",
│       "title": "Bad Argument or Value",
│       "detail": "sample_balancer (v2) can not be updated (immutable)",
│       "instance": "ddf264946a7113b0",
│       "statusCode": 400
│ }
│ 
╵
```

### Steps to Reproduce

1. Create an application load balancer resource.
2. Activate the  resource on production (v1).
3. Make a change, provider will create v2.
4. Activate v2 on staging only.
5. Make a change, provider will error out because it tries to update immutable v2.

Alternatively:
1. Create an application load balancer resource.
2. Activate the  resource on production (v1).
3. Make a change, provider will create v2.
4. Activate v2 on production
5. Activate v1 on production
6. Make a change, provider will error out because it tries to update immutable v2.

### Current Workaround

The only workaround I am currently aware of is:
1. Manually create a new version of the balancer in the control center.
2. Remove the resource from the state using `terraform state rm <resource>`
3. Import the resource using `terraform import`
4. Make a change, the provider will now update the newly created version.

This may also be something the provider could do better - it does not seem to see new versions created outside of terraform. But I would consider this much much lower priority, if we want this at all.

**Comment by Slonimskaia** [comment]
Hi @aci-payon-ops,

Thank you for reporting this issue. We will investigate this and get back to you soon

Best regards,
Tatiana Slonimskaia

**Comment by Slonimskaia** [comment]
Hi @aci-payon-ops,

I was not able to reproduce this issue. Steps which I replicated:
Terraform v1.5.3
akamai terraform provider v5.0.1
1. Created an application load balancer resource
2. Activated the resource on production (v1)
3. Made a change, provider created v2
4. Activated v2 on staging only
5. Made a change in resource, as a result provider didn't error out

Could you try to reproduce this issue again and in case it still exists from your side, please add terraform configuration (it can be dummy) which you are using and also add information what you are changing to create a new versions. This way we will continue our investigations

Best regards,
Tatiana Slonimskaia

**Comment by aci-payon-ops** [comment]
Hi @Slonimskaia 

I also cannot reproduce this behavior anymore on the latest Terraform version with the latest provider.
I will close this issue as it seems to be fixed.

Best regards!
