### ISSUE TITLE
Error: Title: Rate Limit Exceeded

### ISSUE THREAD

**Issue by helvpk** [akamai/terraform-provider-akamai#439]
Dear team,

as discussed with Mark Nadler we are now trying to create support tickets for the terraform provider as GitHub issues.

We are experiencing issues with the Teraform Provider and Akamai APIs.

When using bigger configuratinos, a RATE-LIMIT Exceeded message is displayed, e.g.

<img width="716" alt="image" src="https://github.com/akamai/terraform-provider-akamai/assets/138114062/3f1aa649-c495-4f87-85d6-85533b88cb01">

Could you please let us know about the timelime of proper fix on that?

**Comment by helvpk** [comment]
Additional information:

We are using a terraform cloud workspace and execute terraform remotely on terraform.io.

In order to make it run, we tried the following parallelism settings:

TF_CLI_ARGS_apply="-parallelism=3"
TF_CLI_ARGS_plan="-parallelism=3"
TFE_PARALLELISM="3"

The Issue happens on "terraform init" when terraform attempts to read the platform status from the API when running the APPSEC configuration which we use to configure Bot Management, WAF and DOS Settings.

**Comment by lkowalsk-akamai-com** [comment]
Hi, please try setting up limit for the requests to avoid hitting 429 errors: 
https://techdocs.akamai.com/terraform/docs/request-limits-1
