### ISSUE TITLE
DXE-2829 Custom timeouts for akamai_cps_dv_enrollment and  akamai_property_activation

### ISSUE THREAD

**Issue by chrisorisawayi** [akamai/terraform-provider-akamai#440]
Creating  or destroying `akamai_property_activation` and `akamai_cps_dv_enrollment`,  resources sometimes produces the error "activation context terminated: context deadline exceeded".

Both resources currently does not appear to support custom timeouts (no indication in resource docs).  Could this  be looked  into as create/delete operations may often  take several  hours?

**Comment by majakubiec** [comment]
Hi @chrisorisawayi,

Thank you for your feedback.
You are right, these resources don't support custom timeouts, but it should be easy to implement.
I will create an internal ticket to add it.

**Comment by chrisorisawayi** [comment]
Thanks for the update @majakubiec

**Comment by lkowalsk-akamai-com** [comment]
Customizable timeouts were added to various resources with 5.4.0 release.
