### ISSUE TITLE
DXE-2839 No reactivation of appsec if the config was deactivated manually

### ISSUE THREAD

**Issue by fkieling** [akamai/terraform-provider-akamai#441]
Hi there,

we have a problem with terraform state and the real state in akamai aap.

### Terraform Version
```
$ terraform -v
Terraform v1.5.2
on linux_arm64
+ provider registry.terraform.io/akamai/akamai v4.1.0
```

### Affected Resource(s)
- akamai_appsec_activations

### Terraform Configuration Files
```hcl
data "akamai_appsec_configuration" "config" {
  name = var.name
}

resource "akamai_appsec_activations" "appsecactivation" {
  config_id           = var.config_id
  network             = var.network
  note                = var.note
  notification_emails = var.notification_emails
  version             = data.akamai_appsec_configuration.config.latest_version
}

```

### Debug Output
https://gist.github.com/fkieling/fbedc4a4379601e5d11f86add23f6db6

### Expected Behavior
Terraform will detects that the config has disabled an re-enables the config.

### Actual Behavior
When the Web Security Configuration was disabled through the Control Center terraform doesn't detect a difference between the TF-Status (enabled) and the really status (disabled). Terraform will not reactivate the config.
```
No changes. Your infrastructure matches the configuration.
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Create a new terraform config for akamai_appsec and apply it with `terraform apply`.
2. Disable this config from the Akamai Control Center.
3. Execute `terraform apply`or `terraform plan`.

**Comment by lkowalsk-akamai-com** [comment]
Hi, this was addressed in recent 5.6.0 release.
