### ISSUE TITLE
DXE-2840 appsec config can't deactivate fully

### ISSUE THREAD

**Issue by fkieling** [akamai/terraform-provider-akamai#442]
Hi there,

we have a problem with tf destroy and akamai aap.

### Terraform Version$ terraform -v
```
Terraform v1.5.2
on linux_arm64
+ provider registry.terraform.io/akamai/akamai v4.1.0
```

### Affected Resource(s)
- akamai_appsec_activations

### Debug Output
https://gist.github.com/fkieling/32f81e824b1f5252452c859a0fea67fc

### Expected Behavior
If execute "terraform destroy" the AAP config will be deactivated and removed.

### Actual Behavior
If there no active config in the production terraform provider generates an error:
> Error: Title: Invalid Input Error; Type: https://problems.luna.akamaiapis.net/appsec-configuration/error-types/INVALID-INPUT-ERROR; Detail: Config 93500 and version 4 is not active on the network PRODUCTION.

### Steps to Reproduce
1. Deactivate the aap configuration for production through the control center. 
2. Execute "terraform destroy" # it will deactivare config in production network
3. Execute "terraform destroy -var "network=STAGING""

**Comment by lkowalsk-akamai-com** [comment]
Hi, this was addressed in recent 5.6.0 release.
