### ISSUE TITLE
DXE-2842 V5 is bad

### ISSUE THREAD

**Issue by ericrichtert** [akamai/terraform-provider-akamai#444]
We are waiting for weeks for a solution to issue 422.

We get provider v5, with so many breaking changes. It takes me hours today to get v5 to work and everything fails.

Issues like:
```│ Warning: Failed to decode resource from state
│ 
│ Error decoding "akamai_property.tf-property-www-ohra-nl" from prior state:
│ unsupported attribute "contact"
╵
╷
│ Warning: Failed to decode resource from state
│ 
│ Error decoding "akamai_property_activation.tf-activate-production" from
│ prior state: unsupported attribute "property"
╵
╷
│ Warning: Missing resource schema from provider
│ 
│ No resource schema found for local_file when decoding prior state
```

and

```╷
│ Error: Recordset create failure
│ 
│   with akamai_dns_record.xxxx,
│   on ohra.nl.tf line 826, in resource "akamai_dns_record" "xxxx":
│  826: resource "akamai_dns_record" "xxxx" {
│ 
│ Title: Not authorized; Type:
│ https://problems.luna.akamaiapis.net/-/pep-authn/deny; Detail: The
│ signature does not match
```

Why doeas every major release of the terraform provider so many issues?

Why are simple fixes not delivered as a minor release?

**Comment by dstopka** [comment]
Hi @ericrichtert,

Thank you for sharing your issues and concerns with us. 
I've been trying to reproduce the first of the mentioned issues - "Error decoding xyz", but without any luck so far. May I ask you to provide additional details, so we can understand it better? Most importantly, please let me know what terraform version you are using, what was the version of our provider before upgrading to v5.0.0 and a description of steps you took while upgrading.

For the second issue, can you let me know if you were using any of the deprecated fields in the provider configuration block?

Best regards,
Darek

**Comment by ericrichtert** [comment]
'''unsupported attribute "contact"''' is caused by changes in the provider, that don't handle the old config. After a first apply, it's gone.

**Comment by ericrichtert** [comment]
The issue regarding "Title: Not authorized;" is caused by the same issue as #446 . My code also looks like this:

```hcl
provider "akamai" {

  config {
    host          = var.akamai_host
    client_secret = var.akamai_client_secret
    client_token  = var.akamai_client_token
    access_token  = var.akamai_access_token
  }
}
```
According to https://developer.hashicorp.com/terraform/language/providers/configuration#:~:text=You%20can%20use,in%20the%20configuration). it should work. But with the akamai provider, it doesn't. And my old config was using the env vars AKAMAI_ACCESS_TOKEN, AKAMAI_CLIENT_TOKEN, AKAMAI_HOST, AKAMAI_CLIENT_SECRET. These were documented in the past, not deprecated in 4.x, but suddenly removed in 5.0. 

WHY?????

I've spent many hours with debugging the implementation of this version, because we were waiting for a fix on #422. But this is (again) a very nasty way to deliver a new release.

**Comment by sebagomez** [comment]
My config used to be like this

```yaml
provider "akamai" {
  edgerc         = "~/.edgerc"
  config_section = "default"

}
```

I was told by somebody from Akamai to use the variables, why would they stop supporting them? :(  

**Edit:** https://github.com/akamai/terraform-provider-akamai/issues/407#issuecomment-1584139145

**Comment by dstopka** [comment]
Hi @ericrichtert, @sebagomez,

We are sorry for the inconvenience. There's been a bug introduced that results in POST calls returning `The signature does not match` errors when using config block. Until we fix it I can suggest using `max_body` in the config block which solves the issue.

```hcl
provider "akamai" {
  config {
    host          = var.akamai_host
    client_secret = var.akamai_client_secret
    client_token  = var.akamai_client_token
    access_token  = var.akamai_access_token
    max_body      = 131072
  }
}
```

Best regards,
Darek

**Comment by ericrichtert** [comment]
This is again a major issue in the provider, caused by bad tested changes in the provider. 

And still the question remains: Why did akamai remove the option to use AKAMAI_ACCESS_TOKEN, AKAMAI_CLIENT_TOKEN, AKAMAI_HOST, AKAMAI_CLIENT_SECRET even without deprecating it?

As a customer of akamai, I expect a decent lifecyclemanagement of the services of akamai. I've spent weeks on debugging the terraform provider for the past 3 years.

**Comment by sebagomez** [comment]
Thanks again @dstopka for providing a workaround, but as I mentioned before, I'm in the middle of a move to prod so I can't afford a workaround with undocumented features (and mystery numbers).

I can afford to stick with 4.1.0 for now so I'll just stay there.

Also, the documentation hasn't been updated: https://techdocs.akamai.com/terraform/docs/overview

**Comment by dstopka** [comment]
Hi all,
 
Apologizes for the inconvenience caused by the unexpected removal of environmental variables support, which some of you relied upon. We understand the importance of this feature to your experience using our terraform provider. 
 
1)    Users authenticating with .edgerc can continue to use any version including v5.0.0 (and should not have similar issues as described with the provider `config`)
2)    For users using alternative authentication methods, please stay with v4.1.0 or earlier, as patch for v5.0.0 is in progress. The patch will include:
- reintroducing environmental variable support, noted in #407
- a fix for the provider `config` block, noted in #446
 
In the meantime, please do not hesitate to reach out, we do appreciate all of the feedback. We will continue to share the progress of the pending patch here.
 
Akamai Developer Experience Team

**Comment by KyleMarMcTVG** [comment]
thanks @dstopka - this is great news and shows that you are listening to your customers. Really looking forward to seeing this in place soon.

**Comment by dstopka** [comment]
Hi all, I want to share with you that release v5.0.1 is scheduled for this week.

**Comment by mgwoj** [comment]
This issue was fixed in recent release.
