### ISSUE TITLE
DXE-4067 Remove Adaptive Image Compression from Rules JSON in the examples

### ISSUE THREAD

**Issue by chr1Sc0** [akamai/terraform-provider-akamai#445]
### Affected Resource(s)
examples/akamai_property/property-json/rules.json

## Description
Adaptive Image Compression is getting deprecated so we should remove this behavior from the example rules file (Behavior Name: "JPEG Images")

**Comment by lkowalsk-akamai-com** [comment]
This was removed in one of recent releases hence closing.
