### ISSUE TITLE
DXE-2906 Error: Property Validation Failure

### ISSUE THREAD

**Issue by oscarsb66** [akamai/terraform-provider-akamai#450]
Hi there,

### Terraform Version
 - Terraform version 0.13.7
 - Akaimai provider
```
terraform {
  required_providers {
    akamai = {
      source = "akamai/akamai"
      version = "2.3.0"
    }
  }
}
```
 
### Affected Resource(s)
Please list the resources as a list, for example:
- akamai_gtm_property gtm-property

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.
```
Error: property Update failed: API error:
{
	"type": "https://problems.luna.akamaiapis.net/config-gtm/v1/propertyValidationFailed",
	"title": "Property Validation Failure",
	"detail": "",
	"instance": "https://akab-ousuyy7f6wzhtx5n-gycuuzjlyihsaubk.luna.akamaiapis.net/config-gtm-api/v1/domains/somedomaine.com.akadns.net/properties/retention-service#81663452-3983-4ff2-a1cb-29cf357c4882"
}
```
### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
What should have happened?

Changing the weight of a datacenter of an existing gtm property.

### Actual Behavior
What actually happened?

When changing the weight of a datacenter on an existing gtm property, it fails with the error above. We're only seeing this with one of our domains.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- GH-1234

**Comment by mimazaka** [comment]
Hi @oscarsb66,
We will start investigating this issue, looks like some API validation, but in mean time please provide some exemplary configuration file for which you have experienced this issue.

**Comment by sebagomez** [comment]
I had this same issue, I solved it by adding an empty value to the property

```json
      {
        "name": "PROPETY_NAME",
        "description": "My description",
        "value": "", // <------
        "hidden": false,
        "sensitive": false
      }
```

**Comment by lkowalsk-akamai-com** [comment]
@oscarsb66  can you please try to reproduce it with latest Akamai Terraform Provider version?
