### ISSUE TITLE
DXE-2975 Destroying a akamai_property_activation should be possible with active cnames

### ISSUE THREAD

**Issue by rolmo** [akamai/terraform-provider-akamai#455]
### Terraform Version
terraform 1.5.4
akamai-provider: 5.1.0

### Affected Resource(s)

akamai_property_activation

### Terraform Configuration Files
```hcl
resource "akamai_property_activation" "activate" {
  property_id                    = var.property.id
  contact                        = ["my.name@company.com"]
  version                        = var.property.latest_version
  network                        = upper(var.env)
  auto_acknowledge_rule_warnings = true
  note                           = var.note
}
```

### Problem

We create properties via Github-Actions with this steps:
* ***Step1***: Create the `akamai_property` together with a `akamai_edge_hostname` and the necessary CNAMEs in our DNS.
* ***Step2***: Create a `akamai_property_activation` for network=staging
* ***Step3***: Test the property in Staging
* ***Step4***: Create a `akamai_property_activation` for network=production

To destroy all this resources, we try to run the steps in descending order (Step4, Step3, Step2, Step1)

But when we run The `terreaform destroy` for Step4, we get this error, because the CNAME still points to the edge hostname:
```
│ Error: create deactivation failed: creating activation: API error:
│ {
│ 	"type": "https://problems.luna.akamaiapis.net/papi/v0/deactivation/property_deactivation_failed_hostname_cnamed_to_akamai",
│ 	"title": "Property Deactivation Failed",
│ 	"detail": "[Message{messageId=cannot_deactivate_hostname_cnamed_to_akamai, id=..., severity=ERROR, params=[test1-akamai...., test1-akamai....]}, Message{messageId=cannot_deactivate_hostname_cnamed_to_akamai, id=..., severity=ERROR, params=[test1-akamai...., test2-akamai....]}].",
│ 	"instance": "https://akab-...",
│ 	"statusCode": 400
│ }

```
But the deletion of the CNAMEs will happen only in "Step1" - and even then they are still cached for some time.

So it should possible to destroy a `akamai_property_activation` and a `akamai_property` even when a CNAME pointing to the edge hostname.

**Comment by mgwoj** [comment]
Hello @rolmo ,

Is there any particular reason why do you destroy those resources in 4 steps instead of removing everything in one step for all? Have you tries to remove all at once?

**Comment by rolmo** [comment]
If I want to delete them all in one step, I have to create them in one step.
But I don't want to do the `akamai_property_activation` for ***production*** in the same step as the `akamai_property_activation` for ***staging***, because I want to run tests between them.

Therefore there are several own folders in the deploy pipeline with own terraform code and own terraform state.

**Comment by mgwoj** [comment]
When requested to deactivate, the portal checks if the hostnames referenced in the property are pointing at Akamai, in DNS. If the portal sees DNS reporting that the CNAME is still pointing at e.g. `www.example.com.edgekey.net`, then it will refuse to proceed. Blocking the removal of properties with CNAMEs pointing at the platform is a safety measure that we have to protect customers from DoS-ing themselves.
You should then de-provision the `www.example.com`, or update it to point to a new location, to allow the deactivation (and hence, the property deletion) to proceed.
This is something you should be doing using a different terraform provider or process. Some hint about that you can find [here](https://community.akamai.com/customers/s/question/0D50f00006L0KBeCAN/is-there-any-possibility-to-overcome-cannotdeactivatehostnamecnamedtoakamai?language=en_US).
