### ISSUE TITLE
DXE-2940 akamai_dns_zone errors due to optional group parameter

### ISSUE THREAD

**Issue by brucep-care** [akamai/terraform-provider-akamai#456]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Terraform v1.3.7
on linux_amd64
\+ provider registry.terraform.io/akamai/akamai v5.1.0

### Affected Resource(s)

akamai_dns_zone

### Terraform Configuration Files
```hcl
resource "akamai_dns_zone" "xxx-test_com" {
    contract = "3-XXXXXXX"
    zone = xxx-test.com
    type = "PRIMARY"
    comment = "test"
}
```

### Expected Behavior
Zone should be created upon apply

### Actual Behavior
```Error: value not found: group```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids

The [Akamai documentation](https://techdocs.akamai.com/terraform/docs/dns-zone) for this resource indicates the `group` parameter is optional. Furthermore, the example provided in the documentation indicates a value such as `100` can be provided as a value to this parameter. Specifying a blank value for this parameter, a number as shown in the example, or any other value results in a cryptic error message:
```
Title: Illegal parameter value; Type: https://problems.luna.akamaiapis.net/authoritative-dns/illegalValue; Detail: Illegal value for request parameter 'gid'
```

**Comment by mgwoj** [comment]
Hello, please confirm that you have more than one group in your context that have Edge DNS entitlements.

**Comment by brucep-care** [comment]
Yes, we do. I am able to create new zones through the portal but I'm unable to via terraform due to this issue.

**Comment by mgwoj** [comment]
Are you able to mitigate this issue by providing `group_id` in the `akamai_dns_zone` resource?

**Comment by mgwoj** [comment]
@brucep-care , were you able to verify if the mitigation steps work for you?
