### ISSUE TITLE
DXE-3005 Terraform does not detect drift

### ISSUE THREAD

**Issue by rolmo** [akamai/terraform-provider-akamai#457]
### Terraform Version

terraform 1.5.4
akamai-provider: 5.1.0

### Affected Resource(s)

akamai_edge_hostname

### Terraform Configuration Files

```hcl
resource "akamai_edge_hostname" "hostname" {
  contract_id   = data.akamai_contract.contract.id
  group_id      = data.akamai_group.group.id
  ip_behavior   = "IPV6_COMPLIANCE" # IPV4|IPV6_PERFORMANCE|IPV6_COMPLIANCE
  edge_hostname = local.edge_hostname
}
```

### Problem

Terraform does not recognize when the actual configuration differs from the definition of the resource.

### Expected Behavior

Terraform should detect the deviation and display and correct the deviation in plan/apply.

### Actual Behavior

Terraform does not recognize deviations

Output:
```
No changes. Your infrastructure matches the configuration.
```

### Steps to Reproduce

* Create a `akamai_edge_hostname`with the code above (in this example withIPv6 support)
* Change the edge hostname in Akamai-Control-Center (e.g. switch to IPv4)
* Run `terraform plan` or `terraform apply`

**Comment by Slonimskaia** [comment]
Hi @rolmo,

Thank you for reporting this issue. We will investigate this and get back to you soon

Best regards,
Tatiana Slonimskaia

**Comment by lkowalsk-akamai-com** [comment]
This issue should now be fixed
