### ISSUE TITLE
Edgeworkers mpulse report enable not able to set in terraform.

### ISSUE THREAD

**Issue by shadow625** [akamai/terraform-provider-akamai#461]
Hi there,
We are facing an issue when trying to apply terraform config into akamai.  Terraform return an error complain as:    
> The Enable mPulse reports option on the `EdgeWorkers` behavior is required    

This property don't have any change since last successful deployment on this Wed (23/8), and this error pop up when we wanna remove "useUniqueCacheKey: false" in behavior of rules. which we think is not relvant with this issue.

### Terraform Version
Terraform v1.5.6

### Affected Resource(s)
- akamai_edgeworker

### Terraform Configuration Files
here is the code from our terrafrom repo:
```
    {
      "name": "edgeWorker",
      "options": {
        "createEdgeWorker": "",
        "edgeWorkerId": "${variable}",
        "enabled": true,
        "resourceTier": ""
      }
    }
```
👉  [the above code snippet is same with the example in this repo](https://github.com/akamai/terraform-provider-akamai/blob/e646305537c8dc87f397244e21cc64538398f6e2/examples/onboard-Ion/rules/snippets/edgeworker.json#L5-L11)

### Debug Output
This is the error prompt when do Apply.
```
"rule_errors": [
  {
    "behavior_name": "",
    "detail": "The Enable mPulse reports option on the `EdgeWorkers` behavior is required.",
    "error_location": "#/rules/children/5/behaviors/0/options/mPulse",
    "instance": "",
    "status_code": 0,
    "title": "",
    "type": "https://problems.luna.akamaiapis.net/papi/v0/validation/attribute_required"
  }
]
```

### Panic Output
NA

### Expected Behavior
We should able to set an option called `mpulse report enable`, then we are able set the mpulse report to false.
```
    {
      "name": "edgeWorker",
      "options": {
        "createEdgeWorker": "",
        "edgeWorkerId": "${variable}",
        "enabled": true,
        "resourceTier": ",
 ->>> [ "mpulse report enable": "false" ]. <<<-
      }
    }
```

### Actual Behavior
Apply failed and complain:
> The Enable mPulse reports option on the `EdgeWorkers` behavior is required.

### Steps to Reproduce
1. `terraform apply`

### References
we found only two variables in this doc:
https://techdocs.akamai.com/terraform/reference/ga-edge-worker

Plz let me know if you need further information. 🙏

**Comment by dstopka** [comment]
Hi @shadow625!

Thanks for reporting that issue. Information that you provided is not enough for me to understand the issue and reproduce it. I'd like to ask you to provide the following:
- akamai terraform provider version
- property rule format
- the rule tree you are using (please remove all sensitive information)

The error you are getting is rather vague and I need those for the investigation. At this time I can only say that the documented options for the `edgeworker` behavior are the only ones available.
