### ISSUE TITLE
DXE-3041 how to disable some specific protections with akamai_appsec_security_policy_default_protections resource ?

### ISSUE THREAD

**Issue by benbrd** [akamai/terraform-provider-akamai#464]
As per the last release of the terraform provider https://github.com/akamai/terraform-provider-akamai/releases/tag/v5.1.0, it appears that some resources are deprecated : 

> DEPRECATIONS
> 
>     Appsec
>         deprecated following resources; use akamai_appsec_security_policy_default_protections resource instead:
>             akamai_appsec_api_constraint_protection
>             akamai_appsec_ip_geo_protection
>             akamai_appsec_malware_protection
>             akamai_appsec_rate_protection
>             akamai_appsec_reputation_protection
>             akamai_appsec_slowpost_protection

As per the documentation, the akamai_appsec_security_policy_default_protections resource creates a new security policy with all of the account's available protections set to true.

Could you please let us know how to disable some specific protections in that case with the deprecations of resources?

**Comment by lkowalsk-akamai-com** [comment]
This is the current behavior and we can't disable any individual protections with this resource -It will enable the default protections only based on the user entitlement. Closing this ticket now, please let us know if you have any more questions.
