### ISSUE TITLE
DXE-3124 Akamai Terraform provider does not support "Retries and Customizable Timeouts"

### ISSUE THREAD

**Issue by gfuchs27** [akamai/terraform-provider-akamai#471]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
1.4

### Affected Resource(s)
Akamai activation resource blocks
property, security config, etc.

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
N/A

### Debug Output
Error: Unsupported block type

  on [main.tf](http://main.tf/) line 83, in resource "akamai_appsec_selected_hostnames" "appsecselectedhostnames":
  83:   timeouts {

Blocks of type "timeouts" are not expected here.

### Panic Output
N/A

### Expected Behavior
Behavior should be in line with the documentation from hashicorp found here:
https://developer.hashicorp.com/terraform/plugin/sdkv2/resources/retries-and-customizable-timeouts

### Actual Behavior
Retries and Customizable Timeouts are not supported by Akamai provider so an error is thrown

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Implement the following resource block
2.
resource "akamai_appsec_activations" "staging_activation" {
  # ...

  timeouts {
    create = "10m"
  }
}
3. Run "terraform plan"

### Important Factoids
N/A

### References
N/A

**Comment by mimazaka** [comment]
Hello @gfuchs27 

Thank you for reporting this issue. We have started our investigation on it. I will inform you about updates.

Regards,
Michał

**Comment by lkowalsk-akamai-com** [comment]
Update on this case, configurable timeouts were added to multiple resoures (see https://github.com/akamai/terraform-provider-akamai/releases/tag/v5.4.0) and retry mechanism was added to property acitvation. We will work on adding this to other resoueces (appsec actviations) as well.

**Comment by lkowalsk-akamai-com** [comment]
Hi, this was addressed in recent 5.6.0 release.
