### ISSUE TITLE
DXE-3135 Terraform Akamai provider plugin crashes when trying to fetch a Security policy within a security config

### ISSUE THREAD

**Issue by akaganeshmurthy** [akamai/terraform-provider-akamai#473]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Terraform v1.5.6

### Affected Resource(s)
Please list the resources as a list, for example:
- data "akamai_appsec_security_policy"

### Terraform Configuration Files
N/A

### Debug Output
https://gist.github.com/akaganeshmurthy/0f8070863891fe327312be9886dc4769

### Expected Behavior
Expected behavior is that terraform returns the details about the specific security policy.

### Actual Behavior
Plugin crashed with an error "The plugin encountered an error, and failed to respond to the plugin. ("GRPCProvider). ReadDataSource call. The plugin logs may contain more details."

### Steps to Reproduce
1. `terraform plan`

![Akamai Failed Run Part 1](https://github.com/akamai/terraform-provider-akamai/assets/128630856/e4c0c1ff-4398-4b7b-b2cd-c0a419e56a7d)
![Akamai Failed Run Part 2](https://github.com/akamai/terraform-provider-akamai/assets/128630856/77212016-fefc-43b2-a93e-570684e25ba8)

**Comment by mimazaka** [comment]
Hello @akaganeshmurthy

Thank you for reporting this issue. We have started our investigation on it. I will inform you about updates.

Regards,
Michal

**Comment by temibayo** [comment]
Hello, we are trying to reproduce this problem. 
Could you share the config file you used when you encountered this behavior. Also let us know if this is reproducible for you. 
Thanks

**Comment by lkowalsk-akamai-com** [comment]
Hi, this issues is caused by problem with bigcache library that is not working correctly on 32bits Windows machines. Please consider using different machine/os combination. Further more, I'm closing this issue as duplicate of this one: https://github.com/akamai/terraform-provider-akamai/issues/470
