### ISSUE TITLE
Bypass List Not Added To Match Target

### ISSUE THREAD

**Issue by billvangos** [akamai/terraform-provider-akamai#477]
### Terraform Version
Terraform v1.4.0

### Affected Resource
- akamai_appsec_match_target

### Terraform Configuration Files
```hcl
provider "akamai" {
  edgerc         = "~/.edgerc"
  config_section = "default"
}

data "akamai_appsec_configuration" "config" {
  name = "Testing Config"
}

resource "akamai_appsec_match_target" "match_target" {
  config_id              = data.akamai_appsec_configuration.config.id
  match_target           =  jsonencode(
    {
      type = "website"
      hostnames = ["testing-hostname.com"]
      securityPolicy = {
        policyId = "test_111111"
      }
      byPassNetworkLists = [
        {
            id = "11111_IPBYPASSLIST"
        }
      ]
      filePaths = [ "/*" ]
    }
  )
}
```

### Debug Output
https://gist.github.com/billvangos/635d4c3e52818d86bb1a75adee398546

### Expected Behavior
The apply is successful and the bypass network list is added to the match target configuration.

### Actual Behavior
The apply is successful and the bypass network list is not added to the match target configuration.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoidz
Subsequent applies will detect that the bylass network list is missing and attempt to recreate it.

**Comment by billvangos** [comment]
casing on `bypassNetworkLists` was incorrect, closing.

**Comment by Slonimskaia** [comment]
Hi @billvangos,

As I understand it correctly from your last comment, this issue is not valid. I am closing it, please reopen if necessary.

Best regards,
Tatiana Slonimskaia
