### ISSUE TITLE
DXE-3241 akamai_cloudlets_policy doesn't get updated upon a 'terraform refresh'

### ISSUE THREAD

**Issue by mf-sky** [akamai/terraform-provider-akamai#478]
Hi!

When creating a cloudlet policy and activating it, if i want to refresh the state after a manual change, the resource **akamai_cloudlets_policy** does not get updated

### Terraform Version
Terraform v1.5.7
on darwin_arm64
+ provider registry.terraform.io/akamai/akamai v5.3.0

### Affected Resource(s)
- akamai_cloudlets_policy

### Terraform Configuration Files

N/A

### Debug Output

N/A

### Panic Output

N/A

### Expected Behavior
Import the current active version of the policy

### Actual Behavior
The resource was not refreshed

### Steps to Reproduce
1. terraform apply
2. Manually change the resource
3. terraform refresh or  terraform apply -refresh-only

### Important Factoids
**akamai_cloudlets_policy_activation** gets refreshed correctly

### References
N/A

**Comment by majakubiec** [comment]
Hi, @mf-sky

Thank you for raising this issue. I was able to reproduce it and created internal ticket.

**Comment by lkowalsk-akamai-com** [comment]
Hi, this was addressed in recent 5.6.0 release.

**Comment by hypnotisttom** [comment]
@aka-mark, this might be what we discussed today regarding the cloudlet policy refresh on 5.5.0.  I will have to retest on 5.6.0.

**Comment by hypnotisttom** [comment]
Just to circle back, after testing, this does appear to resolve our issue with 5.5.0 with cloudlets changing in the console and showing no drift in the TF.  Thanks!
