### ISSUE TITLE
DXE-3268 Buggy example for `create-property.tf`

### ISSUE THREAD

**Issue by necipallef** [akamai/terraform-provider-akamai#485]
### Terraform Version
v1.5.7

### Affected Resource(s)
examples

### Terraform Configuration Files
[the example for creating property](https://github.com/akamai/terraform-provider-akamai/blob/master/examples/akamai_property/create-property/create-property.tf)

### Expected Behavior
Successfully creates a property

### Actual Behavior
Gives below error:
```bash
│ Error: Unsupported attribute
│
│   on akamai.tf line 43, in data "akamai_contract" "contract":
│   43:   group_name = data.akamai_group.group.name
│
│ This object has no argument, nested block, or exported attribute named "name".
```

### Steps to Reproduce
1. Copy and paste the example `tf` file with correct credentials.
2. Run `terraform plan`

**Comment by wzagrajcz** [comment]
Hello @necipallef 
Thanks for opening the issue and providing fix. We will review your PR internally and merge it afterwards if everything is correct. 

Best regards,
Wojciech
