### ISSUE TITLE
DXE-3310 akamai_property - Version notes

### ISSUE THREAD

**Issue by drdkmkkr** [akamai/terraform-provider-akamai#494]
### Feature request

Add a way to set these fields for  the `akamai_property` resource
- Version notes
- Property Description (nice to have)

Seems related to https://github.com/akamai/terraform-provider-akamai/issues/55, but this is marked as complete, and I can only see a way to add notes for the `akamai_property_activation` resource.

**Comment by mstojanowski** [comment]
@drdkmkkr, thank you for your suggestions. We will consider them.

Regards,
Marcin

**Comment by lkowalsk-akamai-com** [comment]
Hi, this was addressed in recent 5.6.0 release.
