### ISSUE TITLE
DXE-3352 bug: akamai_property.rules.rules.uuid doesn't update

### ISSUE THREAD

**Issue by drdkmkkr** [akamai/terraform-provider-akamai#495]
Hi there,

We are having issues with updating/adding/removing `rules.rules.uuid` field in `akamai_property`.
Apply runs without error, but does not change the UUID, which results in a never ending diff.

### Terraform Version
1.5.7

### Provider version
Tested on both versions, with same result.
- v5.4.0
- v3.6.0

### Affected Resource(s)
- akamai_property

### Terraform diff
```
  # module.akamai_property.xxxx will be updated in-place
  ~ resource "akamai_property" "xxxx" {
        id                 = "XXXXX"
      ~ latest_version     = 122 -> (known after apply)
        name               = "XXXXX"
      ~ production_version = 122 -> (known after apply)
      ~ rules              = jsonencode(
          ~ {
              ~ rules = {
                    name      = "default"
                  - uuid      = "default"
                    # (5 unchanged attributes hidden)
                }
            }
        )
      ~ staging_version    = 122 -> (known after apply)
        # (6 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }
```

### Expected Behavior
`akamai_property.rules.rules.uuid` should be updated/created/deleted

### Actual Behavior
`akamai_property.rules.rules.uuid` does not change, but applies without error.

#### Hypothesis
It could seem that only creation of `akamai_property` can set this vaule, and then later on, won't be able to change/add/remove it, but still shows a diff.

**Comment by psnoch-akamai** [comment]
Hello @drdkmkkr,

Thank you for raising this issue. We were able to reproduce it and create internal ticket to fix it. 

Greetings,
Pawel

**Comment by wzagrajcz** [comment]
Hello @drdkmkkr 

Hello

Two questions appeared during analysis of this issue.
1. The uuid is strongly related to locking mechanism. The modifications to locking and uuids should be done only by Akamai representative as mentioned [here](https://techdocs.akamai.com/property-mgr/reference/advanced-and-locked-features). If You are missing this information in terraform docs, please let us know, we will add it also there. Can You confirm that the update was done by Akamai representative?
2. The never ending diff is a result of unsuccessful update of those fields - the server still holds the value as it saw the update incorrect. The UUIDs on top most level is a result of UUIDs somewhere in direct behaviors/criteria (or somewhere in children's) - if it's there, it also must be in parent (so also in root level). The UUIDs must be set for either locked behaviours/criteria or read-only behaviors/criteria. Can You please verify that in your configuration all behaviours/criteria (including children's) all behaviors/criteria are read-write (info about it can be find in behaviour/criterion doc or the read only will have in description a phrase: `This option is for internal usage only.`) and does not have `"locked": true` set?

Best regards,
Wojciech
