### ISSUE TITLE
Feature request: import

### ISSUE THREAD

**Issue by lfallet** [akamai/terraform-provider-akamai#5]
Do you support `terraform import` command?
It's very useful when starting with existing live config.

**Comment by dshafik** [comment]
@lfallet we do support `terraform import` for the following resources:

- `akamai_property`
- `akamai_property_rules`
- `akamai_property_variables`
- `akamai_edge_hostname`
- `akamai_dns_zone`
- `akamai_dns_record`

We _strongly_ recommend against using it, as unless you have 100% migrated your configuration to Terraform, you will **lose** configuration data next time you `terraform apply`. Rather, we recommend  that for properties, you export the `rules.json` (either via the API, CLI, or Akamai Control Center), and create a new property from scratch. Akamai will automatically handle migration of traffic to the new property when it is activated with the existing hostnames (and will deactivate the old property if all hostnames are taken by the new one).

For DNS, zones doesn't have much value in importing (they cannot be deleted), and records are cheap and simple to recreate anyway, minimizing the value there.

Ultimately, it's important to understand that `terraform import`, merely imports the current **state**, and `terraform apply` will then use that known state to make your config reality.

**Comment by molodchenko** [comment]
I am managing Akamai properties with terraform, but somebody changed property version and added new rules.
After this i did `terraform apply`. Then i can see that Terraform created the new version of property but with rules which were added manually.
If it is expected behavior then how can i guarantee immutability of Akamai configuration with terraform?

**Comment by jeohist** [comment]
@dshafik Could documentation for terraform import be added? For example, like this AWS Provider example: https://www.terraform.io/docs/providers/aws/r/route53_zone.html#import

**Comment by jazzista88** [comment]
Hello @dshafik
I would ask if there is a way to avoid the new property creation.
I mean we have more that 50 akamai properties and we cannot migrate all of them in this way.
We would use terraform akamai provider to edit an existing property version, making changes and then apply them to the existing property?
Is this possible?

**Comment by jazzista88** [comment]
> I am managing Akamai properties with terraform, but somebody changed property version and added new rules.
> After this i did `terraform apply`. Then i can see that Terraform created the new version of property but with rules which were added manually.
> If it is expected behavior then how can i guarantee immutability of Akamai configuration with terraform?

Hello @molodchenko 
Sorry i am confused, how did you created a new version? I have created a new akamai property, so it is now V1, it is not active neither on staging nor on production, when i run terraform apply i don't see any new version created the apply is editing just the V1.
it is needed that they are activated on one of these env? Or there is a way to create a new version secifying a parameter in .tf files? Thanks

**Comment by jazzista88** [comment]
Ii found also this old thread where it seems that terraform import can be applied:
[https://community.akamai.com/customers/s/article/How-to-load-an-existing-property-in-Terraform](https://community.akamai.com/customers/s/article/How-to-load-an-existing-property-in-Terraform)

**Comment by sbfaulkner** [comment]
it would be nice to be able to import the cpcode resource too

**Comment by zstlaw** [comment]
Import support has been improved and is better documented in cp_code, edge_hostname, and property as part of the 1.0.0 release.

Please try upgrading to 1.0.0 and if you still face issues, Please let us know. Please refer https://registry.terraform.io/providers/akamai/akamai/latest/docs/guides/1.0_migration for additional details.
