### ISSUE TITLE
WAF deny rule IPBLOCK-BURST4-54013 While Refreshing State

### ISSUE THREAD

**Issue by dogmd** [akamai/terraform-provider-akamai#500]
Hi, while performing Terraform plans, the Akamai API requests appear to be getting rate limited (some values have been obfuscated):
```
Error: failed to get activations for property: fetching activations: API error

{
"type": "https://problems.luna.akamaiapis.net/-/pep-authn/request-error",
"title": "Bad request",
"detail": "WAF deny rule IPBLOCK-BURST4-54013",
"instance": "https://akab-[API_HOST].luna.akamaiapis.net/papi/v1/properties/[PROPERTY_ID]/activations?groupId=[GROUP_ID]\u0026contractId=[CONTRACT_ID]",
"statusCode": 400
}
```
This happens even when using `-parallelism=1`, albeit less frequently.

### Terraform Version
```
$ terraform -v
Terraform v1.6.2
on linux_amd64
+ provider registry.terraform.io/akamai/akamai v5.2.0
+ provider registry.terraform.io/hashicorp/tfe v0.48.0
+ provider registry.terraform.io/scottwinkler/shell v1.7.10
```

### Affected Resource(s)
This happens often with `akamai_property_activation` resources, but occasionally with other resources, too.

### Steps to Reproduce
Create a Terraform configuration with many (about 30-40) different Akamai properties as modules, and plan a change to refresh the state.

### Important Factoids
This configuration contains resources for about ~30 Akamai properties, 8 DNS zones, and an AppSec security configuration. The states of these are all refreshed by `terraform plan`

**Comment by ckulinsk** [comment]
Hi @dogmd,
Thank you for reporting this issue. We will investigate your issue and we will inform you of any progress.
BR,
Cyryl

**Comment by ckulinsk** [comment]
Hi,
Could you provide us with log files or with information how many requests per second are you making when using your config? You should be able to check that by using command: `grep -E 'GET /papi/v1/properties' terraform.log`
BR,
Cyryl

**Comment by ckulinsk** [comment]
Hello @dogmd, I am reaching out to verify if you are still facing the issue. If that is the case, could you please share your logs and config file? That would help us in investigating the issue. Please remember to redact any sensitive information before sharing your configuration.
