### ISSUE TITLE
akamai_datastream needs import support

### ISSUE THREAD

**Issue by hypnotisttom** [akamai/terraform-provider-akamai#505]
### Affected Resource(s)
- akamai_datastream

### Expected Behavior
Import should be supported.

### Actual Behavior
Import is ignored.

### Important Factoids
Unfortunately, our PAPI import and CI/CD workflow are heavily reliant on Datastream.  While we did find a few other imports missing, this one is holding up our rollout, so I'm opening up this issue to help with prioritization.

**Comment by IanCassTwo** [comment]
Import should already work using just the datastream id

`terraform import akamai_datastream.my_datastream <id>`

**Comment by hypnotisttom** [comment]
Thanks.  Preliminary testing looks good.  Didn't seem obvious from the code or the docs, but I'm glad it exists.  Will continue testing some more since we programmatically determine when to provision a stream.

Do you know if import of activations of cloudlets works the same way?  I vaguely remember having an import problem with one of these.

**Comment by IanCassTwo** [comment]
Cloudlets needs just the policy name. Documented here https://techdocs.akamai.com/terraform/docs/cs-rc-policy

**Comment by hypnotisttom** [comment]
> Cloudlets needs just the policy name. Documented here https://techdocs.akamai.com/terraform/docs/cs-rc-policy

Not policy, activation. How do I import an existing activation of a clouflet?

**Comment by dawiddzhafarov** [comment]
Hi @hypnotisttom,
We are currently working on supporting import for cloudlets activations.

With regards,
Dawid

**Comment by lkowalsk-akamai-com** [comment]
@hypnotisttom since the original ticket was about datastream, can you please close it? If you want to create a ticket for cloudlets activation import, feel free to do so, although we are already woring on it.

**Comment by hypnotisttom** [comment]
> @hypnotisttom since the original ticket was about datastream, can you please close it? If you want to create a ticket for cloudlets activation import, feel free to do so, although we are already woring on it.

Yes, I was actually writing now to do that.  Initial tests of datastream look good.  We will continue testing and will update here if we encounter any datastream import issues.  Closing this issue for now.
