### ISSUE TITLE
China CDN cannot be managed with terraform

### ISSUE THREAD

**Issue by chouraamine** [akamai/terraform-provider-akamai#508]
China CDN cannot be managed with terraform

**Comment by mstojanowski** [comment]
Hi @chouraamine, 

Thank you for reporting this request. We will investigate it and come back to you.

**Comment by lkowalsk-akamai-com** [comment]
Hi @chouraamine, thank you for rising this with us, but we are not planning to add this functionality to our Akamai Terraform provider.
