### ISSUE TITLE
DXE-3418 [Request] Missing mapping for /config-dns/v2/zones/dns-sec-status

### ISSUE THREAD

**Issue by aci-payon-ops** [akamai/terraform-provider-akamai#509]
Hello!

I believe that there is no way to fetch the DNSSEC status with the latest version of the Akamai Terraform provider.
The `akamai_dns_zone` resource does not map these details, and that is likely the correct choice given that there is a different API endpoint for the DNSSEC status.

Thus, adding a dedicated datasource `akamai_zone_dnssec_status`  which maps `/config-dns/v2/zones/dns-sec-status` would be a useful addition.

### Terraform Version
Terraform v1.6.4
on linux_amd64
+ provider registry.terraform.io/akamai/akamai v5.5.0

### Affected Resource(s)
N/A, resource is not implemented.

### Terraform Configuration Files
Example usage:

```hcl
data "akamai_zone_dnssec_status" "example_com" {
  zone = "example.com"
}

output "example_com_dnskey" {
  value = akamai_zone_dnssec_status.example_com.dnskey_record
}

output "example_com_ds" {
  value = akamai_zone_dnssec_status.example_com.ds_record
}
```

I hope this can be implemented to allow end-to-end DNS provisioning with Terraform including DNSSEC.

Best regards,
Fabian

**Comment by mstojanowski** [comment]
Hi @aci-payon-ops, 

Thank you for reporting this request. We will investigate it and come back to you.

**Comment by mgwoj** [comment]
Hi @aci-payon-ops , this issue should be fixed in the recent release.
