### ISSUE TITLE
DXE-3551 Updating akamai_appsec_configuration fails when there are multiple policies associated with it.

### ISSUE THREAD

**Issue by sriraamas** [akamai/terraform-provider-akamai#523]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
1.6.2

### Affected Resource(s)
Please list the resources as a list, for example:
- akamai_appsec_configuration

### Terraform Configuration Files
```hcl
resource "akamai_appsec_configuration" "config" {
  name        = "Lucid Security Configuration"
  description = "Lucid Security Configuration"
  contract_id = <contractId>
  group_id    = <groupId>
  host_names  = ["*.lucid.co"]
}

```

### Expected Behavior
No errors should happen

### Actual Behavior
What actually happened?
**Error: setting property value: Title: Invalid Input Error; Type: https://problems.luna.akamaiapis.net/appsec/error-types/INVALID-INPUT-ERROR; Detail: Config(xxxxx) and version(xx) has more than one policy.**

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. create an akamai appsec configuration and link two security policies with it.
2. Update the hostnames attribute with new hostname.

**Comment by psnoch-akamai** [comment]
Hi @sriraamas ,

Thank you for reporting this issue. I created internal ticket for addressing it.

Best regards,
Pawel

**Comment by psnoch-akamai** [comment]
Hi @sriraamas ,
could you please provide some more details about this issue?
1. Account Name
2. Security Config Name
3. The resource definition for the 2 security policies

Thanks,
Pawel
