### ISSUE TITLE
"description" field not importing for SHARED cloudlets

### ISSUE THREAD

**Issue by hypnotisttom** [akamai/terraform-provider-akamai#526]
### Terraform Version
1.3.1

### Provider Version
5.6.0

### Affected Resource(s)
akamai_cloudlets_policy

### Expected Behavior
When importing a shared cloudlet with Provider version 5.6.0, I would expect the `description` field to be imported.  Not importing it results in drift immediately after import.  It should be noted that for unshared cloudlets the `description` field does import correctly.

### Actual Behavior
The `description` field is left out of the state (via `terraform state show`) after import, which causes immediate drift.

### Steps to Reproduce
1. Import a shared cloudlet (we tested with Edge Redirector) that has a `description` on a cloudlet version
2. Run a `terraform plan` to see the drift
3. Check `terraform state show` to see no description field
4. Repeat the same steps for an unshared cloudlet, noticing that the `description` field is imported to state, with no immediate drift

**Comment by lsadlon** [comment]
Hi @hypnotisttom 

I was not able to reproduce it, but could you check if you have set this description for **policy version**, because there is also other description for **policy** itself. Terraform is taking it from **policy version**. Could check if that was a case?

BR,
Lukasz

**Comment by hypnotisttom** [comment]
Hi @lsadlon,

I checked with my peer again because we did check that yesterday; however, in re-checking it does appear the version notes field is blank.  I apologize - not sure what happened here.

I will close this out for now.  We have more shared cloudlets to import; if I can find an issue where the field isn't importing from the version, I'll let you know.

Again, please forgive me.  We knew it was only the version notes field that would import, but somehow our eyes saw something that wasn't there. :-)

**Comment by lsadlon** [comment]
Hi @hypnotisttom,

No worries. :-) If something else pop out, please don't hesitate reporting it.

BR,
Lukasz
