### ISSUE TITLE
akamai_cp_code stuck on "Modifying"

### ISSUE THREAD

**Issue by packet-blaster** [akamai/terraform-provider-akamai#529]
Whenever terraform needs to modify the name of an akamai_cp_code, it seemingly creates a NEW cp code and tries to delete the old one, causing tarraform to hang on "Modifying" because cp_codes cannot be deleted. 

The plan shows a MODIFICATION and not a CREATE/DESTROY, but the GUI shows a duplicate being created and I have to create a support ticket to delete it. 

### Terraform Version
Terraform v1.7.3
provider registry.terraform.io/akamai/akamai v5.6.0

### Affected Resource(s)
Please list the resources as a list, for example:
- akamai_cp_code

### Terraform Configuration Files
```hcl
~ resource "akamai_cp_code" "cpcode" {
        id          = "1111111"
      ~ name        = "some-name" -> "some-name.example.com"
        # (3 unchanged attributes hidden)
    }
```

### Debug Output
```hcl
module.some-name.akamai_cp_code.cpcode: Still modifying... [id=1111111, 12m40s elapsed]
module.some-name.akamai_cp_code.cpcode: Still modifying... [id=1111111, 12m50s elapsed]
...
```

### Expected Behavior
CP code should successfully be modified

### Actual Behavior
CP code is duplicated and unable to cleanup original

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply` with name modification to akamai_cp_code

**Comment by lsadlon** [comment]
Hi @packet-blaster 

Are you using latest akamai terraform provider (5.6.0) if not could you try with it?
Could you also share terraform.log? It will help us investigate it.

BR,
Lukasz
