### ISSUE TITLE
Support the creation of DNS records of type AKAMAICDN

### ISSUE THREAD

**Issue by bogdan-grozoiu** [akamai/terraform-provider-akamai#53]
Hi Akamai team,

As you have your own types of records, please enhance the provider to support the creation of DNS records of type `AKAMAICDN`.

### Terraform Version
Terraform v0.12.7
+ provider.akamai v0.1.3

### Affected Resource(s)
- akamai_dns_record

### Terraform Configuration Files
```hcl
resource "akamai_dns_record" "akamaicdn_acc_companyname_com" {
  zone       = var.zone
  name       = "acc.companyname.com"
  recordtype = "AKAMAICDN"
  ttl        = 20
  active     = true
  target = [
    "acc.companyname.edgekey.net",
  ]
}
```

### Expected Behavior
Be able to create DNS records of type AKAMAICDN using the latest version of TF and of the provider.

### Actual Behavior
```
Error: expected recordtype to be one of [A AAAA CNAME LOC NS PTR SPF TXT AFSDB DNSKEY DS HINFO MX NAPTR NSEC3 NSEC3PARAM RP RRSIG SRV SSHFP], got AKAMAICDN

  on acc.companyname.com.tf line 1064, in resource "akamai_dns_record" "akamaicdn_acc_companyname_com":
1064: resource "akamai_dns_record" "akamaicdn_acc_companyname_com" {
```

### Steps to Reproduce
1. `terraform plan`

**Comment by ghost** [comment]
As of October 2019, the AKAMAICDN record is not able to be set by customers and partners on a Fast DNS level. Therefore this record is disallowed on a Terraform level as well. Updating the Terraform code to whitelist AKAMAICDN will not result in successful setting of the AKAMAICDN record. 

In your use-case above acc.companyname.com CNAME acc.companyname.edgekey.net, a normal CNAME record would suffice.

**Comment by ericrichtert** [comment]
As far as I can see is AKAMAICDN and AKAMAITLC still a valid option. AKAMAITLC is the only way to set a CNAME on a the toplevel of the DNS domain.
Can these be added to the provider?

**Comment by ericdebeij** [comment]
Small correction; AKAMAICDN is the option which is self-serviceable and therefor should be added.

**Comment by IanCassTwo** [comment]
https://github.com/terraform-providers/terraform-provider-akamai/pull/123

**Comment by martinstibbe** [comment]
simplerecord := map[string]bool{"A": true, "AAAA": true, "AKAMAICDN": true This will be in next release

**Comment by ericrichtert** [comment]
@martinstibbe When will the next version release? We are waiting for this item.
