### ISSUE TITLE
cdn property Advance customBehavior

### ISSUE THREAD

**Issue by BAu0002** [akamai/terraform-provider-akamai#530]
We have a special behavior requirement in our cdn property, which an akamai support person have applied.
This result in adding a cdn property with json (as shown in akamai console):

`{ 
  "behaviors": [
    {
      "name": "customBehavior",
      "options": {
          "behaviorId": "xxxxxxx"
      }
    }
  ],
  "comments": "",
  "name": "special behaviour",
  "options": {},
  "criteriaMustSatisfy": "all"
}`

When I try and add this using terraform, I get the error 
" cannot parse rules JSON from config: json: cannot unmarshal string into Go struct field Rules.rules.children of type papi.Rules "

Can you advise how I can manage this behaviour in terraform?

**Comment by mstojanowski** [comment]
@BAu0002,

Thank you for your inquiry. Unfortunately I'm unable to reproduce the issue. Could you please provide entire json file with special behaviour?

Regards,
Marcin

**Comment by BAu0002** [comment]
The following is saved as response-header-max-size.json
`{ 
  "behaviors": [
    {
      "name": "customBehavior",
      "options": {
          "behaviorId": "cbe_437830325"
      }
    }
  ],
  "comments": "",
  "name": "Response Header Max Size",
  "options": {},
  "criteriaMustSatisfy": "all"
}
  `

The following is the main.json
`{
  "rules": {
    "name": "default",
    "behaviors": [
      {
        "name": "origin",
        "options": {
          "cacheKeyHostname": "REQUEST_HOST_HEADER",
          "compress": true,
          "customValidCnValues": [
            "{{Origin Hostname}}",
            "{{Forward Host Header}}"
          ],
          "enableTrueClientIp": true,
          "forwardHostHeader": "REQUEST_HOST_HEADER",
          "hostname": "${env.originalHostname}",
          "httpPort": 80,
          "httpsPort": 443,
          "originCertificate": "",
          "originCertsToHonor": "STANDARD_CERTIFICATE_AUTHORITIES",
          "originSni": true,
          "originType": "CUSTOMER",
          "ports": "",
          "standardCertificateAuthorities": [
            "akamai-permissive",
            "THIRD_PARTY_AMAZON"
          ],
          "trueClientIpClientSetting": false,
          "trueClientIpHeader": "True-Client-IP",
          "verificationMode": "CUSTOM"
        }
      },
      {
        "name": "cpCode",
        "options": {
          "value": {
            "cpCodeLimits": {
              "currentCapacity": 77,
              "limit": 100,
              "limitType": "global"
            },
            "id": "${env.cpCodeId}",
            "name": "${env.propertyName}",
            "products": [
              "Fresca"
            ]
          }
        }
      },
      {
        "name": "autoDomainValidation",
        "options": {
          "autodv": ""
        }
      }
    ],
    "children": [
      "#response-header-max-size.json"
    ],
    "comments": "The Default Rule template contains all the necessary and recommended behaviors. Rules are evaluated from top to bottom and the last matching rule wins.",
    "options": {
      "is_secure": true
    }
  }
}
`

**Comment by mstojanowski** [comment]
@BAu0002 ,

I managed to reproduce your error. It's caused by incorrect way you refer to children element in main.json file. Please try this way:

`"children": [
      "#include:response-header-max-size.json"
    ],`

This could help.

Regards,
Marcin

**Comment by BAu0002** [comment]
doh, how did I miss that.
I must be looking at this code too long.

Thanks for the help.

**Comment by mstojanowski** [comment]
Glad I could help :)

Marcin
