### ISSUE TITLE
SECKSD-25927 akamai_appsec_wap_selected_hostnames resource doesn't create new Security Config version

### ISSUE THREAD

**Issue by dogmd** [akamai/terraform-provider-akamai#540]
Whenever I modify my akamai_appsec_wap_selected_hostnames resource without making other changes to other resources, a new security configuration version isn't created, resulting in the following error:
```
Error: setting property value: Title: This operation is invalid; Type: https://problems.luna.akamaiapis.net/appsec-configuration/error-types/FORBIDDEN-OPERATION; Detail: You can't edit this security configuration version. It may be active, previously active, pending activation, or not fully created yet.
```

### Terraform Version
```
Terraform v1.8.0
on linux_amd64
+ provider registry.terraform.io/akamai/akamai v6.0.0
```

### Affected Resource(s)
- akamai_appsec_wap_selected_hostnames

### Terraform Configuration Files
```hcl
resource "akamai_appsec_wap_selected_hostnames" "hostnames" {
  config_id = data.akamai_appsec_configuration.config.config_id
  security_policy_id = akamai_appsec_security_policy.first_security_policy.security_policy_id
  protected_hosts = ["terraform-test.REDACTED.com"]
}
```

```hcl
resource "akamai_appsec_security_policy" "first_security_policy" {
  config_id              = data.akamai_appsec_configuration.config.config_id
  default_settings       = true
  security_policy_name   = "First Security Policy"
  security_policy_prefix = "qik1"
}
```

```hcl
data "akamai_appsec_configuration" "config" {
  name = var.name
}

resource "akamai_appsec_version_notes" "version_notes" {
  config_id     = data.akamai_appsec_configuration.config.config_id
  version_notes = "Test"
}

data "akamai_group" "group" {
  group_name  = var.group_name
  contract_id = var.contract_id
}

output "config_id" {
  value = data.akamai_appsec_configuration.config.config_id
}
```

### Debug Output
https://gist.github.com/dogmd/a90b4865ddfc8c136c7dd8e18e659883

### Expected Behavior
A new security configuration version should be created if the current version has been activated, similar to what happens with `akamai_appsec_selected_hostnames`

### Actual Behavior
No new security configuration version is created resulting in the following error message:
```
Error: setting property value: Title: This operation is invalid; Type: https://problems.luna.akamaiapis.net/appsec-configuration/error-types/FORBIDDEN-OPERATION; Detail: You can't edit this security configuration version. It may be active, previously active, pending activation, or not fully created yet.
```

### Steps to Reproduce
1. Ensure that the latest version of the security configuration has been activated.
2. Modify the akamai_appsec_wap_selected_hostnames resource without modifying other resources
3. `terraform apply`

**Comment by mstojanowski** [comment]
@dogmd ,

Thank you for raising this issue. It's currently under investigation.


Regards,
Marcin

**Comment by mgwoj** [comment]
Hello @dogmd, this issue should be fixed in the recent release.
