### ISSUE TITLE
DXE-3797 Order of targets in akamai_dns_record can cause problems.

### ISSUE THREAD

**Issue by tmccombs** [akamai/terraform-provider-akamai#541]
### Terraform Version
```
Terraform v1.7.2
on linux_amd64
+ provider registry.terraform.io/akamai/akamai v5.5.0
+ provider registry.terraform.io/hashicorp/tfe v0.53.0
+ provider registry.terraform.io/scottwinkler/shell v1.7.10

Your version of Terraform is out of date! The latest version
is 1.8.1. You can update by downloading from https://www.terraform.io/downloads.html
```

### Affected Resource(s)
- akamai_dns_record

### Terraform Configuration Files
```hcl
resource "akamai_dns_record" "example" {
  zone = var.akamai_zone
  name = "test.example.com"
  recordtype = "txt"
  ttl = 60
  target = [
    "zzz",
   "aaa",
   "123",
  ]
}
```

### Expected Behavior
If I change the "zzz" record to something else, like sy "yyz", then it will update that one record.

### Actual Behavior
First of all, the diff shows up really strange, something like:

```
~ target = [
    "123",
    "aaa"
  - "zzz",
 + "123",
 ]
```

Which is really weird.

And secondly, if you assume this is just a bug in the diff engine and try to apply the change, you get an error like:

```
Error: Title: Invalid record; Type: https://problems.luna.akamaiapis.net/authoritative-dns/invalidRecord; Detail: Duplicate rdata found for record with name test.example.com and type TXT
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1.terraform apply the original config
2. change the "zzz" target to "yyz"
3. run `terraform plan`
4. try to apply the plan

**Comment by psnoch-akamai** [comment]
Hello @tmccombs ,

Thank you for reporting this ticket.
I was able to reproduce similar case. Could you please add your "target" value from terraform.tfstate after first apply?

Thanks,
Pawel

**Comment by tmccombs** [comment]
In my real application, the value of target in tfstate after first apply was:

```
[
              "\"3z1fjzgxsdy86ky8szvm6gwtxndz6mm0\"",
              "\"google-site-verification=pUccO5tWSRUD5eVkunk5MFAA3B-G-_c5Yh75tSLdjYE\"",
              "\"v=spf1 include:usb._netblocks.mimecast.com include:mktomail.com include:email.influitive.com ~all\""
 ]
```

The config was in the order:

```
[                                                                                                               
  "v=spf1 include:mktomail.com include:email.influitive.com ~all",                                              
  "google-site-verification=pUccO5tWSRUD5eVkunk5MFAA3B-G-_c5Yh75tSLdjYE",                  
  "3z1fjzgxsdy86ky8szvm6gwtxndz6mm0",                                     
]       
```                                                                  


and the plan showed:
![image](https://github.com/akamai/terraform-provider-akamai/assets/2541726/d31de653-db57-4ea0-91f2-277a8a96f0d0)

If I changed the order of config to match what was in state, then it worked fine. 

Interestingly, this behavior seems to be specific to TXT records. For MX records, akamai preserves the order of the inputs.

**Comment by mgwoj** [comment]
Hi @tmccombs, this issue should be fixed in the recent release.
