### ISSUE TITLE
[DXE-3799] Error while updating rule template value and activating it using terraform

### ISSUE THREAD

**Issue by SinghPavan** [akamai/terraform-provider-akamai#543]
Hi there,

 We are using terraform to create property, but today when we try to update certain value like caching time and other vales we are getting below error:

### Terraform Version
Terraform v1.8.1
on linux_amd64
 akamai/akamai v6.0.0...

### Affected Resource(s)
Please list the resources as a list, for example:
- akamai_property
- akamai_property_activation
- akamai_property_rules_template

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```
data "akamai_property_rules_template" "rules" {
  template_file = abspath("${path.root}/templates/common-snippets/main.json")
variables {
    name  = "caching_ttl"
    value = var.caching_ttl
  }
}
resource "akamai_property" "akamai_property_provisioning" {
  name = "example_iac"
  #Product Identifier (Ion), This remain fixed for all the groups under Unilever account
  
  #Group ID, This will change per groups                          
  group_id = "121232"
  #Contract ID, will remain fixed for all the groups      
  contract_id = "12312312"

  hostnames {
      cname_from             = "example.com"
      cname_to 	             = "example.com.edgekey.net"
      cert_provisioning_type = "DEFAULT"
    }
  rule_format = "latest"
  rules       = data.akamai_property_rules_template.rules.json

}

resource "akamai_property_activation" "pm_activation" {
  property_id                    = akamai_property.akamai_property_provisioning.id
  version                        = akamai_property.akamai_property_provisioning.latest_version
  network                        = staging
  auto_acknowledge_rule_warnings = true
}
```

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
Should update the rule template and property and activate it.

### Actual Behavior
What actually happened?
│ Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for
│ module.property.akamai_property.akamai_property_provisioning to include new
│ values learned so far during apply, provider
│ "registry.terraform.io/akamai/akamai" produced an invalid new value for
│ .staging_version: was known, but now unknown.
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Create the code for rule template, property and activation 
2. Add a variable that will pass in the list of children to be included
3. `terraform apply`

### Important Factoids
No

### References
No

**Comment by psnoch-akamai** [comment]
Hello @SinghPavan, 

Thank you for reporting this ticket.
We try to reproduce your issue. Could you please add more details about your updates, especially if there were any changes for 
`resource "akamai_property_activation" "pm_activation"`?

Thanks,
Pawel

**Comment by SinghPavan** [comment]
Hello PawelSnoch,

I connected with akamai partner support and they told me to change the version to 5.4.0 from 6.0.0. I reverted akamai version for terraform to 5.4.0 and it worked. 

Are you able to replicate the issue?

Thank you.

**Comment by SinghPavan** [comment]
But the revert is temporary to recover from outage.

**Comment by psnoch-akamai** [comment]
Hello @SinghPavan ,

we are unable to reproduce the same issue, but we have started an investigation. It would be great if you could check what else was modified - you mentioned about caching time and other vales.

Thank you,
Pawel

**Comment by SinghPavan** [comment]
Hi @PawelSnoch 

There was no change in actual terraform code.  We just tried to update certain value like ttl and others value (Like hostname) through existing tfvars file and we have done this type of changes earlier also and it had succeeded. But this time we stuck with the error mentioned above.

```
Below is the debug output for the error,

2024-04-19T18:44:11.276+0530 [DEBUG] State storage *remote.State declined to persist a state snapshot
2024-04-19T18:44:11.330+0530 [WARN]  Provider "registry.terraform.io/akamai/akamai" produced an invalid plan for module.property.akamai_property.akamai_property_provisioning, but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .rules: planned value cty.StringVal("SOME COMMENT")
2024-04-19T18:44:11.336+0530 [ERROR] vertex "module.property.akamai_property.akamai_property_provisioning" error: Provider produced inconsistent final plan
2024-04-19T18:44:11.336+0530 [ERROR] vertex "module.property.akamai_property.akamai_property_provisioning" error: Provider produced inconsistent final plan
2024-04-19T18:44:11.336+0530 [ERROR] vertex "module.property.akamai_property.akamai_property_provisioning" error: Provider produced inconsistent final plan
2024-04-19T18:44:11.336+0530 [DEBUG] states/remote: state read serial is: 13; serial is: 13
2024-04-19T18:44:11.337+0530 [DEBUG] states/remote: state read lineage is: ca3e08df-a1ad-f092-e0eb-2dcb75fc0be2; lineage is: ca3e08df-a1ad-f092-e0eb-2dcb75fc0be2
2024-04-19T18:44:11.831+0530 [DEBUG] provider.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = error reading from server: EOF"
2024-04-19T18:44:11.859+0530 [DEBUG] provider: plugin process exited: path=.terraform/providers/registry.terraform.io/akamai/akamai/6.0.0/windows_amd64/terraform-provider-akamai_v6.0.0.exe pid=9160
2024-04-19T18:44:11.859+0530 [DEBUG] provider: plugin exited

```

Thank you.

**Comment by FilipAntkowiak** [comment]
Hi @SinghPavan,
Is this error still occurring in the latest version of the provider?
> "registry.terraform.io/akamai/akamai" produced an invalid new value for .staging_version: was known, but now unknown. 

Thanks,
Filip

**Comment by SinghPavan** [comment]
Hi @FilipAntkowiak 

We contacted regarding it to akamai support team, and they mentioned to lower the version. As soon as we lowered the version the issue got resolved (we mad small changes in terraform, to make it compatible with lower version). But it didn't affect anything, and it worked with older state file updating all the changes.

The akamai support team told they are trying to resolve it, but they don't know ETA for it.

Below is the screenshot from same mail.

![image](https://github.com/akamai/terraform-provider-akamai/assets/122888783/299144a9-20e3-488a-90a5-afaac5f63d3a)


Thank you.

**Comment by FilipAntkowiak** [comment]
Hi @SinghPavan,

We still cannot reproduce this error. Could you provide more context. Did it work before 6.0.0, or did the errors started appearing when moving from an older version to 6.0.0. It would also help to know exactly what values were changed and the rule template associated with them. Could you provide them?

Thanks,
Filip

**Comment by SinghPavan** [comment]
Hi @FilipAntkowiak 

No, we didn't use older version, the development started with the new version 6, but then we started facing the issue and we rolled it back to previous version. As suggested by akamai technical support team.

If you need more details, please do provide your mail id.

Thank you.

**Comment by FilipAntkowiak** [comment]
Hi, @SinghPavan,

Thanks for the quick response, you can send details to fantkowi@akamai.com.

Thanks,
Filip

**Comment by chouraamine** [comment]
Hi, 
I have the same error : 
Akamai version : 5.6.0

<img width="308" alt="image" src="https://github.com/akamai/terraform-provider-akamai/assets/115227803/e79214ff-5c5d-46f7-bc38-e76f9f56abb4">

**Comment by mgwoj** [comment]
Hello @SinghPavan ,

We were able to replicate similar issue reported at https://github.com/akamai/terraform-provider-akamai/issues/567 . It happens when rule content depends on the value from other resource. As we cannot replicate your exact scenario, we would like to confirm that the problematic setup is exactly as it was when the error occurred and wasn't altered before posting? Was it part of some bigger setup or the content of value `caching_ttl` was provided from resource, not variable? 

Thanks,
Michal

**Comment by SinghPavan** [comment]
The value provided from tfvars files.

**Comment by mgwoj** [comment]
And only those two resources and one datasource were used in the scenario?

**Comment by SinghPavan** [comment]
I gave all files to @FilipAntkowiak, you can check with him.

**Comment by mgwoj** [comment]
thank you

**Comment by lkowalsk-akamai-com** [comment]
Hi @SinghPavan , we released some changes in this area. Can you please check if this error is still occurring for you?
