### ISSUE TITLE
Add Version Notes 

### ISSUE THREAD

**Issue by jazzista88** [akamai/terraform-provider-akamai#55]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
0.12.8.

I was wondering if there is any way to add a Version Notes related to the current property i'm going to change.

**Comment by jazzista88** [comment]
Any news on this?
I would add another question to this topic, is there a way to create a new version from an existing property?

**Comment by ynohat** [comment]
I'd suggest including in this scope:

* property notes
* version notes (as OP requested)
* activation notes

**Comment by ynohat** [comment]
Also see #166
