### ISSUE TITLE
Property activation fail

### ISSUE THREAD

**Issue by chouraamine** [akamai/terraform-provider-akamai#553]
Hi there,

The activation goes through (I can see it on the UI) but the Terraform code returns an error after a few minutes
module.akamai-configuration.akamai_property_activation.production: Still creating... [3m0s elapsed]

### Terraform and Akamai Terraform Provider Versions
Terraform version = 1.4 
Akamai version = 5.4.0

### Affected Resource(s)
- akamai_property_activation

### Actual Behavior
<img width="517" alt="image" src="https://github.com/akamai/terraform-provider-akamai/assets/115227803/62c52484-d7d3-4dc4-9169-2a5191178073">

### Steps to Reproduce
It doesn't happen often

**Comment by mgwoj** [comment]
Please migrate to version `5.5.0` (or newer) as this issue was fixed there:
```
* Improved error handling and added retries in `akamai_property_activation` resource
```

**Comment by chouraamine** [comment]
Hi @mgwoj, 

after updating the property using akamai_property_rules_template I have this issue :

<img width="479" alt="image" src="https://github.com/akamai/terraform-provider-akamai/assets/115227803/643a5c91-8a5c-426b-a869-f30826ad151c">

using this version : 6.1.0

Any idea please ? 
_Same issue https://github.com/akamai/terraform-provider-akamai/issues/549_

**Comment by ckulinsk** [comment]
Hello @chouraamine,

After investigation it seems that your problem might be different than #549, could you please provide as much details regarding your scenario so we can reproduce your issue?
What is your configuration and what are the relations between resources?
What is being changed during terraform apply?

Best regards,
Cyryl

**Comment by mgwoj** [comment]
Hello @chouraamine ,

If possible, please start separate issue for this particular problem.

Thanks,
Michal

**Comment by lkowalsk-akamai-com** [comment]
Hi @chouraamine ,

This issue should be resolved with addition of retries for property activations in 5.6.0 release: https://github.com/akamai/terraform-provider-akamai/releases/tag/v5.6.0

Let me close the ticket now. Please report new one if some issues are still occurring.
