### ISSUE TITLE
All Akamai documentation on registry.terraform.io redirect to techdocs.akamai.com

### ISSUE THREAD

**Issue by chouraamine** [akamai/terraform-provider-akamai#555]
Hi, 

All links under the Akamai provider on registry.terraform.io redirect to techdocs.akamai.com witch not ergonomic for terraform users ...
Can we do something about this ? 

Thanks,

**Comment by lkowalsk-akamai-com** [comment]
We are not planning to move the documentation back to Terraform Registry at this point. We will work on maitaining and making even more developer frieldy the documenation hosted on [techdocs.akami.com](https://techdocs.akamai.com/)
