### ISSUE TITLE
DXE-3949 Sensitive data disclosed when running terraform plan

### ISSUE THREAD

**Issue by rensvanleeuwen** [akamai/terraform-provider-akamai#556]
There does not seem to be a way to prevent disclosing secrets from output of running `terraform plan`.

Disclaimer: I've worked with Terraform for a day, so I'm probably using some wrong terminology here and there.

I am in the process of capturing my property configuration using Terraform. Many of the properties make use of secrets, such as API keys. These are configured as `PMUSER_API_KEY` variables in the property.

As a store for the secrets, I'm using AWS Secrets Manager. I made a module in the project that retrieves the secrets and then uses it to supply the value in the `akamai_property_rules_builder`. The module that retrieves the secrets exposes them as follows:

```
output "secrets_map" {
  value     = local.secrets_map
  sensitive = true
}
```

The property rules are defined as follows:

```
data "akamai_property_rules_builder" "my_property" {
  rules_v2024_02_12 {
    name      = "default"
    is_secure = true
    comments  = "The Default Rule template contains all the necessary and recommended behaviors. Rules are evaluated from top to bottom and the last matching rule wins."
    variable {
      name        = "PMUSER_API_KEY"
      description = ""
      value       = module.secrets.secrets_map["my_secret_value"]
      hidden      = false
      sensitive   = true
    }
  }
  # All the other stuff here ..
}
```

When I run a `terraform plan`, it shows the secret in plain text in the console. After reading [this](https://github.com/akamai/terraform-provider-akamai/blob/86da2eeee4d9b78e57aaa78b5135b1d216bd1309/pkg/providers/property/data_akamai_property_rules_builder.go#L20) and [this](https://github.com/akamai/terraform-provider-akamai/blob/86da2eeee4d9b78e57aaa78b5135b1d216bd1309/pkg/providers/property/data_akamai_property_rules_builder.go#L64), it kinda makes sense where this goes wrong.

I see that the notion of `sensitive = true` is lost, and it then is just a string.

Given that working with secrets for property configuration using Terraform look like a common practice, I was wondering if I'm using the right way to do what I want. And if not: could this be considered a sensible feature request?

### Terraform and Akamai Terraform Provider Versions

```
❯ terraform -v
Terraform v1.8.4
on darwin_arm64
+ provider registry.terraform.io/akamai/akamai v6.1.0
+ provider registry.terraform.io/hashicorp/aws v5.51.1
```

### Affected Resource(s)

- Property rules
- Most likely a lot of other resource types managed by the Akamai provider as well?

### Expected Behavior

When running a `terraform plan`, data is marked `sensitive = true` should not be visible in the output of the plan.

### Actual Behavior

Secrets are disclosed in the output.

**Comment by lsadlon** [comment]
Hi @rensvanleeuwen 

Thanks for reporting this issue. We will go back to you after investigation.

BR,
Lukasz

**Comment by wzagrajcz** [comment]
Hello @rensvanleeuwen 

The sensitive is lost due to usage of json which we cannot abandon (e.g. due to Terraform limit for recursion in schema and rules schema size) so we cannot add a rules implementation that will support sensitive value natively.

I can propose a workaround that hopefully will be satisfactory for you: defining an [include](https://techdocs.akamai.com/terraform/docs/pm-rc-include) that will contain all rules/variables/data that needs to be sensitive, use [hashicorp's sensitive function](https://developer.hashicorp.com/terraform/language/functions/sensitive) to sanitize that include's data (sanitizing whole json) and add this include to your property.
It's definitely not perfect, but that's the best that we can do or recommend.

Hope that helps

Wojciech

**Comment by rensvanleeuwen** [comment]
Hi @wzagrajcz, sorry for the delay. I was on holiday.

I am by no means a Terraform, nor an Akamai expert, so take the following with a grain of salt (disclaimer :))

It feels like Akamai has chosen to use a type-unsafe mechanism to import rules for property configuration. Once you let go of explicitly backing all rules with an associated golang implementation, then (indeed) you lose the notion of what is marked as sensitive.

So, as an alternative, all the rules could also have proper golang definitions and then it would work?

Or is this an approach that'll hit a limit in the depth of the tree that can be built with Terraform? I'm trying to understand what you're saying.

In our case, we had issues that the secrets were leaked in CI pipelines. We worked around it by running the plan in a shell script that uses `sed` to replace the secrets on the fly instead. It is a poor-man's solution, but good enough for what we needed to achieve.

Still my question remains: is it hypothetically possible to achieve this by backing the rules with 'proper' definitions instead of parsing everything into a massive JSON tree?

**Comment by wzagrajcz** [comment]
Hello @rensvanleeuwen 
Creating a structure in golang should not be a problem. Problem is with "child" (nested) rules that are possible in rules.
In nutshell, the rules allow to include other rules. And those to include other rules etc. etc.
So the end rules can look like:
```
{
  "rules": {
    "name": "default",
    "children": [
      {
        "rules": {
          "name": "child1",
          "children": [
            {
              "rules": {
                "name": "child2",
                "children": [
                  ...
                ]
              }
            }
          ]
        }
      }
    ]
  }
}
```
The schema for one level of nesting is quite big already. To handle the first level of nesting, the schema would have to double in size. Actual rules can be very nested so the schema would have to grown a lot. Usage of JSON enables to go around this issue by assuming that each level provides it's own rules which are later treated as JSON (in case that rules are a child).

That's why in previous post I suggested to consider includes as they are not "embedded" into whole rules but added by ID. And having those smaller rules (in includes) may be possible to hide using the "sensitive" method without loosing readability.

Hope that cleared something.

Best regards,
Wojciech

**Comment by rensvanleeuwen** [comment]
Hi @lkowalsk-akamai-com, sorry to bring this up again.

I'm still not sure if I follow what you're saying. The trick with defining the domain for this is to break it down in smaller chunks and reference to reusable components and use recursive definitions to describe it fully.

https://json-schema.org/understanding-json-schema/structuring#recursion has a good example of the case that you described in your last comment?

```
{
  "type": "object",
  "properties": {
    "name": { "type": "string" },
    "children": {
      "type": "array",
      "items": { "$ref": "#" }
    }
  }
}
```

This makes it possible to build something like this:

```
{
  "name": "Elizabeth",
  "children": [
    {
      "name": "Charles",
      "children": [
        {
          "name": "William",
          "children": [
            { "name": "George" },
            { "name": "Charlotte" }
          ]
        },
        {
          "name": "Harry"
        }
      ]
    }
  ]
}
```

**Comment by wzagrajcz** [comment]
Hello @rensvanleeuwen 

The idea suggested above is to use a concept of Includes. In a nutshell it's a way of separating a rule tree into smaller chunks ([general TechDoc page about includes](https://techdocs.akamai.com/property-mgr/docs/includes-overview)). The idea is to extract the behaviour that needs to be sensitive into include, define include that will be sensitive and later add "include" behaviour to rules.

For high level example let's assume that you have such rules and you wish to have beh2 sensitive:
```
resource "akamai_property" "prp" {
   rules = data.akamai_property_rules_builder.rules.json
}

data "akamai_property_rules_builder" "rules" {
  rules_v2025_01_13 {
    behavior {
       beh1 {
       }
     }
    behavior {
       beh2 {
       }
     }
    behavior {
       beh3 {
       }
     }
  }
}
```
Would become:
```
resource "akamai_property" "prp" {
   rules = data.akamai_property_rules_builder.rules.json
}

resource "akamai_property_include" "beh2_include" {
   rules = sensitive(data.akamai_property_rules_builder.beh2_include_rules.json)
}

// resource "akamai_property_include_activation" "include_beh2_activation_staging"

data "akamai_property_rules_builder" "rules" {
  rules_v2025_01_13 {
    behavior {
       beh1 {
       }
     }
    behavior {
       include {
          id = akamai_property_include.beh2_include.id
       }
     }
    behavior {
       beh3 {
       }
     }
  }

data "akamai_property_rules_builder" "beh2_include_rules" {
  rules_v2025_01_13 {
    behavior {
       beh2 {
       }
     }
  }
}
}
```
This way the behaviour that should be sensitive is not shown with sensitive details on plan.

Hope that helped

Best regards,
Wojciech
