### ISSUE TITLE
akamai_appsec_version_notes is not working (version note on appsec)

### ISSUE THREAD

**Issue by chouraamine** [akamai/terraform-provider-akamai#558]
Hi, 

Issue : Error message while adding a version note on the latest version (not yet activated)

### Terraform and Akamai Terraform Provider Versions
**terraform version 1.5.7**
**Akamai provider versions tested : 6.2.0, 5.3.0 ,4.0.0, 3.5.0**
**Terraform plan work properly**

### Panic Output
akamai_appsec_version_notes.version_notes_api: Creating...
╷
│ Error: Plugin did not respond
│
│   with akamai_appsec_version_notes.version_notes_api,
│   on main.tf line 89, in resource "akamai_appsec_version_notes" "version_notes_api":
│   89: resource "akamai_appsec_version_notes" "version_notes_api" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.        
╵

Stack trace from the terraform-provider-akamai_v3.5.0.exe plugin:

panic: unaligned 64-bit atomic operation

goroutine 48 [running]:
runtime/internal/atomic.panicUnaligned()
        runtime/internal/atomic/unaligned.go:8 +0x2d
runtime/internal/atomic.Xadd64(0x132c8fac, 0x1)
        runtime/internal/atomic/atomic_386.s:125 +0x11
github.com/allegro/bigcache/v2.(*cacheShard).miss(...)
        github.com/allegro/bigcache/v2@v2.2.5/shard.go:398
github.com/allegro/bigcache/v2.(*cacheShard).getWrappedEntry(0x132c8f20, 0xbdf45bc69b527e08)
        github.com/allegro/bigcache/v2@v2.2.5/shard.go:88 +0x10e
github.com/allegro/bigcache/v2.(*cacheShard).get(0x132c8f20, {0x12e829f0, 0x25}, 0xbdf45bc69b527e08)
        github.com/allegro/bigcache/v2@v2.2.5/shard.go:64 +0x4a
github.com/allegro/bigcache/v2.(*BigCache).Get(0x12d2a980, {0x12e829f0, 0x25})
        github.com/allegro/bigcache/v2@v2.2.5/bigcache.go:117 +0x76
github.com/akamai/terraform-provider-akamai/v3/pkg/akamai.(*meta).CacheGet(0x28a7e9a0, {0x1258adc, 0x12e89650}, {0x13a706e0, 0x1e}, {0xeaf280, 0x28a794c0})       
        github.com/akamai/terraform-provider-akamai/v3/pkg/akamai/meta.go:91 +0x16b
github.com/akamai/terraform-provider-akamai/v3/pkg/providers/appsec.getModifiableConfigVersion({0x1257fa0, 0x28a79140}, 0x100, {0x105150a, 0x10}, {0xfc0f60, 0x28a7e9a0})
        github.com/akamai/terraform-provider-akamai/v3/pkg/providers/appsec/config_versions.go:46 +0x223
github.com/akamai/terraform-provider-akamai/v3/pkg/providers/appsec.resourceVersionNotesCreate({0x1257fa0, 0x28a79140}, 0x292a0b40, {0xfc0f60, 0x28a7e9a0})       
        github.com/akamai/terraform-provider-akamai/v3/pkg/providers/appsec/resource_akamai_appsec_version_notes.go:62 +0x1d8
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x13014af0, {0x1257fc0, 0x28a6d938}, 0x292a0b40, {0xfc0f60, 0x28a7e9a0})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/resource.go:707 +0x11f
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0x13014af0, {0x1257fc0, 0x28a6d938}, 0x292947e0, 0x292a0a50, {0xfc0f60, 0x28a7e9a0}) 
google.golang.org/grpc.(*Server).handleStream(0x12f4e7e0, {0x1259d24, 0x12f4e900}, 0x29316fa0, 0x0)
        google.golang.org/grpc@v1.50.1/server.go:1713 +0xa17
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.50.1/server.go:965 +0xb1
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.50.1/server.go:963 +0x25f

Error: The terraform-provider-akamai_v3.5.0.exe plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

**Comment by mgwoj** [comment]
It is caused by https://github.com/allegro/bigcache/issues/368

**Comment by lkowalsk-akamai-com** [comment]
Hi @chouraamine, this issue is casued by underlying library not supporting 32 bit systems. We are not planning to support such systems as well.
