### ISSUE TITLE
Create edge hostname 400 error Bad Request Request parameter Slot Number

### ISSUE THREAD

**Issue by mikecarrington** [akamai/terraform-provider-akamai#56]
Hi
Have an issue with creating Enhanced TLS edge hostname.
When executing simple terraform script to create a new edge hostname, the process errors:
```
Error: API Error: 400 400 Bad Request Request parameter Slot Number of type numeric is missing More Info /hapi/problems/missing-required-param

  on main.tf line 28, in resource "akamai_edge_hostname" "edgename":
  28: resource "akamai_edge_hostname" "edgename" {
```

### Terraform Version
```
Terraform version: 0.12.7  
Go runtime version: go1.12.9
terraform-provider-akamai_v0.1.3_x4
```

### Affected Resource(s)
- akamai_edge_hostname

### Terraform Configuration Files
```hcl
# Configure the Akamai Provider
provider "akamai" {
    property {
      host = "${var.akamai_host}"
      access_token = "${var.akamai_access_token}"
      client_token = "${var.akamai_client_token}"
      client_secret = "${var.akamai_client_secret}"
    }
}


# Get Contract I
Ddata "akamai_contract" "default" {
  group = "Company Name"
}

# Get Group ID for group 'QA'
data "akamai_group" "default" {
  name = "test"
}

# Create Edge Hostname
resource "akamai_edge_hostname" "edgename" {
  group         = "${data.akamai_group.default.id}"
  contract      = "${data.akamai_contract.default.id}"
  product       = "prd_Progressive_Media"
  edge_hostname = "123.example.net.edgekey.net"
  certificate   = 12345
}

```

### Debug Output
https://gist.github.com/mikecarrington/e5cf6dddc7bc4d1935f4230137a2a63c

### Expected Behavior
Edge hostname should have been created.

### Actual Behavior
400 error from the Akamai API (see above).

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
Looking at the debug I can see the JSON includes `SlotNumber:0`
```
...
DomainSuffix:"edgekey.net", 
CertEnrollmentId:12345, 
SlotNumber:0, 
SecureNetwork:"ENHANCED_TLS", 
Status:"", 
Secure:false, 
...
```
Looking at the API reference for Enhanced TLS POST;
https://developer.akamai.com/api/core_features/property_manager/v1.html#postedgehostnames
The 'options' needs to include SlotNumber however theres no (obvious) way to set that value in the resource.

```
{
    "productId": "prd_PPP",
    "domainPrefix": "custom.example.com",
    "domainSuffix": "edgesuite.net",
    "secure": true,
    "ipVersionBehavior": "IPV4",
    "slotNumber": 12345
}
```
Feels like the definition of an argument is missing?

Any advice?

Thanks
Mike

**Comment by mikecarrington** [comment]
Trying this in python using the `akamai.edgegrid` library the options payload requires both SlotNumber and certEnrollmentId, the latter is getting set as part of the provider, but SlotNumber is not.

**Comment by Taik** [comment]
We're getting the same issue when creating an `ENHANCED_TLS` edge host name (domainSuffix being `edgekey.net`).

Is the documentation incorrect or needs updating? https://developer.akamai.com/api/core_features/property_manager/v1.html#enhancedtls

**Comment by Taik** [comment]
> 
> Looking at the debug I can see the JSON includes `SlotNumber:0`

Just to clarify, this actually gets omitted from the serialized JSON data because of the [`omitempty` option](https://github.com/akamai/AkamaiOPEN-edgegrid-golang/blob/f85d9fba0c117ecabe725f3bf31a45ddfb182d85/papi-v1/edgehostnames.go#L152). I'm thinking the API has changed and now requires `SlotNumber` to be set.

**Comment by ghost** [comment]
We have identified the root cause for this issue and this is fixed by my colleague Ian and put in PR: https://github.com/terraform-providers/terraform-provider-akamai/pull/59

Both CertEnrollmentId and SlotNumber will now be set for Enhanced TLS configurations.

**Comment by jhoekstra** [comment]
Do you have an ETA for when this enters in a release used by Terraform?
Running into this issue when onboarding a new customer.

**Comment by martinstibbe** [comment]
Released https://releases.hashicorp.com/terraform-provider-akamai/0.1.4/ feel free to test
