### ISSUE TITLE
Unable to Create Edge Hostname Property for Type: DEFAULT certificates

### ISSUE THREAD

**Issue by sap-erp** [akamai/terraform-provider-akamai#563]
### Terraform and Akamai Terraform Provider Versions
Terraform v1.5.7
on darwin_arm64
+ provider registry.terraform.io/akamai/akamai v6.2.0

### Affected Resource(s)
- akamai_edge_hostname
- akamai_property

### Expected Behavior
When manually creating a Hostname Property the DEFAULT certificate type in the Akamai console, an Edge Hostname is properly created and associated.  When trying to do the same with Terraform resources, the expected behavior is that Terraform does exactly the same thing that manually creating does.  This is not the case, unfortunately.

### Actual Behavior
When creating the following resources:
```
resource "akamai_property" "btp-ias" {
  name        = "btp-ias"
  contract_id = var.contract_id
  group_id    = var.group_id
  product_id  = "prd_Fresca"
  hostnames {
    cname_from             = var.delivery.cname_from_1
    cname_to               = var.delivery.edge_hostname
    cert_provisioning_type = "DEFAULT"
  }
  hostnames {
    cname_from             = var.delivery.cname_from_2
    cname_to               = var.delivery.edge_hostname
    cert_provisioning_type = "DEFAULT"
  }
  rule_format = data.akamai_property_rules_builder.btp-ias_rule_default.rule_format
  rules       = data.akamai_property_rules_builder.btp-ias_rule_default.json
}

resource "akamai_property_activation" "btp-ias-staging" {
  property_id                    = akamai_property.btp-ias.id
  contact                        = [var.delivery.contact_email]
  version                        = var.activate_latest_on_staging ? akamai_property.btp-ias.latest_version : akamai_property.btp-ias.staging_version
  network                        = "STAGING"
  auto_acknowledge_rule_warnings = true
}
```
The property is created and activated, but no Edge Hostname is created when Staging is activated (which it does in the console).

So I then tried to create an edge hostname property and associate the edge hostname to the cname_to of the hostname property
```
resource "akamai_edge_hostname" "btp-ias" {
contract_id   = var.contract_id
group_id      = var.group_id
product_id  = "prd_Fresca"
ip_behavior   = "IPV6_COMPLIANCE"
edge_hostname = var.delivery.edge_hostname
}

resource "akamai_property" "btp-ias" {
  name        = "btp-ias"
  contract_id = var.contract_id
  group_id    = var.group_id
  product_id  = "prd_Fresca"
  hostnames {
    cname_from             = var.delivery.cname_from_1
    cname_to               = akamai_edge_hostname.btp-ias.edge_hostname
    cert_provisioning_type = "DEFAULT"
  }
  hostnames {
    cname_from             = var.delivery.cname_from_2
    cname_to               = vakamai_edge_hostname.btp-ias.edge_hostname
    cert_provisioning_type = "DEFAULT"
  }
  rule_format = data.akamai_property_rules_builder.btp-ias_rule_default.rule_format
  rules       = data.akamai_property_rules_builder.btp-ias_rule_default.json
}
```
I am met with errors when trying to do so:
```
│ Error: a certificate enrollment ID is required for Enhanced TLS edge hostnames with 'edgekey.net' suffix
│ 
│   with akamai_edge_hostname.btp-ias,
│   on property.tf line 1, in resource "akamai_edge_hostname" "btp-ias":
│    1: resource "akamai_edge_hostname" "btp-ias" {
```

### Steps to Reproduce
Run terraform apply on the resources above

### Important Factoids
In the GitHub examples, I cannot find any reference to the enrollment ID for the "akamai_edge_hostname" property.

### References
Example documentation:
https://github.com/akamai/examples-terraform/blob/fe5396880eb802640c78702c6dd04f4c35aac704/2024%20%7C%20App%20%26%20API%20Protector%20%2B%20DSA%20%2B%20Edge%20DNS%20%2B%20Secure%20By%20Default%20template%20%7C%20Compatible%20with%20Akamai%20Terraform%20v6.0.0%20and%20up/1.%20DSA%20%2B%20Edge%20DNS%20%2B%20Secure%20By%20Default%20workflow/akamai-property/property.tf

**Comment by lsadlon** [comment]
Hi @sap-erp 

Thanks for reporting this issue. You need to specify `certificate` in `akamai_edge_hostname` resource. Something like that:

```
resource "akamai_edge_hostname" "btp-ias" {
  contract_id   = var.contract_id
  group_id      = var.group_id
  product_id    = "prd_Fresca"
  ip_behavior   = "IPV6_COMPLIANCE"
  edge_hostname = var.delivery.edge_hostname
  certificate   = 123456
}
```

This `certificate` is `enrollmentID`, you can get `enrollmentID` for example listing yours enrollment with https://techdocs.akamai.com/cps/reference/get-enrollments and look for one that you want to use.

Let us know it that help.

BR,
Lukasz

**Comment by sap-erp** [comment]
That worked, @lsadlon.  Quick question- I don't see anywhere in the repo where the certificate option is referenced, am I missing it?  I'd like to document it internally so no one else runs into the same issue. Thanks!

**Comment by lsadlon** [comment]
Hi @sap-erp,

There is information under tech doc https://techdocs.akamai.com/terraform/docs/pm-rc-edge-hostname. Is it what you are looking for?

BR,
Lukasz

**Comment by sap-erp** [comment]
That works @lsadlon, thanks.
