### ISSUE TITLE
DXISSUE-3037 Does support data source "akamai_include_activation"

### ISSUE THREAD

**Issue by leonardommello** [akamai/terraform-provider-akamai#566]
Hello everyone!
I am testing the Akamai provider during the implementation of the module for the company I work for. While testing and looking at the provider documentation, I noticed an error in one of the provider usage examples. While trying to retrieve the activation IDs of the include, I got the error below.

### Terraform and Akamai Terraform Provider Versions

```sh
Terraform v1.9.0
on windows_amd64
+ provider registry.terraform.io/akamai/akamai v6.2.0
```
Or
```sh
OpenTofu v1.7.2
on windows_amd64
+ provider registry.opentofu.org/akamai/akamai v6.2.0
```

### Affected Resource(s)
data "akamai_include_activation" [LINK TO DOCS](https://techdocs.akamai.com/terraform/docs/include-activation)

### Terraform Configuration Files
```hcl
# Example configuration based at docs.akamai.com
data "akamai_include_activation" "my_example" {
  contract_id = "ctr_1111" 
  group_id    = "grp_1111"
  include_id  = "inc_1111"
  network     = "PRODUCTION"
}

output "my_example" {
  value = data.akamai_include_activation.my_example
}
```

### Expected Behavior
Get activation details for an include on the provided network.

### Actual Behavior
```sh
│ Error: Invalid data source
│
│   on common-infrastructure\terraform-akamai-site\main.tf line 20, in data "akamai_include_activation" "my_example":
│   20: data "akamai_include_activation" "my_example" {
│
│ The provider akamai/akamai does not support data source "akamai_include_activation".
```
### Steps to Reproduce
1. `terraform apply`

### Important Factoids
No

**Comment by lsadlon** [comment]
Hi @leonardommello 

Look like you use incorrect name. Data source is called `akamai_property_include_activation`. In your code `_property_` part is missing.

BR,
Lukasz

**Comment by lsadlon** [comment]
Hi @leonardommello 

I also create internal ticket to fix documentation. Thanks for reporting it.

BR,
Lukasz

**Comment by leonardommello** [comment]
Thanks a lot! I will open a ticket to for fix the documentation.
