### ISSUE TITLE
Unable to Delete Edge Hostname Property Created in Terraform

### ISSUE THREAD

**Issue by sap-erp** [akamai/terraform-provider-akamai#568]
### Terraform and Akamai Terraform Provider Versions
Terraform v1.5.7
on darwin_arm64

provider registry.terraform.io/akamai/akamai v6.2.0

### Affected Resource(s)
- akamai_edge_hostname

### Expected Behavior
Running `terraform apply` builds the Edge Hostname as expected.  When running `terraform destroy`, it is expected the Edge Hostname will be deleted.  

### Actual Behavior
When running terraform destroy, the Edge Hostname is NOT deleted.

### Steps to Reproduce
Run `terraform destroy`

### Code for reference
```
terraform {
  required_providers {
    akamai = {
      source  = "akamai/akamai"
      version = "6.1"
    }
  }
  required_version = ">= 1.0"
}

provider "akamai" {
  edgerc         = "~/.edgerc"
  config_section = "default"
  request_limit  = 3
}

variable "contract_id" {
  type    = string
  default = "ctr_V-XXXXXX"
}

variable "group_id" {
  type    = string
  default = "XXXXXX"
}

variable "delivery" {
  type    = object({
    edge_hostname = string
  })
  default = {
    edge_hostname = "xxx.xxx.edgekey.net"
    }
}

resource "akamai_edge_hostname" "ehn" {
contract_id   = var.contract_id
group_id      = var.group_id
product_id  = "prd_Fresca"
ip_behavior   = "IPV6_COMPLIANCE"
edge_hostname = var.delivery.edge_hostname
certificate   = XXXXXX #TODO: Set as variable
}
```

**Comment by lkowalsk-akamai-com** [comment]
Hi, 
This is a duplicate. We will give updates under this issue: https://github.com/akamai/terraform-provider-akamai/issues/504
