### ISSUE TITLE
CP Code Created with Terraform Is Not Destroyed By Terraform

### ISSUE THREAD

**Issue by sap-erp** [akamai/terraform-provider-akamai#569]
Hello, hoping you can help here.  

### Terraform and Akamai Terraform Provider Versions
Terraform v1.5.7
on darwin_arm64
provider registry.terraform.io/akamai/akamai v6.2.0

### Affected Resource(s)
- akamai_cp_code

### Expected Behavior
When running terraform apply, the CP Code is created as expected.  However, when running terraform destroy, the output says it has been destroyed, but it has not been destroyed.

### Actual Behavior
```
Terraform will perform the following actions:

  # akamai_cp_code.test_cp_code will be destroyed
  - resource "akamai_cp_code" "test_cp_code" {
      - contract_id = "ctr_X-XXXXX" -> null
      - group_id    = "grp_xxxxx" -> null
      - id          = "1xxxxxx" -> null
      - name        = "cp-code-test" -> null
      - product_id  = "prd_Fresca" -> null
    }

Plan: 0 to add, 0 to change, 1 to destroy.

Do you really want to destroy all resources?
  Terraform will destroy all your managed infrastructure, as shown above.
  There is no undo. Only 'yes' will be accepted to confirm.

  Enter a value: yes

akamai_cp_code.test_cp_code: Destroying... [id=1669821]
akamai_cp_code.test_cp_code: Destruction complete after 0s

Destroy complete! Resources: 1 destroyed.
```

While the console states the resource was destroyed, it is still in my Akamai account.

### Steps to Reproduce
1. `terraform apply`
2. `terraform destroy`

**Comment by psnoch-akamai** [comment]
Hello @sap-erp ,

Thank you for rising this topic. Delating CP Code is not allowed. You can find all API methods on our techdocs page
https://techdocs.akamai.com/property-mgr/reference/post-cpcodes
With terraform you are able to destroy your local state related to _resource "akamai_cp_code"_.

Best regards,
Pawel
