### ISSUE TITLE
Multiple MX records creation issue

### ISSUE THREAD

**Issue by TristanBaoui** [akamai/terraform-provider-akamai#57]
### Terraform Version
Terraform v0.12.7
+ provider.akamai v0.1.3

### Affected Resource(s)
- akamai_dns_record

### Terraform Configuration Files
```hcl
resource "akamai_dns_record" "mx_example_com_1" {
	zone = local.zone
	name = "mx.example.com"
	recordtype = "MX"
	active = true
	ttl = 300
	priority = 10
	target = [
		"mx1.example.com."
	]
	depends_on = [akamai_dns_zone.example_com]
}

resource "akamai_dns_record" "mx_example_com_2" {
	zone = local.zone
	name = "mx.example.com"
	recordtype = "MX"
	active = true
	ttl = 300
	priority = 20
	target = [
		"mx2.example.com."
	]
	depends_on = [akamai_dns_zone.example_com, akamai_dns_record.mx_example_com_1]
}
```

### Debug Output
https://gist.github.com/TristanBaoui/a05bda4c18f1d5690b522fd5b6155585

### Expected Behavior
MX records should both be created and output should be OK

### Actual Behavior
MX records are created BUT terraform state is not up to date as it think creation of mx2 failed.
Terraform output :

```
Error: Provider produced inconsistent result after apply

When applying changes to akamai_dns_record.mx_example_com_2, provider "akamai"
produced an unexpected new value for was present, but now absent.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.
```

In func resourceDNSRecordRead (https://github.com/terraform-providers/terraform-provider-akamai/blob/master/akamai/resource_akamai_dns_record.go) :
    line 433, strings are sorted -> "10 mx1.example.com. 20 mx2.example.com."
    lines 411 412, no sort of strings -> "20 mx2.example.com. 10 mx1.example.com."
    
SHA is different while the record was properly created (or even exists before the apply function)

### Steps to Reproduce
`terraform apply`

**Comment by martinstibbe** [comment]
Fixed in AT-25
Also a more compact form of your stacked MX records would work here as well

resource "akamai_dns_record" "mx_record" {
    zone = "${local.zone}"
    name = "akavdev.net"
    recordtype =  "MX"
    active = true
    ttl =  300
    target = ["smtp-0.akavdev.net.","smtp-1.akavdev.net.","smtp-3.akavdev.net."]
    priority = 10
    priority_increment = 10
}
