### ISSUE TITLE
DXISSUE-3061 ip_behavior in resource "akamai_edge_hostname" 

### ISSUE THREAD

**Issue by rolmo** [akamai/terraform-provider-akamai#581]
Hi there,

your documentation for `akamai_edge_hostname` (https://techdocs.akamai.com/terraform/docs/pm-rc-edge-hostname) (for v4.6) suggest three possible values for `ip_behavior`

- IPV4
- IPV6
- IPV6_IPV4_DUALSTACK

But `IPV6_IPV4_DUALSTACK` gives an error, I must use `IPV6_COMPLIANCE`.

### Terraform and Akamai Terraform Provider Versions
- Terraform v1.9.5 on darwin_amd64
- v4.6

### Affected Resource(s)
- `akamai_edge_hostname`

### Terraform Configuration Files

This fails:
```hcl
resource "akamai_edge_hostname" "edition-issues" {
  contract_id   = var.contract_id
  group_id      = var.group_id
  product_id    = var.product.product_id
  ip_behavior   = "IPV6_IPV4_DUALSTACK"
  edge_hostname = local.edge_hostname
}
```

This works:
```hcl
resource "akamai_edge_hostname" "edition-issues" {
  contract_id   = var.contract_id
  group_id      = var.group_id
  product_id    = var.product.product_id
  ip_behavior   = "IPV6_COMPLIANCE"
  edge_hostname = local.edge_hostname
}
```

### Error Output

With `IPV6_IPV4_DUALSTACK`, I get this error:
```
Error: creating edge hostname: struct validation:
IPVersionBehavior: must be a valid value
```

**Comment by lsadlon** [comment]
Hi @rolmo ,

Thanks for reporting this issue. I will create internal ticket to fix our documentation.

BR,
Lukasz

**Comment by lkowalsk-akamai-com** [comment]
The documentation was updated.
