### ISSUE TITLE
Please provide Terraform support for NetStorage.

### ISSUE THREAD

**Issue by eddgrant** [akamai/terraform-provider-akamai#582]
Hi folks,

I note that there is currently no support for managing NetStorage using the Akamai Terraform provider. Do you have any plans to add this?

Many thanks!

**Comment by lkowalsk-akamai-com** [comment]
Hi @eddgrant , can you share with us what kind of use cases you have in mind?

**Comment by eddgrant** [comment]
Hi @lkowalsk-akamai-com, sure thing.

The main use case is as follows:

I have some assets that I want to use for a visitor prioritisation cloudlet waiting room page. I want to manage the Cloudlet, its associated Property and the assets all using Terraform. 

Currently I can manage the Cloudlet and Property via Terraform, but the creation of the NetStorage and the uploading of the assets has to be done through some other means. Ideally I would manage them all via Terraform.

Hope this helps explain. Please feel free to come back with any questions.

**Comment by lkowalsk-akamai-com** [comment]
Hi @eddgrant, thank you for the answer and suggestion, but there are no plans to add NetStorage support in Terraform Provider.

**Comment by glenthomas** [comment]
We would like to automate the provisioning of upload accounts. Is that a use case you could support @lkowalsk-akamai-com?
