### ISSUE TITLE
DXE-4295 EdgeDNS TXT records with semicolons are interpreted in different way then terraform shows in the plan.

### ISSUE THREAD

**Issue by martin-simek-gen** [akamai/terraform-provider-akamai#586]
Hi there,

We have hit a bit problematic behaving of akamai provider for TXT DNS records containing semicolon.
If the manifest contains semicolon `;` the terraform plan show that target of TXT record will be written with semicolon, but akamai provider or API will cut off semicolon and all behind it.   

### Terraform and Akamai Terraform Provider Versions
Akamai provider: the latest release (6.4.0) and all previous one
Terraform: v1.9.7 + v1.7.5
Terragrunt version v0.67.14

### Affected Resource(s)
- akamai_dns_record (TXT record type)

### Terraform Configuration Files
```hcl
resource "akamai_dns_record" "txt" {
  name       = "testingi2.workplace.avast.com"
  recordtype = "TXT"
  ttl        = 300
  target     = [
    "k=DKIM; test",
    "k=DKIM2; test2; test",
    "\"k=DKIM3; test3\"","foo"
  ]
}
```

### Debug Output
this shows terraform plan:
```
# akamai_dns_record.txt["txt3.testingi2.workplace.avast.com"] will be created
+ resource "akamai_dns_record" "txt" {
    + answer_type = (known after apply)
    + dns_name    = (known after apply)
    + id          = (known after apply)
    + name        = "txt3.testingi2.workplace.avast.com"
    + record_sha  = (known after apply)
    + recordtype  = "TXT"
    + serial      = (known after apply)
    + target      = [
        + "k=DKIM; test",
        + "k=DKIM2; test2; test",
        + "\"k=DKIM3; test3\"",
      ]
    + ttl         = 300
    + zone        = "testingi2.workplace.avast.com"
  }
```
DNS answer:
```
dig @akamai.com txt3.testingi2.workplace.avast.com TXT +short
"k=DKIM"
"k=DKIM3; test3"
"k=DKIM2"
```

### Expected Behavior
- terraform should fail with message wrong escape sequence
- terraform should show exact same plan as the final result, target without semicolon
- should be better documented 

### Actual Behavior
The result of added TXT record is without semicolon

**Comment by KonradRajda** [comment]
Hi @martin-simek-gen 

I was able to reproduce this issue and create internal ticket to fix it. We will inform you about progress.

Best regards,
Konrad

**Comment by lkowalsk-akamai-com** [comment]
Hi @martin-simek-gen, truncation of entries after semicolon is done on the API level. In order to have them preserved you need to wrap the entry in additional quotes, like it was done here: "\"k=DKIM3; test3\"". Please add those escaped quotes if you want to use semicolons.

**Comment by martin-simek-gen** [comment]
Thanks for fix.
