### ISSUE TITLE
firstByteTimeout error on property activation module

### ISSUE THREAD

**Issue by michalinka1994** [akamai/terraform-provider-akamai#590]
Hi there,

Hello I am have been provisioning 8 properties at the same time. I have been able to create properties along side with cpcodes, edge hostnames. Some of this properties have activated using automated job but 4 of them are failing. Just wonder why we are receiving this error.

### Terraform and Akamai Terraform Provider Versions
Terraform v1.9.3
Akamai Terraform version 6.4.0

### Affected Resource(s)
N/A

### Terraform Configuration Files
```hcl
# Resource block for staging property activation
resource "akamai_property_activation" "staging_activation" {
  # Iterate over the properties to create staging activations
  for_each = { for p in var.properties : p.name => p }

  property_id = akamai_property.property[each.key].id  # Reference the property ID
  contact     = [var.static_email]  # Use the static email for notifications
  version     = each.value.staging_version  # Use the specified staging version
  network     = "STAGING"  # Set the activation network to staging
  note        = each.value.staging_note  # Add a note for the activation
  auto_acknowledge_rule_warnings = "true"  # Automatically acknowledge rule warnings

  # Define timeouts for the staging activation process
  timeouts {
    default = "1h"  # Set the default timeout to 1 hour
  }
}

# Resource block for production property activation
resource "akamai_property_activation" "production_activation" {
  # Iterate over the properties to create production activations
  for_each = { for p in var.properties : p.name => p }

  property_id = akamai_property.property[each.key].id  # Reference the property ID
  contact     = [var.static_email]  # Use the static email for notifications
  version     = each.value.production_version  # Use the specified production version
  network     = "PRODUCTION"  # Set the activation network to production
  note        = each.value.production_note  # Add a note for the activation
  auto_acknowledge_rule_warnings = "true"  # Automatically acknowledge rule warnings

  # Define timeouts for the production activation process
  timeouts {
    default = "1h"  # Set the default timeout to 1 hour
  }
}
```

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
What should have happened?

Properties should activate. Some have successfully been activated but some are giving an error.

### Actual Behavior
What actually happened?
Error: activation cannot continue due to rule errors: [
│ 	{
│ 		"behavior_name": "",
│ 		"detail": "The First Byte Timeout option on the `Read Timeout` behavior is required.",
│ 		"error_location": "#/rules/children/0/children/1/behaviors/1/options/firstByteTimeout",
│ 		"instance": "",
│ 		"status_code": 0,
│ 		"title": "",
│ 		"type": "https://problems.luna.akamaiapis.net/papi/v0/validation/attribute_required"
│ 	}
│ ]
│ 
│   with module.[Redacted]_[Redacted]_property.akamai_property_activation.staging_activation["[Redacted]"],
│   on properties/modules/property_provisioning/main.tf line [97]([Redacted]#L97), in resource "akamai_property_activation" "staging_activation":
│   97: resource "akamai_property_activation" "staging_activation" {
### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- GH-1234

**Comment by mgwoj** [comment]
Hello @michalinka1994 ,

Your rules are not included, but it looks that behavior `read_timeout` is not properly configured - missing `first_byte_timeout` field.

**Comment by michalinka1994** [comment]
@mgwoj  Thank you i was going through property and noticed that my json doesn't have "firstByteTimeout": "240s" in my terraform config. Thank you
