### ISSUE TITLE
[DXISSUE-3090] How is akamai_iam_role intended to be used?

### ISSUE THREAD

**Issue by eddgrant** [akamai/terraform-provider-akamai#597]
I'm just looking at the docs for the [akamai_iam_role](https://techdocs.akamai.com/terraform/docs/iam-rc-role) Terraform resource. I can't understand how we would use it to specify the permissions that each role has. 
 
It has an attribute called `granted_roles` which is described as _"A set of the roles given to a user by ID."_. The only thing I can think of is that Akamai has a reference list of roles which are numbered by id, which we would then have to reference by their ids?
 
Maybe I'm looking past something extremely obvious, but would be really helpful if the docs could be improved to include a worked example. Thanks!

**Comment by ckulinsk** [comment]
Hello @eddgrant ,

you can use [grantable roles datasource](https://techdocs.akamai.com/terraform/docs/iam-ds-grantable-roles) to get all the available roles to grant to your users that you can include in a new custom role or add to an existing custom role. You can then reference specific role and pass it in attribute, for example

`data "akamai_iam_grantable_roles" "granted_roles" {}` 
`resource "akamai_iam_role" "role" {`
`  depends_on     = [data.akamai_iam_grantable_roles.granted_roles]`
`  name           = var.role_name`
`  description    = "Role description"`
`  granted_roles  = [data.akamai_iam_grantable_roles.granted_roles.grantable_roles[0].granted_role_id]`
`}`

Feel free to ask if you need further help with this case.

Regards,
Cyryl

**Comment by eddgrant** [comment]
Thanks @ckulinsk, that's helpful. It would be great if that information was in the docs, to help folks like myself understand the intended usage. :pray:

**Comment by ckulinsk** [comment]
Thank you for your feedback, its greatly appreciated! I have reported your suggestion and documentation should be updated  with missing information.
