### ISSUE TITLE
New Property Version doesn't result in auto-Activation

### ISSUE THREAD

**Issue by dmcallis1** [akamai/terraform-provider-akamai#60]
### Terraform Version
Terraform v0.12.3
+ provider.akamai v0.1.3
+ provider.template v2.1.2

### Affected Resource(s)
- akamai_property_activation

### Terraform Configuration Files
```hcl
resource "akamai_property" "epic-tf-demo" {
    name    = "epic-tf-demo"
    contact = ["dmcallis@akamai.com"]

    product  = "prd_SPM"
    contract = "${data.akamai_contract.default.id}"
    group    = "${data.akamai_group.default.id}"
    cp_code  = "${data.akamai_cp_code.default.id}"

    rule_format = "v2018-09-12"
    rules       = "${data.template_file.init.rendered}"
    #rules       = templatefile("${path.module}/rules.json", { origin = "${var.origin}" })
    hostnames = {
        "epictf.duncanmcallister.com" = "${akamai_edge_hostname.epic-tf-demo.edge_hostname}"
    }
}

resource "akamai_property_activation" "epic-tf-demo" {
    property = "${akamai_property.epic-tf-demo.id}"
    version = "${akamai_property.epic-tf-demo.version}"
    network = "PRODUCTION"
    contact = ["dmcallis@akamai.com"]
    activate = true 
}
```

### Actual Behavior
When making changes to rule tree ("akamai_property" resource, rules attribute) with the "akamai_property_activation" resource configured as above. The Provider creates a new property version successfully, but NO activation is performed against the new version (even though activate=true and network are clearly specified). Running a second terraform apply triggers the provider to recognize that the activation state has changed (the current activation state is for the previous version) and the property will activate as expected.

### Expected Behavior
Ideally, generating a new property version with `activate = true` activation resource configuration should both create a new property version and activate it in one action.

### Steps to Reproduce
1. Update rules.json resource, plan and apply (provider should successfully create new property version, with updated rules)
2. Run `terraform plan` again - the provider will recognize the new property version is not active, and activate accordingly

**Comment by ghost** [comment]
Seconded, noticed the same behavior and had to commit the -terraform apply- command twice. Once to create a new version, secondly to activate on both Staging and/or Production.

**Comment by martinstibbe** [comment]
Ok this makes sense based on version = "${akamai_property.epic-tf-demo.version}"
This would have rev/version one behind until a refresh/apply so by time activation resource fires up it sees this old version

Activation latest the version is left blank and it searches for latest according to test cases

resource "akamai_property_activation" "property_activation" {
	property = "${akamai_property.property.id}"
	network = "STAGING"
	activate = true
	contact = ["dshafik@akamai.com"]
}
