### ISSUE TITLE
feature request - CPS support

### ISSUE THREAD

**Issue by an774a** [akamai/terraform-provider-akamai#63]
Hello -- please add CPS support ( https://developer.akamai.com/api/core_features/certificate_provisioning_system/v2.html ) to this provider.

Thank you!

**Comment by ghost** [comment]
Thanks for the feedback!

Certificate management on Akamai is a high priority feature to have enabled in the Akamai provider. This is on the roadmap.

**Comment by yonga00** [comment]
Hi.

You said CPS was on the roadmap.

May I know when this will be possible?

It would be better if only the DV-SAN-SNI certificate was applied first.

**Comment by robertolopezlopez** [comment]
Hi @yonga00 ,

Some members of our team are working on CPS support, which will be published soon. Stay tuned.

Kind regards

**Comment by yonga00** [comment]
Thank you for replay.

I am very much looking forward to it.

If only CPS is supported, it seems that our work can be applied more freely and quickly.

Please.

**Comment by lkowalsk-akamai-com** [comment]
Hi @yonga00 
CPS subprovider was added to the provider. You can check the resources here: 
https://registry.terraform.io/providers/akamai/akamai/latest/docs/resources/cps_dv_enrollment
It covers currently DV certificated and SAN modifications.

**Comment by yonga00** [comment]
Hi. 

I checked what you shared.

I will test it and share it with the development team.

Thank you.
