### ISSUE TITLE
feature request - application_security

### ISSUE THREAD

**Issue by an774a** [akamai/terraform-provider-akamai#65]
Hello -- please add appsec support ( https://developer.akamai.com/api/cloud_security/application_security/v1.html ) to this provider.

Thank you!

**Comment by ghost** [comment]
Thanks for the feedback!

Managing security configurations through Terraform is a high priority feature to have enabled in the Akamai provider. This is on the roadmap.

**Comment by zstlaw** [comment]
Some appsec resources were added as part of the 0.11 release.  We are now at 1.0.0.  Please refer https://registry.terraform.io/providers/akamai/akamai/latest/docs/guides/1.0_migration for additional details.
