### ISSUE TITLE
invalid new value

### ISSUE THREAD

**Issue by ManuelDAlvarez** [akamai/terraform-provider-akamai#67]
### Terraform Version
$ terraform -v
Terraform v0.12.2
+ provider.akamai v0.1.2
+ provider.local v1.3.0

### Affected Resource(s)
- Akamai Provider

### Terraform Configuration Files
https://github.com/ManuelDAlvarez/playTerraform

### Debug Output
Error: Provider produced inconsistent final plan

When expanding the plan for akamai_property_activation.terraform-7-activation
to include new values learned so far during apply, provider "akamai" produced
an invalid new value for .version: was cty.NumberIntVal(14), but now
cty.NumberIntVal(15).

This is a bug in the provider, which should be reported in the provider's own
issue tracker.

Error: Provider produced inconsistent final plan

When expanding the plan for akamai_property_activation.terraform-5-activation
to include new values learned so far during apply, provider "akamai" produced
an invalid new value for .version: was cty.NumberIntVal(2), but now
cty.NumberIntVal(3).

This is a bug in the provider, which should be reported in the provider's own
issue tracker.

### Expected Behavior
I set akamai_property_activation.activate to false and ran terraform apply. It should have done nothing, just update state

### Actual Behavior
It returned an error

### Steps to Reproduce
1. Activate the property using the variable activate = true as
`terraform apply -var="akamnetwork=STAGING" -var="activatedirective=true"`
2. Then run the default state where akamai_property_activation.activate is false
`terraform apply`

**Comment by ManuelDAlvarez** [comment]
The full error report

[fullError.txt](https://github.com/terraform-providers/terraform-provider-akamai/files/3764292/fullError.txt)

**Comment by martinstibbe** [comment]
@ManuelDAlvarez We have made some changes in  0.1.4 seems to be related to version being null vs 1 from first activation let me know if issue goes away using version parameter (we need a strategy on how to handle null)

resource "akamai_property_activation" "property_activation" {
	property = "${akamai_property.property.id}"
	network = "STAGING"
	activate = true
	contact = ["martin@akava.io"]
	version = 1
}
