### ISSUE TITLE
terraform import on akamai_dns_record failing

### ISSUE THREAD

**Issue by TristanBaoui** [akamai/terraform-provider-akamai#69]
### Terraform Version
Terraform v0.12.7
+ provider.akamai v0.1.3

### Affected Resource(s)
Please list the resources as a list, for example:
- akamai_dns_record

### Terraform Configuration Files
```hcl
provider "akamai" {
	edgerc = "~/.edgerc"
	property_section = "papi"
	dns_section = "dns"
}

resource "akamai_dns_zone" "example_fr" {

}

resource "akamai_dns_record" "www_example_fr" {
  zone = "example.fr"
	name = "www.example.fr"
	recordtype = "TXT"
	active = true
	ttl = 7200
	target = "test record"
}
```

### Debug Output
https://gist.github.com/TristanBaoui/f4abb974eabc4b8c8c9034cb98b3b305

### Expected Behavior
The record import should have filled the terraform state

### Actual Behavior
It just doesn't work

**Comment by edglynes** [comment]
In progress. Zone as well.

**Comment by xingxing** [comment]
> In progress. Zone as well.

@edglynes 
Any progress  on this feature ?

**Comment by edglynes** [comment]
yes. targeting the next provider release. Are you a current Akamai customer? I'm looking for beta/evaluation feedback. If so, which company are you with and who is your support/sales contact?

**Comment by xingxing** [comment]
> yes. targeting the next provider release. Are you a current Akamai customer? I'm looking for beta/evaluation feedback. If so, which company are you with and who is your support/sales contact?

I am servicing for  BigONE, and yep, we are a current Akamai customer. Our support engineer is Eric Yan < myan@akamai.com>. We are interest in the test & evaluation, please connect us further.
