### ISSUE TITLE
Provider doesn't support data source: akamai_cpcode

### ISSUE THREAD

**Issue by ElvenSpellmaker** [akamai/terraform-provider-akamai#7]
Hi there,

### Terraform Version
 - 0.11.14
 - 0.12.4

### Affected Resource(s)
Please list the resources as a list, for example:
- `akamai_cpcode`

### Terraform Configuration Files
```hcl
data "akamai_cpcode" "test" {
  name = "Default Foo"
}

resource "akamai_property" "prop" {
  name      = "www.example.org"
  contact   = ["foo@bar.com"]
  cp_code   = "${data.akamai_cpcode.test.id}"
}
```

### Debug Output
https://gist.github.com/ElvenSpellmaker/eecea525359f9a7394f439bdabd8a237

### Expected Behavior
cp_code data source should work as shown here: https://www.terraform.io/docs/providers/akamai/d/cpcode.html

### Actual Behavior
`Error: data.akamai_cpcode.test: Provider doesn't support data source: akamai_cpcode`

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by ElvenSpellmaker** [comment]
This also happens in 0.12.4.

**Comment by dshafik** [comment]
@ElvenSpellmaker this is a typo in the documentation, it is in fact `akamai_cp_code`.

Let me know if this solves you issue, thanks!

**Comment by dshafik** [comment]
The docs should be updated shortly to correctly use `akamai_cp_code`
