### ISSUE TITLE
Only last behaviour applies from the child rule 

### ISSUE THREAD

**Issue by olksdr** [akamai/terraform-provider-akamai#72]
### Terraform Version
Terraform v0.12.12
+ provider.akamai v0.1.3

### Affected Resource(s)
- akamai_property

### Terraform Configuration Files
```hcl
resource "akamai_property" "site" {
  name     = "site"
  contact  = ["user@example.com"]
  product  = "prd_Fresca"
  contract = data.akamai_contract.default.id
  group    = data.akamai_group.default.id
 
  hostnames = {
    for domain in local.domains : domain => akamai_edge_hostname.site[domain].edge_hostname
  }

  rule_format = "v2019-07-25"
  rules       = data.local_file.site_rules.content
  variables   = akamai_property_variables.site.json
}

```

In the  my rules file I have a following child rule:
```json
{
                "name": "Auth",
                "children": [],
                "behaviors": [
                    {
                        "name": "modifyOutgoingRequestHeader",
                        "options": {
                            "action": "MODIFY",
                            "standardModifyHeaderName": "OTHER",
                            "newHeaderValue": "983745893759347539475934857",
                            "avoidDuplicateHeaders": false,
                            "customHeaderName": "X-CLUSTER"
                        }
                    },
                    {
                        "name": "modifyOutgoingRequestHeader",
                        "options": {
                            "action": "ADD",
                            "standardAddHeaderName": "OTHER",
                            "headerValue": "Basic {{user.CREDS}}",
                            "customHeaderName": "Authorization"
                        }
                    }
                ],
                "criteria": [
                    {
                        "name": "hostname",
                        "options": {
                            "matchOperator": "IS_ONE_OF",
                            "values": [
                                "my-clustere.example.com"
                            ]
                        }
                    }
                ],
                "criteriaMustSatisfy": "all",
                "comments": "Set the Basic Auth header"
            },
```

### Expected Behavior
I expect to see all the behaviours to be pushed to the property on the Akamai side in this specific rule. 

### Actual Behavior
There is only one **last** behaviour is saved/applied, in this case it is
```json
 {
     "name": "modifyOutgoingRequestHeader",
     "options": {
        "action": "ADD",
         "standardAddHeaderName": "OTHER",
         "headerValue": "Basic {{user.CREDS}}",
         "customHeaderName": "Authorization"
      }
 }
``` 
 The terraform plan actually shows that the 2 behaviours are changed and applied but only last is actually visible in UI works.  

### Steps to Reproduce
1. create the mentioned above rule
2. apply the configuration 
3. check the property in the UI for this specific rule
4. switch to the JSON view where you will find only the last behaviour defined.

I haven't read seen any mentions about this usecase. Am I missing something or maybe you can point me to the docs where this described? Thank you.

**Comment by sbfaulkner** [comment]
fyi... related (with pending fix) - https://github.com/akamai/AkamaiOPEN-edgegrid-golang/issues/56#issuecomment-558178352

**Comment by olksdr** [comment]
@sbfaulkner thanks for the info! I hope the new release will be up soon 👍

**Comment by martinstibbe** [comment]
https://releases.hashicorp.com/terraform-provider-akamai/0.1.4/ released please test and validate

**Comment by olksdr** [comment]
hi @martinstibbe ,
I can confirm that with `0.1.4` version all the behaviours are submitted and applied. And I can see the corresponding blocks in the UI as well.
