### ISSUE TITLE
Terraform provider not completely following ruleformat

### ISSUE THREAD

**Issue by jhoekstra** [akamai/terraform-provider-akamai#76]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Terraform v0.12.17
### Affected Resource(s)
Please list the resources as a list, for example:
- akamai_property_rules

### Terraform Configuration Files
rule_format = "latest"

affected snippet:
behavior {
     name = "cacheRedirect"
     option {
         key   = "enabled"
         value = "true"
      }
}
Also this variant isn't accepted and errors with same error:
behavior {
     name = "cacheRedirect"
     option {
         key   = "enabled"
         value = true
      }
}
### Debug Output
Error: update rules.Save err: client.APIError{error:error(nil), Type:"https://problems.luna.akamaiapis.net/papi/v0/json-schema-invalid", Title:"400 Bad Request", Status:400, Detail:"Your input has a syntax problem.  Please double check against the schema.", Errors:[]client.APIErrorDetail{client.APIErrorDetail{Type:"", Title:"", Detail:"instance value (true) not found in enum (possible values: [\"false\",\"true\"])", RejectedValue:""}}, Problems:[]client.APIErrorDetail(nil), Instance:"https://akab-<snip>.luna.akamaiapis.net/papi/v1/properties/prp_583944/versions/1/rules#831f5dea582b035a", Method:"", ServerIP:"", ClientIP:"", RequestID:"", RequestTime:"", Response:(*http.Response)(0xc00065e000), RawBody:"{\n  \"type\" : \"https://problems.luna.akamaiapis.net/papi/v0/json-schema-invalid\",\n  \"title\" : \"Input does not match schema\",\n  \"detail\" : \"Your input has a syntax problem.  Please double check against the schema.\",\n  \"instance\" : \"https://akab-<snip>.luna.akamaiapis.net/papi/v1/properties/prp_583944/versions/1/rules#831f5dea582b035a\",\n  \"status\" : 400,\n  \"schemaLink\" : \"/papi/v0/schemas/products/prd_Site_Accel/latest\",\n  \"errors\" : [ {\n    \"location\" : \"/rules/children/2/children/0/behaviors/1/options/enabled\",\n    \"schemaLocation\" : \"/definitions/catalog/behaviors/cacheRedirect/properties/options/properties/enabled\",\n    \"detail\" : \"instance value (true) not found in enum (possible values: [\\\"false\\\",\\\"true\\\"])\",\n    \"foundValue\" : true,\n    \"allowedValues\" : [ \"false\", \"true\" ]\n  } ]\n}"}
### Panic Output
No panic

### Expected Behavior
"name": "cacheRedirect",
                    "options": {
                        "enabled": "true"
                    }
added to json, 
### Actual Behavior
Error:
Error: update rules.Save err: client.APIError{error:error(nil), Type:"https://problems.luna.akamaiapis.net/papi/v0/json-schema-invalid", Title:"400 Bad Request", Status:400, Detail:"Your input has a syntax problem.  Please double check against the schema.", Errors:[]client.APIErrorDetail{client.APIErrorDetail{Type:"", Title:"", Detail:"instance value (true) not found in enum (possible values: [\"false\",\"true\"])", RejectedValue:""}}, Problems:[]client.APIErrorDetail(nil), Instance:"https://akab-<snip>.luna.akamaiapis.net/papi/v1/properties/prp_583944/versions/1/rules#831f5dea582b035a", Method:"", ServerIP:"", ClientIP:"", RequestID:"", RequestTime:"", Response:(*http.Response)(0xc00065e000), RawBody:"{\n  \"type\" : \"https://problems.luna.akamaiapis.net/papi/v0/json-schema-invalid\",\n  \"title\" : \"Input does not match schema\",\n  \"detail\" : \"Your input has a syntax problem.  Please double check against the schema.\",\n  \"instance\" : \"https://akab-<snip>.luna.akamaiapis.net/papi/v1/properties/prp_583944/versions/1/rules#831f5dea582b035a\",\n  \"status\" : 400,\n  \"schemaLink\" : \"/papi/v0/schemas/products/prd_Site_Accel/latest\",\n  \"errors\" : [ {\n    \"location\" : \"/rules/children/2/children/0/behaviors/1/options/enabled\",\n    \"schemaLocation\" : \"/definitions/catalog/behaviors/cacheRedirect/properties/options/properties/enabled\",\n    \"detail\" : \"instance value (true) not found in enum (possible values: [\\\"false\\\",\\\"true\\\"])\",\n    \"foundValue\" : true,\n    \"allowedValues\" : [ \"false\", \"true\" ]\n  } ]\n}"}

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Build ruletree in HCL as per manual
2. 'terraform plan' which doesn't error out
3. `terraform apply` Above error is shown.

### Important Factoids
This is applying to our reseller contract, manual application via luna of this behavior is possible and gives a string value for enabled as shown in expected behavior.
It seems that for this behavior the API requires a string instead of a boolean as documented on: https://developer.akamai.com/api/core_features/property_manager/vlatest.html#cacheredirect
### References
none that I'm aware of.

**Comment by martinstibbe** [comment]
@jhoekstra If you switch from using HCL based rules tree to a json file based approach like snippets concept you can pass this parameter with quotes and it processes normally the use of external file of rules

{"name":"cacheRedirect","options":{"enabled":"true"}},

data "template_file" "rules" {
 template = file("${path.module}/rules.json")
}

and reference in property resource as a datasource

rules = data.template_file.rules.rendered

**Comment by zstlaw** [comment]
From 1.0.0 release, the rule tree will be constructed from template files. Rule format will also be honored as part of this change. Please refer https://registry.terraform.io/providers/akamai/akamai/latest/docs/guides/1.0_migration for details on how to upgrade to this 1.0.0 version. We’re closing this issue. Please file a new issue if you encounter a failure with 1.0.0.
