### ISSUE TITLE
Define order of rules.

### ISSUE THREAD

**Issue by jhoekstra** [akamai/terraform-provider-akamai#77]
Hi,

Generally we setup properties for our customers using a fixed layout which is dependant on order of rules, the tree looks like this:
Default
- ORIGINS
- REDIRECTS
- MEASUREMENTS
- FUNCTIONALITY
- PERFORMANCE
- SECURITY
- AVAILABILITY
- OFFLOAD
- CACHING RULES
- CLOUDLETS
- ADVANCED

When applying this in Terraform rules (since the json variable replacement doesn't always work due to API restrictions) the resulting order of the block with rules is swapped. 
Default
- OFFLOAD
- PERFORMANCE
- SECURITY
- MEASUREMENTS
- FUNCTIONALITY
- REDIRECTS
(other blocks not reproduced yet).
If there's something I'm doing wrong I'd love to know as well. Tried to tie these blocks in a another superblock, but that won't adhere to order either.
### Terraform Version
Terraform v0.12.17
+ provider.akamai (unversioned)(checkoutfrom 26-11-2019)

### Affected Resource(s)
- akamai_property
- akamai_property_variables

### Terraform Configuration Files
NA
### Debug Output
NA
### Panic Output
NA
### Expected Behavior
Property built up in order of rules defined in the tf file.
### Actual Behavior
seemingly random order of rules.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Build terraform file
2. ' terraform plan'  result ok
3 'terraform apply' result ok, property not in expected order.

### Important Factoids
Due to order being important in rules, randomness is an issue.
### References

**Comment by sidph** [comment]
Hi @jhoekstra - curious to dig in more into this. Can you provide us a copy of your tf file?

**Comment by jhoekstra** [comment]
Hi,

Sorry for the late reply, was assigned to other projects.
Attached a stripped down version of a setup for a property, order in which rules are defined is preferred way to have them show up in the property. We first disable all caching to build up cache later on in the property. Stuff like imagemanager should go to the bottom in advanced to make sure it applies to all images for instance.

[property.tf.zip](https://github.com/terraform-providers/terraform-provider-akamai/files/4299351/property.tf.zip)

Best regards,

**Comment by sidph** [comment]
@jhoekstra we'd recommend just passing in all settings through your property_rules.json for this one. You are right - the underlying API will tweak the inputs to reorder it in your setup

**Comment by jhoekstra** [comment]
The replacement of variables via terraform in the json file have been troublesome in the past, ie extending a rule to do more of the same thing comes to mind here. In my example that would be the ' ORIGINS' which behave the same way but differ on hostname match, origin-servers, certificates etc.
If I understand you correctly, there's currently no other way to provision this via terraform?
