### ISSUE TITLE
The NetStorage Account option on the `Origin Server` behavior is required.

### ISSUE THREAD

**Issue by melissabrooksQHR** [akamai/terraform-provider-akamai#83]
Hi there,

I have a terraform script that successfully creates a new property and sets the origin type to NetStorage, however it errors saying I need to set the storage account. 

Can someone provide an example of what that syntax would look like? This is the json equivalent:

```
"behaviors": [
            {
                "name": "origin",
                "options": {
                    "originType": "NET_STORAGE",
                    "netStorage": {
                        "downloadDomainName": "example.download.akamai.com",
                        "cpCode": 12345,
                        "g2oToken": null
                    }
                }
            },

``` 

### Terraform Version
```
Terraform v0.12.17
+ provider.akamai v0.1.4
```

### Terraform Configuration Files
```
variable "akamai_contact" {}
variable "product" {}
variable "product_id" {}
variable "contract_id" {}

provider "akamai" {
  edgerc = "~/.edgerc" 
}

data "akamai_property_rules" "rules" {

  rules { 

    behavior {
      name = "origin"
      option {
        key = "hostname"
        value = "hostname.example.com"
      }
      option {
        key = "originType"
        value = "NET_STORAGE"
      }
    }
  }
  
}  


resource "akamai_property" "example" {
  
  name    = "hostname.example.com"

  contact = ["example@gmail.com"]

  contract = var.contract_id
  group = data.akamai_group.example.id
  product  = var.product_id
  cp_code  = akamai_cp_code.example.id
  is_secure = "true"

  hostnames = {
    "hostname.example.com" = "hostname.example.com"
  }
  
  rules = data.akamai_property_rules.rules.json
  
}

```

### Debug Output
Plan works as expected, and then apply throws this error:

```
Error: Error - Invalid Property Rules
 Rule validation error: https://problems.luna.akamaiapis.net/papi/v0/validation/attribute_required  The NetStorage Account option on the `Origin Server` behavior is required.
```
How can I include the provided json in an "option", "behavior" or "criteria" ?

**Comment by mvanhornakamai** [comment]
Netstorage is a special origin type that requires a user had already setup a folder and access control under their Netstorage account.  The PAPI JSON would look something like this:

            {
                "name": "origin",
                "options": {
                    "originType": "NET_STORAGE",
                    "netStorage": {
                        "downloadDomainName": "example.download.akamai.com",
                        "cpCode": 12345,
                        "g2oToken": "12345=abcdefghijklmnopqrstuvwxyz1234567890"
                    }
                }
            }


The " NetStorage Account option" is actually the "netStorage" object above that is required.

**Comment by melissabrooksQHR** [comment]
> Netstorage is a special origin type that requires a user had already setup a folder and access control under their Netstorage account. The PAPI JSON would look something like this:
> 
> ```
>         {
>             "name": "origin",
>             "options": {
>                 "originType": "NET_STORAGE",
>                 "netStorage": {
>                     "downloadDomainName": "example.download.akamai.com",
>                     "cpCode": 12345,
>                     "g2oToken": "12345=abcdefghijklmnopqrstuvwxyz1234567890"
>                 }
>             }
>         }
> ```
> 
> The " NetStorage Account option" is actually the "netStorage" object above that is required.

Thank you so much for the reply. 

Do you know how to convert this JSON snippet to terraform?

**Comment by sidph** [comment]
@melissabrooksQHR The recommended approach to construct any advanced Akamai attributes is to leverage the JSON directly via local_file as detailed [here](https://www.terraform.io/docs/providers/akamai/g/get_started_property.html) . In the coming days we'll be adding examples that leverage template_file to construct JSON snippets too so you can modularize the configuration

**Comment by melissabrooksQHR** [comment]
@sidph thank you very much, this information was useful. 

I will update my script to use the JSON directly as you have suggested.
