### ISSUE TITLE
crash when try activation of property version 1

### ISSUE THREAD

**Issue by jazzista88** [akamai/terraform-provider-akamai#84]
#28 # Terraform Version
# terraform version
Terraform v0.12.18
+ provider.akamai v0.1.4
+ provider.aws v2.41.0
+ provider.template v2.1.2

### Affected Resource(s)
Please list the resources as a list, for example:
# terraform state list
data.akamai_contract.ctr_3-RIE557
data.akamai_cp_code.cpc_372168
data.akamai_group.grp_63157
data.aws_caller_identity.current
data.aws_region.current
data.template_file.terraform_property_test1_rendered_template
akamai_edge_hostname.terraform_property_test1-edge-hostname
akamai_property.terraform_property_test1

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
resource "akamai_property_activation" "terraform_property_test1-activation" {
     property = akamai_property.terraform_property_test1.id
     contact  = ["email@address.com"]
}
```

### Debug Output
https://gist.github.com/jazzista88/d8565dccbabb4420f8160a189b3896a7

### Expected Behavior
```
$ terraform init
$ terraform plan
$ terraform apply
```
The apply should run the activation on staging environment. Currently i'm trying to activate the version 1 so the property has not been activated before.

### Actual Behavior
```hcl
$ terraform init
$ terraform apply
$ terraform apply
2019/12/30 10:19:35 [WARN] Log levels other than TRACE are currently unreliable, and are supported only for backward compatibility.
  Use TF_LOG=TRACE to see Terraform's internal logs.
  ----
data.template_file.terraform_property_test1_rendered_template: Refreshing state...
data.akamai_contract.ctr_3-RIE557: Refreshing state...
data.akamai_group.grp_63157: Refreshing state...
akamai_edge_hostname.terraform_property_test1-edge-hostname: Refreshing state... [id=ehn_3967840]
data.akamai_cp_code.cpc_372168: Refreshing state...
akamai_property.terraform_property_test1: Refreshing state... [id=prp_577407]
data.aws_region.current: Refreshing state...
data.aws_caller_identity.current: Refreshing state...

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # akamai_property_activation.terraform_property_test1-activation will be created
  + resource "akamai_property_activation" "terraform_property_test1-activation" {
      + activate = true
      + contact  = [
          + "stefano.bianchi@ynap.com",
        ]
      + id       = (known after apply)
      + network  = "staging"
      + property = "prp_577407"
      + status   = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value:
akamai_property_activation.terraform_property_test1-activation: Creating...

Error: rpc error: code = Unavailable desc = transport is closing
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by martinstibbe** [comment]
Could you try using this additional parameter ?

resource "akamai_property_activation" "property_activation" {
	property = "${akamai_property.terraform_property_test1.property.id}"
	version = "${akamai_property.terraform_property_test1.version}"
	network = "STAGING"
	activate = true
	contact = ["email@address.com"]
}

**Comment by jazzista88** [comment]
By adding **property = "${akamai_property.terraform_property_test1.property.id}"**

terraform plan
```hcl
Warning: Interpolation-only expressions are deprecated

  on property.tf line 38, in resource "akamai_property_activation" "terraform_property_test1-activation":
  38: property = "${akamai_property.terraform_property_test1.property.id}"

Terraform 0.11 and earlier required all non-constant expressions to be
provided via interpolation syntax, but this pattern is now deprecated. To
silence this warning, remove the "${ sequence from the start and the }"
sequence from the end of this expression, leaving just the inner expression.

Template interpolation syntax is still used to construct strings from
expressions when the template includes multiple interpolation sequences or a
mixture of literal strings and interpolations. This deprecation applies only
to templates that consist entirely of a single interpolation sequence.

(and one more similar warning elsewhere)


Error: Unsupported attribute

  on property.tf line 38, in resource "akamai_property_activation" "terraform_property_test1-activation":
  38: property = "${akamai_property.terraform_property_test1.property.id}"

This object has no argument, nested block, or exported attribute named
"property".
```
Following your suggestion it seems that akamai_property.terraform_property_test1.**property**.id
does not exists.
I checked on doc and that argument does not exist indeed.
Moreover in doc i see this:
```hcl
resource "akamai_property_activation" "example" {
     property = "${akamai_property.example.id}"
     network  = "STAGING"
     activate = "${var.akamai_property_activate}"
     contact  = ["user@example.org"] 
}
```
Where the akamai property id is called like **akamai_property.example.id** that is exactly what i'm doing. I don't understand what im doing wrong.

**Comment by martinstibbe** [comment]
example "${akamai_property.example.id}"  you could change to "${akamai_property.terraform_property_test1.id}"
