### ISSUE TITLE
akamai_dns_zone TXT Record Produces Inconsistent Results

### ISSUE THREAD

**Issue by christopherbox** [akamai/terraform-provider-akamai#92]
# Terraform Version
```Terraform version: 0.12.18```

### Affected Resource(s)
Please list the resources as a list, for example:
- akamai_dns_zone

### Terraform Configuration Files
```
resource "akamai_dns_record" "cloudflare_domain_verification" {
    zone = "stagehidemycompany.com"
    name = "cloudflare-verify.hidemyname-test.stagehidemycompany.com"
    recordtype =  "TXT"
    active = true
    ttl =  300 
    target = ["276212564-221025253"]
}
```

### Debug Output
[Gist-Link](https://gist.github.com/christopherbox/c8e4b23a8378f19b58f31413b542e253)

### Expected Behavior
The apply should perform normally with no error and no inconsistent results where the SHA sum do not miss-match.

### Actual Behavior
```
Error: Provider produced inconsistent result after apply
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Setup a resource for a TXT record
2. `terraform apply`

Approve the change and wait for the error to occur on the zone. 

### Important Factoids
Right now I am running this locally on my machine. No state file on any cloud provider.

**Comment by martinstibbe** [comment]
If you try target = ["\"276212564-221025253\""] it should work
